In [1]:
import pandas as pd

In [2]:
models= pd.read_csv('../data/models.csv').columns

In [3]:
number_of_models = len(models)

In [4]:
for n in range(number_of_models):
    model_num = n
    print()
    print()
    print("OPTIMIZING MODEL " + str(model_num))
    print()
    print()
    %run TM-Optimize-Models.ipynb

OPTIMIZING MODEL 0


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_0
LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)
['R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'B_Pound-for-Pound_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'lose_streak_dif', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'B_ev', 'empty_arena']
0
Current best score is: 20831.638148474805
Feature: B_odds Score: 20967.43793880679
Feature: title_bout Score: 22260.536664951116
Feature: B_longest_win_streak Score: 22729.162115488394
Feature: R_longest_win_streak Score: 22929.162115488394
The best feature was R_longest_win_streak.  It scored 22929.162115488394
Current best score is: 22929.162115488394
Feature: title_bout Score: 23786.699022943794
Feature: avg_sub_att_dif Score: 23979.984956077267
The best feature was avg_sub_att_dif.  It scored 23979.984956077267
Current best score is: 23979.984956077267
Feature: R_Reach_cms Score: 24223.528965849466
The best feature was R_Reach_cms.  It scored 24223.528965849466
Current best score is: 24223.528965849466
Feature: title_bout Score: 24370.18376023705
Feature: B_longest_win_streak Score: 24433.52896584947
The best feature was B_longest_win_streak.  It scored 24433.52896584947
Current best score is: 24433.52896584947
NO IMPROVEMENT
FINAL BEST SCORE: 24433.52896584947

model_0
LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)
['B_longest_win_streak', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'B_Pound-for-Pound_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'lose_streak_dif', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'B_ev', 'empty_arena']
0

(4554, 36)

(4554,)

(4554, 2)

(250, 36)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.623551  0.376449       1
1       -320      250  0.682419  0.317581       1
2        130     -155  0.445105  0.554895       0
3       -155      135  0.648168  0.351832       1
4       -240      195  0.688174  0.311826       0
..       ...      ...       ...       ...     ...
245      175     -230  0.399123  0.600877       0
246      250     -305  0.322568  0.677432       0
247     -134      105  0.568085  0.431915       1
248     -105     -117  0.588912  0.411088       1
249      115     -143  0.530229  0.469771       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 185
          Number of winning bets: 99
          Number of losing bets: 86
          Number of underdog bets: 106
          Number of underdog wins: 43
          Number of underdog losses: 63
          Number of Favorite bets: 78
          Number of favorite wins: 56
          Number of favorite losses: 22
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 677.4691783448036
          Profit per bet: 3.66199555862056
          Profit per match: 2.7098767133792143


HI
HI
HI
HI
HI


Starting New Run for LogisticRegression


Previous Best Score: 24433.52896584947
solver: newton-cg penalty: l2 tol: 9.6e-05 Score: 24433.52896584947
solver: newton-cg penalty: l2 tol: 0.0001152 Score: 24433.52896584947
solver: newton-cg penalty: l2 tol: 7.680000000000001e-05 Score: 24433.52896584947
solver: newton-cg penalty: l2 tol: 3.0565145405107144 Score: 23179.243167962733
solver: newton-cg penalty: none tol: 9.6e-05 Score: 24425.13100646416
solver: newton-cg penalty: none tol: 0.0001152 Score: 24425.13100646416
solver: newton-cg penalty: none tol: 7.680000000000001e-05 Score: 24425.13100646416
solver: newton-cg penalty: none tol: 3.0565145405107144 Score: 24188.03426912667
solver: lbfgs penalty: l2 tol: 9.6e-05 Score: 24433.52896584947
solver: lbfgs penalty: l2 tol: 0.0001152 Score: 24433.52896584947
solver: lbfgs penalty: l2 tol: 7.680000000000001e-05 Score: 24433.52896584947
solver: lbfgs penalty: l2 tol: 3.0565145405107144 Score: 24393.649062919427
solver: lbfgs penalty: none tol: 9.6e-05 Score: 24425.13100646416
solver: lbfgs penalty: none tol: 0.0001152 Score: 24425.13100646416
solver: lbfgs penalty: none tol: 7.680000000000001e-05 Score: 24425.13100646416
solver: lbfgs penalty: none tol: 3.0565145405107144 Score: 24262.203033809546
solver: sag penalty: l2 tol: 9.6e-05 Score: 24333.52896584947
solver: sag penalty: l2 tol: 0.0001152 Score: 24333.52896584947
solver: sag penalty: l2 tol: 7.680000000000001e-05 Score: 24333.52896584947
solver: sag penalty: l2 tol: 3.0565145405107144 Score: 6997.874709588745
solver: sag penalty: none tol: 9.6e-05 Score: 24301.321482654632
solver: sag penalty: none tol: 0.0001152 Score: 24301.321482654632
solver: sag penalty: none tol: 7.680000000000001e-05 Score: 24301.321482654632
solver: sag penalty: none tol: 3.0565145405107144 Score: 7005.017566731602
Real output model: LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)

model_0
LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)
['B_longest_win_streak', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'B_Pound-for-Pound_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'lose_streak_dif', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'B_ev', 'empty_arena']
0

(4554, 36)

(4554,)

(4554, 2)

(250, 36)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.623551  0.376449       1
1       -320      250  0.682419  0.317581       1
2        130     -155  0.445105  0.554895       0
3       -155      135  0.648168  0.351832       1
4       -240      195  0.688174  0.311826       0
..       ...      ...       ...       ...     ...
245      175     -230  0.399123  0.600877       0
246      250     -305  0.322568  0.677432       0
247     -134      105  0.568085  0.431915       1
248     -105     -117  0.588912  0.411088       1
249      115     -143  0.530229  0.469771       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 185
          Number of winning bets: 99
          Number of losing bets: 86
          Number of underdog bets: 106
          Number of underdog wins: 43
          Number of underdog losses: 63
          Number of Favorite bets: 78
          Number of favorite wins: 56
          Number of favorite losses: 22
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 677.4691783448036
          Profit per bet: 3.66199555862056
          Profit per match: 2.7098767133792143


HI
HI
HI
HI
HI
0 24433.52896584947
1 19817.673344895506
2 17518.125029850176
3 17822.418195147347
4 16834.304764349286
5 10681.757288598074
6 9064.127810481208
7 7767.503737293542
8 7307.368373641593
9 6874.065222992473
10 6877.510500879478
11 7036.708715974223
12 7192.10277480352
13 7141.050640544964
14 5727.112953058968
15 6506.681445258812
16 4773.46952355424
17 5297.342460124669
18 5452.667450990581
19 4180.624313556139
20 4081.814789746615
21 4053.6586343078507
22 2442.5423950932127
23 2291.9108161458444
24 2562.910816145845
25 2959.031217483637
26 2893.8883603407803
27 3811.8883603407803
28 4076.7216936741133
29 3893.7216936741133
30 3414.400040484536
31 2629.0667071512025
32 2606.828611913107
33 1690.9195210040164
34 1920.9195210040164
35 1840.0104300949256
36 1445.053908355795
37 2210.053908355795
38 1504.7205750224616
39 1974.7205750224616
40 2004.7205750224616
41 809.7205750224617
42 634.7205750224617
43 904.7205750224617
44 444.72057502246173
45 341.72057502246173
46 371.72057502246173
47 586.7205750224617
48 446.72057502246173
49 546.7205750224617
50 646.7205750224617
51 176.7205750224618
52 176.7205750224618
53 276.72057502246173
54 396.7205750224618
55 339.5777178796047
56 469.5777178796046
57 669.5777178796046
58 769.5777178796046
59 769.5777178796046
60 644.5777178796046
61 944.5777178796046
62 949.3396226415094
63 1049.3396226415093
64 879.3396226415094
65 879.3396226415094
66 879.3396226415094
67 669.3396226415094
68 599.3396226415094
69 599.3396226415094
70 699.3396226415094
71 799.3396226415094
72 799.3396226415094
73 749.3396226415094
74 749.3396226415094
75 749.3396226415094
76 749.3396226415094
77 749.3396226415094
78 374.33962264150944
79 169.33962264150944
80 169.33962264150944
81 169.33962264150944
82 269.33962264150944
83 269.33962264150944
84 269.33962264150944
85 469.33962264150944
86 375.0
87 375.0
88 375.0
89 375.0
90 375.0
91 375.0
92 375.0
93 375.0
94 375.0
95 375.0
96 375.0
97 130.0
98 130.0
99 230.0
100 230.0
101 230.0
102 230.0
103 85.0
104 85.0
105 85.0
106 85.0
107 85.0
108 85.0
109 85.0
110 85.0
111 85.0
112 85.0
113 85.0
114 85.0
115 85.0
116 85.0
117 85.0
118 85.0
119 85.0
120 85.0
121 85.0
122 85.0
123 85.0
124 85.0
125 85.0
126 85.0
127 85.0
128 185.0
129 185.0
130 185.0
131 185.0
132 185.0
133 185.0
134 185.0
135 185.0
136 185.0
137 185.0
138 185.0
139 185.0
140 0
141 0
142 0
143 0
144 0
145 0
146 0
147 0
148 0
149 0
150 0
151 0
152 0
153 0
154 0
155 0
156 0
157 0
158 0
159 0
160 0
161 0
162 0
163 0
164 0
165 0
166 0
167 0
168 0
169 0
170 0
171 0
172 0
173 0
174 0
175 0
176 0
177 0
178 0
179 0
180 0
181 0
182 0
183 0
184 0
185 0
186 0
187 0
188 0
189 0
190 0
191 0
192 0
193 0
194 0
195 0
196 0
197 0
198 0
199 0
200 0
201 0
202 0
203 0
204 0
205 0
206 0
207 0
208 0
209 0
210 0
211 0
212 0
213 0
214 0
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0
239 0
240 0
241 0
242 0
243 0
244 0
245 0
246 0
247 0
248 0
249 0

model_0
LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)
['B_longest_win_streak', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'B_Pound-for-Pound_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'lose_streak_dif', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'B_ev', 'empty_arena']
0

(4554, 36)

(4554,)

(4554, 2)

(250, 36)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.623551  0.376449       1
1       -320      250  0.682419  0.317581       1
2        130     -155  0.445105  0.554895       0
3       -155      135  0.648168  0.351832       1
4       -240      195  0.688174  0.311826       0
..       ...      ...       ...       ...     ...
245      175     -230  0.399123  0.600877       0
246      250     -305  0.322568  0.677432       0
247     -134      105  0.568085  0.431915       1
248     -105     -117  0.588912  0.411088       1
249      115     -143  0.530229  0.469771       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 185
          Number of winning bets: 99
          Number of losing bets: 86
          Number of underdog bets: 106
          Number of underdog wins: 43
          Number of underdog losses: 63
          Number of Favorite bets: 78
          Number of favorite wins: 56
          Number of favorite losses: 22
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 677.4691783448036
          Profit per bet: 3.66199555862056
          Profit per match: 2.7098767133792143


HI
HI
HI
HI
HI
The original score is 24433.52896584947
Score:  24223.528965849466
Score:  23979.984956077267
Score:  23315.656038746012
Score:  24433.52896584947
Score:  23764.870800852546
Score:  23270.82238513301
Score:  24408.95944819692
Score:  23712.788062981497
Score:  12000.391502956265
Score:  19015.159240635217
Score:  24030.598375177964
Score:  24433.52896584947
Score:  22571.98772691592
Score:  20432.022629486935
NEW BEST FEATURE SET
['B_longest_win_streak', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'B_Pound-for-Pound_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'B_ev', 'empty_arena']
25235.301847570954
Score:  10013.041364233235
Score:  17803.56235435366
Score:  20539.754848350196
Score:  24906.58818405383
Score:  22425.768307604234
Score:  23223.624839971722
Score:  23657.888621928207
Score:  23809.301828522173
Score:  21818.6050727495
Score:  18065.49350102205
Score:  13613.474024333387
Score:  24784.04566133632
Score:  24266.678732879784
Score:  20761.658974820526
Score:  23983.378456674585
Score:  23656.554331630166
Score:  23652.855458782484
Score:  24997.13791153954
Score:  24515.97181184507
Score:  4998.85626304638
Score:  21701.448681414076
The original score is 25235.301847570954
Score:  25235.301847570954
Score:  24781.201908563893
Score:  22913.805685387702
Score:  25235.301847570954
Score:  23762.561645901405
Score:  23550.869423522112
NEW BEST FEATURE SET
['B_longest_win_streak', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'B_Pound-for-Pound_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'B_ev', 'empty_arena']
25832.300652587404
Score:  23577.9735617399
Score:  13583.346679442531
Score:  20941.698225289307
Score:  25714.363111683546
Score:  25182.670268623588
Score:  25080.665001771536
Score:  22738.580148448902
Score:  9529.041353732551
Score:  18167.420042893595
Score:  19906.09515400706
Score:  24952.398648118695
Score:  24031.045632155863
Score:  24101.762138484
Score:  24872.96797528973
Score:  24524.890209557772
Score:  22555.245675651084
Score:  18913.525856794797
Score:  13176.883220973908
Score:  24744.813253428492
Score:  25579.121765654334
Score:  22010.001515386128
Score:  24422.98135468454
Score:  25674.762621816823
Score:  25211.246794211012
NEW BEST FEATURE SET
['B_longest_win_streak', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'B_Pound-for-Pound_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']
26167.915271166697
Score:  25503.175580134288
Score:  6618.202059851325
Score:  22652.846170225585
The original score is 26167.915271166697
NEW BEST FEATURE SET
['R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'B_Pound-for-Pound_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']
26232.431400198955
Score:  25956.035496855136
Score:  24222.351714996254
Score:  26232.431400198955
Score:  23716.050410099684
Score:  24820.358202915402
Score:  25293.47368210513
Score:  24419.495827247356
Score:  13567.714423632226
Score:  22342.118984118937
NEW BEST FEATURE SET
['B_longest_win_streak', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']
26510.054736650498
Score:  26258.824362075786
Score:  25750.13052449995
Score:  22946.583443276904
Score:  11161.633333508162
Score:  20340.090103525843
Score:  20452.341667497698
Score:  25837.647610696273
Score:  25579.18226266039
Score:  25435.79263524957
Score:  25052.983394951116
Score:  25852.793637097577
Score:  23011.45205339627
Score:  19079.23492616937
Score:  14521.797614815772
Score:  25736.412156141563
Score:  26353.63046054311
Score:  22101.20612258483
Score:  25815.855484127
Score:  26259.053297341514
Score:  25605.746760930186
Score:  26156.96633246944
Score:  6807.7869309175585
Score:  23020.389994191934
The original score is 26510.054736650498
NEW BEST FEATURE SET
['R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']
26610.054736650498
Score:  24506.423187387336
Score:  24324.813866024117
Score:  26510.054736650498
Score:  24009.483659097532
Score:  25139.050537520594
Score:  25621.479960277575
Score:  25352.271033757545
Score:  13822.245720688472
Score:  21127.988252653216
Score:  26510.054736650498
Score:  24851.5606313751
Score:  23321.737926199407
Score:  10674.033969350425
Score:  20686.224571530056
Score:  20567.30901417259
Score:  26092.79116678118
Score:  25940.587820728637
Score:  25021.575136207764
Score:  24637.36782593719
Score:  26066.466377996698
Score:  22830.96360628599
Score:  19250.04537987637
Score:  15135.425345020758
Score:  25529.357128906835
Score:  25869.863067530903

Score:  21340.01108219257
Score:  26122.850334165865
Score:  26586.115768885473
Score:  26073.408708812647
Score:  26184.14691947025
Score:  7529.745781021888
Score:  23051.34432077719
The original score is 26610.054736650498
Score:  24439.756520720668
Score:  24268.31669088287
Score:  24049.900721136022
Score:  23976.69677385163
Score:  25139.050537520594
Score:  25621.479960277575
Score:  25373.547629502227
Score:  13782.851781294532
Score:  21227.988252653216
Score:  20855.102884820106
Score:  25086.00507581955
Score:  23186.737926199407
Score:  10574.033969350428
Score:  20836.224571530052
Score:  20417.309014172588
Score:  26134.457833447843
Score:  25840.587820728637
Score:  24997.76561239824
Score:  24515.722804292167
Score:  25966.466377996698
Score:  22700.96360628599
Score:  19295.499925330918
Score:  15035.425345020758
Score:  25850.87886803727
Score:  25829.863067530903
Score:  21340.01108219257
Score:  26222.850334165865
Score:  26547.654230423934
Score:  26104.408708812647
Score:  26084.14691947025
Score:  7507.0185082946155
Score:  23263.487177920048
The features are different
OLD:
['B_longest_win_streak', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'B_Pound-for-Pound_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'lose_streak_dif', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'loss_dif', 'B_ev', 'empty_arena']
NEW:
['R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']

model_0
LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)
['R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']
0

(4554, 32)

(4554,)

(4554, 2)

(250, 32)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.623605  0.376395       1
1       -320      250  0.679642  0.320358       1
2        130     -155  0.452538  0.547462       0
3       -155      135  0.664645  0.335355       1
4       -240      195  0.686090  0.313910       0
..       ...      ...       ...       ...     ...
245      175     -230  0.408885  0.591115       0
246      250     -305  0.328494  0.671506       0
247     -134      105  0.567083  0.432917       1
248     -105     -117  0.590489  0.409511       1
249      115     -143  0.534190  0.465810       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 187
          Number of winning bets: 102
          Number of losing bets: 85
          Number of underdog bets: 106
          Number of underdog wins: 43
          Number of underdog losses: 63
          Number of Favorite bets: 80
          Number of favorite wins: 59
          Number of favorite losses: 21
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 951.746246306082
          Profit per bet: 5.08955211928386
          Profit per match: 3.806984985224328


HI
HI
HI
HI
HI
Current best score is: 26610.054736650498
Feature: B_Light Heavyweight_rank Score: 26618.124103582068
Feature: B_Welterweight_rank Score: 26950.25955289586
The best feature was B_Welterweight_rank.  It scored 26950.25955289586
Current best score is: 26950.25955289586
Feature: R_Women's Featherweight_rank Score: 27515.125667457633
The best feature was R_Women's Featherweight_rank.  It scored 27515.125667457633
Current best score is: 27515.125667457633
Feature: B_longest_win_streak Score: 27586.554238886198
The best feature was B_longest_win_streak.  It scored 27586.554238886198
Current best score is: 27586.554238886198
NO IMPROVEMENT
FINAL BEST SCORE: 27586.554238886198

model_0
LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)
['B_longest_win_streak', "R_Women's Featherweight_rank", 'B_Welterweight_rank', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']
0

(4554, 35)

(4554,)

(4554, 2)

(250, 35)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.622438  0.377562       1
1       -320      250  0.679703  0.320297       1
2        130     -155  0.454447  0.545553       0
3       -155      135  0.663487  0.336513       1
4       -240      195  0.685772  0.314228       0
..       ...      ...       ...       ...     ...
245      175     -230  0.407810  0.592190       0
246      250     -305  0.331161  0.668839       0
247     -134      105  0.568877  0.431123       1
248     -105     -117  0.590396  0.409604       1
249      115     -143  0.534511  0.465489       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 189
          Number of winning bets: 104
          Number of losing bets: 85
          Number of underdog bets: 106
          Number of underdog wins: 43
          Number of underdog losses: 63
          Number of Favorite bets: 82
          Number of favorite wins: 61
          Number of favorite losses: 21
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 1002.003183613379
          Profit per bet: 5.301604146102534
          Profit per match: 4.008012734453516


HI
HI
HI
HI
HI


Starting New Run for LogisticRegression


Previous Best Score: 27586.554238886198
solver: newton-cg penalty: l2 tol: 9.6e-05 Score: 27586.554238886198
solver: newton-cg penalty: l2 tol: 0.0001152 Score: 27586.554238886198
solver: newton-cg penalty: l2 tol: 7.680000000000001e-05 Score: 27586.554238886198
solver: newton-cg penalty: l2 tol: 7.6140098254243345 Score: 20834.98814162445
solver: newton-cg penalty: none tol: 9.6e-05 Score: 26243.35001591675
solver: newton-cg penalty: none tol: 0.0001152 Score: 26243.35001591675
solver: newton-cg penalty: none tol: 7.680000000000001e-05 Score: 26243.35001591675
solver: newton-cg penalty: none tol: 7.6140098254243345 Score: 20678.003554219405
solver: lbfgs penalty: l2 tol: 9.6e-05 Score: 27486.554238886198
solver: lbfgs penalty: l2 tol: 0.0001152 Score: 27486.554238886198
solver: lbfgs penalty: l2 tol: 7.680000000000001e-05 Score: 27486.554238886198
solver: lbfgs penalty: l2 tol: 7.6140098254243345 Score: 18455.9663665197
solver: lbfgs penalty: none tol: 9.6e-05 Score: 26243.35001591675
solver: lbfgs penalty: none tol: 0.0001152 Score: 26243.35001591675
solver: lbfgs penalty: none tol: 7.680000000000001e-05 Score: 26243.35001591675
solver: lbfgs penalty: none tol: 7.6140098254243345 Score: 18573.30608241014
solver: sag penalty: l2 tol: 9.6e-05 Score: 27586.554238886198
solver: sag penalty: l2 tol: 0.0001152 Score: 27586.554238886198
solver: sag penalty: l2 tol: 7.680000000000001e-05 Score: 27586.554238886198
solver: sag penalty: l2 tol: 7.6140098254243345 Score: 9902.249172152144
solver: sag penalty: none tol: 9.6e-05 Score: 26243.35001591675
solver: sag penalty: none tol: 0.0001152 Score: 26243.35001591675
solver: sag penalty: none tol: 7.680000000000001e-05 Score: 26243.35001591675
solver: sag penalty: none tol: 7.6140098254243345 Score: 10001.87038427336
Real output model: LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)

model_0
LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)
['B_longest_win_streak', "R_Women's Featherweight_rank", 'B_Welterweight_rank', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']
0

(4554, 35)

(4554,)

(4554, 2)

(250, 35)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.622438  0.377562       1
1       -320      250  0.679703  0.320297       1
2        130     -155  0.454447  0.545553       0
3       -155      135  0.663487  0.336513       1
4       -240      195  0.685772  0.314228       0
..       ...      ...       ...       ...     ...
245      175     -230  0.407810  0.592190       0
246      250     -305  0.331161  0.668839       0
247     -134      105  0.568877  0.431123       1
248     -105     -117  0.590396  0.409604       1
249      115     -143  0.534511  0.465489       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 189
          Number of winning bets: 104
          Number of losing bets: 85
          Number of underdog bets: 106
          Number of underdog wins: 43
          Number of underdog losses: 63
          Number of Favorite bets: 82
          Number of favorite wins: 61
          Number of favorite losses: 21
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 1002.003183613379
          Profit per bet: 5.301604146102534
          Profit per match: 4.008012734453516


HI
HI
HI
HI
HI
0 27586.554238886198
1 21670.34296906381
2 19102.286926326382
3 17451.616979715778
4 15688.525531637542
5 12379.81431389496
6 11219.817950315297
7 12015.273947273188
8 9703.11142022821
9 7912.807827766148
10 7421.610024556939
11 9070.060738242328
12 8493.155096088205
13 8771.288471213942
14 5926.643562464667
15 6625.115316909421
16 5552.00921197004
17 6019.776803209931
18 6819.084332545356
19 7055.518693035015
20 5663.5580305091335
21 4875.096492047595
22 5141.607770243084
23 4168.976191295716
24 3892.9761912957156
25 4841.140070894378
26 4384.997213751521
27 4000.8305470848536
28 3644.4909244433447
29 3669.4909244433447
30 2443.5978426823385
31 2792.2571833416787
32 2571.3480924325877
33 2029.3480924325881
34 1662.0104300949256
35 1720.053908355795
36 1716.7205750224616
37 1211.7205750224616
38 1016.7205750224617
39 1396.7205750224616
40 1069.7205750224616
41 1029.7205750224616
42 601.7205750224617
43 131.72057502246173
44 531.7205750224617
45 336.72057502246173
46 -278.27942497753827
47 -263.27942497753827
48 136.72057502246173
49 101.72057502246173
50 -78.27942497753821
51 321.72057502246173
52 291.72057502246173
53 391.72057502246173
54 426.72057502246173
55 299.5777178796046
56 399.5777178796046
57 499.5777178796046
58 374.5777178796046
59 374.5777178796046
60 574.5777178796046
61 574.5777178796046
62 679.3396226415094
63 779.3396226415094
64 609.3396226415094
65 609.3396226415094
66 609.3396226415094
67 359.33962264150944
68 249.33962264150944
69 349.33962264150944
70 449.33962264150944
71 549.3396226415094
72 549.3396226415094
73 549.3396226415094
74 549.3396226415094
75 444.33962264150944
76 444.33962264150944
77 544.3396226415094
78 169.33962264150944
79 169.33962264150944
80 169.33962264150944
81 169.33962264150944
82 169.33962264150944
83 269.33962264150944
84 369.33962264150944
85 369.33962264150944
86 375.0
87 375.0
88 375.0
89 375.0
90 375.0
91 375.0
92 130.0
93 130.0
94 130.0
95 130.0
96 130.0
97 130.0
98 230.0
99 230.0
100 230.0
101 230.0
102 230.0
103 230.0
104 230.0
105 85.0
106 85.0
107 85.0
108 85.0
109 85.0
110 85.0
111 85.0
112 85.0
113 85.0
114 85.0
115 85.0
116 85.0
117 85.0
118 85.0
119 85.0
120 85.0
121 -100
122 -100
123 0
124 0
125 0
126 0
127 0
128 0
129 0
130 0
131 0
132 0
133 0
134 0
135 0
136 0
137 0
138 0
139 0
140 0
141 0
142 0
143 0
144 0
145 0
146 0
147 0
148 0
149 0
150 0
151 0
152 0
153 0
154 0
155 0
156 0
157 0
158 0
159 0
160 0
161 0
162 0
163 0
164 0
165 0
166 0
167 0
168 0
169 0
170 0
171 0
172 0
173 0
174 0
175 0
176 0
177 0
178 0
179 0
180 0
181 0
182 0
183 0
184 0
185 0
186 0
187 0
188 0
189 0
190 0
191 0
192 0
193 0
194 0
195 0
196 0
197 0
198 0
199 0
200 0
201 0
202 0
203 0
204 0
205 0
206 0
207 0
208 0
209 0
210 0
211 0
212 0
213 0
214 0
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0
239 0
240 0
241 0
242 0
243 0
244 0
245 0
246 0
247 0
248 0
249 0

model_0
LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)
['B_longest_win_streak', "R_Women's Featherweight_rank", 'B_Welterweight_rank', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']
0

(4554, 35)

(4554,)

(4554, 2)

(250, 35)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.622438  0.377562       1
1       -320      250  0.679703  0.320297       1
2        130     -155  0.454447  0.545553       0
3       -155      135  0.663487  0.336513       1
4       -240      195  0.685772  0.314228       0
..       ...      ...       ...       ...     ...
245      175     -230  0.407810  0.592190       0
246      250     -305  0.331161  0.668839       0
247     -134      105  0.568877  0.431123       1
248     -105     -117  0.590396  0.409604       1
249      115     -143  0.534511  0.465489       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 189
          Number of winning bets: 104
          Number of losing bets: 85
          Number of underdog bets: 106
          Number of underdog wins: 43
          Number of underdog losses: 63
          Number of Favorite bets: 82
          Number of favorite wins: 61
          Number of favorite losses: 21
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 1002.003183613379
          Profit per bet: 5.301604146102534
          Profit per match: 4.008012734453516


HI
HI
HI
HI
HI
The original score is 27586.554238886198
Score:  27515.125667457633
Score:  26950.25955289586
Score:  26527.716248797136
Score:  25377.02819933954
Score:  24880.480825854804
Score:  27586.554238886198
Score:  25479.540981210936
Score:  25077.792913586763
Score:  26352.14247031903
Score:  25915.96023929859
Score:  13810.944254617127
Score:  22510.805590462354
Score:  27586.554238886198
Score:  25528.18156429777
Score:  21646.083929122797
Score:  11245.882763517551
Score:  20640.952904155463
Score:  21008.51678309616
Score:  27026.186194728296
Score:  25922.05074332126
Score:  25494.579520520245
Score:  24378.34062525405
Score:  26695.07966541878
Score:  23189.019666946308
Score:  17754.172258475486
Score:  15447.982939980142
Score:  26853.401569326878
Score:  27251.186948453054
Score:  21334.747659577795
Score:  25947.37802033139
Score:  25957.992923711725
Score:  25649.49968612664
Score:  27143.44475684362
Score:  7931.030302469634
Score:  23216.185236369365

model_0
LogisticRegression(max_iter=50000, random_state=75, solver='newton-cg',
                   tol=9.6e-05)
['B_longest_win_streak', "R_Women's Featherweight_rank", 'B_Welterweight_rank', 'R_Reach_cms', 'avg_sub_att_dif', 'R_longest_win_streak', 'R_total_title_bouts', "R_Women's Strawweight_rank", 'R_current_win_streak', 'B_Featherweight_rank', 'B_age', 'R_Flyweight_rank', 'longest_win_streak_dif', 'B_win_by_Decision_Majority', 'R_odds', 'R_ev', 'avg_td_dif', 'win_dif', 'reach_dif', "B_Women's Strawweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'R_Bantamweight_rank', "R_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'R_age', 'R_draw', 'B_Bantamweight_rank', 'B_Lightweight_rank', 'B_Reach_cms', 'B_draw', 'R_Welterweight_rank', 'loss_dif', 'B_ev', 'empty_arena']
0

(4554, 35)

(4554,)

(4554, 2)

(250, 35)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.622438  0.377562       1
1       -320      250  0.679703  0.320297       1
2        130     -155  0.454447  0.545553       0
3       -155      135  0.663487  0.336513       1
4       -240      195  0.685772  0.314228       0
..       ...      ...       ...       ...     ...
245      175     -230  0.407810  0.592190       0
246      250     -305  0.331161  0.668839       0
247     -134      105  0.568877  0.431123       1
248     -105     -117  0.590396  0.409604       1
249      115     -143  0.534511  0.465489       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 189
          Number of winning bets: 104
          Number of losing bets: 85
          Number of underdog bets: 106
          Number of underdog wins: 43
          Number of underdog losses: 63
          Number of Favorite bets: 82
          Number of favorite wins: 61
          Number of favorite losses: 21
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 1002.003183613379
          Profit per bet: 5.301604146102534
          Profit per match: 4.008012734453516


HI
HI
HI
HI
HI

(4554, 35)

(4554,)

(4554, 2)

(250, 35)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.622438  0.377562       1
1       -320      250  0.679703  0.320297       1
2        130     -155  0.454447  0.545553       0
3       -155      135  0.663487  0.336513       1
4       -240      195  0.685772  0.314228       0
..       ...      ...       ...       ...     ...
245      175     -230  0.407810  0.592190       0
246      250     -305  0.331161  0.668839       0
247     -134      105  0.568877  0.431123       1
248     -105     -117  0.590396  0.409604       1
249      115     -143  0.534511  0.465489       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 189
          Number of winning bets: 104
          Number of losing bets: 85
          Number of underdog bets: 106
          Number of underdog wins: 43
          Number of underdog losses: 63
          Number of Favorite bets: 82
          Number of favorite wins: 61
          Number of favorite losses: 21
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 1002.003183613379
          Profit per bet: 5.301604146102534
          Profit per match: 4.008012734453516


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 1


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_1
DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')
['B_avg_TD_landed', 'R_Bantamweight_rank', 'lose_streak_dif', "B_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'win_dif', 'weight_class', 'R_odds', 'location', 'empty_arena']
1
Current best score is: -4544.9438699531565
Feature: B_odds Score: 2163.5740063138455
Feature: R_ev Score: 4147.2276195489085
Feature: R_Women's Flyweight_rank Score: 6091.172343059438
The best feature was R_Women's Flyweight_rank.  It scored 6091.172343059438
Current best score is: 6091.172343059438
Feature: gender Score: 9211.4035547255
The best feature was gender.  It scored 9211.4035547255
Current best score is: 9211.4035547255
NO IMPROVEMENT
FINAL BEST SCORE: 9211.4035547255

model_1
DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')
['gender', "R_Women's Flyweight_rank", 'B_avg_TD_landed', 'R_Bantamweight_rank', 'lose_streak_dif', "B_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'win_dif', 'weight_class', 'R_odds', 'location', 'empty_arena']
1

(3721, 169)

(3721,)

(3721, 2)

(250, 169)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764706  0.235294       1
1       -320      250  0.924528  0.075472       1
2        130     -155  0.295082  0.704918       0
3       -155      135  0.560000  0.440000       1
4       -240      195  0.764706  0.235294       0
..       ...      ...       ...       ...     ...
245      175     -230  0.451613  0.548387       0
246      250     -305  0.336134  0.663866       0
247     -134      105  0.522727  0.477273       1
248     -105     -117  0.582278  0.417722       1
249      115     -143  0.512376  0.487624       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 178
          Number of winning bets: 93
          Number of losing bets: 86
          Number of underdog bets: 81
          Number of underdog wins: 34
          Number of underdog losses: 47
          Number of Favorite bets: 95
          Number of favorite wins: 59
          Number of favorite losses: 36
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -539.3397233086184
          Profit per bet: -3.0299984455540363
          Profit per match: -2.157358893234474


HI
HI
HI
HI
HI


Starting New Run for DecisionTree


Previous Best Score: 9211.4035547255
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 336 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 336 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 336 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 336 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 336 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 336 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 336 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 336 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 336 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 336 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 336 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 336 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 336 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 336 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 336 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 336 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 336 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 336 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 336 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 336 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 336 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 336 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 336 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 336 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 336 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 336 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 336 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 336 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 336 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 336 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 336 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 336 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 335 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 335 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 335 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 335 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 335 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 335 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 335 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 335 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 335 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 335 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 335 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 335 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 335 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 335 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 335 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 335 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 2388.694861612946

Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 335 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 335 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 335 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 335 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 335 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 335 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 335 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 335 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 335 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 335 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 335 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 335 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 335 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 335 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 335 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 335 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 337 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 337 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 337 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 337 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 337 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 337 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 337 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 337 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 337 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 337 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 337 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 337 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 337 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 337 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 337 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 337 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 337 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 337 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 337 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 337 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 337 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 337 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 337 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 337 7437.478919624491

Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 337 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 337 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 337 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 337 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 337 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 337 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 337 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 337 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 201 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 201 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 201 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 201 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 201 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 201 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 201 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 201 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 201 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 201 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 201 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 201 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 201 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 201 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 201 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.0099 max_leaf_nodes: 201 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 201 980.8564113824798
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 201 9211.4035547255
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 201 2388.694861612946
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 201 1465.8610628562813
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 201 1085.1600244363935
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 201 3673.192151665373
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 201 9087.931659597833
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 201 1602.0000814040905
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 201 7437.478919624491
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 201 7272.377076332793
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 201 -2405.6562361468414
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 201 -4069.3427408491902
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 201 -3920.3975299108783
Criterion: gini splitter: random max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 201 -8690.575921373167
Criterion: gini splitter: best max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 201 -297.6765716760103
Criterion: entropy splitter: random max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 201 -8639.139110286796
Criterion: entropy splitter: best max_depth: 15 min_samples_leaf: 0.009801 max_leaf_nodes: 201 980.8564113824798
Real output model: DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')

model_1
DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')
['gender', "R_Women's Flyweight_rank", 'B_avg_TD_landed', 'R_Bantamweight_rank', 'lose_streak_dif', "B_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'win_dif', 'weight_class', 'R_odds', 'location', 'empty_arena']
1

(3721, 169)

(3721,)

(3721, 2)

(250, 169)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764706  0.235294       1
1       -320      250  0.924528  0.075472       1
2        130     -155  0.295082  0.704918       0
3       -155      135  0.560000  0.440000       1
4       -240      195  0.764706  0.235294       0
..       ...      ...       ...       ...     ...
245      175     -230  0.451613  0.548387       0
246      250     -305  0.336134  0.663866       0
247     -134      105  0.522727  0.477273       1
248     -105     -117  0.582278  0.417722       1
249      115     -143  0.512376  0.487624       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 178
          Number of winning bets: 93
          Number of losing bets: 86
          Number of underdog bets: 81
          Number of underdog wins: 34
          Number of underdog losses: 47
          Number of Favorite bets: 95
          Number of favorite wins: 59
          Number of favorite losses: 36
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -539.3397233086184
          Profit per bet: -3.0299984455540363
          Profit per match: -2.157358893234474


HI
HI
HI
HI
HI
0 8484.808113598086
1 9211.4035547255
2 9269.330099391282
3 10572.414137090309
4 8038.017808041334
5 9688.603984290648
6 11752.51025902318
7 10924.78329077315
8 12955.045357870938
9 13836.309198636725
10 11175.037642896536
11 9771.508623221898
12 7886.176898606565
13 6563.187811790607
14 7016.519066908497
15 8245.876682676868
16 8874.805649725076
17 7820.5706569984595
18 6015.705696088722
19 4986.433495171359
20 4283.332479091457
21 4159.703330462307
22 3592.6943739782064
23 3172.146484657559
24 2978.556741067817
25 3046.003549578455
26 1883.7431819267827
27 1783.844192027792
28 2033.225144408745
29 643.9471940981857
30 1163.9471940981857
31 332.65104971754545
32 12.651049717545447
33 -344.27202720553146
34 -409.27202720553146
35 -232.24669533365204
36 -174.16977225672895
37 -34.28157349896492
38 510.7184265010351
39 275.7184265010353
40 550.7184265010351
41 427.4803312629399
42 992.4803312629397
43 493.4803312629399
44 5.523809523809405
45 -164.4761904761906
46 -109.4761904761906
47 390.5238095238094
48 376.0
49 1246.0
50 596.0
51 406.0
52 551.0
53 266.0
54 136.0
55 191.0
56 -419.0
57 -565.0
58 -1155.0
59 -1055.0
60 -1018.0
61 -953.0
62 -1013.0
63 -988.0
64 -1228.0
65 -1128.0
66 -828.0
67 -528.0
68 -588.0
69 -488.0
70 -188.0
71 -143.0
72 57.0
73 -173.0
74 -33.0
75 -313.0
76 -213.0
77 -13.0
78 187.0
79 187.0
80 -373.0
81 -308.0
82 -208.0
83 -488.0
84 -288.0
85 -288.0
86 -188.0
87 12.0
88 212.0
89 312.0
90 312.0
91 412.0
92 612.0
93 292.0
94 -193.0
95 -193.0
96 -193.0
97 -198.0
98 -98.0
99 2.0
100 302.0
101 302.0
102 502.0
103 502.0
104 502.0
105 602.0
106 602.0
107 -23.0
108 77.0
109 77.0
110 0.0
111 100.0
112 200.0
113 600.0
114 600.0
115 700.0
116 800.0
117 800.0
118 800.0
119 900.0
120 1100.0
121 1100.0
122 1100.0
123 1100.0
124 1200.0
125 1400.0
126 1400.0
127 1400.0
128 1230.0
129 1230.0
130 980.0
131 1180.0
132 1180.0
133 1180.0
134 1180.0
135 1180.0
136 1280.0
137 1280.0
138 1380.0
139 720.0
140 820.0
141 820.0
142 820.0
143 750.0
144 850.0
145 850.0
146 850.0
147 850.0
148 850.0
149 850.0
150 720.0
151 720.0
152 720.0
153 720.0
154 720.0
155 720.0
156 720.0
157 720.0
158 245.0
159 245.0
160 245.0
161 245.0
162 245.0
163 245.0
164 245.0
165 245.0
166 245.0
167 345.0
168 345.0
169 345.0
170 345.0
171 345.0
172 345.0
173 345.0
174 345.0
175 345.0
176 80.0
177 80.0
178 180.0
179 180.0
180 180.0
181 180.0
182 280.0
183 380.0
184 380.0
185 380.0
186 380.0
187 380.0
188 480.0
189 480.0
190 480.0
191 155.0
192 155.0
193 155.0
194 255.0
195 255.0
196 255.0
197 255.0
198 355.0
199 355.0
200 355.0
201 355.0
202 355.0
203 355.0
204 355.0
205 355.0
206 355.0
207 355.0
208 355.0
209 355.0
210 355.0
211 355.0
212 355.0
213 355.0
214 455.0
215 455.0
216 455.0
217 455.0
218 455.0
219 455.0
220 455.0
221 455.0
222 455.0
223 455.0
224 455.0
225 455.0
226 455.0
227 455.0
228 455.0
229 455.0
230 455.0
231 455.0
232 455.0
233 455.0
234 455.0
235 455.0
236 455.0
237 455.0
238 455.0
239 455.0
240 455.0
241 455.0
242 455.0
243 455.0
244 455.0
245 455.0
246 455.0
247 455.0
248 455.0
249 455.0

model_1
DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')
['gender', "R_Women's Flyweight_rank", 'B_avg_TD_landed', 'R_Bantamweight_rank', 'lose_streak_dif', "B_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'win_dif', 'weight_class', 'R_odds', 'location', 'empty_arena']
9

(3721, 169)

(3721,)

(3721, 2)

(250, 169)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764706  0.235294       1
1       -320      250  0.924528  0.075472       1
2        130     -155  0.295082  0.704918       0
3       -155      135  0.560000  0.440000       1
4       -240      195  0.764706  0.235294       0
..       ...      ...       ...       ...     ...
245      175     -230  0.451613  0.548387       0
246      250     -305  0.336134  0.663866       0
247     -134      105  0.522727  0.477273       1
248     -105     -117  0.582278  0.417722       1
249      115     -143  0.512376  0.487624       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 98
          Number of winning bets: 51
          Number of losing bets: 48
          Number of underdog bets: 54
          Number of underdog wins: 22
          Number of underdog losses: 32
          Number of Favorite bets: 45
          Number of favorite wins: 29
          Number of favorite losses: 16
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 164.33600649695893
          Profit per bet: 1.6768980254791728
          Profit per match: 0.6573440259878357


HI
HI
HI
HI
HI
The original score is 13836.309198636725
Score:  156.78328166688766
Score:  -5491.145756664797
Score:  -16632.882959084513
Score:  -4307.523506266689
Score:  -8432.803836230782
Score:  -8457.840727951723
Score:  -5511.413583015517
Score:  -3053.4060508738853
Score:  1248.5051002858722
Score:  -9660.10914977947
Score:  2909.7086886327756
Score:  8445.085290997333
The EV is different
OLD:
1
NEW:
9

model_1
DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')
['gender', "R_Women's Flyweight_rank", 'B_avg_TD_landed', 'R_Bantamweight_rank', 'lose_streak_dif', "B_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'win_dif', 'weight_class', 'R_odds', 'location', 'empty_arena']
9

(3721, 169)

(3721,)

(3721, 2)

(250, 169)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764706  0.235294       1
1       -320      250  0.924528  0.075472       1
2        130     -155  0.295082  0.704918       0
3       -155      135  0.560000  0.440000       1
4       -240      195  0.764706  0.235294       0
..       ...      ...       ...       ...     ...
245      175     -230  0.451613  0.548387       0
246      250     -305  0.336134  0.663866       0
247     -134      105  0.522727  0.477273       1
248     -105     -117  0.582278  0.417722       1
249      115     -143  0.512376  0.487624       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 98
          Number of winning bets: 51
          Number of losing bets: 48
          Number of underdog bets: 54
          Number of underdog wins: 22
          Number of underdog losses: 32
          Number of Favorite bets: 45
          Number of favorite wins: 29
          Number of favorite losses: 16
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 164.33600649695893
          Profit per bet: 1.6768980254791728
          Profit per match: 0.6573440259878357


HI
HI
HI
HI
HI
Current best score is: 13836.309198636725
NO IMPROVEMENT
FINAL BEST SCORE: 13836.309198636725

model_1
DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')
['gender', "R_Women's Flyweight_rank", 'B_avg_TD_landed', 'R_Bantamweight_rank', 'lose_streak_dif', "B_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'win_dif', 'weight_class', 'R_odds', 'location', 'empty_arena']
9

(3721, 169)

(3721,)

(3721, 2)

(250, 169)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764706  0.235294       1
1       -320      250  0.924528  0.075472       1
2        130     -155  0.295082  0.704918       0
3       -155      135  0.560000  0.440000       1
4       -240      195  0.764706  0.235294       0
..       ...      ...       ...       ...     ...
245      175     -230  0.451613  0.548387       0
246      250     -305  0.336134  0.663866       0
247     -134      105  0.522727  0.477273       1
248     -105     -117  0.582278  0.417722       1
249      115     -143  0.512376  0.487624       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 98
          Number of winning bets: 51
          Number of losing bets: 48
          Number of underdog bets: 54
          Number of underdog wins: 22
          Number of underdog losses: 32
          Number of Favorite bets: 45
          Number of favorite wins: 29
          Number of favorite losses: 16
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 164.33600649695893
          Profit per bet: 1.6768980254791728
          Profit per match: 0.6573440259878357


HI
HI
HI
HI
HI


Starting New Run for DecisionTree


Previous Best Score: 13836.309198636725
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 336 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 336 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 336 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 336 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 336 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 336 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 336 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 336 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 336 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 336 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 336 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 336 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 336 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 336 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 336 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 336 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 336 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 336 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 336 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 336 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 336 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 336 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 336 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 336 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 336 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 336 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 336 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 336 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 336 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 336 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 336 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 336 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 336 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 335 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 335 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 335 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 335 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 335 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 335 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 335 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 335 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 335 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 335 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 335 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 335 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 335 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 335 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 335 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 335 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 4641.312890681343

Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 335 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 335 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 335 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 335 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 335 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 335 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 335 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 335 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 335 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 335 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 335 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 335 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 335 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 335 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 335 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 335 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 335 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 337 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 337 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 337 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 337 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 337 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 337 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 337 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 337 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 337 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 337 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 337 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 337 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 337 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 337 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 337 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 337 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 337 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 337 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 337 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 337 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 337 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 337 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 337 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 337 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 337 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 337 6131.322266123159

Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 337 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 337 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 337 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 337 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 337 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 337 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 337 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 391 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 391 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 391 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.0099 max_leaf_nodes: 391 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 391 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 391 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 391 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.0099 max_leaf_nodes: 391 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 391 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 391 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 391 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.0099 max_leaf_nodes: 391 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 391 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 391 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 391 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.0099 max_leaf_nodes: 391 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 391 2734.7380622716237
Criterion: gini splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 391 13836.309198636725
Criterion: gini splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 391 4641.312890681343
Criterion: entropy splitter: random max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 391 3690.20800784807
Criterion: entropy splitter: best max_depth: 8 min_samples_leaf: 0.009801 max_leaf_nodes: 391 1989.7157883278767
Criterion: gini splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 391 5602.11031082046
Criterion: gini splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 391 7748.676749645672
Criterion: entropy splitter: random max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 391 3804.1449444003665
Criterion: entropy splitter: best max_depth: 7 min_samples_leaf: 0.009801 max_leaf_nodes: 391 5258.4194751194145
Criterion: gini splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 391 6131.322266123159
Criterion: gini splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 391 2524.707181005222
Criterion: entropy splitter: random max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 391 1898.783447131048
Criterion: entropy splitter: best max_depth: 9 min_samples_leaf: 0.009801 max_leaf_nodes: 391 107.99741297473861
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 391 468.63950503058595
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 391 3001.3526349702643
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 391 -2660.17431305374
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009801 max_leaf_nodes: 391 2734.7380622716237
Real output model: DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')

model_1
DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')
['gender', "R_Women's Flyweight_rank", 'B_avg_TD_landed', 'R_Bantamweight_rank', 'lose_streak_dif', "B_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'win_dif', 'weight_class', 'R_odds', 'location', 'empty_arena']
9

(3721, 169)

(3721,)

(3721, 2)

(250, 169)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764706  0.235294       1
1       -320      250  0.924528  0.075472       1
2        130     -155  0.295082  0.704918       0
3       -155      135  0.560000  0.440000       1
4       -240      195  0.764706  0.235294       0
..       ...      ...       ...       ...     ...
245      175     -230  0.451613  0.548387       0
246      250     -305  0.336134  0.663866       0
247     -134      105  0.522727  0.477273       1
248     -105     -117  0.582278  0.417722       1
249      115     -143  0.512376  0.487624       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 98
          Number of winning bets: 51
          Number of losing bets: 48
          Number of underdog bets: 54
          Number of underdog wins: 22
          Number of underdog losses: 32
          Number of Favorite bets: 45
          Number of favorite wins: 29
          Number of favorite losses: 16
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 164.33600649695893
          Profit per bet: 1.6768980254791728
          Profit per match: 0.6573440259878357


HI
HI
HI
HI
HI
0 8484.808113598086
1 9211.4035547255
2 9269.330099391282
3 10572.414137090309
4 8038.017808041334
5 9688.603984290648
6 11752.51025902318
7 10924.78329077315
8 12955.045357870938
9 13836.309198636725
10 11175.037642896536
11 9771.508623221898
12 7886.176898606565
13 6563.187811790607
14 7016.519066908497
15 8245.876682676868
16 8874.805649725076
17 7820.5706569984595
18 6015.705696088722
19 4986.433495171359
20 4283.332479091457
21 4159.703330462307
22 3592.6943739782064
23 3172.146484657559
24 2978.556741067817
25 3046.003549578455
26 1883.7431819267827
27 1783.844192027792
28 2033.225144408745
29 643.9471940981857
30 1163.9471940981857
31 332.65104971754545
32 12.651049717545447
33 -344.27202720553146
34 -409.27202720553146
35 -232.24669533365204
36 -174.16977225672895
37 -34.28157349896492
38 510.7184265010351
39 275.7184265010353
40 550.7184265010351
41 427.4803312629399
42 992.4803312629397
43 493.4803312629399
44 5.523809523809405
45 -164.4761904761906
46 -109.4761904761906
47 390.5238095238094
48 376.0
49 1246.0
50 596.0
51 406.0
52 551.0
53 266.0
54 136.0
55 191.0
56 -419.0
57 -565.0
58 -1155.0
59 -1055.0
60 -1018.0
61 -953.0
62 -1013.0
63 -988.0
64 -1228.0
65 -1128.0
66 -828.0
67 -528.0
68 -588.0
69 -488.0
70 -188.0
71 -143.0
72 57.0
73 -173.0
74 -33.0
75 -313.0
76 -213.0
77 -13.0
78 187.0
79 187.0
80 -373.0
81 -308.0
82 -208.0
83 -488.0
84 -288.0
85 -288.0
86 -188.0
87 12.0
88 212.0
89 312.0
90 312.0
91 412.0
92 612.0
93 292.0
94 -193.0
95 -193.0
96 -193.0
97 -198.0
98 -98.0
99 2.0
100 302.0
101 302.0
102 502.0
103 502.0
104 502.0
105 602.0
106 602.0
107 -23.0
108 77.0
109 77.0
110 0.0
111 100.0
112 200.0
113 600.0
114 600.0
115 700.0
116 800.0
117 800.0
118 800.0
119 900.0
120 1100.0
121 1100.0
122 1100.0
123 1100.0
124 1200.0
125 1400.0
126 1400.0
127 1400.0
128 1230.0
129 1230.0
130 980.0
131 1180.0
132 1180.0
133 1180.0
134 1180.0
135 1180.0
136 1280.0
137 1280.0
138 1380.0
139 720.0
140 820.0
141 820.0
142 820.0
143 750.0
144 850.0
145 850.0
146 850.0
147 850.0
148 850.0
149 850.0
150 720.0
151 720.0
152 720.0
153 720.0
154 720.0
155 720.0
156 720.0
157 720.0
158 245.0
159 245.0
160 245.0
161 245.0
162 245.0
163 245.0
164 245.0
165 245.0
166 245.0
167 345.0
168 345.0
169 345.0
170 345.0
171 345.0
172 345.0
173 345.0
174 345.0
175 345.0
176 80.0
177 80.0
178 180.0
179 180.0
180 180.0
181 180.0
182 280.0
183 380.0
184 380.0
185 380.0
186 380.0
187 380.0
188 480.0
189 480.0
190 480.0
191 155.0
192 155.0
193 155.0
194 255.0
195 255.0
196 255.0
197 255.0
198 355.0
199 355.0
200 355.0
201 355.0
202 355.0
203 355.0
204 355.0
205 355.0
206 355.0
207 355.0
208 355.0
209 355.0
210 355.0
211 355.0
212 355.0
213 355.0
214 455.0
215 455.0
216 455.0
217 455.0
218 455.0
219 455.0
220 455.0
221 455.0
222 455.0
223 455.0
224 455.0
225 455.0
226 455.0
227 455.0
228 455.0
229 455.0
230 455.0
231 455.0
232 455.0
233 455.0
234 455.0
235 455.0
236 455.0
237 455.0
238 455.0
239 455.0
240 455.0
241 455.0
242 455.0
243 455.0
244 455.0
245 455.0
246 455.0
247 455.0
248 455.0
249 455.0

model_1
DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')
['gender', "R_Women's Flyweight_rank", 'B_avg_TD_landed', 'R_Bantamweight_rank', 'lose_streak_dif', "B_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'win_dif', 'weight_class', 'R_odds', 'location', 'empty_arena']
9

(3721, 169)

(3721,)

(3721, 2)

(250, 169)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764706  0.235294       1
1       -320      250  0.924528  0.075472       1
2        130     -155  0.295082  0.704918       0
3       -155      135  0.560000  0.440000       1
4       -240      195  0.764706  0.235294       0
..       ...      ...       ...       ...     ...
245      175     -230  0.451613  0.548387       0
246      250     -305  0.336134  0.663866       0
247     -134      105  0.522727  0.477273       1
248     -105     -117  0.582278  0.417722       1
249      115     -143  0.512376  0.487624       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 98
          Number of winning bets: 51
          Number of losing bets: 48
          Number of underdog bets: 54
          Number of underdog wins: 22
          Number of underdog losses: 32
          Number of Favorite bets: 45
          Number of favorite wins: 29
          Number of favorite losses: 16
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 164.33600649695893
          Profit per bet: 1.6768980254791728
          Profit per match: 0.6573440259878357


HI
HI
HI
HI
HI
The original score is 13836.309198636725
Score:  156.78328166688766
Score:  -5491.145756664797
Score:  -16632.882959084513
Score:  -4307.523506266689
Score:  -8432.803836230782
Score:  -8457.840727951723
Score:  -5511.413583015517
Score:  -3053.4060508738853
Score:  1248.5051002858722
Score:  -9660.10914977947
Score:  2909.7086886327756
Score:  8445.085290997333

model_1
DecisionTreeClassifier(max_depth=8, max_leaf_nodes=336, min_samples_leaf=0.0099,
                       random_state=75, splitter='random')
['gender', "R_Women's Flyweight_rank", 'B_avg_TD_landed', 'R_Bantamweight_rank', 'lose_streak_dif', "B_Women's Flyweight_rank", 'R_win_by_Decision_Split', 'win_dif', 'weight_class', 'R_odds', 'location', 'empty_arena']
9

(3721, 169)

(3721,)

(3721, 2)

(250, 169)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764706  0.235294       1
1       -320      250  0.924528  0.075472       1
2        130     -155  0.295082  0.704918       0
3       -155      135  0.560000  0.440000       1
4       -240      195  0.764706  0.235294       0
..       ...      ...       ...       ...     ...
245      175     -230  0.451613  0.548387       0
246      250     -305  0.336134  0.663866       0
247     -134      105  0.522727  0.477273       1
248     -105     -117  0.582278  0.417722       1
249      115     -143  0.512376  0.487624       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 98
          Number of winning bets: 51
          Number of losing bets: 48
          Number of underdog bets: 54
          Number of underdog wins: 22
          Number of underdog losses: 32
          Number of Favorite bets: 45
          Number of favorite wins: 29
          Number of favorite losses: 16
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 164.33600649695893
          Profit per bet: 1.6768980254791728
          Profit per match: 0.6573440259878357


HI
HI
HI
HI
HI

(3721, 169)

(3721,)

(3721, 2)

(250, 169)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764706  0.235294       1
1       -320      250  0.924528  0.075472       1
2        130     -155  0.295082  0.704918       0
3       -155      135  0.560000  0.440000       1
4       -240      195  0.764706  0.235294       0
..       ...      ...       ...       ...     ...
245      175     -230  0.451613  0.548387       0
246      250     -305  0.336134  0.663866       0
247     -134      105  0.522727  0.477273       1
248     -105     -117  0.582278  0.417722       1
249      115     -143  0.512376  0.487624       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 98
          Number of winning bets: 51
          Number of losing bets: 48
          Number of underdog bets: 54
          Number of underdog wins: 22
          Number of underdog losses: 32
          Number of Favorite bets: 45
          Number of favorite wins: 29
          Number of favorite losses: 16
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 164.33600649695893
          Profit per bet: 1.6768980254791728
          Profit per match: 0.6573440259878357


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 2


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_2
RandomForestClassifier(criterion='entropy', max_depth=83, max_features=None,
                       max_leaf_nodes=20, min_samples_leaf=0.01009899,
                       n_estimators=140, n_jobs=-1, random_state=75)
['B_odds', 'R_draw', 'R_Middleweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'total_title_bout_dif', 'better_rank', 'sig_str_dif', 'R_Weight_lbs', 'R_avg_TD_landed', 'no_of_rounds', 'B_draw', 'country', 'B_ev', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']
1
Current best score is: 13342.955086256316
Feature: B_total_rounds_fought Score: 13509.693945025512
Feature: B_win_by_Decision_Split Score: 13828.120812728364
Feature: avg_td_dif Score: 14417.362369498476
The best feature was avg_td_dif.  It scored 14417.362369498476
Current best score is: 14417.362369498476
Feature: R_Pound-for-Pound_rank Score: 14452.77471625536
Feature: B_Pound-for-Pound_rank Score: 14480.08964222575
The best feature was B_Pound-for-Pound_rank.  It scored 14480.08964222575
Current best score is: 14480.08964222575
Feature: B_total_title_bouts Score: 14651.961343517349
Feature: R_current_lose_streak Score: 14731.979458879941
The best feature was R_current_lose_streak.  It scored 14731.979458879941
Current best score is: 14731.979458879941
Feature: gender Score: 14925.601253606954
The best feature was gender.  It scored 14925.601253606954
Current best score is: 14925.601253606954
Feature: R_Welterweight_rank Score: 14941.857898012022
The best feature was R_Welterweight_rank.  It scored 14941.857898012022
Current best score is: 14941.857898012022
Feature: B_win_by_Decision_Majority Score: 15334.287247247179
Feature: R_Women's Strawweight_rank Score: 15398.803376279437
The best feature was R_Women's Strawweight_rank.  It scored 15398.803376279437
Current best score is: 15398.803376279437
NO IMPROVEMENT
FINAL BEST SCORE: 15398.803376279437

model_2
RandomForestClassifier(criterion='entropy', max_depth=83, max_features=None,
                       max_leaf_nodes=20, min_samples_leaf=0.01009899,
                       n_estimators=140, n_jobs=-1, random_state=75)
["R_Women's Strawweight_rank", 'R_Welterweight_rank', 'gender', 'R_current_lose_streak', 'B_Pound-for-Pound_rank', 'avg_td_dif', 'B_odds', 'R_draw', 'R_Middleweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'total_title_bout_dif', 'better_rank', 'sig_str_dif', 'R_Weight_lbs', 'R_avg_TD_landed', 'no_of_rounds', 'B_draw', 'country', 'B_ev', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']
1

(3601, 55)

(3601,)

(3601, 2)

(250, 55)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.642396  0.357604       1
1       -320      250  0.741981  0.258019       1
2        130     -155  0.512509  0.487491       0
3       -155      135  0.498026  0.501974       1
4       -240      195  0.674856  0.325144       0
..       ...      ...       ...       ...     ...
245      175     -230  0.386478  0.613522       0
246      250     -305  0.419217  0.580783       0
247     -134      105  0.551043  0.448957       1
248     -105     -117  0.568189  0.431811       1
249      115     -143  0.556241  0.443759       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 167
          Number of winning bets: 86
          Number of losing bets: 83
          Number of underdog bets: 112
          Number of underdog wins: 46
          Number of underdog losses: 66
          Number of Favorite bets: 56
          Number of favorite wins: 40
          Number of favorite losses: 16
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 161.77754938359948
          Profit per bet: 0.9687278406203561
          Profit per match: 0.6471101975343979


HI
HI
HI
HI
HI


Starting New Run for RandomForestClassifier


Previous Best Score: 15398.803376279437
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 9996.345656676822
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 6972.5409957132715
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 6226.332779263632
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 6673.9092021531505
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 14237.42036192203
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 15398.803376279437
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 8434.288604167994
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 7540.066864034924
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 6062.077042571023
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 7110.257395623258
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 13632.462238896955
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 140 14759.323858301424
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 9996.345656676822
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 6972.5409957132715
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 6226.332779263632
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 6673.9092021531505
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 14237.42036192203
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 15398.803376279437
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 8434.288604167994
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 7540.066864034924
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 6062.077042571023
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 7110.257395623258
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 13632.462238896955
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 140 14759.323858301424
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 8458.384728909012
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 9225.076966665169
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 7544.448683557873
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 6571.666506906219
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 13941.000939154565
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 12049.591843570324
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 7703.581149494565
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 7938.477420966454
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 6698.190480904594
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 7708.929032878514
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 13396.813069305035
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 140 13024.796518350624
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 10821.53917734593
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 6102.944646239167
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 6477.82214058196
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 9971.081622736845
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 12271.970474789232
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 12937.15434526964
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 10389.368403067612
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 6066.844989229516
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 4334.581030892601
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 10006.035624194563
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 9269.429353930418
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 140 13339.73435631096
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 10821.53917734593
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 6102.944646239167
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 6477.82214058196
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 9971.081622736845
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 12271.970474789232
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 12937.15434526964
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 10389.368403067612

Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 6066.844989229516
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 4334.581030892601
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 10006.035624194563
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 9269.429353930418
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 140 13339.73435631096
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 7413.883786897013
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 7022.523392106741
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 10451.66617901277
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 8003.1381818149175
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 11204.616812109025
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 13499.61175946466
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 8137.341559894867
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 8321.496424359782
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 8702.042884016391
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 9680.942263794164
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 11633.222299056324
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 140 12590.069446375033
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 5179.278184905981
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 4661.489430868311
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 4179.846781857057
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 219.0224167300546
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 10071.47053333237
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 9828.795066583865
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 6088.203760578882
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 3392.1499426336886
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 4295.280684036602
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 -334.93738774437327
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 10297.540346655718
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 n_estimators 17 9660.978974629841
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 5179.278184905981
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 4661.489430868311
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 4179.846781857057
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 219.0224167300546
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 10071.47053333237
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 9828.795066583865
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 6088.203760578882
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 3392.1499426336886
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 4295.280684036602
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 -334.93738774437327
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 10297.540346655718
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 20 n_estimators 17 9660.978974629841
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 4401.957384263938
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 4217.198006665272
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 5916.846602072895
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 -1369.8042919644722
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 8622.152268902395
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 11122.64045831475
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 5061.465720878693
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 1245.936965202467
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 6599.874809334809
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 -3809.6996965326152
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 10563.893103518378
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 20 n_estimators 17 11122.64045831475
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 10554.33615064327
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 3155.621014777856
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 4095.2777011922567
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 211.54333918404632
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 9028.948894878366
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 5706.074267162277

NEW BEST SCORE
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 15826.690634183573

Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 4098.705561308381
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 2237.2869133727845
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 -934.5032590114304
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 7902.08564757702
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 8828.8525948926
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 10554.33615064327
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 3155.621014777856
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 4095.2777011922567
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 211.54333918404632
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 9028.948894878366
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 5706.074267162277
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 15826.690634183573
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 4098.705561308381
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 2237.2869133727845
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 -934.5032590114304
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 7902.08564757702
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 8828.8525948926
Criterion: gini max_features: auto max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 7737.439512638754
Criterion: entropy max_features: auto max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 3899.6006978379746
Criterion: gini max_features: log2 max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 2693.7678774918695
Criterion: entropy max_features: log2 max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 -3962.3570825867446
Criterion: gini max_features: None max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 10989.988866088159
Criterion: entropy max_features: None max_depth: 83 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 6903.4470774468045
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 4332.940998753467
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 -909.6254214487838
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 4267.804884405346
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 -4258.489249042016
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 11066.27805351432
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 6290.198376190478
[[140, 17], [20, 845], [0.01009899, 0.010199979900000001, 0.0099980001], [83, 9], ['auto', 'log2', None], ['gini', 'entropy']]
6


Starting New Run for RandomForestClassifier


Previous Best Score: 15826.690634183573
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 10554.33615064327
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 3155.621014777856
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 4095.2777011922567
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 211.54333918404632
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 9028.948894878366
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 5706.074267162277
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 10554.33615064327
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 3155.621014777856
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 4095.2777011922567
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 211.54333918404632
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 9028.948894878366
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 5706.074267162277
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
PASS.  We have already tested this.
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 7737.439512638754
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 3899.6006978379746
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 2693.7678774918695
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 -3962.3570825867446
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 10989.988866088159
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 6903.4470774468045
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 15826.690634183573
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 4098.705561308381
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 2237.2869133727845
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 -934.5032590114304
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 7902.08564757702
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 8828.8525948926
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 10554.33615064327

Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 3155.621014777856
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 4095.2777011922567
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 211.54333918404632
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 9028.948894878366
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 17 5706.074267162277
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 15826.690634183573
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 4098.705561308381
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 2237.2869133727845
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 -934.5032590114304
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 7902.08564757702
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 8828.8525948926
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 10554.33615064327
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 3155.621014777856
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 4095.2777011922567
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 211.54333918404632
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 9028.948894878366
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 17 5706.074267162277
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 4332.940998753467
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 -909.6254214487838
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 4267.804884405346
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 -4258.489249042016
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 11066.27805351432
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 6290.198376190478
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 7737.439512638754
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 3899.6006978379746
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 2693.7678774918695
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 -3962.3570825867446
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 10989.988866088159
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 17 6903.4470774468045
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 11734.19140481351
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 5297.402988039256
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 8538.068666034429
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 9814.013508506834
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 11326.944314353299
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 12847.892517160515
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 11273.007341094832
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 5849.909733870514
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 7299.269278304255
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 10400.43152456321
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 10826.208724899385
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 93 13155.259829226521
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 11734.19140481351
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 5297.402988039256
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 8538.068666034429
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 9814.013508506834
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 11326.944314353299
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 12847.892517160515
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 11273.007341094832
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 5849.909733870514
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 7299.269278304255
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 10400.43152456321
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 10826.208724899385
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 93 13155.259829226521
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 9765.360867868792
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 7266.646295179175
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 7714.0388196673375
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 9600.297536467777
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 10971.149634332516
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 11308.913806461424
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 9166.895218581227

Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 6730.276926045509
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 6724.788551882399
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 10503.561165282295
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 10401.407026814823
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 93 12815.01936915489
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 11734.19140481351
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 5297.402988039256
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 8538.068666034429
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 9814.013508506834
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 11326.944314353299
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 12847.892517160515
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 11273.007341094832
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 5849.909733870514
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 7299.269278304255
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 10400.43152456321
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 10826.208724899385
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 712 n_estimators 93 13155.259829226521
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 11734.19140481351
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 5297.402988039256
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 8538.068666034429
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 9814.013508506834
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 11326.944314353299
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 12847.892517160515
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 11273.007341094832
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 5849.909733870514
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 7299.269278304255
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 10400.43152456321
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 10826.208724899385
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 712 n_estimators 93 13155.259829226521
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 9765.360867868792
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 7266.646295179175
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 7714.0388196673375
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 9600.297536467777
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 10971.149634332516
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 11308.913806461424
Criterion: gini max_features: auto max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 9166.895218581227
Criterion: entropy max_features: auto max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 6730.276926045509
Criterion: gini max_features: log2 max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 6724.788551882399
Criterion: entropy max_features: log2 max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 10503.561165282295
Criterion: gini max_features: None max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 10401.407026814823
Criterion: entropy max_features: None max_depth: 84 min_samples_leaf: 0.0099980001 max_leaf_nodes: 712 n_estimators 93 12815.01936915489
[[17, 93], [845, 712], [0.01009899, 0.010199979900000001, 0.0099980001], [9, 84], ['auto', 'log2', None], ['gini', 'entropy']]
6
Real output model: RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)

model_2
RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)
["R_Women's Strawweight_rank", 'R_Welterweight_rank', 'gender', 'R_current_lose_streak', 'B_Pound-for-Pound_rank', 'avg_td_dif', 'B_odds', 'R_draw', 'R_Middleweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'total_title_bout_dif', 'better_rank', 'sig_str_dif', 'R_Weight_lbs', 'R_avg_TD_landed', 'no_of_rounds', 'B_draw', 'country', 'B_ev', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']
1

(3601, 55)

(3601,)

(3601, 2)

(250, 55)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.652651  0.347349       1
1       -320      250  0.757546  0.242454       1
2        130     -155  0.477863  0.522137       0
3       -155      135  0.576915  0.423085       1
4       -240      195  0.668680  0.331320       0
..       ...      ...       ...       ...     ...
245      175     -230  0.406036  0.593964       0
246      250     -305  0.495166  0.504834       0
247     -134      105  0.564656  0.435344       1
248     -105     -117  0.554330  0.445670       1
249      115     -143  0.545113  0.454887       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 179
          Number of winning bets: 83
          Number of losing bets: 97
          Number of underdog bets: 131
          Number of underdog wins: 49
          Number of underdog losses: 82
          Number of Favorite bets: 47
          Number of favorite wins: 34
          Number of favorite losses: 13
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -785.2211020075208
          Profit per bet: -4.386710067081122
          Profit per match: -3.1408844080300833


HI
HI
HI
HI
HI
0 16525.781183602838
1 15826.690634183573
2 14532.383783019213
3 14205.67728732052
4 13995.998997692648
5 11055.953966029232
6 10877.198887191396
7 8373.030959821086
8 9534.252412296253
9 9974.828181933895
10 10820.98148606335
11 10467.116537226622
12 10115.08476043464
13 10124.160761650859
14 10006.21028178401
15 8819.451982309609
16 9786.793079618095
17 8821.979415021822
18 8972.467787114845
19 8289.229691876752
20 8064.2296918767515
21 7020.991596638656
22 6840.753501400561
23 6100.515406162465
24 6140.27731092437
25 5400.0392156862745
26 5180.0392156862745
27 4165.0392156862745
28 4305.0392156862745
29 3585.0
30 3155.0
31 1935.0
32 2755.0
33 3500.0
34 3670.0
35 3980.0
36 3838.0
37 3223.0
38 2683.0
39 2443.0
40 2873.0
41 1963.0
42 1373.0
43 1443.0
44 1973.0
45 1818.0
46 1438.0
47 1743.0
48 2543.0
49 1983.0
50 1988.0
51 2588.0
52 2988.0
53 3588.0
54 3643.0
55 4043.0
56 4643.0
57 3933.0
58 3963.0
59 1798.0
60 1393.0
61 983.0
62 23.0
63 23.0
64 188.0
65 188.0
66 -382.0
67 -182.0
68 -142.0
69 -122.0
70 78.0
71 278.0
72 -272.0
73 28.0
74 -402.0
75 -102.0
76 -192.0
77 -92.0
78 8.0
79 -515.0
80 -215.0
81 -215.0
82 -215.0
83 -825.0
84 -725.0
85 -725.0
86 -625.0
87 -525.0
88 -425.0
89 -225.0
90 -125.0
91 -125.0
92 -25.0
93 -95.0
94 -95.0
95 -170.0
96 -495.0
97 -815.0
98 -715.0
99 -840.0
100 -840.0
101 -740.0
102 -440.0
103 -440.0
104 -140.0
105 -140.0
106 60.0
107 60.0
108 60.0
109 -110.0
110 -10.0
111 90.0
112 190.0
113 190.0
114 290.0
115 390.0
116 590.0
117 590.0
118 690.0
119 890.0
120 890.0
121 890.0
122 890.0
123 890.0
124 890.0
125 1090.0
126 690.0
127 690.0
128 690.0
129 690.0
130 690.0
131 790.0
132 790.0
133 790.0
134 790.0
135 790.0
136 990.0
137 990.0
138 1090.0
139 1090.0
140 1090.0
141 1190.0
142 1190.0
143 1190.0
144 1190.0
145 1190.0
146 1190.0
147 1190.0
148 1190.0
149 535.0
150 535.0
151 535.0
152 535.0
153 50.0
154 -300
155 -300
156 -300
157 -300
158 -300
159 -300
160 -300
161 -300
162 -300
163 -300
164 -300
165 -300
166 -300
167 -300
168 -300
169 -300
170 -300
171 -200
172 -200
173 -200
174 -200
175 -200
176 -200
177 -200
178 -200
179 -200
180 -200
181 -200
182 -200
183 -200
184 -200
185 -200
186 -200
187 -200
188 -200
189 -200
190 -200
191 -200
192 -200
193 -200
194 -200
195 -200
196 -200
197 -200
198 -200
199 -200
200 -200
201 -200
202 -200
203 -100
204 -100
205 -100
206 -100
207 -100
208 0
209 0
210 0
211 0
212 0
213 0
214 0
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0
239 0
240 0
241 0
242 0
243 0
244 0
245 0
246 0
247 0
248 0
249 0

model_2
RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)
["R_Women's Strawweight_rank", 'R_Welterweight_rank', 'gender', 'R_current_lose_streak', 'B_Pound-for-Pound_rank', 'avg_td_dif', 'B_odds', 'R_draw', 'R_Middleweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'total_title_bout_dif', 'better_rank', 'sig_str_dif', 'R_Weight_lbs', 'R_avg_TD_landed', 'no_of_rounds', 'B_draw', 'country', 'B_ev', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']
0

(3601, 55)

(3601,)

(3601, 2)

(250, 55)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.652651  0.347349       1
1       -320      250  0.757546  0.242454       1
2        130     -155  0.477863  0.522137       0
3       -155      135  0.576915  0.423085       1
4       -240      195  0.668680  0.331320       0
..       ...      ...       ...       ...     ...
245      175     -230  0.406036  0.593964       0
246      250     -305  0.495166  0.504834       0
247     -134      105  0.564656  0.435344       1
248     -105     -117  0.554330  0.445670       1
249      115     -143  0.545113  0.454887       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 192
          Number of winning bets: 91
          Number of losing bets: 102
          Number of underdog bets: 137
          Number of underdog wins: 52
          Number of underdog losses: 85
          Number of Favorite bets: 54
          Number of favorite wins: 39
          Number of favorite losses: 15
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -724.7527920960694
          Profit per bet: -3.7747541255003614
          Profit per match: -2.8990111683842774


HI
HI
HI
HI
HI
The original score is 16525.781183602838
Score:  11052.601619632293
Score:  7390.175464919791
Score:  13502.354262802135
Score:  6378.6069322745625
Score:  8901.255813634973
Score:  7549.439963624699
Score:  4704.883029251023
Score:  4433.644158095384
Score:  2120.0747221248266
Score:  -1235.520586262914
Score:  6277.002530884942
Score:  6780.361818617814
Score:  5576.698280785949
Score:  4837.844331243852
Score:  8567.088247067608
Score:  14315.194821374036
Score:  5936.883133774356
Score:  4971.222863731553
Score:  3669.2554584076943
Score:  9828.386334626954
Score:  8863.11928962146
Score:  11740.31212877604
Score:  2857.7203409134067
Score:  8403.374308477676
Score:  3077.314488137415
The hyperparameters are different
OLD:
RandomForestClassifier(criterion='entropy', max_depth=83, max_features=None,
                       max_leaf_nodes=20, min_samples_leaf=0.01009899,
                       n_estimators=140, n_jobs=-1, random_state=75)
NEW:
RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)
The EV is different
OLD:
1
NEW:
0

model_2
RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)
["R_Women's Strawweight_rank", 'R_Welterweight_rank', 'gender', 'R_current_lose_streak', 'B_Pound-for-Pound_rank', 'avg_td_dif', 'B_odds', 'R_draw', 'R_Middleweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'total_title_bout_dif', 'better_rank', 'sig_str_dif', 'R_Weight_lbs', 'R_avg_TD_landed', 'no_of_rounds', 'B_draw', 'country', 'B_ev', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']
0

(3601, 55)

(3601,)

(3601, 2)

(250, 55)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.652651  0.347349       1
1       -320      250  0.757546  0.242454       1
2        130     -155  0.477863  0.522137       0
3       -155      135  0.576915  0.423085       1
4       -240      195  0.668680  0.331320       0
..       ...      ...       ...       ...     ...
245      175     -230  0.406036  0.593964       0
246      250     -305  0.495166  0.504834       0
247     -134      105  0.564656  0.435344       1
248     -105     -117  0.554330  0.445670       1
249      115     -143  0.545113  0.454887       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 192
          Number of winning bets: 91
          Number of losing bets: 102
          Number of underdog bets: 137
          Number of underdog wins: 52
          Number of underdog losses: 85
          Number of Favorite bets: 54
          Number of favorite wins: 39
          Number of favorite losses: 15
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -724.7527920960694
          Profit per bet: -3.7747541255003614
          Profit per match: -2.8990111683842774


HI
HI
HI
HI
HI
Current best score is: 16525.781183602838
NO IMPROVEMENT
FINAL BEST SCORE: 16525.781183602838

model_2
RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)
["R_Women's Strawweight_rank", 'R_Welterweight_rank', 'gender', 'R_current_lose_streak', 'B_Pound-for-Pound_rank', 'avg_td_dif', 'B_odds', 'R_draw', 'R_Middleweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'total_title_bout_dif', 'better_rank', 'sig_str_dif', 'R_Weight_lbs', 'R_avg_TD_landed', 'no_of_rounds', 'B_draw', 'country', 'B_ev', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']
0

(3601, 55)

(3601,)

(3601, 2)

(250, 55)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.652651  0.347349       1
1       -320      250  0.757546  0.242454       1
2        130     -155  0.477863  0.522137       0
3       -155      135  0.576915  0.423085       1
4       -240      195  0.668680  0.331320       0
..       ...      ...       ...       ...     ...
245      175     -230  0.406036  0.593964       0
246      250     -305  0.495166  0.504834       0
247     -134      105  0.564656  0.435344       1
248     -105     -117  0.554330  0.445670       1
249      115     -143  0.545113  0.454887       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 192
          Number of winning bets: 91
          Number of losing bets: 102
          Number of underdog bets: 137
          Number of underdog wins: 52
          Number of underdog losses: 85
          Number of Favorite bets: 54
          Number of favorite wins: 39
          Number of favorite losses: 15
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -724.7527920960694
          Profit per bet: -3.7747541255003614
          Profit per match: -2.8990111683842774


HI
HI
HI
HI
HI


Starting New Run for RandomForestClassifier


Previous Best Score: 16525.781183602838
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 16525.781183602838
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 2910.3596107085023
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 2571.119104032031
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 -2964.1163786592224
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 7159.500291677125
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 7619.646680917869
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 12588.490393613652
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 3753.083822509485
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 1879.23950325243
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 -3450.282848695999
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 8009.357165149393
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 17 5829.042631756345
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 16525.781183602838
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 2910.3596107085023
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 2571.119104032031
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 -2964.1163786592224
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 7159.500291677125
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 7619.646680917869
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 12588.490393613652
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 3753.083822509485
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 1879.23950325243
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 -3450.282848695999
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 8009.357165149393
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 17 5829.042631756345
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 4712.60840889481
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 161.84029009754659
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 3561.9914754142087
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 -6986.485970423168
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 10554.130139824469
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 5840.868290678272
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 7226.268329596283
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 3829.3216209107236
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 234.44659760533114
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 -4854.276458829394
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 11042.59949451567
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 17 5430.263270098312
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 16525.781183602838
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 2910.3596107085023
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 2571.119104032031
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 -2964.1163786592224
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 7159.500291677125
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 7619.646680917869
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 12588.490393613652
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 3753.083822509485
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 1879.23950325243
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 -3450.282848695999
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 8009.357165149393
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 17 5829.042631756345
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 16525.781183602838
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 2910.3596107085023
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 2571.119104032031
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 -2964.1163786592224
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 7159.500291677125
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 7619.646680917869
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 12588.490393613652

Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 3753.083822509485
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 1879.23950325243
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 -3450.282848695999
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 8009.357165149393
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 17 5829.042631756345
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 4712.60840889481
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 161.84029009754659
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 3561.9914754142087
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 -6986.485970423168
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 10554.130139824469
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 5840.868290678272
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 7226.268329596283
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 3829.3216209107236
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 234.44659760533114
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 -4854.276458829394
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 11042.59949451567
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 17 5430.263270098312
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 14197.864136827991
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 8755.390518090251
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 5631.709619832394
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 3783.26865378401
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 11932.32957870014
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 7284.68318732612
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 14178.19468363341
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 6204.414472554971
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 6031.071449124899
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 6302.107794194602
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 11398.241634205348
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 845 n_estimators 32 8789.40740350679
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 14197.864136827991
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 8755.390518090251
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 5631.709619832394
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 3783.26865378401
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 11932.32957870014
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 7284.68318732612
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 14178.19468363341
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 6204.414472554971
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 6031.071449124899
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 6302.107794194602
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 11398.241634205348
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 845 n_estimators 32 8789.40740350679
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 8965.103824769818
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 4969.68785694017
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 4907.9721063558245
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 3301.811147774211
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 14054.452329007621
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 12400.325733393081
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 10342.714416356059
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 5768.205314458276
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 4570.580772528416
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 4351.667748156424
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 14301.665986988884
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 845 n_estimators 32 11366.256458831944
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 14197.864136827991
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 8755.390518090251
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 5631.709619832394
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 3783.26865378401
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 11932.32957870014
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 7284.68318732612
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 14178.19468363341

Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 6204.414472554971
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 6031.071449124899
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 6302.107794194602
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 11398.241634205348
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.01009899 max_leaf_nodes: 413 n_estimators 32 8789.40740350679
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 14197.864136827991
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 8755.390518090251
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 5631.709619832394
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 3783.26865378401
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 11932.32957870014
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 7284.68318732612
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 14178.19468363341
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 6204.414472554971
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 6031.071449124899
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 6302.107794194602
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 11398.241634205348
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.010199979900000001 max_leaf_nodes: 413 n_estimators 32 8789.40740350679
Criterion: gini max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 8965.103824769818
Criterion: entropy max_features: auto max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 4969.68785694017
Criterion: gini max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 4907.9721063558245
Criterion: entropy max_features: log2 max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 3301.811147774211
Criterion: gini max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 14054.452329007621
Criterion: entropy max_features: None max_depth: 9 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 12400.325733393081
Criterion: gini max_features: auto max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 10342.714416356059
Criterion: entropy max_features: auto max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 5768.205314458276
Criterion: gini max_features: log2 max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 4570.580772528416
Criterion: entropy max_features: log2 max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 4351.667748156424
Criterion: gini max_features: None max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 14301.665986988884
Criterion: entropy max_features: None max_depth: 95 min_samples_leaf: 0.0099980001 max_leaf_nodes: 413 n_estimators 32 11366.256458831944
[[17, 32], [845, 413], [0.01009899, 0.010199979900000001, 0.0099980001], [9, 95], ['auto', 'log2', None], ['gini', 'entropy']]
6
Real output model: RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)

model_2
RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)
["R_Women's Strawweight_rank", 'R_Welterweight_rank', 'gender', 'R_current_lose_streak', 'B_Pound-for-Pound_rank', 'avg_td_dif', 'B_odds', 'R_draw', 'R_Middleweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'total_title_bout_dif', 'better_rank', 'sig_str_dif', 'R_Weight_lbs', 'R_avg_TD_landed', 'no_of_rounds', 'B_draw', 'country', 'B_ev', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']
0

(3601, 55)

(3601,)

(3601, 2)

(250, 55)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.652651  0.347349       1
1       -320      250  0.757546  0.242454       1
2        130     -155  0.477863  0.522137       0
3       -155      135  0.576915  0.423085       1
4       -240      195  0.668680  0.331320       0
..       ...      ...       ...       ...     ...
245      175     -230  0.406036  0.593964       0
246      250     -305  0.495166  0.504834       0
247     -134      105  0.564656  0.435344       1
248     -105     -117  0.554330  0.445670       1
249      115     -143  0.545113  0.454887       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 192
          Number of winning bets: 91
          Number of losing bets: 102
          Number of underdog bets: 137
          Number of underdog wins: 52
          Number of underdog losses: 85
          Number of Favorite bets: 54
          Number of favorite wins: 39
          Number of favorite losses: 15
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -724.7527920960694
          Profit per bet: -3.7747541255003614
          Profit per match: -2.8990111683842774


HI
HI
HI
HI
HI
0 16525.781183602838
1 15826.690634183573
2 14532.383783019213
3 14205.67728732052
4 13995.998997692648
5 11055.953966029232
6 10877.198887191396
7 8373.030959821086
8 9534.252412296253
9 9974.828181933895
10 10820.98148606335
11 10467.116537226622
12 10115.08476043464
13 10124.160761650859
14 10006.21028178401
15 8819.451982309609
16 9786.793079618095
17 8821.979415021822
18 8972.467787114845
19 8289.229691876752
20 8064.2296918767515
21 7020.991596638656
22 6840.753501400561
23 6100.515406162465
24 6140.27731092437
25 5400.0392156862745
26 5180.0392156862745
27 4165.0392156862745
28 4305.0392156862745
29 3585.0
30 3155.0
31 1935.0
32 2755.0
33 3500.0
34 3670.0
35 3980.0
36 3838.0
37 3223.0
38 2683.0
39 2443.0
40 2873.0
41 1963.0
42 1373.0
43 1443.0
44 1973.0
45 1818.0
46 1438.0
47 1743.0
48 2543.0
49 1983.0
50 1988.0
51 2588.0
52 2988.0
53 3588.0
54 3643.0
55 4043.0
56 4643.0
57 3933.0
58 3963.0
59 1798.0
60 1393.0
61 983.0
62 23.0
63 23.0
64 188.0
65 188.0
66 -382.0
67 -182.0
68 -142.0
69 -122.0
70 78.0
71 278.0
72 -272.0
73 28.0
74 -402.0
75 -102.0
76 -192.0
77 -92.0
78 8.0
79 -515.0
80 -215.0
81 -215.0
82 -215.0
83 -825.0
84 -725.0
85 -725.0
86 -625.0
87 -525.0
88 -425.0
89 -225.0
90 -125.0
91 -125.0
92 -25.0
93 -95.0
94 -95.0
95 -170.0
96 -495.0
97 -815.0
98 -715.0
99 -840.0
100 -840.0
101 -740.0
102 -440.0
103 -440.0
104 -140.0
105 -140.0
106 60.0
107 60.0
108 60.0
109 -110.0
110 -10.0
111 90.0
112 190.0
113 190.0
114 290.0
115 390.0
116 590.0
117 590.0
118 690.0
119 890.0
120 890.0
121 890.0
122 890.0
123 890.0
124 890.0
125 1090.0
126 690.0
127 690.0
128 690.0
129 690.0
130 690.0
131 790.0
132 790.0
133 790.0
134 790.0
135 790.0
136 990.0
137 990.0
138 1090.0
139 1090.0
140 1090.0
141 1190.0
142 1190.0
143 1190.0
144 1190.0
145 1190.0
146 1190.0
147 1190.0
148 1190.0
149 535.0
150 535.0
151 535.0
152 535.0
153 50.0
154 -300
155 -300
156 -300
157 -300
158 -300
159 -300
160 -300
161 -300
162 -300
163 -300
164 -300
165 -300
166 -300
167 -300
168 -300
169 -300
170 -300
171 -200
172 -200
173 -200
174 -200
175 -200
176 -200
177 -200
178 -200
179 -200
180 -200
181 -200
182 -200
183 -200
184 -200
185 -200
186 -200
187 -200
188 -200
189 -200
190 -200
191 -200
192 -200
193 -200
194 -200
195 -200
196 -200
197 -200
198 -200
199 -200
200 -200
201 -200
202 -200
203 -100
204 -100
205 -100
206 -100
207 -100
208 0
209 0
210 0
211 0
212 0
213 0
214 0
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0
239 0
240 0
241 0
242 0
243 0
244 0
245 0
246 0
247 0
248 0
249 0

model_2
RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)
["R_Women's Strawweight_rank", 'R_Welterweight_rank', 'gender', 'R_current_lose_streak', 'B_Pound-for-Pound_rank', 'avg_td_dif', 'B_odds', 'R_draw', 'R_Middleweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'total_title_bout_dif', 'better_rank', 'sig_str_dif', 'R_Weight_lbs', 'R_avg_TD_landed', 'no_of_rounds', 'B_draw', 'country', 'B_ev', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']
0

(3601, 55)

(3601,)

(3601, 2)

(250, 55)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.652651  0.347349       1
1       -320      250  0.757546  0.242454       1
2        130     -155  0.477863  0.522137       0
3       -155      135  0.576915  0.423085       1
4       -240      195  0.668680  0.331320       0
..       ...      ...       ...       ...     ...
245      175     -230  0.406036  0.593964       0
246      250     -305  0.495166  0.504834       0
247     -134      105  0.564656  0.435344       1
248     -105     -117  0.554330  0.445670       1
249      115     -143  0.545113  0.454887       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 192
          Number of winning bets: 91
          Number of losing bets: 102
          Number of underdog bets: 137
          Number of underdog wins: 52
          Number of underdog losses: 85
          Number of Favorite bets: 54
          Number of favorite wins: 39
          Number of favorite losses: 15
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -724.7527920960694
          Profit per bet: -3.7747541255003614
          Profit per match: -2.8990111683842774


HI
HI
HI
HI
HI
The original score is 16525.781183602838
Score:  11052.601619632293
Score:  7390.175464919791
Score:  13502.354262802135
Score:  6378.6069322745625
Score:  8901.255813634973
Score:  7549.439963624699
Score:  4704.883029251023
Score:  4433.644158095384
Score:  2120.0747221248266
Score:  -1235.520586262914
Score:  6277.002530884942
Score:  6780.361818617814
Score:  5576.698280785949
Score:  4837.844331243852
Score:  8567.088247067608
Score:  14315.194821374036
Score:  5936.883133774356
Score:  4971.222863731553
Score:  3669.2554584076943
Score:  9828.386334626954
Score:  8863.11928962146
Score:  11740.31212877604
Score:  2857.7203409134067
Score:  8403.374308477676
Score:  3077.314488137415

model_2
RandomForestClassifier(max_depth=9, max_leaf_nodes=845,
                       min_samples_leaf=0.01009899, n_estimators=17, n_jobs=-1,
                       random_state=75)
["R_Women's Strawweight_rank", 'R_Welterweight_rank', 'gender', 'R_current_lose_streak', 'B_Pound-for-Pound_rank', 'avg_td_dif', 'B_odds', 'R_draw', 'R_Middleweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'total_title_bout_dif', 'better_rank', 'sig_str_dif', 'R_Weight_lbs', 'R_avg_TD_landed', 'no_of_rounds', 'B_draw', 'country', 'B_ev', 'B_age', 'R_Reach_cms', 'B_avg_TD_pct', 'R_odds', 'B_avg_TD_landed']
0

(3601, 55)

(3601,)

(3601, 2)

(250, 55)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.652651  0.347349       1
1       -320      250  0.757546  0.242454       1
2        130     -155  0.477863  0.522137       0
3       -155      135  0.576915  0.423085       1
4       -240      195  0.668680  0.331320       0
..       ...      ...       ...       ...     ...
245      175     -230  0.406036  0.593964       0
246      250     -305  0.495166  0.504834       0
247     -134      105  0.564656  0.435344       1
248     -105     -117  0.554330  0.445670       1
249      115     -143  0.545113  0.454887       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 192
          Number of winning bets: 91
          Number of losing bets: 102
          Number of underdog bets: 137
          Number of underdog wins: 52
          Number of underdog losses: 85
          Number of Favorite bets: 54
          Number of favorite wins: 39
          Number of favorite losses: 15
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -724.7527920960694
          Profit per bet: -3.7747541255003614
          Profit per match: -2.8990111683842774


HI
HI
HI
HI
HI

(3601, 55)

(3601,)

(3601, 2)

(250, 55)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.652651  0.347349       1
1       -320      250  0.757546  0.242454       1
2        130     -155  0.477863  0.522137       0
3       -155      135  0.576915  0.423085       1
4       -240      195  0.668680  0.331320       0
..       ...      ...       ...       ...     ...
245      175     -230  0.406036  0.593964       0
246      250     -305  0.495166  0.504834       0
247     -134      105  0.564656  0.435344       1
248     -105     -117  0.554330  0.445670       1
249      115     -143  0.545113  0.454887       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 192
          Number of winning bets: 91
          Number of losing bets: 102
          Number of underdog bets: 137
          Number of underdog wins: 52
          Number of underdog losses: 85
          Number of Favorite bets: 54
          Number of favorite wins: 39
          Number of favorite losses: 15
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -724.7527920960694
          Profit per bet: -3.7747541255003614
          Profit per match: -2.8990111683842774


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 3


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_3
GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)
['R_win_by_Submission', 'better_rank', 'R_Reach_cms', 'R_losses', 'total_round_dif', "R_Women's Strawweight_rank", 'B_Lightweight_rank', 'B_Pound-for-Pound_rank', "R_Women's Featherweight_rank", 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'R_Pound-for-Pound_rank', 'reach_dif', "R_Women's Bantamweight_rank", 'age_dif', 'weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
11
Current best score is: 18291.04296409622
Feature: location Score: 24704.730958870932
The best feature was location.  It scored 24704.730958870932
Current best score is: 24704.730958870932
Feature: B_win_by_Decision_Majority Score: 25374.7647753469
Feature: B_win_by_TKO_Doctor_Stoppage Score: 25906.190727367804
Feature: R_match_weightclass_rank Score: 26418.112372142656
The best feature was R_match_weightclass_rank.  It scored 26418.112372142656
Current best score is: 26418.112372142656
Feature: B_age Score: 27756.209190005997
The best feature was B_age.  It scored 27756.209190005997
Current best score is: 27756.209190005997
NO IMPROVEMENT
FINAL BEST SCORE: 27756.209190005997

model_3
GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)
['B_age', 'R_match_weightclass_rank', 'location', 'R_win_by_Submission', 'better_rank', 'R_Reach_cms', 'R_losses', 'total_round_dif', "R_Women's Strawweight_rank", 'B_Lightweight_rank', 'B_Pound-for-Pound_rank', "R_Women's Featherweight_rank", 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'R_Pound-for-Pound_rank', 'reach_dif', "R_Women's Bantamweight_rank", 'age_dif', 'weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
11

(3513, 217)

(3513,)

(3513, 2)

(248, 217)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.996563  0.003437       1
1       -320      250  0.109191  0.890809       1
2        130     -155  0.992315  0.007685       0
3       -155      135  0.858259  0.141741       1
4       -240      195  0.662251  0.337749       0
..       ...      ...       ...       ...     ...
243      175     -230  0.953148  0.046852       0
244      250     -305  0.782527  0.217473       0
245     -134      105  0.954424  0.045576       1
246     -105     -117  0.628113  0.371887       1
247      115     -143  0.976108  0.023892       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 225
          Number of winning bets: 115
          Number of losing bets: 110
          Number of underdog bets: 107
          Number of underdog wins: 43
          Number of underdog losses: 64
          Number of Favorite bets: 115
          Number of favorite wins: 72
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -792.7253652993277
          Profit per bet: -3.5232238457747895
          Profit per match: -3.1964732471747084


HI
HI
HI
HI
HI
HI


Starting New Run


Previous Best Score: 27756.209190005997
144
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 9882.578013531087
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 9138.528267185373
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 9882.578013531087
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 9138.528267185373
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 9882.578013531087
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 9138.528267185373
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 16101.147398933535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 12918.948926621928
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 16101.147398933535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 12918.948926621928
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 16101.147398933535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 12918.948926621928
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 4791.037692165848
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 3312.6724539370935
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 4791.037692165848
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 3312.6724539370935
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 4791.037692165848
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 3312.6724539370935
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 10501.691820760749
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 9310.62478314633
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 10501.691820760749
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 9310.62478314633
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 10501.691820760749
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 9310.62478314633
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 27756.209190005997
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 25962.43911391689
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 27756.209190005997
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 25962.43911391689
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 27756.209190005997
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 25962.43911391689
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 21448.525077483268
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 26147.482650446007
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 21448.525077483268
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 26147.482650446007
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 21448.525077483268
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 26147.482650446007
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 11059.838740691535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 16720.367358174008
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 11059.838740691535

Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 16720.367358174008
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 11059.838740691535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 16720.367358174008
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 17540.543086408965
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 15631.86777642943
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 17540.543086408965
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 15631.86777642943
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 17540.543086408965
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.0001 Score: 15631.86777642943
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 8806.414180789598
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 12120.250064478094
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 8806.414180789598
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 12120.250064478094
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 8806.414180789598
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 12120.250064478094
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 11846.38363791148
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 7646.794235342512
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 11846.38363791148
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 7646.794235342512
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 11846.38363791148
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.0001 Score: 7646.794235342512
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 15544.686087935288
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 21596.335921453974
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 15544.686087935288
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 21596.335921453974
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 15544.686087935288
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 21596.335921453974
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 22398.05681202496
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 22297.404178172805
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 22398.05681202496
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 22297.404178172805
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 22398.05681202496
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.0001 Score: 22297.404178172805
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 9882.578013531087
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 9138.528267185373
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 9882.578013531087
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 9138.528267185373
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 9882.578013531087
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 9138.528267185373
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 16101.147398933535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 12918.948926621928
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 16101.147398933535

Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 12918.948926621928
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 16101.147398933535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: None tol: 0.5985784583335374 Score: 12918.948926621928
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 4791.037692165848
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 3312.6724539370935
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 4791.037692165848
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 3312.6724539370935
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 4791.037692165848
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 3312.6724539370935
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 10501.691820760749
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 9310.62478314633
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 10501.691820760749
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 9310.62478314633
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 10501.691820760749
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: log2 Max Leaf Nodes: None tol: 0.5985784583335374 Score: 9310.62478314633
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 27756.209190005997
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 25962.43911391689
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 27756.209190005997
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 25962.43911391689
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 27756.209190005997
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 25962.43911391689
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 21448.525077483268
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 26147.482650446007
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 21448.525077483268
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 26147.482650446007
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 21448.525077483268
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: None Max Leaf Nodes: None tol: 0.5985784583335374 Score: 26147.482650446007
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 11059.838740691535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 16720.367358174008
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 11059.838740691535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 16720.367358174008
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 11059.838740691535
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 16720.367358174008
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 17540.543086408965
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 15631.86777642943
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 17540.543086408965
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 15631.86777642943
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 17540.543086408965
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: sqrt Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 15631.86777642943
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 8806.414180789598

Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 12120.250064478094
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 8806.414180789598
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 12120.250064478094
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 8806.414180789598
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 12120.250064478094
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 11846.38363791148
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 7646.794235342512
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 11846.38363791148
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 7646.794235342512
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 11846.38363791148
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: log2 Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 7646.794235342512
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 15544.686087935288
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 21596.335921453974
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 15544.686087935288
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 21596.335921453974
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 15544.686087935288
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 21596.335921453974
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 22398.05681202496
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 22297.404178172805
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 22398.05681202496
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 22297.404178172805
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 22398.05681202496
Criterion: friedman_mse n_estimators: 79 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 46 Max Features: None Max Leaf Nodes: 329 tol: 0.5985784583335374 Score: 22297.404178172805
Real output model: GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)

model_3
GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)
['B_age', 'R_match_weightclass_rank', 'location', 'R_win_by_Submission', 'better_rank', 'R_Reach_cms', 'R_losses', 'total_round_dif', "R_Women's Strawweight_rank", 'B_Lightweight_rank', 'B_Pound-for-Pound_rank', "R_Women's Featherweight_rank", 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'R_Pound-for-Pound_rank', 'reach_dif', "R_Women's Bantamweight_rank", 'age_dif', 'weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
11

(3513, 217)

(3513,)

(3513, 2)

(248, 217)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.996563  0.003437       1
1       -320      250  0.109191  0.890809       1
2        130     -155  0.992315  0.007685       0
3       -155      135  0.858259  0.141741       1
4       -240      195  0.662251  0.337749       0
..       ...      ...       ...       ...     ...
243      175     -230  0.953148  0.046852       0
244      250     -305  0.782527  0.217473       0
245     -134      105  0.954424  0.045576       1
246     -105     -117  0.628113  0.371887       1
247      115     -143  0.976108  0.023892       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 225
          Number of winning bets: 115
          Number of losing bets: 110
          Number of underdog bets: 107
          Number of underdog wins: 43
          Number of underdog losses: 64
          Number of Favorite bets: 115
          Number of favorite wins: 72
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -792.7253652993277
          Profit per bet: -3.5232238457747895
          Profit per match: -3.1964732471747084


HI
HI
HI
HI
HI
0 27215.06194050582
1 26768.45247417019
2 26779.65106456101
3 26827.661280859204
4 26752.819568312116
5 26525.070508729124
6 26318.245335409883
7 26872.59572515008
8 27138.873758229372
9 27485.712933724557
10 27714.917133531053
11 27756.209190005997
12 27556.829963377873
13 27455.771113653696
14 27804.248557578976
15 27922.639368459248
16 27509.913948187776
17 27443.218223723467
18 27861.576378459686
19 28075.633604667244
20 27932.16939383818
21 27691.870221393172
22 26836.26741139111
23 26778.139639802394
24 26706.18609668324
25 26869.480734833327
26 26885.48112908849
27 26088.737877129955
28 25099.05963621917
29 25449.368481317728
30 25288.947146366998
31 25704.26778258352
32 24968.472111451483
33 25225.088215826017
34 24383.129991601774
35 24578.431507479094
36 23671.281306144192
37 23303.9143627754
38 23815.741597659195
39 23470.44989569413
40 22945.565711201503
41 22720.595661440682
42 22805.64978825717
43 21626.61881927304
44 21495.476725213855
45 21182.4807045067
46 22153.996049442983
47 22379.922501897014
48 21838.90020319483
49 21890.248603890082
50 22137.800571061824
51 22410.05830590537
52 22613.67711751285
53 21794.478840623393
54 21875.368116996535
55 21012.426230348283
56 21241.596680137394
57 20703.832319257002
58 21093.05998683724
59 21764.39704361897
60 21091.657155642053
61 20885.181880618395
62 20874.82415789508
63 21263.648999309153
64 21496.52770363947
65 20617.720650163483
66 20851.05398349682
67 20419.90897907595
68 20722.667723876486
69 20831.969802823438
70 20564.252520106154
71 20065.804341875366
72 19726.34821551801
73 20135.292031016634
74 19860.562665505648
75 19591.162661323036
76 19677.484339644714
77 19847.099724260097
78 19539.905107282873
79 20072.94858554374
80 20133.884026913962
81 20288.64593167587
82 20043.415508696737
83 20734.792320290937
84 21206.22089171951
85 21363.50845191892
86 21703.21623206148
87 21099.58269168881
88 20234.387886494005
89 19934.14979125591
90 19820.422518528638
91 18782.764509870627
92 18892.288319394436
93 19201.812128918245
94 19061.996315800545
95 18427.602784803243
96 17887.126594327052
97 17340.039215686273
98 17437.0
99 17802.0
100 17009.0
101 16503.0
102 16235.0
103 16140.0
104 15428.0
105 16123.0
106 15898.0
107 15743.0
108 15258.0
109 15588.0
110 13931.0
111 14091.0
112 14107.0
113 14307.0
114 15007.0
115 14759.0
116 14069.0
117 13949.0
118 14104.0
119 14519.0
120 14274.0
121 14113.0
122 14283.0
123 13803.0
124 13658.0
125 13138.0
126 13078.0
127 12913.0
128 13413.0
129 12973.0
130 11908.0
131 11513.0
132 11273.0
133 11538.0
134 11773.0
135 11193.0
136 11693.0
137 11463.0
138 11103.0
139 10923.0
140 10823.0
141 10493.0
142 10806.0
143 10766.0
144 11011.0
145 10976.0
146 11276.0
147 11301.0
148 11466.0
149 10881.0
150 10156.0
151 9761.0
152 8971.0
153 8601.0
154 8141.0
155 8321.0
156 8091.0
157 8474.0
158 8287.0
159 8239.0
160 8354.0
161 8199.0
162 8499.0
163 8419.0
164 7799.0
165 7439.0
166 7539.0
167 7534.0
168 7564.0
169 7354.0
170 7104.0
171 6504.0
172 6439.0
173 5881.0
174 6081.0
175 5856.0
176 6056.0
177 5699.0
178 5619.0
179 6119.0
180 6324.0
181 6624.0
182 6724.0
183 6414.0
184 5784.0
185 5459.0
186 5559.0
187 5369.0
188 5379.0
189 5379.0
190 5484.0
191 5584.0
192 5234.0
193 5136.0
194 5336.0
195 5021.0
196 5221.0
197 4956.0
198 4856.0
199 5156.0
200 4951.0
201 4951.0
202 4496.0
203 4696.0
204 4896.0
205 5191.0
206 5291.0
207 5046.0
208 5446.0
209 5531.0
210 4711.0
211 4696.0
212 4481.0
213 4581.0
214 4521.0
215 4921.0
216 5021.0
217 5121.0
218 5321.0
219 5421.0
220 5301.0
221 5361.0
222 4986.0
223 4986.0
224 5086.0
225 4826.0
226 4926.0
227 5126.0
228 5426.0
229 5526.0
230 5136.0
231 5081.0
232 4538.0
233 4303.0
234 4268.0
235 3723.0
236 3378.0
237 3130.0
238 3130.0
239 3130.0
240 2670.0
241 2425.0
242 2725.0
243 2725.0
244 2780.0
245 2425.0
246 2725.0
247 2100.0
248 2200.0
249 1900.0

model_3
GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)
['B_age', 'R_match_weightclass_rank', 'location', 'R_win_by_Submission', 'better_rank', 'R_Reach_cms', 'R_losses', 'total_round_dif', "R_Women's Strawweight_rank", 'B_Lightweight_rank', 'B_Pound-for-Pound_rank', "R_Women's Featherweight_rank", 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'R_Pound-for-Pound_rank', 'reach_dif', "R_Women's Bantamweight_rank", 'age_dif', 'weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
19

(3513, 217)

(3513,)

(3513, 2)

(248, 217)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.996563  0.003437       1
1       -320      250  0.109191  0.890809       1
2        130     -155  0.992315  0.007685       0
3       -155      135  0.858259  0.141741       1
4       -240      195  0.662251  0.337749       0
..       ...      ...       ...       ...     ...
243      175     -230  0.953148  0.046852       0
244      250     -305  0.782527  0.217473       0
245     -134      105  0.954424  0.045576       1
246     -105     -117  0.628113  0.371887       1
247      115     -143  0.976108  0.023892       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 214
          Number of winning bets: 106
          Number of losing bets: 108
          Number of underdog bets: 105
          Number of underdog wins: 43
          Number of underdog losses: 62
          Number of Favorite bets: 106
          Number of favorite wins: 63
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -963.4611352656166
          Profit per bet: -4.5021548376897975
          Profit per match: -3.8849239325226477


HI
HI
HI
HI
HI
The original score is 28075.633604667244
Score:  26419.991187392872
Score:  19633.184798482234
Score:  21806.402286933488
Score:  26010.458082810765
Score:  22340.052209544403
Score:  19216.202153856662
Score:  19977.063016541462
Score:  26151.496491847785
Score:  18791.444180352715
Score:  17927.35298667848
Score:  25209.948716540912
Score:  23921.86802138567
Score:  19633.582993790693
Score:  24684.162316783855
Score:  22550.19133640609
Score:  17231.594324569425
Score:  21000.30389158406
Score:  17387.43557002863
Score:  19099.844115626554
Score:  19799.784848434443
Score:  18543.455566261626
Score:  15911.708861848037
Score:  18392.759651140546
Score:  15072.515991942868
Score:  23535.26366576432
Score:  19488.35327620292
Score:  22893.417220378546
Score:  20011.89024980731
Score:  19720.131642713844
Score:  25627.263677567295
Score:  4734.795298474282
Score:  21171.71341205181
The EV is different
OLD:
11
NEW:
19

model_3
GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)
['B_age', 'R_match_weightclass_rank', 'location', 'R_win_by_Submission', 'better_rank', 'R_Reach_cms', 'R_losses', 'total_round_dif', "R_Women's Strawweight_rank", 'B_Lightweight_rank', 'B_Pound-for-Pound_rank', "R_Women's Featherweight_rank", 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'R_Pound-for-Pound_rank', 'reach_dif', "R_Women's Bantamweight_rank", 'age_dif', 'weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
19

(3513, 217)

(3513,)

(3513, 2)

(248, 217)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.996563  0.003437       1
1       -320      250  0.109191  0.890809       1
2        130     -155  0.992315  0.007685       0
3       -155      135  0.858259  0.141741       1
4       -240      195  0.662251  0.337749       0
..       ...      ...       ...       ...     ...
243      175     -230  0.953148  0.046852       0
244      250     -305  0.782527  0.217473       0
245     -134      105  0.954424  0.045576       1
246     -105     -117  0.628113  0.371887       1
247      115     -143  0.976108  0.023892       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 214
          Number of winning bets: 106
          Number of losing bets: 108
          Number of underdog bets: 105
          Number of underdog wins: 43
          Number of underdog losses: 62
          Number of Favorite bets: 106
          Number of favorite wins: 63
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -963.4611352656166
          Profit per bet: -4.5021548376897975
          Profit per match: -3.8849239325226477


HI
HI
HI
HI
HI
Current best score is: 28075.633604667244
NO IMPROVEMENT
FINAL BEST SCORE: 28075.633604667244

model_3
GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)
['B_age', 'R_match_weightclass_rank', 'location', 'R_win_by_Submission', 'better_rank', 'R_Reach_cms', 'R_losses', 'total_round_dif', "R_Women's Strawweight_rank", 'B_Lightweight_rank', 'B_Pound-for-Pound_rank', "R_Women's Featherweight_rank", 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'R_Pound-for-Pound_rank', 'reach_dif', "R_Women's Bantamweight_rank", 'age_dif', 'weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
19

(3513, 217)

(3513,)

(3513, 2)

(248, 217)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.996563  0.003437       1
1       -320      250  0.109191  0.890809       1
2        130     -155  0.992315  0.007685       0
3       -155      135  0.858259  0.141741       1
4       -240      195  0.662251  0.337749       0
..       ...      ...       ...       ...     ...
243      175     -230  0.953148  0.046852       0
244      250     -305  0.782527  0.217473       0
245     -134      105  0.954424  0.045576       1
246     -105     -117  0.628113  0.371887       1
247      115     -143  0.976108  0.023892       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 214
          Number of winning bets: 106
          Number of losing bets: 108
          Number of underdog bets: 105
          Number of underdog wins: 43
          Number of underdog losses: 62
          Number of Favorite bets: 106
          Number of favorite wins: 63
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -963.4611352656166
          Profit per bet: -4.5021548376897975
          Profit per match: -3.8849239325226477


HI
HI
HI
HI
HI
HI


Starting New Run


Previous Best Score: 28075.633604667244
144
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 10853.939701620564
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 8722.725671094337
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 10853.939701620564
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 8722.725671094337
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 10853.939701620564
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 8722.725671094337
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 18019.602878993202
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 10811.562621662673
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 18019.602878993202
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 10811.562621662673
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 18019.602878993202
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.0001 Score: 10811.562621662673
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 6316.983547304417
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 4836.049033510866
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 6316.983547304417
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 4836.049033510866
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 6316.983547304417
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 4836.049033510866
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 13849.811908227954
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 10261.567321602746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 13849.811908227954
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 10261.567321602746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 13849.811908227954
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.0001 Score: 10261.567321602746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 28075.633604667244
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 26445.674019596758
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 28075.633604667244
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 26445.674019596758
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 28075.633604667244
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 26445.674019596758
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 23161.87806469268
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 22353.03706092723
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 23161.87806469268
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 22353.03706092723
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 23161.87806469268
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.0001 Score: 22353.03706092723
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 10236.324132736187
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 9190.84632416739
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 10236.324132736187

Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 9190.84632416739
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 10236.324132736187
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 9190.84632416739
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 16084.700788114045
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 9680.714618811146
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 16084.700788114045
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 9680.714618811146
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 16084.700788114045
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.0001 Score: 9680.714618811146
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 8848.867009101874
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 11766.443029767746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 8848.867009101874
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 11766.443029767746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 8848.867009101874
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 11766.443029767746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 5535.953384032461
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 7343.72082886884
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 5535.953384032461
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 7343.72082886884
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 5535.953384032461
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.0001 Score: 7343.72082886884
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 19203.515159101684
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 22507.938078630326
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 19203.515159101684
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 22507.938078630326
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 19203.515159101684
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 22507.938078630326
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 20517.24712929747
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 19666.822710302353
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 20517.24712929747
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 19666.822710302353
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 20517.24712929747
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.0001 Score: 19666.822710302353
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 10853.939701620564
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 8722.725671094337
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 10853.939701620564
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 8722.725671094337
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 10853.939701620564
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 8722.725671094337
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 18019.602878993202
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 10811.562621662673
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 18019.602878993202
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 10811.562621662673

Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 18019.602878993202
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: None tol: 0.2263957688957019 Score: 10811.562621662673
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 6316.983547304417
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 4836.049033510866
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 6316.983547304417
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 4836.049033510866
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 6316.983547304417
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 4836.049033510866
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 13849.811908227954
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 10261.567321602746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 13849.811908227954
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 10261.567321602746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 13849.811908227954
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: log2 Max Leaf Nodes: None tol: 0.2263957688957019 Score: 10261.567321602746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 28075.633604667244
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 26445.674019596758
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 28075.633604667244
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 26445.674019596758
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 28075.633604667244
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 26445.674019596758
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 23161.87806469268
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 22353.03706092723
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 23161.87806469268
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 22353.03706092723
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 23161.87806469268
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: None Max Leaf Nodes: None tol: 0.2263957688957019 Score: 22353.03706092723
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 10236.324132736187
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 9190.84632416739
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 10236.324132736187
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 9190.84632416739
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 10236.324132736187
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 9190.84632416739
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 16084.700788114045
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 9680.714618811146
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 16084.700788114045
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 9680.714618811146
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 16084.700788114045
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: sqrt Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 9680.714618811146
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 8848.867009101874
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 11766.443029767746

Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 8848.867009101874
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 11766.443029767746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 8848.867009101874
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 11766.443029767746
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 5535.953384032461
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 7343.72082886884
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 5535.953384032461
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 7343.72082886884
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 5535.953384032461
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: log2 Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 7343.72082886884
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 19203.515159101684
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 22507.938078630326
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 19203.515159101684
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 22507.938078630326
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 19203.515159101684
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 69 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 22507.938078630326
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 20517.24712929747
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.0015 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 19666.822710302353
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 20517.24712929747
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001485 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 19666.822710302353
Criterion: friedman_mse n_estimators: 190 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 20517.24712929747
Criterion: friedman_mse n_estimators: 52 Loss: deviance Learning Rate: 0.1 Min Samples/Leaf: 0.001515 Max Depth: 31 Max Features: None Max Leaf Nodes: 223 tol: 0.2263957688957019 Score: 19666.822710302353
Real output model: GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)

model_3
GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)
['B_age', 'R_match_weightclass_rank', 'location', 'R_win_by_Submission', 'better_rank', 'R_Reach_cms', 'R_losses', 'total_round_dif', "R_Women's Strawweight_rank", 'B_Lightweight_rank', 'B_Pound-for-Pound_rank', "R_Women's Featherweight_rank", 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'R_Pound-for-Pound_rank', 'reach_dif', "R_Women's Bantamweight_rank", 'age_dif', 'weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
19

(3513, 217)

(3513,)

(3513, 2)

(248, 217)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.996563  0.003437       1
1       -320      250  0.109191  0.890809       1
2        130     -155  0.992315  0.007685       0
3       -155      135  0.858259  0.141741       1
4       -240      195  0.662251  0.337749       0
..       ...      ...       ...       ...     ...
243      175     -230  0.953148  0.046852       0
244      250     -305  0.782527  0.217473       0
245     -134      105  0.954424  0.045576       1
246     -105     -117  0.628113  0.371887       1
247      115     -143  0.976108  0.023892       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 214
          Number of winning bets: 106
          Number of losing bets: 108
          Number of underdog bets: 105
          Number of underdog wins: 43
          Number of underdog losses: 62
          Number of Favorite bets: 106
          Number of favorite wins: 63
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -963.4611352656166
          Profit per bet: -4.5021548376897975
          Profit per match: -3.8849239325226477


HI
HI
HI
HI
HI
0 27215.06194050582
1 26768.45247417019
2 26779.65106456101
3 26827.661280859204
4 26752.819568312116
5 26525.070508729124
6 26318.245335409883
7 26872.59572515008
8 27138.873758229372
9 27485.712933724557
10 27714.917133531053
11 27756.209190005997
12 27556.829963377873
13 27455.771113653696
14 27804.248557578976
15 27922.639368459248
16 27509.913948187776
17 27443.218223723467
18 27861.576378459686
19 28075.633604667244
20 27932.16939383818
21 27691.870221393172
22 26836.26741139111
23 26778.139639802394
24 26706.18609668324
25 26869.480734833327
26 26885.48112908849
27 26088.737877129955
28 25099.05963621917
29 25449.368481317728
30 25288.947146366998
31 25704.26778258352
32 24968.472111451483
33 25225.088215826017
34 24383.129991601774
35 24578.431507479094
36 23671.281306144192
37 23303.9143627754
38 23815.741597659195
39 23470.44989569413
40 22945.565711201503
41 22720.595661440682
42 22805.64978825717
43 21626.61881927304
44 21495.476725213855
45 21182.4807045067
46 22153.996049442983
47 22379.922501897014
48 21838.90020319483
49 21890.248603890082
50 22137.800571061824
51 22410.05830590537
52 22613.67711751285
53 21794.478840623393
54 21875.368116996535
55 21012.426230348283
56 21241.596680137394
57 20703.832319257002
58 21093.05998683724
59 21764.39704361897
60 21091.657155642053
61 20885.181880618395
62 20874.82415789508
63 21263.648999309153
64 21496.52770363947
65 20617.720650163483
66 20851.05398349682
67 20419.90897907595
68 20722.667723876486
69 20831.969802823438
70 20564.252520106154
71 20065.804341875366
72 19726.34821551801
73 20135.292031016634
74 19860.562665505648
75 19591.162661323036
76 19677.484339644714
77 19847.099724260097
78 19539.905107282873
79 20072.94858554374
80 20133.884026913962
81 20288.64593167587
82 20043.415508696737
83 20734.792320290937
84 21206.22089171951
85 21363.50845191892
86 21703.21623206148
87 21099.58269168881
88 20234.387886494005
89 19934.14979125591
90 19820.422518528638
91 18782.764509870627
92 18892.288319394436
93 19201.812128918245
94 19061.996315800545
95 18427.602784803243
96 17887.126594327052
97 17340.039215686273
98 17437.0
99 17802.0
100 17009.0
101 16503.0
102 16235.0
103 16140.0
104 15428.0
105 16123.0
106 15898.0
107 15743.0
108 15258.0
109 15588.0
110 13931.0
111 14091.0
112 14107.0
113 14307.0
114 15007.0
115 14759.0
116 14069.0
117 13949.0
118 14104.0
119 14519.0
120 14274.0
121 14113.0
122 14283.0
123 13803.0
124 13658.0
125 13138.0
126 13078.0
127 12913.0
128 13413.0
129 12973.0
130 11908.0
131 11513.0
132 11273.0
133 11538.0
134 11773.0
135 11193.0
136 11693.0
137 11463.0
138 11103.0
139 10923.0
140 10823.0
141 10493.0
142 10806.0
143 10766.0
144 11011.0
145 10976.0
146 11276.0
147 11301.0
148 11466.0
149 10881.0
150 10156.0
151 9761.0
152 8971.0
153 8601.0
154 8141.0
155 8321.0
156 8091.0
157 8474.0
158 8287.0
159 8239.0
160 8354.0
161 8199.0
162 8499.0
163 8419.0
164 7799.0
165 7439.0
166 7539.0
167 7534.0
168 7564.0
169 7354.0
170 7104.0
171 6504.0
172 6439.0
173 5881.0
174 6081.0
175 5856.0
176 6056.0
177 5699.0
178 5619.0
179 6119.0
180 6324.0
181 6624.0
182 6724.0
183 6414.0
184 5784.0
185 5459.0
186 5559.0
187 5369.0
188 5379.0
189 5379.0
190 5484.0
191 5584.0
192 5234.0
193 5136.0
194 5336.0
195 5021.0
196 5221.0
197 4956.0
198 4856.0
199 5156.0
200 4951.0
201 4951.0
202 4496.0
203 4696.0
204 4896.0
205 5191.0
206 5291.0
207 5046.0
208 5446.0
209 5531.0
210 4711.0
211 4696.0
212 4481.0
213 4581.0
214 4521.0
215 4921.0
216 5021.0
217 5121.0
218 5321.0
219 5421.0
220 5301.0
221 5361.0
222 4986.0
223 4986.0
224 5086.0
225 4826.0
226 4926.0
227 5126.0
228 5426.0
229 5526.0
230 5136.0
231 5081.0
232 4538.0
233 4303.0
234 4268.0
235 3723.0
236 3378.0
237 3130.0
238 3130.0
239 3130.0
240 2670.0
241 2425.0
242 2725.0
243 2725.0
244 2780.0
245 2425.0
246 2725.0
247 2100.0
248 2200.0
249 1900.0

model_3
GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)
['B_age', 'R_match_weightclass_rank', 'location', 'R_win_by_Submission', 'better_rank', 'R_Reach_cms', 'R_losses', 'total_round_dif', "R_Women's Strawweight_rank", 'B_Lightweight_rank', 'B_Pound-for-Pound_rank', "R_Women's Featherweight_rank", 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'R_Pound-for-Pound_rank', 'reach_dif', "R_Women's Bantamweight_rank", 'age_dif', 'weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
19

(3513, 217)

(3513,)

(3513, 2)

(248, 217)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.996563  0.003437       1
1       -320      250  0.109191  0.890809       1
2        130     -155  0.992315  0.007685       0
3       -155      135  0.858259  0.141741       1
4       -240      195  0.662251  0.337749       0
..       ...      ...       ...       ...     ...
243      175     -230  0.953148  0.046852       0
244      250     -305  0.782527  0.217473       0
245     -134      105  0.954424  0.045576       1
246     -105     -117  0.628113  0.371887       1
247      115     -143  0.976108  0.023892       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 214
          Number of winning bets: 106
          Number of losing bets: 108
          Number of underdog bets: 105
          Number of underdog wins: 43
          Number of underdog losses: 62
          Number of Favorite bets: 106
          Number of favorite wins: 63
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -963.4611352656166
          Profit per bet: -4.5021548376897975
          Profit per match: -3.8849239325226477


HI
HI
HI
HI
HI
The original score is 28075.633604667244
Score:  26419.991187392872
Score:  19633.184798482234
Score:  21806.402286933488
Score:  26010.458082810765
Score:  22340.052209544403
Score:  19216.202153856662
Score:  19977.063016541462
Score:  26151.496491847785
Score:  18791.444180352715
Score:  17927.35298667848
Score:  25209.948716540912
Score:  23921.86802138567
Score:  19633.582993790693
Score:  24684.162316783855
Score:  22550.19133640609
Score:  17231.594324569425
Score:  21000.30389158406
Score:  17387.43557002863
Score:  19099.844115626554
Score:  19799.784848434443
Score:  18543.455566261626
Score:  15911.708861848037
Score:  18392.759651140546
Score:  15072.515991942868
Score:  23535.26366576432
Score:  19488.35327620292
Score:  22893.417220378546
Score:  20011.89024980731
Score:  19720.131642713844
Score:  25627.263677567295
Score:  4734.795298474282
Score:  21171.71341205181

model_3
GradientBoostingClassifier(max_depth=69, min_samples_leaf=0.0015,
                           n_estimators=190, random_state=75)
['B_age', 'R_match_weightclass_rank', 'location', 'R_win_by_Submission', 'better_rank', 'R_Reach_cms', 'R_losses', 'total_round_dif', "R_Women's Strawweight_rank", 'B_Lightweight_rank', 'B_Pound-for-Pound_rank', "R_Women's Featherweight_rank", 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'R_Pound-for-Pound_rank', 'reach_dif', "R_Women's Bantamweight_rank", 'age_dif', 'weight_class', 'B_Reach_cms', 'B_Welterweight_rank', 'B_total_title_bouts', 'R_avg_TD_pct', 'B_Bantamweight_rank', 'R_Featherweight_rank', 'no_of_rounds', 'B_draw', 'B_Stance', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
19

(3513, 217)

(3513,)

(3513, 2)

(248, 217)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.996563  0.003437       1
1       -320      250  0.109191  0.890809       1
2        130     -155  0.992315  0.007685       0
3       -155      135  0.858259  0.141741       1
4       -240      195  0.662251  0.337749       0
..       ...      ...       ...       ...     ...
243      175     -230  0.953148  0.046852       0
244      250     -305  0.782527  0.217473       0
245     -134      105  0.954424  0.045576       1
246     -105     -117  0.628113  0.371887       1
247      115     -143  0.976108  0.023892       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 214
          Number of winning bets: 106
          Number of losing bets: 108
          Number of underdog bets: 105
          Number of underdog wins: 43
          Number of underdog losses: 62
          Number of Favorite bets: 106
          Number of favorite wins: 63
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -963.4611352656166
          Profit per bet: -4.5021548376897975
          Profit per match: -3.8849239325226477


HI
HI
HI
HI
HI

(3513, 217)

(3513,)

(3513, 2)

(248, 217)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.996563  0.003437       1
1       -320      250  0.109191  0.890809       1
2        130     -155  0.992315  0.007685       0
3       -155      135  0.858259  0.141741       1
4       -240      195  0.662251  0.337749       0
..       ...      ...       ...       ...     ...
243      175     -230  0.953148  0.046852       0
244      250     -305  0.782527  0.217473       0
245     -134      105  0.954424  0.045576       1
246     -105     -117  0.628113  0.371887       1
247      115     -143  0.976108  0.023892       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 214
          Number of winning bets: 106
          Number of losing bets: 108
          Number of underdog bets: 105
          Number of underdog wins: 43
          Number of underdog losses: 62
          Number of Favorite bets: 106
          Number of favorite wins: 63
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -963.4611352656166
          Profit per bet: -4.5021548376897975
          Profit per match: -3.8849239325226477


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 4


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_4
GaussianNB()
['R_win_by_Submission', 'B_current_lose_streak', 'lose_streak_dif', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
0
Current best score is: 10985.935917160201
Feature: B_avg_TD_landed Score: 13501.374504975898
Feature: R_win_by_Decision_Majority Score: 15801.279705747154
The best feature was R_win_by_Decision_Majority.  It scored 15801.279705747154
Current best score is: 15801.279705747154
Feature: B_avg_SIG_STR_landed Score: 16454.32571275076
The best feature was B_avg_SIG_STR_landed.  It scored 16454.32571275076
Current best score is: 16454.32571275076
Feature: B_Heavyweight_rank Score: 17358.998908637383
The best feature was B_Heavyweight_rank.  It scored 17358.998908637383
Current best score is: 17358.998908637383
NO IMPROVEMENT
FINAL BEST SCORE: 17358.998908637383

model_4
GaussianNB()
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'lose_streak_dif', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
0

(3513, 46)

(3513,)

(3513, 2)

(250, 46)

(250,)

(250, 2)

     t1_odds  t2_odds       t1_prob   t2_prob  winner
0       -210      175  9.961829e-01  0.003817       1
1       -320      250  9.684284e-01  0.031572       1
2        130     -155  9.898506e-01  0.010149       0
3       -155      135  4.804075e-05  0.999952       1
4       -240      195  8.218795e-01  0.178121       0
..       ...      ...           ...       ...     ...
245      175     -230  8.375546e-01  0.162445       0
246      250     -305  1.984803e-12  1.000000       0
247     -134      105  7.615525e-01  0.238448       1
248     -105     -117  5.400438e-01  0.459956       1
249      115     -143  4.447035e-01  0.555297       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 247
          Number of winning bets: 136
          Number of losing bets: 111
          Number of underdog bets: 93
          Number of underdog wins: 38
          Number of underdog losses: 55
          Number of Favorite bets: 151
          Number of favorite wins: 98
          Number of favorite losses: 53
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -934.0401024133099
          Profit per bet: -3.7815388761672466
          Profit per match: -3.7361604096532397


HI
HI
HI
HI
HI


Starting New Run for GaussianNB


Previous Best Score: 17358.998908637383
var_smoothing: 1e-12 Score: 17358.998908637383
var_smoothing: 1e-11 Score: 17358.998908637383
var_smoothing: 1e-10 Score: 17358.998908637383
var_smoothing: 1e-09 Score: 17358.998908637383
var_smoothing: 1e-08 Score: 17358.998908637383
var_smoothing: 1e-07 Score: 17358.998908637383
var_smoothing: 1e-06 Score: 17358.998908637383
Real output model: GaussianNB()

model_4
GaussianNB()
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'lose_streak_dif', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
0

(3513, 46)

(3513,)

(3513, 2)

(250, 46)

(250,)

(250, 2)

     t1_odds  t2_odds       t1_prob   t2_prob  winner
0       -210      175  9.961829e-01  0.003817       1
1       -320      250  9.684284e-01  0.031572       1
2        130     -155  9.898506e-01  0.010149       0
3       -155      135  4.804075e-05  0.999952       1
4       -240      195  8.218795e-01  0.178121       0
..       ...      ...           ...       ...     ...
245      175     -230  8.375546e-01  0.162445       0
246      250     -305  1.984803e-12  1.000000       0
247     -134      105  7.615525e-01  0.238448       1
248     -105     -117  5.400438e-01  0.459956       1
249      115     -143  4.447035e-01  0.555297       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 247
          Number of winning bets: 136
          Number of losing bets: 111
          Number of underdog bets: 93
          Number of underdog wins: 38
          Number of underdog losses: 55
          Number of Favorite bets: 151
          Number of favorite wins: 98
          Number of favorite losses: 53
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -934.0401024133099
          Profit per bet: -3.7815388761672466
          Profit per match: -3.7361604096532397


HI
HI
HI
HI
HI
0 17358.998908637383
1 17711.989484820806
2 16759.055790278795
3 16288.297800564873
4 16229.120501831028
5 14630.111791922163
6 14494.18037324361
7 13970.81925410067
8 13847.273893946374
9 13193.83557270576
10 12456.759725120872
11 11663.512253845956
12 10299.462642322604
13 10626.787152135068
14 10276.875606684862
15 9964.163512256308
16 10927.440122775868
17 11349.241953835808
18 12278.427526887795
19 11956.246914699497
20 12033.472235759142
21 12298.684972082832
22 11493.266371651447
23 12244.702073266613
24 11356.701362591784
25 11107.206722245039
26 11205.110830900385
27 11799.288582116682
28 12692.037780314009
29 12088.835019950955
30 11215.762945598799
31 10797.351468422876
32 10444.972154536597
33 10407.690503102447
34 10099.570492700386
35 10616.041380627687
36 10185.399526768811
37 10375.080965703391
38 10244.46360122989
39 9185.49903162882
40 8837.287801300283
41 8300.446206702643
42 8637.899775509508
43 8448.187901357363
44 8030.872543763329
45 8611.204399995715
46 7807.177525202711
47 8065.894672209008
48 7400.90903549074
49 6959.740426895238
50 6884.365941085686
51 7333.868953855996
52 6571.789235328908
53 7035.994524937301
54 7265.4414749811485
55 7461.415771503114
56 7183.151582129744
57 6839.0380349522
58 6990.155476800919
59 7169.971328424171
60 7629.410423811542
61 8267.600613164963
62 8233.613703536601
63 8930.720621775596
64 8412.654379152998
65 8162.881839864331
66 9059.842248548877
67 9600.556534263163
68 9422.409348115978
69 9491.666642545684
70 9098.29392729797
71 9002.455220738262
72 8930.23414873458
73 8095.576144147031
74 7546.189900760788
75 7665.639636210524
76 7552.279496514379
77 7459.315648767922
78 7219.315648767922
79 6929.315648767922
80 6479.077553529827
81 6169.211940881605
82 6427.230726377455
83 6853.317682899195
84 7073.02782782673
85 6447.833210849505
86 7011.876689110375
87 7161.007123892983
88 7480.8123186981775
89 7559.903227789086
90 7299.903227789086
91 7276.2668641527225
92 7271.2668641527225
93 7441.927241511213
94 7670.587618869704
95 7646.247996228194
96 7236.009900990099
97 7311.009900990099
98 7254.009900990099
99 7434.009900990099
100 7420.0
101 7087.0
102 6737.0
103 7052.0
104 7222.0
105 7967.0
106 7668.0
107 7843.0
108 7813.0
109 7603.0
110 7393.0
111 7593.0
112 7623.0
113 8023.0
114 8063.0
115 8408.0
116 8608.0
117 8123.0
118 7863.0
119 7688.0
120 7333.0
121 7433.0
122 7403.0
123 7603.0
124 7908.0
125 7351.0
126 7241.0
127 7441.0
128 7116.0
129 7116.0
130 6421.0
131 6111.0
132 6111.0
133 6251.0
134 6159.0
135 5384.0
136 5184.0
137 5384.0
138 5584.0
139 5524.0
140 5749.0
141 5579.0
142 5309.0
143 5409.0
144 5244.0
145 5544.0
146 5304.0
147 5249.0
148 5249.0
149 5449.0
150 4979.0
151 5019.0
152 5219.0
153 5319.0
154 5519.0
155 5719.0
156 5659.0
157 5204.0
158 5446.0
159 5446.0
160 5006.0
161 5306.0
162 5061.0
163 5361.0
164 5111.0
165 5193.0
166 5293.0
167 5393.0
168 5168.0
169 5268.0
170 5393.0
171 5593.0
172 5103.0
173 5068.0
174 4993.0
175 5018.0
176 5133.0
177 5028.0
178 5228.0
179 4993.0
180 5113.0
181 4943.0
182 4733.0
183 4833.0
184 4833.0
185 4043.0
186 3388.0
187 3388.0
188 3488.0
189 2983.0
190 2893.0
191 2993.0
192 2953.0
193 3053.0
194 3053.0
195 2898.0
196 2898.0
197 2898.0
198 3098.0
199 3098.0
200 3098.0
201 2683.0
202 2783.0
203 2983.0
204 2983.0
205 2308.0
206 2408.0
207 2508.0
208 2508.0
209 2608.0
210 2608.0
211 2048.0
212 1800.0
213 1900.0
214 1900.0
215 2100.0
216 2100.0
217 2200.0
218 2300.0
219 2300.0
220 2700.0
221 3000.0
222 3000.0
223 3200.0
224 3300.0
225 3075.0
226 3075.0
227 3075.0
228 3175.0
229 3175.0
230 3175.0
231 3175.0
232 3175.0
233 3175.0
234 3175.0
235 3040.0
236 3040.0
237 2895.0
238 2995.0
239 2995.0
240 3095.0
241 3195.0
242 3195.0
243 3395.0
244 3140.0
245 2505.0
246 2605.0
247 2605.0
248 2705.0
249 2705.0

model_4
GaussianNB()
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'lose_streak_dif', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
1

(3513, 46)

(3513,)

(3513, 2)

(250, 46)

(250,)

(250, 2)

     t1_odds  t2_odds       t1_prob   t2_prob  winner
0       -210      175  9.961829e-01  0.003817       1
1       -320      250  9.684284e-01  0.031572       1
2        130     -155  9.898506e-01  0.010149       0
3       -155      135  4.804075e-05  0.999952       1
4       -240      195  8.218795e-01  0.178121       0
..       ...      ...           ...       ...     ...
245      175     -230  8.375546e-01  0.162445       0
246      250     -305  1.984803e-12  1.000000       0
247     -134      105  7.615525e-01  0.238448       1
248     -105     -117  5.400438e-01  0.459956       1
249      115     -143  4.447035e-01  0.555297       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 246
          Number of winning bets: 135
          Number of losing bets: 111
          Number of underdog bets: 93
          Number of underdog wins: 38
          Number of underdog losses: 55
          Number of Favorite bets: 150
          Number of favorite wins: 97
          Number of favorite losses: 53
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -975.7067690799767
          Profit per bet: -3.966287679186897
          Profit per match: -3.9028270763199067


HI
HI
HI
HI
HI
The original score is 17711.989484820806
Score:  16168.306513543062
Score:  13779.877967946619
Score:  9899.373120721664
Score:  17609.075805005392
Score:  16399.683742966103
NEW BEST FEATURE SET
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
18781.946604232424
Score:  7391.8979043318795
Score:  14414.276113837115
Score:  13669.658056518072
Score:  16881.283999718136
Score:  14768.231483097159
Score:  16445.19276938519
Score:  14892.019363490703
Score:  16192.602531197077
Score:  11862.744070815503
Score:  15840.11165118622
Score:  17027.5883985607
Score:  3639.3761432647007
Score:  15471.557531175265
Score:  16699.638905544765
Score:  15996.004178873774
Score:  17286.674857219576
Score:  14166.002547910537
Score:  12309.900478921405
Score:  7750.468918792641
Score:  15902.78547941307
Score:  16680.426652135946
Score:  13687.972328756798
Score:  14220.502007833486
Score:  17558.48264408885
Score:  14351.197635621811
Score:  14688.520863407353
Score:  16854.84755966533
Score:  7017.530749428053
Score:  16412.960413048706
Score:  17089.387051886108
Score:  13357.67361158365
Score:  11128.599262923068
Score:  10568.950064421257
Score:  10833.177652225419
Score:  11012.52244916056
The original score is 18781.946604232424
Score:  18175.57575524027
Score:  15121.648577646236
Score:  11589.888220734996
NEW BEST FEATURE SET
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'B_current_lose_streak', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
19517.76221682876
Score:  18437.39914080661
Score:  7864.969064380384
Score:  15427.217185476122
Score:  15690.315089967526
Score:  18552.126855016126
Score:  17086.661091401278
Score:  18589.918694632648
Score:  16745.42046960012
Score:  16701.927159669238
Score:  13188.205223905716
Score:  18368.96208465374
Score:  18229.796181315898
Score:  4363.714367345939
Score:  16025.85742720297
Score:  18651.59269217833
Score:  18681.679108286648
Score:  17986.924569713006
Score:  16395.46538744808
Score:  13327.637805722374
Score:  8294.661098147431
Score:  18487.442635342726
Score:  18995.14578079809
Score:  15439.540090417768
Score:  16551.616133747437
NEW BEST FEATURE SET
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
19776.296152281822
Score:  16088.22862954297
Score:  17179.88975948622
Score:  17721.647859421162
Score:  9039.764389524516
Score:  17784.891055103708
Score:  18518.945861697037
Score:  15247.202654543442
Score:  12719.459289737588
Score:  11328.52702906792
Score:  11252.232484151635
Score:  11848.95336440434
The original score is 19776.296152281822
Score:  19307.621658759745
Score:  15976.70431114427
Score:  11574.734975833784
Score:  19740.127635562465
Score:  18786.576922750875
Score:  9356.118866310499
Score:  15325.0793838838
Score:  15871.930295441587
Score:  19315.085936677802
Score:  17858.225957769566
Score:  19155.47052286923
Score:  18698.968820805316
Score:  17097.62614054357
Score:  13486.277098640887
Score:  18585.766457170153
Score:  19452.57988747168
Score:  4939.539628499651
Score:  17634.744274380548
Score:  19033.50520160799
Score:  19277.578361304164
Score:  17378.731168748127
Score:  17732.04386938524
Score:  14667.41873877715
Score:  9192.082443339606
Score:  19267.0299926169
Score:  19623.4147026738
Score:  15721.268012581613
Score:  18623.83580318105
Score:  16973.354372557405
Score:  18567.5400187048
Score:  19227.18844096238
Score:  8300.352283993316
Score:  19049.88647323257
Score:  19454.21852488567
Score:  15906.761245144371
Score:  12546.931464576091
Score:  11228.63688069144
Score:  12599.608398051561
Score:  12819.6125429875
The features are different
OLD:
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'lose_streak_dif', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'R_win_by_Decision_Unanimous', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
NEW:
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
The EV is different
OLD:
0
NEW:
1

model_4
GaussianNB()
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
1

(3513, 44)

(3513,)

(3513, 2)

(250, 44)

(250,)

(250, 2)

     t1_odds  t2_odds       t1_prob   t2_prob  winner
0       -210      175  9.965698e-01  0.003430       1
1       -320      250  9.677500e-01  0.032250       1
2        130     -155  9.885826e-01  0.011417       0
3       -155      135  6.189663e-05  0.999938       1
4       -240      195  8.212021e-01  0.178798       0
..       ...      ...           ...       ...     ...
245      175     -230  8.516243e-01  0.148376       0
246      250     -305  1.833756e-12  1.000000       0
247     -134      105  7.418911e-01  0.258109       1
248     -105     -117  5.345844e-01  0.465416       1
249      115     -143  4.331774e-01  0.566823       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 245
          Number of winning bets: 134
          Number of losing bets: 111
          Number of underdog bets: 91
          Number of underdog wins: 37
          Number of underdog losses: 54
          Number of Favorite bets: 151
          Number of favorite wins: 97
          Number of favorite losses: 54
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -1068.2993616725696
          Profit per bet: -4.360405557847223
          Profit per match: -4.273197446690278


HI
HI
HI
HI
HI
Current best score is: 19776.296152281822
NO IMPROVEMENT
FINAL BEST SCORE: 19776.296152281822

model_4
GaussianNB()
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
1

(3513, 44)

(3513,)

(3513, 2)

(250, 44)

(250,)

(250, 2)

     t1_odds  t2_odds       t1_prob   t2_prob  winner
0       -210      175  9.965698e-01  0.003430       1
1       -320      250  9.677500e-01  0.032250       1
2        130     -155  9.885826e-01  0.011417       0
3       -155      135  6.189663e-05  0.999938       1
4       -240      195  8.212021e-01  0.178798       0
..       ...      ...           ...       ...     ...
245      175     -230  8.516243e-01  0.148376       0
246      250     -305  1.833756e-12  1.000000       0
247     -134      105  7.418911e-01  0.258109       1
248     -105     -117  5.345844e-01  0.465416       1
249      115     -143  4.331774e-01  0.566823       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 245
          Number of winning bets: 134
          Number of losing bets: 111
          Number of underdog bets: 91
          Number of underdog wins: 37
          Number of underdog losses: 54
          Number of Favorite bets: 151
          Number of favorite wins: 97
          Number of favorite losses: 54
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -1068.2993616725696
          Profit per bet: -4.360405557847223
          Profit per match: -4.273197446690278


HI
HI
HI
HI
HI


Starting New Run for GaussianNB


Previous Best Score: 19776.296152281822
var_smoothing: 1e-12 Score: 19776.296152281822
var_smoothing: 1e-11 Score: 19776.296152281822
var_smoothing: 1e-10 Score: 19776.296152281822
var_smoothing: 1e-09 Score: 19776.296152281822
var_smoothing: 1e-08 Score: 19776.296152281822
var_smoothing: 1e-07 Score: 19776.296152281822
var_smoothing: 1e-06 Score: 19776.296152281822
Real output model: GaussianNB()

model_4
GaussianNB()
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
1

(3513, 44)

(3513,)

(3513, 2)

(250, 44)

(250,)

(250, 2)

     t1_odds  t2_odds       t1_prob   t2_prob  winner
0       -210      175  9.965698e-01  0.003430       1
1       -320      250  9.677500e-01  0.032250       1
2        130     -155  9.885826e-01  0.011417       0
3       -155      135  6.189663e-05  0.999938       1
4       -240      195  8.212021e-01  0.178798       0
..       ...      ...           ...       ...     ...
245      175     -230  8.516243e-01  0.148376       0
246      250     -305  1.833756e-12  1.000000       0
247     -134      105  7.418911e-01  0.258109       1
248     -105     -117  5.345844e-01  0.465416       1
249      115     -143  4.331774e-01  0.566823       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 245
          Number of winning bets: 134
          Number of losing bets: 111
          Number of underdog bets: 91
          Number of underdog wins: 37
          Number of underdog losses: 54
          Number of Favorite bets: 151
          Number of favorite wins: 97
          Number of favorite losses: 54
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -1068.2993616725696
          Profit per bet: -4.360405557847223
          Profit per match: -4.273197446690278


HI
HI
HI
HI
HI
0 18965.93682221099
1 19776.296152281822
2 19361.882230911135
3 19186.750862424626
4 18008.484910797546
5 17112.86289191446
6 16060.367210924112
7 16714.338881755677
8 16036.962301192016
9 14973.524223284552
10 14716.266181431103
11 14738.348054140031
12 13162.393794125244
13 13182.154417712134
14 12826.05153445599
15 13526.422021699336
16 13238.554947462773
17 13217.179596032664
18 13613.457109176034
19 12282.325858308981
20 12099.691673041325
21 12563.570153577715
22 11728.262017478486
23 11774.745049788618
24 12177.118221801502
25 11773.561206886925
26 12450.350660589198
27 11962.076865333707
28 12214.9603785155
29 12155.686959329381
30 11655.871523965645
31 10972.485464463502
32 11086.052862892686
33 10583.033542374887
34 10996.786655660271
35 11443.499361921953
36 11974.210340546037
37 12022.909148559529
38 11387.69987409077
39 10364.275647520526
40 9916.006969419916
41 9328.614693214353
42 9396.922368730038
43 10040.484450324033
44 9249.0836989706
45 8616.83104822335
46 8686.356941222526
47 8169.316467583305
48 7621.923178001061
49 7056.952835349974
50 7140.596941501819
51 7483.277084050382
52 7628.8517733007175
53 7960.957158315953
54 8006.858587853285
55 8212.851515169743
56 7743.563477564514
57 7378.07665849757
58 7050.4085742781535
59 7108.262221439203
60 7366.904929306047
61 7994.711349804347
62 8272.899606039895
63 8239.084538463288
64 8529.325374823995
65 8199.807765790258
66 8113.842248548878
67 8609.573369279999
68 9089.573369279999
69 9468.830663709708
70 9281.73109661014
71 8558.082086409904
72 7783.147050647482
73 7305.338048908938
74 7010.189900760789
75 7267.87773144862
76 7357.075055863335
77 7193.641122646794
78 7125.644653096926
79 7000.168462620735
80 6580.168462620735
81 6637.168462620735
82 6585.211940881605
83 6482.036109400229
84 6610.789732588635
85 6513.833210849505
86 6535.967598201283
87 6425.098032983891
88 6754.9032277890865
89 6954.9032277890865
90 7359.9032277890865
91 7796.2668641527225
92 7211.2668641527225
93 7356.927241511214
94 7577.587618869704
95 7406.247996228194
96 7541.009900990099
97 7986.009900990099
98 7551.009900990099
99 7462.009900990099
100 6368.0
101 6289.0
102 6397.0
103 6697.0
104 7092.0
105 7422.0
106 7988.0
107 8028.0
108 8003.0
109 7508.0
110 7188.0
111 7348.0
112 7478.0
113 7513.0
114 7343.0
115 7488.0
116 7888.0
117 7663.0
118 7603.0
119 7663.0
120 7126.0
121 7226.0
122 6961.0
123 7061.0
124 7331.0
125 6841.0
126 6841.0
127 6681.0
128 6241.0
129 6386.0
130 6081.0
131 6136.0
132 6336.0
133 6536.0
134 6441.0
135 6186.0
136 5426.0
137 5626.0
138 5926.0
139 5509.0
140 5949.0
141 5949.0
142 5989.0
143 5439.0
144 5539.0
145 5939.0
146 5704.0
147 5549.0
148 5549.0
149 5749.0
150 5349.0
151 5329.0
152 5369.0
153 4949.0
154 4961.0
155 5061.0
156 5001.0
157 5201.0
158 4688.0
159 4888.0
160 4931.0
161 4931.0
162 4768.0
163 4568.0
164 4668.0
165 5038.0
166 5338.0
167 5213.0
168 4903.0
169 5003.0
170 4958.0
171 5158.0
172 5183.0
173 4968.0
174 4893.0
175 4848.0
176 4963.0
177 5063.0
178 4658.0
179 4523.0
180 4088.0
181 4188.0
182 4048.0
183 4048.0
184 4148.0
185 3458.0
186 3323.0
187 2803.0
188 2903.0
189 2903.0
190 2548.0
191 2508.0
192 2608.0
193 2808.0
194 2653.0
195 2653.0
196 2753.0
197 2588.0
198 2588.0
199 2588.0
200 2488.0
201 2073.0
202 2073.0
203 2273.0
204 2268.0
205 2163.0
206 2163.0
207 2263.0
208 2363.0
209 2048.0
210 2048.0
211 2048.0
212 1800.0
213 1900.0
214 1900.0
215 2100.0
216 2200.0
217 2300.0
218 2300.0
219 2300.0
220 2700.0
221 2900.0
222 2900.0
223 3000.0
224 3100.0
225 2875.0
226 2975.0
227 2975.0
228 2975.0
229 3075.0
230 3075.0
231 3075.0
232 3075.0
233 3275.0
234 3275.0
235 3140.0
236 2895.0
237 2895.0
238 3095.0
239 3195.0
240 3295.0
241 3295.0
242 3295.0
243 3295.0
244 3140.0
245 2605.0
246 2605.0
247 2705.0
248 2705.0
249 2705.0

model_4
GaussianNB()
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
1

(3513, 44)

(3513,)

(3513, 2)

(250, 44)

(250,)

(250, 2)

     t1_odds  t2_odds       t1_prob   t2_prob  winner
0       -210      175  9.965698e-01  0.003430       1
1       -320      250  9.677500e-01  0.032250       1
2        130     -155  9.885826e-01  0.011417       0
3       -155      135  6.189663e-05  0.999938       1
4       -240      195  8.212021e-01  0.178798       0
..       ...      ...           ...       ...     ...
245      175     -230  8.516243e-01  0.148376       0
246      250     -305  1.833756e-12  1.000000       0
247     -134      105  7.418911e-01  0.258109       1
248     -105     -117  5.345844e-01  0.465416       1
249      115     -143  4.331774e-01  0.566823       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 245
          Number of winning bets: 134
          Number of losing bets: 111
          Number of underdog bets: 91
          Number of underdog wins: 37
          Number of underdog losses: 54
          Number of Favorite bets: 151
          Number of favorite wins: 97
          Number of favorite losses: 54
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -1068.2993616725696
          Profit per bet: -4.360405557847223
          Profit per match: -4.273197446690278


HI
HI
HI
HI
HI
The original score is 19776.296152281822
Score:  19307.621658759745
Score:  15976.70431114427
Score:  11574.734975833784
Score:  19740.127635562465
Score:  18786.576922750875
Score:  9356.118866310499
Score:  15325.0793838838
Score:  15871.930295441587
Score:  19315.085936677802
Score:  17858.225957769566
Score:  19155.47052286923
Score:  18698.968820805316
Score:  17097.62614054357
Score:  13486.277098640887
Score:  18585.766457170153
Score:  19452.57988747168
Score:  4939.539628499651
Score:  17634.744274380548
Score:  19033.50520160799
Score:  19277.578361304164
Score:  17378.731168748127
Score:  17732.04386938524
Score:  14667.41873877715
Score:  9192.082443339606
Score:  19267.0299926169
Score:  19623.4147026738
Score:  15721.268012581613
Score:  18623.83580318105
Score:  16973.354372557405
Score:  18567.5400187048
Score:  19227.18844096238
Score:  8300.352283993316
Score:  19049.88647323257
Score:  19454.21852488567
Score:  15906.761245144371
Score:  12546.931464576091
Score:  11228.63688069144
Score:  12599.608398051561
Score:  12819.6125429875

model_4
GaussianNB()
['B_Heavyweight_rank', 'B_avg_SIG_STR_landed', 'R_win_by_Decision_Majority', 'R_win_by_Submission', 'B_current_lose_streak', 'better_rank', 'B_win_by_Decision_Split', "R_Women's Featherweight_rank", 'B_avg_TD_pct', 'empty_arena', 'R_Welterweight_rank', 'B_match_weightclass_rank', 'R_Middleweight_rank', 'R_Lightweight_rank', 'B_Light Heavyweight_rank', 'B_Weight_lbs', 'R_Stance', 'R_current_lose_streak', 'B_longest_win_streak', 'R_avg_SIG_STR_landed', 'R_total_rounds_fought', 'R_avg_TD_pct', 'R_age', 'B_Lightweight_rank', 'R_longest_win_streak', 'longest_win_streak_dif', 'reach_dif', 'avg_sub_att_dif', 'sig_str_dif', 'B_Height_cms', 'B_avg_SUB_ATT', 'R_win_by_TKO_Doctor_Stoppage', 'height_dif', 'B_draw', 'avg_td_dif', 'R_win_by_Decision_Split', 'age_dif', 'B_current_win_streak', 'R_odds']
1

(3513, 44)

(3513,)

(3513, 2)

(250, 44)

(250,)

(250, 2)

     t1_odds  t2_odds       t1_prob   t2_prob  winner
0       -210      175  9.965698e-01  0.003430       1
1       -320      250  9.677500e-01  0.032250       1
2        130     -155  9.885826e-01  0.011417       0
3       -155      135  6.189663e-05  0.999938       1
4       -240      195  8.212021e-01  0.178798       0
..       ...      ...           ...       ...     ...
245      175     -230  8.516243e-01  0.148376       0
246      250     -305  1.833756e-12  1.000000       0
247     -134      105  7.418911e-01  0.258109       1
248     -105     -117  5.345844e-01  0.465416       1
249      115     -143  4.331774e-01  0.566823       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 245
          Number of winning bets: 134
          Number of losing bets: 111
          Number of underdog bets: 91
          Number of underdog wins: 37
          Number of underdog losses: 54
          Number of Favorite bets: 151
          Number of favorite wins: 97
          Number of favorite losses: 54
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -1068.2993616725696
          Profit per bet: -4.360405557847223
          Profit per match: -4.273197446690278


HI
HI
HI
HI
HI

(3513, 44)

(3513,)

(3513, 2)

(250, 44)

(250,)

(250, 2)

     t1_odds  t2_odds       t1_prob   t2_prob  winner
0       -210      175  9.965698e-01  0.003430       1
1       -320      250  9.677500e-01  0.032250       1
2        130     -155  9.885826e-01  0.011417       0
3       -155      135  6.189663e-05  0.999938       1
4       -240      195  8.212021e-01  0.178798       0
..       ...      ...           ...       ...     ...
245      175     -230  8.516243e-01  0.148376       0
246      250     -305  1.833756e-12  1.000000       0
247     -134      105  7.418911e-01  0.258109       1
248     -105     -117  5.345844e-01  0.465416       1
249      115     -143  4.331774e-01  0.566823       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 245
          Number of winning bets: 134
          Number of losing bets: 111
          Number of underdog bets: 91
          Number of underdog wins: 37
          Number of underdog losses: 54
          Number of Favorite bets: 151
          Number of favorite wins: 97
          Number of favorite losses: 54
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -1068.2993616725696
          Profit per bet: -4.360405557847223
          Profit per match: -4.273197446690278


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 5


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_5
ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)
['R_ev', 'B_avg_TD_landed']
7
Current best score is: 9452.386852676356
NO IMPROVEMENT
FINAL BEST SCORE: 9452.386852676356

model_5
ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)
['R_ev', 'B_avg_TD_landed']
7

(3721, 2)

(3721,)

(3721, 2)

(250, 2)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.760300  0.239700       1
1       -320      250  0.760300  0.239700       1
2        130     -155  0.455561  0.544439       0
3       -155      135  0.455561  0.544439       1
4       -240      195  0.760300  0.239700       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455561  0.544439       0
246      250     -305  0.455561  0.544439       0
247     -134      105  0.455561  0.544439       1
248     -105     -117  0.455561  0.544439       1
249      115     -143  0.455561  0.544439       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 141
          Number of winning bets: 62
          Number of losing bets: 79
          Number of underdog bets: 110
          Number of underdog wins: 43
          Number of underdog losses: 67
          Number of Favorite bets: 31
          Number of favorite wins: 19
          Number of favorite losses: 12
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: -501.13574377600185
          Profit per bet: -3.554154211177318
          Profit per match: -2.0045429751040076


HI
HI
HI
HI
HI


Starting New Run for DecisionTree


Previous Best Score: 9452.386852676356
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 3869.418522781817
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1990.3842014403053
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1032.6007753820545
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1615.245191869434
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 3869.418522781817
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1990.3842014403053
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1032.6007753820545
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1615.245191869434
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 3869.418522781817
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1990.3842014403053
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1032.6007753820545
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1615.245191869434
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 3869.418522781817
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1990.3842014403053
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1032.6007753820545
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 1615.245191869434
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 7017.941707231308
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 2239.4652159812094
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 8751.13009342648
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 1017.083096515945
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 7017.941707231308
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 2239.4652159812094
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 8751.13009342648
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 1017.083096515945
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 7017.941707231308
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 2239.4652159812094
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 8751.13009342648
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 1017.083096515945
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 7017.941707231308
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 2239.4652159812094
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 8751.13009342648
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 1017.083096515945
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 3869.418522781817
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1990.3842014403053
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1032.6007753820545
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1615.245191869434
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 3869.418522781817
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1990.3842014403053
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1032.6007753820545
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1615.245191869434
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 3869.418522781817
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1990.3842014403053
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1032.6007753820545
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1615.245191869434
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 3869.418522781817
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1990.3842014403053
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1032.6007753820545
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 1615.245191869434
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 3798.4184114573336
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 2859.817174708728
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 1123.6899640121637
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 1495.045794813144
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 3798.4184114573336
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 2859.817174708728
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 1123.6899640121637
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 1495.045794813144
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 3798.4184114573336
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 2859.817174708728
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 1123.6899640121637
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 1495.045794813144
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 3798.4184114573336
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 2859.817174708728

Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 1123.6899640121637
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 1495.045794813144
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 7102.941707231308
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 2495.664158172207
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 8515.600590825321
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 1562.1492525989668
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 7102.941707231308
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 2495.664158172207
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 8515.600590825321
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 1562.1492525989668
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 7102.941707231308
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 2495.664158172207
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 8515.600590825321
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 1562.1492525989668
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 7102.941707231308
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 2495.664158172207
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 8515.600590825321
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 1562.1492525989668
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 3798.4184114573336
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 2859.817174708728
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 1123.6899640121637
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 1495.045794813144
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 3798.4184114573336
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 2859.817174708728
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 1123.6899640121637
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 1495.045794813144
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 3798.4184114573336
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 2859.817174708728
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 1123.6899640121637
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 1495.045794813144
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 3798.4184114573336
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 2859.817174708728
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 1123.6899640121637
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 1495.045794813144
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 2369.418522781817
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 2682.2657299653356
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 1091.3890122093983
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -61.63491696590097
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 2369.418522781817
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 2682.2657299653356
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 1091.3890122093983
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -61.63491696590097
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 2369.418522781817
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 2682.2657299653356
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 1091.3890122093983
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -61.63491696590097
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 2369.418522781817
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 2682.2657299653356
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 1091.3890122093983
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -61.63491696590097
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 7017.941707231308
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 2074.3820475820467
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 8617.512735272157
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -567.2805398476911
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 7017.941707231308
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 2074.3820475820467
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 8617.512735272157
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -567.2805398476911
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 7017.941707231308
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 2074.3820475820467
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 8617.512735272157
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -567.2805398476911
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 7017.941707231308
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 2074.3820475820467
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 8617.512735272157
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -567.2805398476911
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 2369.418522781817
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 2682.2657299653356
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 1091.3890122093983

Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -61.63491696590097
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 2369.418522781817
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 2682.2657299653356
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 1091.3890122093983
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -61.63491696590097
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 2369.418522781817
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 2682.2657299653356
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 1091.3890122093983
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -61.63491696590097
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 2369.418522781817
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 2682.2657299653356
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 1091.3890122093983
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -61.63491696590097
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 2590.429511857951
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 -3106.270812986536
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 1718.713832316827
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 -6390.347833519903
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 2590.429511857951
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 -3106.270812986536
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 1718.713832316827
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 -6390.347833519903
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 2590.429511857951
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 -3106.270812986536
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 1718.713832316827
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 -6390.347833519903
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 2590.429511857951
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 -3106.270812986536
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 1718.713832316827
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 846 -6390.347833519903
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 7413.97825933169
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 -3804.555889633644
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 8494.108021576621
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 -8160.998091621455
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 7413.97825933169
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 -3804.555889633644
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 8494.108021576621
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 -8160.998091621455
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 7413.97825933169
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 -3804.555889633644
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 8494.108021576621
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 -8160.998091621455
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 7413.97825933169
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 -3804.555889633644
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 8494.108021576621
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.01009899 max_leaf_nodes: 846 -8160.998091621455
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 2590.429511857951
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 -3106.270812986536
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 1718.713832316827
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 -6390.347833519903
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 2590.429511857951
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 -3106.270812986536
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 1718.713832316827
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 -6390.347833519903
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 2590.429511857951
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 -3106.270812986536
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 1718.713832316827
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 -6390.347833519903
Criterion: gini splitter: random max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 2590.429511857951
Criterion: gini splitter: best max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 -3106.270812986536
Criterion: entropy splitter: random max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 1718.713832316827
Criterion: entropy splitter: best max_depth: 85 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 846 -6390.347833519903
Real output model: ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)

model_5
ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)
['R_ev', 'B_avg_TD_landed']
7

(3721, 2)

(3721,)

(3721, 2)

(250, 2)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.760300  0.239700       1
1       -320      250  0.760300  0.239700       1
2        130     -155  0.455561  0.544439       0
3       -155      135  0.455561  0.544439       1
4       -240      195  0.760300  0.239700       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455561  0.544439       0
246      250     -305  0.455561  0.544439       0
247     -134      105  0.455561  0.544439       1
248     -105     -117  0.455561  0.544439       1
249      115     -143  0.455561  0.544439       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 141
          Number of winning bets: 62
          Number of losing bets: 79
          Number of underdog bets: 110
          Number of underdog wins: 43
          Number of underdog losses: 67
          Number of Favorite bets: 31
          Number of favorite wins: 19
          Number of favorite losses: 12
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: -501.13574377600185
          Profit per bet: -3.554154211177318
          Profit per match: -2.0045429751040076


HI
HI
HI
HI
HI
0 7676.861129757999
1 8403.750200250894
2 6195.223476927736
3 6843.628131544133
4 5369.82215521856
5 5865.602616970329
6 7730.724702689694
7 9452.386852676356
8 8901.090013545409
9 6607.055716786232
10 7127.722314011358
11 6630.85977742449
12 5838.75802297965
13 7459.262391801842
14 6790.452867992318
15 8168.119534658985
16 8922.636776038295
17 8871.42174107326
18 9617.058104709624
19 8744.058104709624
20 7614.0781709476905
21 8044.990451649445
22 6994.953414612408
23 7836.847031633684
24 7338.368770764119
25 7501.368770764119
26 6090.368770764119
27 4506.857142857143
28 4905.0
29 4222.0
30 3282.0
31 3615.0
32 4047.0
33 3319.0
34 3086.0
35 3406.0
36 3116.0
37 3116.0
38 3511.0
39 3396.0
40 3186.0
41 3571.0
42 3241.0
43 2636.0
44 2736.0
45 2996.0
46 2551.0
47 2631.0
48 2961.0
49 2961.0
50 2751.0
51 2751.0
52 2821.0
53 2631.0
54 2556.0
55 1816.0
56 2216.0
57 2191.0
58 2246.0
59 2101.0
60 2205.0
61 2455.0
62 2755.0
63 3095.0
64 2330.0
65 1905.0
66 700.0
67 640.0
68 -305.0
69 -5.0
70 -80.0
71 -490.0
72 -770.0
73 -545.0
74 -830.0
75 -730.0
76 -910.0
77 -1665.0
78 -1850.0
79 -2425.0
80 -2605.0
81 -2305.0
82 -2205.0
83 -2105.0
84 -1605.0
85 -1005.0
86 -1115.0
87 -1015.0
88 -515.0
89 -415.0
90 -15.0
91 85.0
92 160.0
93 -60.0
94 140.0
95 240.0
96 540.0
97 315.0
98 315.0
99 315.0
100 515.0
101 815.0
102 815.0
103 815.0
104 665.0
105 665.0
106 420.0
107 420.0
108 620.0
109 720.0
110 720.0
111 820.0
112 820.0
113 820.0
114 820.0
115 745.0
116 845.0
117 945.0
118 1345.0
119 1445.0
120 1445.0
121 1445.0
122 1645.0
123 1645.0
124 1260.0
125 1260.0
126 1260.0
127 1260.0
128 1260.0
129 1360.0
130 1360.0
131 1360.0
132 1360.0
133 1460.0
134 1460.0
135 1460.0
136 1660.0
137 1660.0
138 1130.0
139 1130.0
140 390.0
141 390.0
142 165.0
143 265.0
144 265.0
145 365.0
146 365.0
147 565.0
148 565.0
149 415.0
150 415.0
151 415.0
152 415.0
153 415.0
154 715.0
155 715.0
156 715.0
157 715.0
158 815.0
159 815.0
160 815.0
161 815.0
162 815.0
163 915.0
164 440.0
165 440.0
166 440.0
167 440.0
168 540.0
169 540.0
170 55.0
171 55.0
172 55.0
173 55.0
174 55.0
175 255.0
176 255.0
177 -245.0
178 -245.0
179 -245.0
180 -145.0
181 -145.0
182 -145.0
183 -45.0
184 -45.0
185 -45.0
186 -45.0
187 -45.0
188 -45.0
189 -45.0
190 155.0
191 155.0
192 155.0
193 155.0
194 155.0
195 155.0
196 255.0
197 255.0
198 255.0
199 255.0
200 355.0
201 355.0
202 355.0
203 355.0
204 355.0
205 355.0
206 355.0
207 355.0
208 355.0
209 355.0
210 355.0
211 355.0
212 355.0
213 355.0
214 355.0
215 355.0
216 355.0
217 355.0
218 355.0
219 355.0
220 355.0
221 455.0
222 455.0
223 655.0
224 655.0
225 655.0
226 655.0
227 655.0
228 655.0
229 655.0
230 655.0
231 655.0
232 655.0
233 655.0
234 655.0
235 655.0
236 655.0
237 655.0
238 655.0
239 655.0
240 655.0
241 655.0
242 655.0
243 655.0
244 655.0
245 655.0
246 655.0
247 655.0
248 655.0
249 0

model_5
ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)
['R_ev', 'B_avg_TD_landed']
18

(3721, 2)

(3721,)

(3721, 2)

(250, 2)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.760300  0.239700       1
1       -320      250  0.760300  0.239700       1
2        130     -155  0.455561  0.544439       0
3       -155      135  0.455561  0.544439       1
4       -240      195  0.760300  0.239700       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455561  0.544439       0
246      250     -305  0.455561  0.544439       0
247     -134      105  0.455561  0.544439       1
248     -105     -117  0.455561  0.544439       1
249      115     -143  0.455561  0.544439       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 56
          Number of winning bets: 20
          Number of losing bets: 36
          Number of underdog bets: 56
          Number of underdog wins: 20
          Number of underdog losses: 36
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: -153.0
          Profit per bet: -2.732142857142857
          Profit per match: -0.612


HI
HI
HI
HI
HI
The original score is 9617.058104709624
Score:  -10329.089027512313
Score:  1038.0
The EV is different
OLD:
7
NEW:
18

model_5
ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)
['R_ev', 'B_avg_TD_landed']
18

(3721, 2)

(3721,)

(3721, 2)

(250, 2)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.760300  0.239700       1
1       -320      250  0.760300  0.239700       1
2        130     -155  0.455561  0.544439       0
3       -155      135  0.455561  0.544439       1
4       -240      195  0.760300  0.239700       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455561  0.544439       0
246      250     -305  0.455561  0.544439       0
247     -134      105  0.455561  0.544439       1
248     -105     -117  0.455561  0.544439       1
249      115     -143  0.455561  0.544439       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 56
          Number of winning bets: 20
          Number of losing bets: 36
          Number of underdog bets: 56
          Number of underdog wins: 20
          Number of underdog losses: 36
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: -153.0
          Profit per bet: -2.732142857142857
          Profit per match: -0.612


HI
HI
HI
HI
HI
Current best score is: 9617.058104709624
NO IMPROVEMENT
FINAL BEST SCORE: 9617.058104709624

model_5
ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)
['R_ev', 'B_avg_TD_landed']
18

(3721, 2)

(3721,)

(3721, 2)

(250, 2)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.760300  0.239700       1
1       -320      250  0.760300  0.239700       1
2        130     -155  0.455561  0.544439       0
3       -155      135  0.455561  0.544439       1
4       -240      195  0.760300  0.239700       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455561  0.544439       0
246      250     -305  0.455561  0.544439       0
247     -134      105  0.455561  0.544439       1
248     -105     -117  0.455561  0.544439       1
249      115     -143  0.455561  0.544439       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 56
          Number of winning bets: 20
          Number of losing bets: 36
          Number of underdog bets: 56
          Number of underdog wins: 20
          Number of underdog losses: 36
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: -153.0
          Profit per bet: -2.732142857142857
          Profit per match: -0.612


HI
HI
HI
HI
HI


Starting New Run for DecisionTree


Previous Best Score: 9617.058104709624
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 5644.0
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 -685.0468640977629
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 4615.438195800278
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 -2899.265590203975
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 5644.0
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 -685.0468640977629
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 4615.438195800278
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 -2899.265590203975
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 5644.0
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 -685.0468640977629
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 4615.438195800278
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 -2899.265590203975
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 5644.0
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 -685.0468640977629
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 4615.438195800278
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 20 -2899.265590203975
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 7249.144233964773
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 -687.0468640977631
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 8762.175686323699
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 -3153.698376252891
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 7249.144233964773
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 -687.0468640977631
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 8762.175686323699
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 -3153.698376252891
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 7249.144233964773
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 -687.0468640977631
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 8762.175686323699
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 -3153.698376252891
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 7249.144233964773
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 -687.0468640977631
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 8762.175686323699
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 20 -3153.698376252891
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 5644.0
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 -685.0468640977629
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 4615.438195800278
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 -2899.265590203975
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 5644.0
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 -685.0468640977629
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 4615.438195800278
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 -2899.265590203975
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 5644.0
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 -685.0468640977629
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 4615.438195800278
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 -2899.265590203975
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 5644.0
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 -685.0468640977629
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 4615.438195800278
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 20 -2899.265590203975
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 5644.0
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 -982.6281632057796
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 4615.438195800278
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 -2554.9627738582594
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 5644.0
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 -982.6281632057796
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 4615.438195800278
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 -2554.9627738582594
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 5644.0
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 -982.6281632057796
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 4615.438195800278
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 -2554.9627738582594
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 5644.0
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 -982.6281632057796
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 4615.438195800278

Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 19 -2554.9627738582594
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 7349.144233964773
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 -1023.1070633752981
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 8587.175686323699
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 -2556.2782919687925
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 7349.144233964773
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 -1023.1070633752981
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 8587.175686323699
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 -2556.2782919687925
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 7349.144233964773
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 -1023.1070633752981
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 8587.175686323699
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 -2556.2782919687925
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 7349.144233964773
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 -1023.1070633752981
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 8587.175686323699
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 19 -2556.2782919687925
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 5644.0
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 -982.6281632057796
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 4615.438195800278
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 -2554.9627738582594
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 5644.0
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 -982.6281632057796
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 4615.438195800278
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 -2554.9627738582594
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 5644.0
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 -982.6281632057796
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 4615.438195800278
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 -2554.9627738582594
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 5644.0
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 -982.6281632057796
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 4615.438195800278
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 19 -2554.9627738582594
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 5644.0
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -1554.1554786466036
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 4671.935370941521
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -3168.35444517189
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 5644.0
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -1554.1554786466036
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 4671.935370941521
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -3168.35444517189
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 5644.0
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -1554.1554786466036
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 4671.935370941521
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -3168.35444517189
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 5644.0
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -1554.1554786466036
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 4671.935370941521
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 21 -3168.35444517189
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 7149.144233964773
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -1901.5844000835898
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 8762.175686323699
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -3047.7872312208065
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 7149.144233964773
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -1901.5844000835898
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 8762.175686323699
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -3047.7872312208065
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 7149.144233964773
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -1901.5844000835898
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 8762.175686323699
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -3047.7872312208065
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 7149.144233964773
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -1901.5844000835898
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 8762.175686323699
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 21 -3047.7872312208065
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 5644.0
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -1554.1554786466036
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 4671.935370941521
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -3168.35444517189
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 5644.0

Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -1554.1554786466036
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 4671.935370941521
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -3168.35444517189
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 5644.0
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -1554.1554786466036
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 4671.935370941521
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -3168.35444517189
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 5644.0
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -1554.1554786466036
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 4671.935370941521
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 21 -3168.35444517189
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 5636.0
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 -6868.8079628225405
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 4648.506799512948
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 -7167.521200072954
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 5636.0
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 -6868.8079628225405
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 4648.506799512948
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 -7167.521200072954
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 5636.0
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 -6868.8079628225405
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 4648.506799512948
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 -7167.521200072954
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 5636.0
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 -6868.8079628225405
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 4648.506799512948
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.009999000000000001 max_leaf_nodes: 940 -7167.521200072954
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 7922.622494834338
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 -5157.985357252257
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 8422.175686323699
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 -6079.429297375046
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 7922.622494834338
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 -5157.985357252257
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 8422.175686323699
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 -6079.429297375046
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 7922.622494834338
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 -5157.985357252257
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 8422.175686323699
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 -6079.429297375046
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 7922.622494834338
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 -5157.985357252257
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 8422.175686323699
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.01009899 max_leaf_nodes: 940 -6079.429297375046
Criterion: gini splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 5636.0
Criterion: gini splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 -6868.8079628225405
Criterion: entropy splitter: random max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 4648.506799512948
Criterion: entropy splitter: best max_depth: 83 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 -7167.521200072954
Criterion: gini splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 5636.0
Criterion: gini splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 -6868.8079628225405
Criterion: entropy splitter: random max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 4648.506799512948
Criterion: entropy splitter: best max_depth: 82 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 -7167.521200072954
Criterion: gini splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 5636.0
Criterion: gini splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 -6868.8079628225405
Criterion: entropy splitter: random max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 4648.506799512948
Criterion: entropy splitter: best max_depth: 84 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 -7167.521200072954
Criterion: gini splitter: random max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 5636.0
Criterion: gini splitter: best max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 -6868.8079628225405
Criterion: entropy splitter: random max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 4648.506799512948
Criterion: entropy splitter: best max_depth: 45 min_samples_leaf: 0.009899010000000001 max_leaf_nodes: 940 -7167.521200072954
Real output model: ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)

model_5
ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)
['R_ev', 'B_avg_TD_landed']
18

(3721, 2)

(3721,)

(3721, 2)

(250, 2)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.760300  0.239700       1
1       -320      250  0.760300  0.239700       1
2        130     -155  0.455561  0.544439       0
3       -155      135  0.455561  0.544439       1
4       -240      195  0.760300  0.239700       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455561  0.544439       0
246      250     -305  0.455561  0.544439       0
247     -134      105  0.455561  0.544439       1
248     -105     -117  0.455561  0.544439       1
249      115     -143  0.455561  0.544439       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 56
          Number of winning bets: 20
          Number of losing bets: 36
          Number of underdog bets: 56
          Number of underdog wins: 20
          Number of underdog losses: 36
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: -153.0
          Profit per bet: -2.732142857142857
          Profit per match: -0.612


HI
HI
HI
HI
HI
0 7676.861129757999
1 8403.750200250894
2 6195.223476927736
3 6843.628131544133
4 5369.82215521856
5 5865.602616970329
6 7730.724702689694
7 9452.386852676356
8 8901.090013545409
9 6607.055716786232
10 7127.722314011358
11 6630.85977742449
12 5838.75802297965
13 7459.262391801842
14 6790.452867992318
15 8168.119534658985
16 8922.636776038295
17 8871.42174107326
18 9617.058104709624
19 8744.058104709624
20 7614.0781709476905
21 8044.990451649445
22 6994.953414612408
23 7836.847031633684
24 7338.368770764119
25 7501.368770764119
26 6090.368770764119
27 4506.857142857143
28 4905.0
29 4222.0
30 3282.0
31 3615.0
32 4047.0
33 3319.0
34 3086.0
35 3406.0
36 3116.0
37 3116.0
38 3511.0
39 3396.0
40 3186.0
41 3571.0
42 3241.0
43 2636.0
44 2736.0
45 2996.0
46 2551.0
47 2631.0
48 2961.0
49 2961.0
50 2751.0
51 2751.0
52 2821.0
53 2631.0
54 2556.0
55 1816.0
56 2216.0
57 2191.0
58 2246.0
59 2101.0
60 2205.0
61 2455.0
62 2755.0
63 3095.0
64 2330.0
65 1905.0
66 700.0
67 640.0
68 -305.0
69 -5.0
70 -80.0
71 -490.0
72 -770.0
73 -545.0
74 -830.0
75 -730.0
76 -910.0
77 -1665.0
78 -1850.0
79 -2425.0
80 -2605.0
81 -2305.0
82 -2205.0
83 -2105.0
84 -1605.0
85 -1005.0
86 -1115.0
87 -1015.0
88 -515.0
89 -415.0
90 -15.0
91 85.0
92 160.0
93 -60.0
94 140.0
95 240.0
96 540.0
97 315.0
98 315.0
99 315.0
100 515.0
101 815.0
102 815.0
103 815.0
104 665.0
105 665.0
106 420.0
107 420.0
108 620.0
109 720.0
110 720.0
111 820.0
112 820.0
113 820.0
114 820.0
115 745.0
116 845.0
117 945.0
118 1345.0
119 1445.0
120 1445.0
121 1445.0
122 1645.0
123 1645.0
124 1260.0
125 1260.0
126 1260.0
127 1260.0
128 1260.0
129 1360.0
130 1360.0
131 1360.0
132 1360.0
133 1460.0
134 1460.0
135 1460.0
136 1660.0
137 1660.0
138 1130.0
139 1130.0
140 390.0
141 390.0
142 165.0
143 265.0
144 265.0
145 365.0
146 365.0
147 565.0
148 565.0
149 415.0
150 415.0
151 415.0
152 415.0
153 415.0
154 715.0
155 715.0
156 715.0
157 715.0
158 815.0
159 815.0
160 815.0
161 815.0
162 815.0
163 915.0
164 440.0
165 440.0
166 440.0
167 440.0
168 540.0
169 540.0
170 55.0
171 55.0
172 55.0
173 55.0
174 55.0
175 255.0
176 255.0
177 -245.0
178 -245.0
179 -245.0
180 -145.0
181 -145.0
182 -145.0
183 -45.0
184 -45.0
185 -45.0
186 -45.0
187 -45.0
188 -45.0
189 -45.0
190 155.0
191 155.0
192 155.0
193 155.0
194 155.0
195 155.0
196 255.0
197 255.0
198 255.0
199 255.0
200 355.0
201 355.0
202 355.0
203 355.0
204 355.0
205 355.0
206 355.0
207 355.0
208 355.0
209 355.0
210 355.0
211 355.0
212 355.0
213 355.0
214 355.0
215 355.0
216 355.0
217 355.0
218 355.0
219 355.0
220 355.0
221 455.0
222 455.0
223 655.0
224 655.0
225 655.0
226 655.0
227 655.0
228 655.0
229 655.0
230 655.0
231 655.0
232 655.0
233 655.0
234 655.0
235 655.0
236 655.0
237 655.0
238 655.0
239 655.0
240 655.0
241 655.0
242 655.0
243 655.0
244 655.0
245 655.0
246 655.0
247 655.0
248 655.0
249 0

model_5
ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)
['R_ev', 'B_avg_TD_landed']
18

(3721, 2)

(3721,)

(3721, 2)

(250, 2)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.760300  0.239700       1
1       -320      250  0.760300  0.239700       1
2        130     -155  0.455561  0.544439       0
3       -155      135  0.455561  0.544439       1
4       -240      195  0.760300  0.239700       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455561  0.544439       0
246      250     -305  0.455561  0.544439       0
247     -134      105  0.455561  0.544439       1
248     -105     -117  0.455561  0.544439       1
249      115     -143  0.455561  0.544439       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 56
          Number of winning bets: 20
          Number of losing bets: 36
          Number of underdog bets: 56
          Number of underdog wins: 20
          Number of underdog losses: 36
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: -153.0
          Profit per bet: -2.732142857142857
          Profit per match: -0.612


HI
HI
HI
HI
HI
The original score is 9617.058104709624
Score:  -10329.089027512313
Score:  1038.0

model_5
ExtraTreeClassifier(criterion='entropy', max_depth=83, max_leaf_nodes=20,
                    min_samples_leaf=0.009999000000000001, random_state=75)
['R_ev', 'B_avg_TD_landed']
18

(3721, 2)

(3721,)

(3721, 2)

(250, 2)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.760300  0.239700       1
1       -320      250  0.760300  0.239700       1
2        130     -155  0.455561  0.544439       0
3       -155      135  0.455561  0.544439       1
4       -240      195  0.760300  0.239700       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455561  0.544439       0
246      250     -305  0.455561  0.544439       0
247     -134      105  0.455561  0.544439       1
248     -105     -117  0.455561  0.544439       1
249      115     -143  0.455561  0.544439       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 56
          Number of winning bets: 20
          Number of losing bets: 36
          Number of underdog bets: 56
          Number of underdog wins: 20
          Number of underdog losses: 36
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: -153.0
          Profit per bet: -2.732142857142857
          Profit per match: -0.612


HI
HI
HI
HI
HI

(3721, 2)

(3721,)

(3721, 2)

(250, 2)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.760300  0.239700       1
1       -320      250  0.760300  0.239700       1
2        130     -155  0.455561  0.544439       0
3       -155      135  0.455561  0.544439       1
4       -240      195  0.760300  0.239700       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455561  0.544439       0
246      250     -305  0.455561  0.544439       0
247     -134      105  0.455561  0.544439       1
248     -105     -117  0.455561  0.544439       1
249      115     -143  0.455561  0.544439       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 56
          Number of winning bets: 20
          Number of losing bets: 36
          Number of underdog bets: 56
          Number of underdog wins: 20
          Number of underdog losses: 36
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: -153.0
          Profit per bet: -2.732142857142857
          Profit per match: -0.612


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 6


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_6
MLPClassifier(hidden_layer_sizes=(7,), max_iter=250, random_state=75)
['lose_streak_dif', 'R_win_by_Decision_Split', 'R_Stance', 'R_age', 'B_age', 'R_win_by_TKO_Doctor_Stoppage', 'B_ev']
0
Current best score is: 23103.382596636708
NO IMPROVEMENT
FINAL BEST SCORE: 23103.382596636708

model_6
MLPClassifier(hidden_layer_sizes=(7,), max_iter=250, random_state=75)
['lose_streak_dif', 'R_win_by_Decision_Split', 'R_Stance', 'R_age', 'B_age', 'R_win_by_TKO_Doctor_Stoppage', 'B_ev']
0

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.649410  0.350590       1
1       -320      250  0.745659  0.254341       1
2        130     -155  0.302078  0.697922       0
3       -155      135  0.579999  0.420001       1
4       -240      195  0.690260  0.309740       0
..       ...      ...       ...       ...     ...
245      175     -230  0.303255  0.696745       0
246      250     -305  0.469932  0.530068       0
247     -134      105  0.570937  0.429063       1
248     -105     -117  0.441755  0.558245       1
249      115     -143  0.427572  0.572428       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 184
          Number of winning bets: 95
          Number of losing bets: 90
          Number of underdog bets: 103
          Number of underdog wins: 39
          Number of underdog losses: 64
          Number of Favorite bets: 81
          Number of favorite wins: 56
          Number of favorite losses: 25
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 116.12776075987121
          Profit per bet: 0.6311291345645175
          Profit per match: 0.4645110430394848


HI
HI
HI
HI
HI
MLPClassifier


Starting New Run for MLPClassifier


Previous Best Score: 23103.382596636708
hidden_layer_sizes: (7,) Score: 15372.900958519987
hidden_layer_sizes: (100,) Score: -327.89256348414096
hidden_layer_sizes: (10, 5) Score: 4329.164766523612
hidden_layer_sizes: (6,) Score: 18298.137676289534
hidden_layer_sizes: (1,) Score: 5317.62164145862
hidden_layer_sizes: (5,) Score: 17266.323846857045
hidden_layer_sizes: (15,) Score: 10917.415742410067
hidden_layer_sizes: (25,) Score: 8216.018546711482
Real output model: MLPClassifier(hidden_layer_sizes=(7,), max_iter=250, random_state=75)

model_6
MLPClassifier(hidden_layer_sizes=(7,), max_iter=250, random_state=75)
['lose_streak_dif', 'R_win_by_Decision_Split', 'R_Stance', 'R_age', 'B_age', 'R_win_by_TKO_Doctor_Stoppage', 'B_ev']
0

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.649410  0.350590       1
1       -320      250  0.745659  0.254341       1
2        130     -155  0.302078  0.697922       0
3       -155      135  0.579999  0.420001       1
4       -240      195  0.690260  0.309740       0
..       ...      ...       ...       ...     ...
245      175     -230  0.303255  0.696745       0
246      250     -305  0.469932  0.530068       0
247     -134      105  0.570937  0.429063       1
248     -105     -117  0.441755  0.558245       1
249      115     -143  0.427572  0.572428       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 184
          Number of winning bets: 95
          Number of losing bets: 90
          Number of underdog bets: 103
          Number of underdog wins: 39
          Number of underdog losses: 64
          Number of Favorite bets: 81
          Number of favorite wins: 56
          Number of favorite losses: 25
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 116.12776075987121
          Profit per bet: 0.6311291345645175
          Profit per match: 0.4645110430394848


HI
HI
HI
HI
HI
0 23103.382596636708
1 21779.78331544798
2 19943.562049179396
3 16518.170364867427
4 16287.780002309353
5 18548.336764464642
6 16924.934213690314
7 16544.922206223808
8 12296.089014513143
9 11043.345816923464
10 9720.155142289193
11 9842.432163672564
12 10001.266565539976
13 10806.137546577183
14 10820.84755037173
15 10796.41907060992
16 10795.687046002378
17 9598.721568213756
18 7669.8190293112175
19 6612.619139595199
20 6962.258933997839
21 6259.158490581605
22 4951.420998937819
23 5084.478356869851
24 4596.212209796706
25 4545.97411455861
26 4581.634491917101
27 5206.9591672417755
28 5015.292500575109
29 3519.459167241776
30 3457.5026455026455
31 3302.5026455026455
32 2962.5026455026455
33 3417.5026455026455
34 3568.4285714285716
35 3038.4285714285716
36 2813.4285714285716
37 3088.4285714285716
38 3493.4285714285716
39 3338.4285714285716
40 2898.4285714285716
41 2458.4285714285716
42 1674.4285714285716
43 1539.4285714285716
44 1081.4285714285716
45 390.0
46 395.0
47 715.0
48 305.0
49 285.0
50 25.0
51 -45.0
52 -420.0
53 -875.0
54 -1355.0
55 -1625.0
56 -1425.0
57 -1355.0
58 -755.0
59 -980.0
60 -610.0
61 -110.0
62 -10.0
63 230.0
64 385.0
65 300.0
66 600.0
67 800.0
68 1200.0
69 1320.0
70 1620.0
71 1300.0
72 885.0
73 455.0
74 230.0
75 230.0
76 -675.0
77 -575.0
78 -375.0
79 -275.0
80 -275.0
81 -175.0
82 25.0
83 -50.0
84 150.0
85 450.0
86 550.0
87 550.0
88 75.0
89 275.0
90 125.0
91 60.0
92 160.0
93 160.0
94 260.0
95 260.0
96 -30.0
97 70.0
98 370.0
99 570.0
100 245.0
101 245.0
102 170.0
103 270.0
104 270.0
105 370.0
106 370.0
107 370.0
108 370.0
109 110.0
110 110.0
111 110.0
112 310.0
113 310.0
114 310.0
115 -75.0
116 -525.0
117 -425.0
118 -325.0
119 -225.0
120 -225.0
121 -225.0
122 -225.0
123 -125.0
124 -25.0
125 75.0
126 75.0
127 75.0
128 75.0
129 75.0
130 75.0
131 75.0
132 75.0
133 75.0
134 75.0
135 75.0
136 175.0
137 -210.0
138 -210.0
139 -210.0
140 -210.0
141 -210.0
142 -210.0
143 -210.0
144 -210.0
145 -110.0
146 -110.0
147 -10.0
148 -10.0
149 -10.0
150 -10.0
151 -10.0
152 -10.0
153 -10.0
154 -10.0
155 -10.0
156 -10.0
157 -10.0
158 -10.0
159 -10.0
160 -10.0
161 -10.0
162 -200
163 -200
164 -200
165 -200
166 -200
167 -200
168 -200
169 -200
170 -200
171 -200
172 -200
173 -200
174 -200
175 -200
176 -100
177 -100
178 -100
179 -100
180 -100
181 -100
182 -100
183 -100
184 -100
185 -100
186 -100
187 -100
188 -100
189 -100
190 -100
191 -100
192 -100
193 -100
194 -100
195 -100
196 -100
197 -100
198 -100
199 -100
200 -100
201 -100
202 -100
203 -100
204 0
205 0
206 0
207 0
208 0
209 0
210 0
211 0
212 0
213 0
214 0
215 0
216 0
217 0
218 0
219 0
220 0
221 0
222 0
223 0
224 0
225 0
226 0
227 0
228 0
229 0
230 0
231 0
232 0
233 0
234 0
235 0
236 0
237 0
238 0
239 0
240 0
241 0
242 0
243 0
244 0
245 0
246 0
247 0
248 0
249 0

model_6
MLPClassifier(hidden_layer_sizes=(7,), max_iter=250, random_state=75)
['lose_streak_dif', 'R_win_by_Decision_Split', 'R_Stance', 'R_age', 'B_age', 'R_win_by_TKO_Doctor_Stoppage', 'B_ev']
0

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.649410  0.350590       1
1       -320      250  0.745659  0.254341       1
2        130     -155  0.302078  0.697922       0
3       -155      135  0.579999  0.420001       1
4       -240      195  0.690260  0.309740       0
..       ...      ...       ...       ...     ...
245      175     -230  0.303255  0.696745       0
246      250     -305  0.469932  0.530068       0
247     -134      105  0.570937  0.429063       1
248     -105     -117  0.441755  0.558245       1
249      115     -143  0.427572  0.572428       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 184
          Number of winning bets: 95
          Number of losing bets: 90
          Number of underdog bets: 103
          Number of underdog wins: 39
          Number of underdog losses: 64
          Number of Favorite bets: 81
          Number of favorite wins: 56
          Number of favorite losses: 25
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 116.12776075987121
          Profit per bet: 0.6311291345645175
          Profit per match: 0.4645110430394848


HI
HI
HI
HI
HI
The original score is 23103.382596636708
Score:  21278.1665457314
Score:  15481.611540674869
Score:  17710.913510580707
Score:  21934.325737467418
Score:  11666.084963775947
Score:  13073.761128197606
Score:  -7153.523907270286

model_6
MLPClassifier(hidden_layer_sizes=(7,), max_iter=250, random_state=75)
['lose_streak_dif', 'R_win_by_Decision_Split', 'R_Stance', 'R_age', 'B_age', 'R_win_by_TKO_Doctor_Stoppage', 'B_ev']
0

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.649410  0.350590       1
1       -320      250  0.745659  0.254341       1
2        130     -155  0.302078  0.697922       0
3       -155      135  0.579999  0.420001       1
4       -240      195  0.690260  0.309740       0
..       ...      ...       ...       ...     ...
245      175     -230  0.303255  0.696745       0
246      250     -305  0.469932  0.530068       0
247     -134      105  0.570937  0.429063       1
248     -105     -117  0.441755  0.558245       1
249      115     -143  0.427572  0.572428       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 184
          Number of winning bets: 95
          Number of losing bets: 90
          Number of underdog bets: 103
          Number of underdog wins: 39
          Number of underdog losses: 64
          Number of Favorite bets: 81
          Number of favorite wins: 56
          Number of favorite losses: 25
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 116.12776075987121
          Profit per bet: 0.6311291345645175
          Profit per match: 0.4645110430394848


HI
HI
HI
HI
HI

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.649410  0.350590       1
1       -320      250  0.745659  0.254341       1
2        130     -155  0.302078  0.697922       0
3       -155      135  0.579999  0.420001       1
4       -240      195  0.690260  0.309740       0
..       ...      ...       ...       ...     ...
245      175     -230  0.303255  0.696745       0
246      250     -305  0.469932  0.530068       0
247     -134      105  0.570937  0.429063       1
248     -105     -117  0.441755  0.558245       1
249      115     -143  0.427572  0.572428       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 184
          Number of winning bets: 95
          Number of losing bets: 90
          Number of underdog bets: 103
          Number of underdog wins: 39
          Number of underdog losses: 64
          Number of Favorite bets: 81
          Number of favorite wins: 56
          Number of favorite losses: 25
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: 116.12776075987121
          Profit per bet: 0.6311291345645175
          Profit per match: 0.4645110430394848


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 7


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_7
RadiusNeighborsClassifier(outlier_label='most_frequent')
["R_Women's Flyweight_rank", 'R_draw', "B_Women's Strawweight_rank", 'B_Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
5
Current best score is: 23422.973030021414
Feature: R_Women's Strawweight_rank Score: 23708.075959687332
The best feature was R_Women's Strawweight_rank.  It scored 23708.075959687332
Current best score is: 23708.075959687332
NO IMPROVEMENT
FINAL BEST SCORE: 23708.075959687332

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent')
["R_Women's Strawweight_rank", "R_Women's Flyweight_rank", 'R_draw', "B_Women's Strawweight_rank", 'B_Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
5

(3513, 20)

(3513,)

(3513, 2)

(250, 20)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  1.000000  0.000000       1
4       -240      195  0.222222  0.777778       0
..       ...      ...       ...       ...     ...
245      175     -230  0.592593  0.407407       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  1.000000  0.000000       1
249      115     -143  0.777778  0.222222       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 232
          Number of winning bets: 127
          Number of losing bets: 105
          Number of underdog bets: 125
          Number of underdog wins: 55
          Number of underdog losses: 70
          Number of Favorite bets: 104
          Number of favorite wins: 72
          Number of favorite losses: 32
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1549.3872900743784
          Profit per bet: 6.678393491699906
          Profit per match: 6.1975491602975135


HI
HI
HI
HI
HI


Starting New Run for RadiusNeighborsClassifier


Previous Best Score: 23708.075959687332
weights: uniform p: 1 Score: 10884.719830500864
weights: uniform p: 2 Score: 23708.075959687332
weights: distance p: 1 Score: 11366.170427195984

NEW BEST SCORE
weights: distance p: 2 Best Score: 24033.295991979932




Starting New Run for RadiusNeighborsClassifier


Previous Best Score: 24033.295991979932
weights: uniform p: 1 Score: 10884.719830500864
weights: uniform p: 2 Score: 23708.075959687332
weights: distance p: 1 Score: 11366.170427195984
weights: distance p: 2 Score: 24033.295991979932
Real output model: RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
["R_Women's Strawweight_rank", "R_Women's Flyweight_rank", 'R_draw', "B_Women's Strawweight_rank", 'B_Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
5

(3513, 20)

(3513,)

(3513, 2)

(250, 20)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  1.000000  0.000000       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  1.000000  0.000000       1
249      115     -143  0.734477  0.265523       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 234
          Number of winning bets: 129
          Number of losing bets: 105
          Number of underdog bets: 125
          Number of underdog wins: 55
          Number of underdog losses: 70
          Number of Favorite bets: 107
          Number of favorite wins: 74
          Number of favorite losses: 33
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: 1634.7206234077123
          Profit per bet: 6.985985570118428
          Profit per match: 6.538882493630849


HI
HI
HI
HI
HI
0 24784.877129618155
1 25458.81890029034
2 24826.164728858275
3 24391.939975117388
4 23908.36675061012
5 24033.295991979932
6 23591.63941006142
7 23593.906872056505
8 23855.861631708627
9 23508.841696178664
10 23732.083557516504
11 23046.95982868087
12 22592.060387568912
13 22198.582846676545
14 22352.880528873204
15 22872.91216038265
16 22752.53872199308
17 22354.298739068967
18 22128.525897875075
19 22688.55006899418
20 23159.962435250665
21 23506.675600916024
22 23078.662358007707
23 23164.312911158257
24 22707.339018419672
25 23629.07634567038
26 23325.36572295976
27 22651.802917042143
28 22380.36367197276
29 22151.211075232903
30 21641.025702979925
31 21322.144584098805
32 21739.235681407292
33 21933.54751864184
34 21992.643139048785
35 22252.575620360578
36 21642.169605322986
37 21553.836271989654
38 21720.809916793485
39 21682.156070639634
40 20789.214894169054
41 21638.500608454768
42 21482.868424546723
43 21305.720413445888
44 20975.068239532848
45 19999.51268397729
46 20416.330865795473
47 19625.749470446637
48 19327.441112138276
49 19586.97102666819
50 18804.0619357591
51 18999.061935759095
52 18511.497833194993
53 18467.65058418241
54 18520.887143322198
55 18411.841436000625
56 18321.063658222847
57 17662.53563181518
58 17942.97898156887
59 18552.198930417977
60 18712.438451376063
61 19080.533689471296
62 19602.076899347845
63 20889.18381758684
64 20372.19841083041
65 20436.875830185247
66 20941.875830185247
67 20480.20916351858
68 20415.20916351858
69 21500.726404897887
70 21265.86626503775
71 20893.599758195272
72 21321.8577232518
73 21180.87962106202
74 21120.87962106202
75 21060.14164427927
76 21119.953674354456
77 20390.925488799552
78 20415.925488799552
79 20437.800488799552
80 20677.800488799552
81 20112.800488799552
82 19245.833275684796
83 19598.188647585623
84 19758.188647585626
85 19263.188647585626
86 18533.188647585626
87 18407.101691063886
88 18807.101691063886
89 19007.101691063886
90 18977.81597677817
91 18196.906885869077
92 18705.163766603022
93 18200.163766603022
94 17625.163766603022
95 17642.144898678496
96 18023.097279630878
97 17908.097279630878
98 17786.0099009901
99 18036.0099009901
100 16847.0
101 16845.0
102 16855.0
103 16745.0
104 16865.0
105 15865.0
106 15965.0
107 16265.0
108 16365.0
109 15942.0
110 14902.0
111 14891.0
112 14602.0
113 14557.0
114 15057.0
115 15377.0
116 14849.0
117 15149.0
118 14720.0
119 14565.0
120 13840.0
121 13715.0
122 13580.0
123 13880.0
124 13590.0
125 12630.0
126 12420.0
127 12200.0
128 12372.0
129 12112.0
130 12622.0
131 12572.0
132 12413.0
133 12380.0
134 12580.0
135 11380.0
136 11344.0
137 10242.0
138 10247.0
139 10107.0
140 10727.0
141 10447.0
142 10747.0
143 10399.0
144 10499.0
145 10314.0
146 10314.0
147 10224.0
148 10189.0
149 10389.0
150 10389.0
151 10689.0
152 10564.0
153 10764.0
154 11064.0
155 9949.0
156 9949.0
157 9712.0
158 9812.0
159 9812.0
160 9972.0
161 10172.0
162 9747.0
163 9747.0
164 9847.0
165 10587.0
166 10207.0
167 10340.0
168 10372.0
169 10572.0
170 10342.0
171 10742.0
172 10842.0
173 10942.0
174 11242.0
175 10817.0
176 10917.0
177 10763.0
178 10685.0
179 10685.0
180 11125.0
181 11225.0
182 10940.0
183 10940.0
184 11040.0
185 10460.0
186 10460.0
187 10660.0
188 10860.0
189 10860.0
190 10710.0
191 10910.0
192 10910.0
193 10460.0
194 10560.0
195 10480.0
196 10480.0
197 10480.0
198 10480.0
199 10480.0
200 9780.0
201 9780.0
202 9880.0
203 9625.0
204 9430.0
205 8575.0
206 8575.0
207 8675.0
208 8775.0
209 8775.0
210 8825.0
211 8925.0
212 8925.0
213 9025.0
214 9225.0
215 8650.0
216 8650.0
217 8650.0
218 8650.0
219 8650.0
220 7620.0
221 7620.0
222 7720.0
223 7720.0
224 7465.0
225 7740.0
226 7740.0
227 8040.0
228 8040.0
229 8140.0
230 8080.0
231 8080.0
232 8080.0
233 8080.0
234 8180.0
235 7575.0
236 7675.0
237 7585.0
238 7585.0
239 7585.0
240 7205.0
241 7305.0
242 7015.0
243 7115.0
244 7115.0
245 6190.0
246 5790.0
247 5890.0
248 5742.0
249 5842.0

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
["R_Women's Strawweight_rank", "R_Women's Flyweight_rank", 'R_draw', "B_Women's Strawweight_rank", 'B_Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 20)

(3513,)

(3513, 2)

(250, 20)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  1.000000  0.000000       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  1.000000  0.000000       1
249      115     -143  0.734477  0.265523       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 242
          Number of winning bets: 131
          Number of losing bets: 111
          Number of underdog bets: 128
          Number of underdog wins: 55
          Number of underdog losses: 73
          Number of Favorite bets: 111
          Number of favorite wins: 76
          Number of favorite losses: 35
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1087.2798813946579
          Profit per bet: 4.492892071878751
          Profit per match: 4.349119525578631


HI
HI
HI
HI
HI
The original score is 25458.81890029034
Score:  25176.675900801412
NEW BEST FEATURE SET
["R_Women's Strawweight_rank", 'R_draw', "B_Women's Strawweight_rank", 'B_Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
26044.36833643877
Score:  25719.025016205836
Score:  25308.81890029034
Score:  25770.353994709854
Score:  25724.068311948307
Score:  24292.481544510963
Score:  24853.17221646768
Score:  23197.4956193223
Score:  18067.87715954154
Score:  16429.82082546493
Score:  24827.82157005599
Score:  22622.70573658625
Score:  21619.57438997031
Score:  20929.862046176404
Score:  18640.08868594371
Score:  24073.2331608673
Score:  18814.304747004386
Score:  8786.103169564774
Score:  13627.635958204231
The original score is 26044.36833643877
Score:  25532.225336949843
NEW BEST FEATURE SET
["R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
26270.02899780881
Score:  25894.36833643877
NEW BEST FEATURE SET
["R_Women's Strawweight_rank", 'R_draw', "B_Women's Strawweight_rank", 'R_Light Heavyweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
26355.90343085828
Score:  26309.617748096738
Score:  25512.071609917417
Score:  25582.199913485674
Score:  23332.32167287029
Score:  20366.33861934163
Score:  17054.884443144892
Score:  24068.096414887357
Score:  22618.557095878958
Score:  22305.123826118746
Score:  21280.205060235876
Score:  19072.275463245605
Score:  24658.78259701573
Score:  19623.96654472932
Score:  8553.806438272382
Score:  13820.531643476155
The original score is 26355.90343085828
Score:  25485.543619051423
NEW BEST FEATURE SET
["R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'R_Light Heavyweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
26581.56409222832
Score:  26205.90343085828
NEW BEST FEATURE SET
["R_Women's Strawweight_rank", 'R_draw', "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
27597.79008115963
Score:  26167.335712848544
Score:  25893.735007905183
Score:  23714.52159896866
Score:  19612.78031242846
Score:  19677.454625916274
Score:  23624.302748365943
Score:  22724.10659432398
Score:  22722.27520674719
Score:  22469.584209576657
Score:  21804.036649763126
Score:  24595.83493281454
Score:  20242.39923135512
Score:  7913.13280514946
Score:  14026.807485526137
The original score is 27597.79008115963
Score:  26665.70187429104
NEW BEST FEATURE SET
["R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
28214.17913759139
Score:  27447.790081159626
Score:  27344.622232176105
Score:  27272.900973094547
Score:  25842.38892633404
Score:  20029.679731763157
Score:  21513.38599033659
Score:  24592.052938112927
Score:  22052.70981625408
Score:  23452.336363321265
Score:  21888.849161580467
Score:  22393.348301286922
Score:  24777.310972221414
Score:  21789.129607482242
Score:  10249.74757773324
Score:  15737.569579065854
The original score is 28214.17913759139
Score:  27182.090930722807
Score:  28064.17913759139
Score:  27822.549750146332
Score:  27889.29002952631
Score:  26156.09984471103
Score:  20770.32443995057
Score:  21454.503297012736
Score:  25345.387692809585
Score:  22645.405178992154
Score:  23670.639295351117
Score:  21623.463091655016
Score:  23009.737357718688
Score:  25393.700028653177
Score:  22565.160232018843
Score:  9472.09907890647
Score:  14933.051405474445
The hyperparameters are different
OLD:
RadiusNeighborsClassifier(outlier_label='most_frequent')
NEW:
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
The features are different
OLD:
["R_Women's Strawweight_rank", "R_Women's Flyweight_rank", 'R_draw', "B_Women's Strawweight_rank", 'B_Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
NEW:
["R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
The EV is different
OLD:
5
NEW:
1

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
["R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 16)

(3513,)

(3513, 2)

(250, 16)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 239
          Number of winning bets: 129
          Number of losing bets: 110
          Number of underdog bets: 127
          Number of underdog wins: 54
          Number of underdog losses: 73
          Number of Favorite bets: 109
          Number of favorite wins: 75
          Number of favorite losses: 34
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 947.8968795830688
          Profit per bet: 3.966095730473091
          Profit per match: 3.791587518332275


HI
HI
HI
HI
HI
Current best score is: 28214.17913759139
Feature: R_win_by_Decision_Majority Score: 28937.46549245758
The best feature was R_win_by_Decision_Majority.  It scored 28937.46549245758
Current best score is: 28937.46549245758
Feature: R_Bantamweight_rank Score: 29071.257674384324
The best feature was R_Bantamweight_rank.  It scored 29071.257674384324
Current best score is: 29071.257674384324
NO IMPROVEMENT
FINAL BEST SCORE: 29071.257674384324

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
['R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 18)

(3513,)

(3513, 2)

(250, 18)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 240
          Number of winning bets: 130
          Number of losing bets: 110
          Number of underdog bets: 129
          Number of underdog wins: 55
          Number of underdog losses: 74
          Number of Favorite bets: 108
          Number of favorite wins: 75
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1128.5066356806296
          Profit per bet: 4.7021109820026235
          Profit per match: 4.514026542722519


HI
HI
HI
HI
HI


Starting New Run for RadiusNeighborsClassifier


Previous Best Score: 29071.257674384324
weights: uniform p: 1 Score: 10092.000779501157
weights: uniform p: 2 Score: 26053.76202217728
weights: distance p: 1 Score: 10737.826335943946
weights: distance p: 2 Score: 29071.257674384324
Real output model: RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
['R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 18)

(3513,)

(3513, 2)

(250, 18)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 240
          Number of winning bets: 130
          Number of losing bets: 110
          Number of underdog bets: 129
          Number of underdog wins: 55
          Number of underdog losses: 74
          Number of Favorite bets: 108
          Number of favorite wins: 75
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1128.5066356806296
          Profit per bet: 4.7021109820026235
          Profit per match: 4.514026542722519


HI
HI
HI
HI
HI
0 29040.557625321482
1 29071.257674384324
2 28298.536996645475
3 27746.9721200806
4 27466.0459763412
5 27583.072032046497
6 27230.728457935656
7 26620.34136503481
8 25846.864260189446
9 25653.5653195436
10 26202.014517404565
11 25680.203801347106
12 25683.641470133178
13 25871.830595907475
14 26838.26819554037
15 27543.31922890125
16 26355.142180997835
17 26476.214894509707
18 25209.98322478802
19 24962.559730850764
20 24976.955927002844
21 24788.669092668206
22 24649.621367001262
23 24369.93440472606
24 23768.133672160635
25 24226.794076334416
26 23805.705831246174
27 22980.65578449921
28 22614.635174848467
29 22644.10011998702
30 22428.023167966254
31 21739.748109691198
32 21722.54572873882
33 21971.341958773548
34 22148.77091251383
35 22208.70339382562
36 22387.964045454697
37 22246.04096853162
38 22316.065191424557
39 22206.502254361625
40 21658.32298265294
41 22212.608696938652
42 22085.30984636394
43 21358.161835263105
44 21605.987922219625
45 20866.466849422693
46 21793.739576695425
47 21680.134925532635
48 21337.735658133366
49 21222.265572663277
50 21364.35648175418
51 21384.356481754185
52 20996.79237919008
53 20182.945130177497
54 19754.181689317284
55 19189.226891086622
56 19232.0046688644
57 18298.47664245673
58 17930.919992210424
59 18469.78699988306
60 17999.9067603621
61 18248.6080590634
62 19073.422873878215
63 19678.02979211721
64 19351.04438536078
65 19918.78632084465
66 20652.99684716044
67 20847.996847160437
68 20417.996847160437
69 22348.275993301653
70 22833.485783511438
71 22396.21927666897
72 22624.477241725494
73 22213.49184026564
74 22263.49184026564
75 22177.75386348289
76 21942.56589355808
77 20825.46078492625
78 21225.46078492625
79 20730.46078492625
80 20725.46078492625
81 19960.46078492625
82 19093.493571811494
83 18830.84894371232
84 19354.182277045657
85 18819.182277045657
86 18129.182277045657
87 17413.095320523917
88 17398.095320523917
89 17698.095320523917
90 17528.809606238203
91 16948.809606238203
92 16787.066486972148
93 16407.066486972148
94 16507.066486972148
95 16424.04761904762
96 16605.0
97 16200.0
98 16075.0
99 16425.0
100 15695.0
101 15593.0
102 15223.0
103 15113.0
104 14928.0
105 13563.0
106 13593.0
107 13693.0
108 14113.0
109 14113.0
110 14118.0
111 13609.0
112 12880.0
113 12565.0
114 12965.0
115 13200.0
116 12968.0
117 13168.0
118 12559.0
119 12204.0
120 11949.0
121 11674.0
122 11874.0
123 12174.0
124 12049.0
125 11424.0
126 11214.0
127 11414.0
128 11281.0
129 11121.0
130 11271.0
131 11271.0
132 11307.0
133 11274.0
134 11374.0
135 10644.0
136 10844.0
137 10267.0
138 10272.0
139 10132.0
140 10302.0
141 10022.0
142 10122.0
143 10079.0
144 10079.0
145 9704.0
146 9484.0
147 9584.0
148 9549.0
149 9749.0
150 9949.0
151 9859.0
152 9834.0
153 9934.0
154 10034.0
155 8819.0
156 8819.0
157 8482.0
158 8582.0
159 8782.0
160 8742.0
161 8942.0
162 8617.0
163 8617.0
164 8617.0
165 8987.0
166 8987.0
167 9120.0
168 9152.0
169 9252.0
170 9022.0
171 9422.0
172 9622.0
173 9722.0
174 9722.0
175 8742.0
176 8842.0
177 8788.0
178 8810.0
179 8430.0
180 8950.0
181 9050.0
182 8765.0
183 8610.0
184 8810.0
185 8045.0
186 8045.0
187 8245.0
188 7895.0
189 7895.0
190 7945.0
191 8045.0
192 8045.0
193 8045.0
194 8045.0
195 8260.0
196 8360.0
197 8460.0
198 8460.0
199 8460.0
200 8160.0
201 8160.0
202 8160.0
203 7905.0
204 7710.0
205 7060.0
206 7060.0
207 7160.0
208 7260.0
209 7260.0
210 7520.0
211 7620.0
212 7620.0
213 7620.0
214 7820.0
215 7145.0
216 7145.0
217 7145.0
218 7145.0
219 7145.0
220 5915.0
221 5915.0
222 5915.0
223 5915.0
224 5915.0
225 6290.0
226 6290.0
227 6490.0
228 6490.0
229 6590.0
230 6630.0
231 6630.0
232 6730.0
233 6730.0
234 6830.0
235 6225.0
236 6225.0
237 6135.0
238 6135.0
239 6135.0
240 5755.0
241 5955.0
242 5955.0
243 6055.0
244 6055.0
245 5030.0
246 4215.0
247 4315.0
248 4167.0
249 4267.0

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
['R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 18)

(3513,)

(3513, 2)

(250, 18)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 240
          Number of winning bets: 130
          Number of losing bets: 110
          Number of underdog bets: 129
          Number of underdog wins: 55
          Number of underdog losses: 74
          Number of Favorite bets: 108
          Number of favorite wins: 75
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1128.5066356806296
          Profit per bet: 4.7021109820026235
          Profit per match: 4.514026542722519


HI
HI
HI
HI
HI
The original score is 29071.257674384324
Score:  28937.46549245758
Score:  28111.794848929894
Score:  27701.20650455277
Score:  28921.257674384324
Score:  27360.06041199621
NEW BEST FEATURE SET
['R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
29446.844756795424
Score:  23182.507029705313
Score:  21781.741017193224
Score:  20597.82048310601
Score:  26567.332690290907
Score:  21650.976813447734
Score:  23941.722142932165
Score:  19437.46672417745
Score:  22835.55127186008
Score:  28511.211076061863
Score:  23850.235255805586
Score:  10165.606518829747
Score:  12662.531721153775
The original score is 29446.844756795424
Score:  29163.052574868685
Score:  27936.905740864815
Score:  28076.793586963875
Score:  29296.844756795424
Score:  27724.241156307777
Score:  24642.55449028389
Score:  20457.8915950123
Score:  21789.46719848406
Score:  26640.350602741535
Score:  21594.491266891237
Score:  24377.44908548313
Score:  17929.41473747784
Score:  20847.873259267388
Score:  28886.798158472964
Score:  23467.92584540921
Score:  11454.88025647631
Score:  11540.023856454587
The features are different
OLD:
['R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_Pound-for-Pound_rank', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
NEW:
['R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
['R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 17)

(3513,)

(3513, 2)

(250, 17)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 240
          Number of winning bets: 131
          Number of losing bets: 109
          Number of underdog bets: 128
          Number of underdog wins: 55
          Number of underdog losses: 73
          Number of Favorite bets: 109
          Number of favorite wins: 76
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1278.5066356806296
          Profit per bet: 5.3271109820026235
          Profit per match: 5.114026542722518


HI
HI
HI
HI
HI
Current best score is: 29446.844756795424
Feature: B_Welterweight_rank Score: 29632.53965308132
The best feature was B_Welterweight_rank.  It scored 29632.53965308132
Current best score is: 29632.53965308132
NO IMPROVEMENT
FINAL BEST SCORE: 29632.53965308132

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
['B_Welterweight_rank', 'R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 18)

(3513,)

(3513, 2)

(250, 18)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 240
          Number of winning bets: 130
          Number of losing bets: 110
          Number of underdog bets: 129
          Number of underdog wins: 55
          Number of underdog losses: 74
          Number of Favorite bets: 108
          Number of favorite wins: 75
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1128.5066356806296
          Profit per bet: 4.7021109820026235
          Profit per match: 4.514026542722519


HI
HI
HI
HI
HI


Starting New Run for RadiusNeighborsClassifier


Previous Best Score: 29632.53965308132
weights: uniform p: 1 Score: 9981.641387497511
weights: uniform p: 2 Score: 26368.470501909476
weights: distance p: 1 Score: 10640.079556552913
weights: distance p: 2 Score: 29632.53965308132
Real output model: RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
['B_Welterweight_rank', 'R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 18)

(3513,)

(3513, 2)

(250, 18)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 240
          Number of winning bets: 130
          Number of losing bets: 110
          Number of underdog bets: 129
          Number of underdog wins: 55
          Number of underdog losses: 74
          Number of Favorite bets: 108
          Number of favorite wins: 75
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1128.5066356806296
          Profit per bet: 4.7021109820026235
          Profit per match: 4.514026542722519


HI
HI
HI
HI
HI
0 29378.800012703025
1 29632.53965308132
2 28959.818975342474
3 28106.4425045747
4 27825.516360835292
5 27641.77318577137
6 27289.42961166053
7 26779.04251875968
8 25880.56541391432
9 25687.26647326847
10 26195.261125674886
11 25818.688504855523
12 25944.66585618128
13 26232.854981955577
14 27032.625914921806
15 27267.382830635623
16 26194.357297883726
17 26416.339102304686
18 25280.107432582998
19 24927.683938645747
20 24862.080134797823
21 24588.793300463178
22 24189.74557479624
23 23627.095649558083
24 22973.257879955625
25 23486.463738674858
26 23174.83003904116
27 22469.7799922942
28 22010.20012117829
29 22028.440141007413
30 21532.512442717998
31 20913.46815367371
32 21026.26577272133
33 21540.106952518086
34 21584.20257292503
35 21644.135054236824
36 21823.3957058659
37 21681.472628942818
38 21781.258756597665
39 22096.69581953473
40 21643.75464306414
41 22098.04035734986
42 21970.741506775143
43 21623.59349567431
44 21914.897843500396
45 20975.376770703464
46 21902.649497976192
47 22014.0448468134
48 21499.026531795083
49 21483.556446324998
50 21816.556446324998
51 21691.556446324998
52 21183.992343760892
53 20465.14509474831
54 20051.381653888093
55 19361.42685565743
56 19504.204633435213
57 18295.67660702754
58 18378.119956781233
59 18858.163435042105
60 18488.283195521148
61 18226.37843361638
62 18771.1932484312
63 19375.800166670193
64 19048.81475991376
65 19816.556695397634
66 20330.767221713424
67 20734.858130804332
68 20824.858130804332
69 22555.137276945545
70 22640.347067155337
71 21993.08056031286
72 22321.338525369385
73 22360.35312390954
74 22410.35312390954
75 22124.61514712678
76 21889.42717720197
77 20772.322068570145
78 21172.322068570145
79 20677.322068570145
80 20672.322068570145
81 20147.322068570145
82 19280.35485545539
83 18917.710227356212
84 19424.376894022884
85 18689.376894022884
86 17999.376894022884
87 17496.333415762012
88 17581.333415762012
89 17981.333415762012
90 17812.0477014763
91 17132.0477014763
92 16970.304582210243
93 16590.304582210243
94 16690.304582210243
95 16707.285714285714
96 16893.0
97 16488.0
98 16263.0
99 16613.0
100 15983.0
101 15881.0
102 15511.0
103 15301.0
104 15116.0
105 13756.0
106 13686.0
107 13786.0
108 14206.0
109 14406.0
110 14311.0
111 13902.0
112 12873.0
113 12558.0
114 12958.0
115 13293.0
116 13061.0
117 13361.0
118 12752.0
119 12397.0
120 12142.0
121 11867.0
122 12067.0
123 12467.0
124 12342.0
125 11907.0
126 11697.0
127 11897.0
128 11764.0
129 11604.0
130 11459.0
131 11459.0
132 11495.0
133 11462.0
134 11562.0
135 10932.0
136 11132.0
137 10555.0
138 10560.0
139 10420.0
140 10450.0
141 10170.0
142 10270.0
143 10227.0
144 10227.0
145 9852.0
146 9632.0
147 9732.0
148 9362.0
149 9562.0
150 9512.0
151 9422.0
152 9397.0
153 9497.0
154 9597.0
155 8382.0
156 8582.0
157 8345.0
158 8545.0
159 8745.0
160 8705.0
161 8905.0
162 8580.0
163 8580.0
164 8580.0
165 9285.0
166 9285.0
167 9418.0
168 9050.0
169 9150.0
170 8820.0
171 9120.0
172 9320.0
173 9420.0
174 9420.0
175 8440.0
176 8440.0
177 8386.0
178 8230.0
179 7850.0
180 8370.0
181 8470.0
182 8185.0
183 8030.0
184 8230.0
185 7650.0
186 7650.0
187 7850.0
188 7790.0
189 7790.0
190 7840.0
191 8040.0
192 8040.0
193 8040.0
194 8040.0
195 8155.0
196 8255.0
197 8355.0
198 8355.0
199 8355.0
200 8055.0
201 8055.0
202 8055.0
203 7800.0
204 7605.0
205 6955.0
206 6955.0
207 7055.0
208 7155.0
209 7155.0
210 7315.0
211 7415.0
212 7415.0
213 7415.0
214 7615.0
215 7040.0
216 7040.0
217 7040.0
218 7040.0
219 7040.0
220 5810.0
221 5810.0
222 5810.0
223 5810.0
224 5810.0
225 6185.0
226 6185.0
227 6385.0
228 6385.0
229 5945.0
230 5985.0
231 5985.0
232 5795.0
233 5795.0
234 5895.0
235 5290.0
236 5290.0
237 5200.0
238 5200.0
239 5200.0
240 4820.0
241 5020.0
242 5020.0
243 5220.0
244 5220.0
245 4440.0
246 3625.0
247 3725.0
248 3577.0
249 3677.0

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
['B_Welterweight_rank', 'R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 18)

(3513,)

(3513, 2)

(250, 18)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 240
          Number of winning bets: 130
          Number of losing bets: 110
          Number of underdog bets: 129
          Number of underdog wins: 55
          Number of underdog losses: 74
          Number of Favorite bets: 108
          Number of favorite wins: 75
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1128.5066356806296
          Profit per bet: 4.7021109820026235
          Profit per match: 4.514026542722519


HI
HI
HI
HI
HI
The original score is 29632.53965308132
Score:  29446.844756795424
Score:  29279.781953913196
Score:  28756.15375070382
Score:  28262.488483249774
Score:  29482.539653081316
Score:  28481.40153971511
Score:  25745.44180062956
Score:  19716.733060748214
Score:  21365.400937591417
Score:  27006.04549902743
Score:  20414.834512512793
Score:  24903.620172245213
Score:  18300.370834821737
Score:  20338.5839722601
Score:  29072.493054758856
Score:  23474.29653933066
Score:  11424.37540636028
Score:  10456.020795552275

model_7
RadiusNeighborsClassifier(outlier_label='most_frequent', weights='distance')
['B_Welterweight_rank', 'R_Bantamweight_rank', 'R_win_by_Decision_Majority', "R_Women's Strawweight_rank", "B_Women's Strawweight_rank", 'B_win_by_TKO_Doctor_Stoppage', 'R_avg_SUB_ATT', 'R_win_by_Decision_Split', 'R_wins', 'empty_arena', 'sub_dif', 'R_Flyweight_rank', 'height_dif', 'B_total_title_bouts', 'B_Bantamweight_rank', 'R_longest_win_streak', 'R_avg_TD_landed', 'B_avg_SIG_STR_landed']
1

(3513, 18)

(3513,)

(3513, 2)

(250, 18)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 240
          Number of winning bets: 130
          Number of losing bets: 110
          Number of underdog bets: 129
          Number of underdog wins: 55
          Number of underdog losses: 74
          Number of Favorite bets: 108
          Number of favorite wins: 75
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1128.5066356806296
          Profit per bet: 4.7021109820026235
          Profit per match: 4.514026542722519


HI
HI
HI
HI
HI

(3513, 18)

(3513,)

(3513, 2)

(250, 18)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  1.000000  0.000000       1
1       -320      250  1.000000  0.000000       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.616446  0.383554       1
4       -240      195  0.253357  0.746643       0
..       ...      ...       ...       ...     ...
245      175     -230  0.507723  0.492277       0
246      250     -305  1.000000  0.000000       0
247     -134      105  1.000000  0.000000       1
248     -105     -117  0.000000  1.000000       1
249      115     -143  0.661841  0.338159       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 240
          Number of winning bets: 130
          Number of losing bets: 110
          Number of underdog bets: 129
          Number of underdog wins: 55
          Number of underdog losses: 74
          Number of Favorite bets: 108
          Number of favorite wins: 75
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: 1128.5066356806296
          Profit per bet: 4.7021109820026235
          Profit per match: 4.514026542722519


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 8


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_8
KNeighborsClassifier()
['R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', "B_Women's Flyweight_rank", 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_Middleweight_rank', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
0
Current best score is: 19123.493628503235
Feature: B_current_win_streak Score: 19416.326053483823
Feature: B_win_by_Decision_Majority Score: 19665.361185174108
The best feature was B_win_by_Decision_Majority.  It scored 19665.361185174108
Current best score is: 19665.361185174108
Feature: B_current_win_streak Score: 21040.970751970268
The best feature was B_current_win_streak.  It scored 21040.970751970268
Current best score is: 21040.970751970268
Feature: B_win_by_TKO_Doctor_Stoppage Score: 23073.93410154793
The best feature was B_win_by_TKO_Doctor_Stoppage.  It scored 23073.93410154793
Current best score is: 23073.93410154793
NO IMPROVEMENT
FINAL BEST SCORE: 23073.93410154793

model_8
KNeighborsClassifier()
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', "B_Women's Flyweight_rank", 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_Middleweight_rank', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
0

(3712, 29)

(3712,)

(3712, 2)

(250, 29)

(250,)

(250, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.8      0.2       1
1       -320      250      0.4      0.6       1
2        130     -155      0.8      0.2       0
3       -155      135      0.4      0.6       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
245      175     -230      1.0      0.0       0
246      250     -305      0.8      0.2       0
247     -134      105      0.8      0.2       1
248     -105     -117      0.6      0.4       1
249      115     -143      0.2      0.8       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 234
          Number of winning bets: 106
          Number of losing bets: 128
          Number of underdog bets: 147
          Number of underdog wins: 54
          Number of underdog losses: 93
          Number of Favorite bets: 84
          Number of favorite wins: 51
          Number of favorite losses: 33
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -699.5888679663103
          Profit per bet: -2.989696016950044
          Profit per match: -2.7983554718652415


HI
HI
HI
HI
HI


Starting New Run for KNeighborsClassifier


Previous Best Score: 23073.93410154793
weights: uniform n_neighbors: 1 Score: 11952.539894781316
weights: uniform n_neighbors: 2 Score: 16672.944187060217
weights: uniform n_neighbors: 3 Score: 13363.418405091876

NEW BEST SCORE
weights: uniform n_neighbors: 4 Best Score: 23983.544072115135


weights: uniform n_neighbors: 5 Score: 23073.93410154793
weights: uniform n_neighbors: 6 Score: 14798.546869204109
weights: uniform n_neighbors: 7 Score: 17831.467811897986
weights: uniform n_neighbors: 8 Score: 9270.938465489748
weights: uniform n_neighbors: 9 Score: 10612.71005048713
weights: uniform n_neighbors: 10 Score: 4736.300616979674
weights: distance n_neighbors: 1 Score: 11952.539894781316
weights: distance n_neighbors: 2 Score: 14095.220038527954
weights: distance n_neighbors: 3 Score: 12693.630536991464

NEW BEST SCORE
weights: distance n_neighbors: 4 Best Score: 24773.20967644701


weights: distance n_neighbors: 5 Score: 20609.544420272116
weights: distance n_neighbors: 6 Score: 13032.625098263194
weights: distance n_neighbors: 7 Score: 15084.432361558549
weights: distance n_neighbors: 8 Score: 10742.79883651266
weights: distance n_neighbors: 9 Score: 10791.044564546404
weights: distance n_neighbors: 10 Score: 5363.221177473981


Starting New Run for KNeighborsClassifier


Previous Best Score: 24773.20967644701
weights: uniform n_neighbors: 1 Score: 11952.539894781316
weights: uniform n_neighbors: 2 Score: 16672.944187060217
weights: uniform n_neighbors: 3 Score: 13363.418405091876
weights: uniform n_neighbors: 4 Score: 23983.544072115135
weights: uniform n_neighbors: 5 Score: 23073.93410154793
weights: uniform n_neighbors: 6 Score: 14798.546869204109
weights: uniform n_neighbors: 7 Score: 17831.467811897986
weights: uniform n_neighbors: 8 Score: 9270.938465489748
weights: uniform n_neighbors: 9 Score: 10612.71005048713
weights: uniform n_neighbors: 10 Score: 4736.300616979674
weights: distance n_neighbors: 1 Score: 11952.539894781316
weights: distance n_neighbors: 2 Score: 14095.220038527954
weights: distance n_neighbors: 3 Score: 12693.630536991464
weights: distance n_neighbors: 4 Score: 24773.20967644701
weights: distance n_neighbors: 5 Score: 20609.544420272116
weights: distance n_neighbors: 6 Score: 13032.625098263194
weights: distance n_neighbors: 7 Score: 15084.432361558549
weights: distance n_neighbors: 8 Score: 10742.79883651266
weights: distance n_neighbors: 9 Score: 10791.044564546404
weights: distance n_neighbors: 10 Score: 5363.221177473981
Real output model: KNeighborsClassifier(n_neighbors=4, weights='distance')

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', "B_Women's Flyweight_rank", 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_Middleweight_rank', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
0

(3712, 29)

(3712,)

(3712, 2)

(250, 29)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.748691  0.251309       1
1       -320      250  0.277952  0.722048       1
2        130     -155  0.769802  0.230198       0
3       -155      135  0.380033  0.619967       1
4       -240      195  0.778200  0.221800       0
..       ...      ...       ...       ...     ...
245      175     -230  1.000000  0.000000       0
246      250     -305  0.811614  0.188386       0
247     -134      105  0.715297  0.284703       1
248     -105     -117  0.556292  0.443708       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 239
          Number of winning bets: 115
          Number of losing bets: 124
          Number of underdog bets: 137
          Number of underdog wins: 50
          Number of underdog losses: 87
          Number of Favorite bets: 99
          Number of favorite wins: 64
          Number of favorite losses: 35
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -742.7765831948304
          Profit per bet: -3.1078518125306713
          Profit per match: -2.9711063327793217


HI
HI
HI
HI
HI
0 24773.20967644701
1 24815.36923877819
2 25005.2634476646
3 25500.176954004026
4 24775.059076570607
5 23732.277318137363
6 23312.64953395386
7 22621.74006821806
8 21519.081666756694
9 21215.879946802477
10 20757.462436387843
11 20572.782163029
12 20675.29397183878
13 19581.248146630965
14 19662.153386531387
15 19597.587771184066
16 18578.034714103538
17 19307.32782909085
18 19717.842633700417
19 19090.956658415067
20 19399.310982887055
21 19378.192498643755
22 19177.4768020335
23 18446.69500115043
24 20284.16925633789
25 19550.054365581705
26 20025.344075871413
27 19629.742137830974
28 19735.10223281436
29 19507.92497861028
30 19219.001113414248
31 18705.967014064357
32 19392.60052941226
33 18977.114169313012
34 18015.361573044287
35 18049.890010311665
36 17952.58198793383
37 17106.522916098897
38 16715.231879517803
39 16586.816163799645
40 16562.9596800856
41 16783.267808010492
42 15848.69963523906
43 16901.079461874207
44 16609.745198883196
45 16920.398399477926
46 15747.695328690359
47 15651.055544477265
48 15731.33692975865
49 15748.666034762173
50 15955.42793952408
51 15758.09027718642
52 15416.688160784306
53 15323.144358095764
54 14521.104916056318
55 14280.597441548844
56 14755.85548415983
57 15618.17853373769
58 15129.950517213434
59 15498.362281919313
60 15041.439204996237
61 14452.196780753813
62 14277.830899721266
63 13967.437817960259
64 14052.43781796026
65 13205.832595226004
66 13547.043121541794
67 14465.376454875128
68 14333.138359637032
69 14860.310773430137
70 14587.310773430137
71 13771.388787614535
72 12930.160627285653
73 12912.160627285653
74 12662.160627285653
75 11372.909659900355
76 10557.909659900355
77 10293.0353204993
78 10066.0353204993
79 10301.0353204993
80 9597.0353204993
81 9242.0353204993
82 9222.0353204993
83 8812.0353204993
84 9085.368653832633
85 8895.368653832633
86 9335.368653832635
87 8808.8469147022
88 9898.8469147022
89 10016.8469147022
90 9828.275486130771
91 9315.093667948953
92 9920.093667948953
93 10320.093667948953
94 11184.093667948953
95 10694.754045307443
96 9983.087378640776
97 9230.087378640776
98 9613.0
99 9508.0
100 9248.0
101 8605.0
102 8600.0
103 8585.0
104 8490.0
105 8010.0
106 8025.0
107 8005.0
108 8155.0
109 8000.0
110 7575.0
111 7715.0
112 6670.0
113 6660.0
114 6720.0
115 7120.0
116 6968.0
117 7093.0
118 7366.0
119 7881.0
120 7436.0
121 7166.0
122 6351.0
123 5821.0
124 5533.0
125 5838.0
126 5908.0
127 6008.0
128 6508.0
129 6748.0
130 6343.0
131 5723.0
132 6023.0
133 6028.0
134 5894.0
135 4844.0
136 5044.0
137 5124.0
138 4974.0
139 5159.0
140 4214.0
141 3994.0
142 4189.0
143 4494.0
144 3852.0
145 3592.0
146 3357.0
147 3657.0
148 3857.0
149 4142.0
150 4442.0
151 3847.0
152 4247.0
153 4587.0
154 4787.0
155 4612.0
156 3847.0
157 3892.0
158 3382.0
159 3327.0
160 3147.0
161 3347.0
162 3427.0
163 3012.0
164 3112.0
165 2567.0
166 2427.0
167 1965.0
168 1820.0
169 1880.0
170 1100.0
171 875.0
172 480.0
173 580.0
174 780.0
175 390.0
176 590.0
177 813.0
178 636.0
179 638.0
180 418.0
181 205.0
182 145.0
183 245.0
184 385.0
185 -150.0
186 250.0
187 350.0
188 -340.0
189 -535.0
190 -1095.0
191 -1385.0
192 -1825.0
193 -1625.0
194 -1705.0
195 -1305.0
196 -1105.0
197 -1005.0
198 -905.0
199 -1230.0
200 -830.0
201 -1115.0
202 -1015.0
203 -1005.0
204 -1245.0
205 -1560.0
206 -1740.0
207 -1440.0
208 -1340.0
209 -1775.0
210 -1880.0
211 -1780.0
212 -1930.0
213 -1830.0
214 -1830.0
215 -2285.0
216 -2285.0
217 -2185.0
218 -2185.0
219 -2085.0
220 -2460.0
221 -3310.0
222 -3010.0
223 -3760.0
224 -3660.0
225 -3660.0
226 -3560.0
227 -3260.0
228 -3605.0
229 -3405.0
230 -3105.0
231 -3005.0
232 -3005.0
233 -3005.0
234 -3005.0
235 -2505.0
236 -2505.0
237 -2750.0
238 -3005.0
239 -2905.0
240 -2945.0
241 -2845.0
242 -2745.0
243 -2645.0
244 -2645.0
245 -2345.0
246 -2145.0
247 -2510.0
248 -2410.0
249 -2310.0

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', "B_Women's Flyweight_rank", 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_Middleweight_rank', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 29)

(3712,)

(3712, 2)

(250, 29)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.748691  0.251309       1
1       -320      250  0.277952  0.722048       1
2        130     -155  0.769802  0.230198       0
3       -155      135  0.380033  0.619967       1
4       -240      195  0.778200  0.221800       0
..       ...      ...       ...       ...     ...
245      175     -230  1.000000  0.000000       0
246      250     -305  0.811614  0.188386       0
247     -134      105  0.715297  0.284703       1
248     -105     -117  0.556292  0.443708       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 229
          Number of winning bets: 110
          Number of losing bets: 119
          Number of underdog bets: 134
          Number of underdog wins: 49
          Number of underdog losses: 85
          Number of Favorite bets: 92
          Number of favorite wins: 60
          Number of favorite losses: 32
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -537.2289136477307
          Profit per bet: -2.3459777888547193
          Profit per match: -2.148915654590923


HI
HI
HI
HI
HI
The original score is 25500.176954004026
Score:  22465.78232001344
Score:  22180.398279401
Score:  23745.431444642854
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', "B_Women's Flyweight_rank", 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_Middleweight_rank', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
25592.484964399922
Score:  24508.676852004508
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'B_Heavyweight_rank', "B_Women's Flyweight_rank", 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_Middleweight_rank', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
26051.62157688529
Score:  24078.04531896347
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_Middleweight_rank', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
26334.605815275238
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', "B_Women's Flyweight_rank", 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_Middleweight_rank', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
26868.513536111932
Score:  24428.019927327758
Score:  25002.383435483043
Score:  24375.722464234073
Score:  26149.879431076934
Score:  24955.297601271028
Score:  22398.503113981526
Score:  25351.963244195445
Score:  24184.367500982145
Score:  24662.310344711204
Score:  3639.381804499769
Score:  18484.53588244163
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', "B_Women's Flyweight_rank", 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
27021.802684690556
Score:  24883.15102776419
Score:  24586.053868073148
Score:  24267.3173793373
Score:  19916.891412700425
Score:  -2122.4217759443222
Score:  11448.896628344364
Score:  23617.366004598174
The original score is 27021.802684690556
Score:  22938.457361283352
Score:  22502.084171983595
Score:  24181.80192468595
Score:  26456.030117607967
Score:  25297.603303998854
Score:  26884.345799629154
Score:  24029.955221018285
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
27425.4537938766
Score:  26608.856029826427
Score:  24886.302633674615
Score:  26837.320993743742
Score:  25558.838252811365
Score:  27023.86100022029
Score:  25602.18425371072
Score:  22486.130203512494
Score:  26204.523769675026
Score:  23598.040314104324
Score:  25361.914893872527
Score:  5229.992829231701
Score:  19069.20705505278
Score:  26481.605131124757
Score:  25846.3588440427
Score:  24879.562077637882
Score:  18576.024594508104
Score:  -4351.2236552749655
Score:  8765.987213164
Score:  22911.632143644292
The original score is 27425.4537938766
Score:  22750.507544922515
Score:  22998.952537440946
Score:  24875.73810856704
Score:  27066.164636942478
Score:  26151.85904428339
Score:  27253.06920194153
Score:  23809.291271552007
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
27597.28938884876
Score:  24982.619769936664
Score:  27041.657044277465
Score:  25857.114059333973
Score:  25442.308671566796
Score:  26220.46360922307
Score:  23311.427273536472
Score:  26823.535659708352
Score:  24209.013329973735
Score:  26074.21196389651
Score:  7284.414909538473
Score:  20516.554448425766
Score:  26449.15563383111
Score:  26249.17315544599
Score:  25227.918194409667
Score:  19069.185151776917
Score:  -4565.6991192956575
Score:  9298.513389779977
Score:  22917.43033879031
The original score is 27597.28938884876
Score:  21933.428461205203
Score:  21750.52295381875
Score:  25272.164082712883
Score:  24551.073961842638
Score:  26002.638967552113
Score:  27182.671469852437
Score:  25429.01931208992
Score:  26195.70644195196
Score:  26563.321767526948
Score:  25899.54105758072
Score:  25331.863689595037
Score:  25966.122026822708
Score:  23840.42629446739
Score:  26562.515524145005
Score:  25931.892531781545
Score:  25239.482971374888
Score:  7529.137008017596
Score:  19940.047336760144
Score:  26695.05584437819
Score:  26029.362789580227
Score:  26206.726423873697
Score:  21297.68651201351
Score:  -2584.9888476428164
Score:  7400.587650721927
Score:  22265.645052737542
The hyperparameters are different
OLD:
KNeighborsClassifier()
NEW:
KNeighborsClassifier(n_neighbors=4, weights='distance')
The features are different
OLD:
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', "B_Women's Flyweight_rank", 'R_Welterweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_Middleweight_rank', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
NEW:
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
The EV is different
OLD:
0
NEW:
3

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 26)

(3712,)

(3712, 2)

(250, 26)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.748691  0.251309       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  1.000000  0.000000       0
246      250     -305  0.811614  0.188386       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 229
          Number of winning bets: 112
          Number of losing bets: 117
          Number of underdog bets: 136
          Number of underdog wins: 51
          Number of underdog losses: 85
          Number of Favorite bets: 90
          Number of favorite wins: 60
          Number of favorite losses: 30
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -55.13507615847247
          Profit per bet: -0.24076452470948678
          Profit per match: -0.22054030463388988


HI
HI
HI
HI
HI
Current best score is: 27597.28938884876
Feature: B_Lightweight_rank Score: 28707.602787496908
The best feature was B_Lightweight_rank.  It scored 28707.602787496908
Current best score is: 28707.602787496908
Feature: R_win_by_Decision_Majority Score: 29568.51504322044
The best feature was R_win_by_Decision_Majority.  It scored 29568.51504322044
Current best score is: 29568.51504322044
NO IMPROVEMENT
FINAL BEST SCORE: 29568.51504322044

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 28)

(3712,)

(3712, 2)

(250, 28)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.748691  0.251309       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  1.000000  0.000000       0
246      250     -305  0.482047  0.517953       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 227
          Number of winning bets: 109
          Number of losing bets: 118
          Number of underdog bets: 137
          Number of underdog wins: 50
          Number of underdog losses: 87
          Number of Favorite bets: 87
          Number of favorite wins: 58
          Number of favorite losses: 29
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -406.75898348291213
          Profit per bet: -1.791889795078908
          Profit per match: -1.6270359339316485


HI
HI
HI
HI
HI


Starting New Run for KNeighborsClassifier


Previous Best Score: 29568.51504322044
weights: uniform n_neighbors: 1 Score: 8299.068063394578
weights: uniform n_neighbors: 2 Score: 20499.410604718658
weights: uniform n_neighbors: 3 Score: 15300.98646917459
weights: uniform n_neighbors: 4 Score: 28651.07747100884
weights: uniform n_neighbors: 5 Score: 23758.913039869847
weights: uniform n_neighbors: 6 Score: 17362.23182169556
weights: uniform n_neighbors: 7 Score: 16726.58813459626
weights: uniform n_neighbors: 8 Score: 9792.909368302526
weights: uniform n_neighbors: 9 Score: 10627.822623884465
weights: uniform n_neighbors: 10 Score: 3411.5705399040035
weights: distance n_neighbors: 1 Score: 8299.068063394578
weights: distance n_neighbors: 2 Score: 16012.85904820553
weights: distance n_neighbors: 3 Score: 14523.063255023908
weights: distance n_neighbors: 4 Score: 29568.51504322044
weights: distance n_neighbors: 5 Score: 23011.23496918448
weights: distance n_neighbors: 6 Score: 17789.12255986671
weights: distance n_neighbors: 7 Score: 15811.603384727172
weights: distance n_neighbors: 8 Score: 11396.141295125442
weights: distance n_neighbors: 9 Score: 11816.30444123848
weights: distance n_neighbors: 10 Score: 7649.701744825541
Real output model: KNeighborsClassifier(n_neighbors=4, weights='distance')

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 28)

(3712,)

(3712, 2)

(250, 28)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.748691  0.251309       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  1.000000  0.000000       0
246      250     -305  0.482047  0.517953       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 227
          Number of winning bets: 109
          Number of losing bets: 118
          Number of underdog bets: 137
          Number of underdog wins: 50
          Number of underdog losses: 87
          Number of Favorite bets: 87
          Number of favorite wins: 58
          Number of favorite losses: 29
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -406.75898348291213
          Profit per bet: -1.791889795078908
          Profit per match: -1.6270359339316485


HI
HI
HI
HI
HI
0 29464.2574694606
1 29404.092904342113
2 29181.768527376833
3 29568.51504322044
4 28685.228871539264
5 27308.23770673645
6 27183.09354190601
7 26285.177583464098
8 25872.79540835842
9 25396.244223990918
10 24683.154818625146
11 24507.310057580074
12 24249.064338479417
13 23776.88772605359
14 23668.230356577566
15 22223.078068301555
16 20931.479184967196
17 21381.818434928537
18 21545.313471729758
19 21069.754042494176
20 22501.582734843778
21 22462.30292004302
22 22031.788778150447
23 21279.78453362558
24 22566.461457535774
25 21620.0506030173
26 22337.2322051989
27 22126.910122381145
28 21722.64783737805
29 21694.347355593087
30 21767.92377794425
31 20485.03068917015
32 20509.82558017943
33 19765.1007337571
34 19689.939290262322
35 18709.68858166699
36 18217.331586522792
37 17387.36031877566
38 17485.055746584414
39 16513.75820254964
40 16602.75890853422
41 15712.828941221022
42 14391.975242381457
43 15193.884983546515
44 14275.797285584678
45 14383.049519995833
46 13729.255728334934
47 13007.37784888375
48 12581.607286113187
49 12411.064994220924
50 13225.155903311834
51 13497.81824097417
52 13156.654219810149
53 13506.08554268255
54 12403.760386357391
55 11706.859089456097
56 12175.156347753355
57 13062.479397331212
58 12475.160471716048
59 13152.395765833697
60 12906.395765833697
61 12641.915246353175
62 12174.277760382356
63 11781.38467862135
64 11945.475587712259
65 11018.354235945744
66 11527.564762261536
67 12747.564762261536
68 12627.326667023439
69 13552.430115299303
70 12982.430115299303
71 12466.5081294837
72 11930.279969154819
73 12580.279969154819
74 12300.279969154819
75 11019.72994151524
76 10431.72994151524
77 10076.855602114181
78 9569.855602114181
79 9904.855602114181
80 9810.855602114181
81 9570.855602114181
82 9063.888388999429
83 8463.888388999429
84 8720.555055666096
85 8980.555055666096
86 8920.555055666096
87 8424.03331653566
88 9464.03331653566
89 9539.03331653566
90 10059.747602249947
91 9255.656693159037
92 10205.656693159037
93 10705.656693159039
94 11669.656693159039
95 11345.317070517529
96 11282.126594327052
97 10112.126594327052
98 10110.039215686274
99 10612.0
100 10452.0
101 10049.0
102 10309.0
103 10424.0
104 10374.0
105 9724.0
106 9439.0
107 9254.0
108 9214.0
109 8794.0
110 7904.0
111 7869.0
112 7544.0
113 7154.0
114 7304.0
115 7804.0
116 7563.0
117 7393.0
118 7798.0
119 8398.0
120 7673.0
121 6988.0
122 6345.0
123 6165.0
124 5877.0
125 5907.0
126 6072.0
127 6472.0
128 6627.0
129 6527.0
130 6517.0
131 6277.0
132 5980.0
133 6380.0
134 6146.0
135 4971.0
136 5371.0
137 5151.0
138 5106.0
139 5606.0
140 4546.0
141 3756.0
142 3851.0
143 4056.0
144 3801.0
145 3151.0
146 2891.0
147 3391.0
148 3891.0
149 3971.0
150 4221.0
151 3766.0
152 4066.0
153 4406.0
154 4486.0
155 4266.0
156 3521.0
157 3766.0
158 3256.0
159 3301.0
160 3681.0
161 3981.0
162 3861.0
163 3861.0
164 3861.0
165 3256.0
166 2701.0
167 2117.0
168 2072.0
169 2032.0
170 1452.0
171 1112.0
172 522.0
173 622.0
174 822.0
175 -263.0
176 -163.0
177 160.0
178 160.0
179 -38.0
180 82.0
181 -66.0
182 74.0
183 -463.0
184 -423.0
185 -1143.0
186 -743.0
187 -823.0
188 -978.0
189 -1173.0
190 -1733.0
191 -2023.0
192 -2463.0
193 -2363.0
194 -2353.0
195 -1853.0
196 -1653.0
197 -1553.0
198 -1453.0
199 -1778.0
200 -1478.0
201 -2038.0
202 -1838.0
203 -1928.0
204 -2268.0
205 -2073.0
206 -1873.0
207 -1673.0
208 -1473.0
209 -1908.0
210 -1813.0
211 -1713.0
212 -1963.0
213 -2263.0
214 -2163.0
215 -2403.0
216 -2403.0
217 -2203.0
218 -2103.0
219 -1903.0
220 -2178.0
221 -2728.0
222 -2428.0
223 -2428.0
224 -2328.0
225 -2668.0
226 -2568.0
227 -2368.0
228 -2513.0
229 -2413.0
230 -2013.0
231 -1913.0
232 -1913.0
233 -1913.0
234 -1913.0
235 -1513.0
236 -1513.0
237 -1758.0
238 -1913.0
239 -1813.0
240 -1953.0
241 -1853.0
242 -1853.0
243 -1653.0
244 -1653.0
245 -1353.0
246 -1153.0
247 -1518.0
248 -1418.0
249 -1318.0

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 28)

(3712,)

(3712, 2)

(250, 28)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.748691  0.251309       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  1.000000  0.000000       0
246      250     -305  0.482047  0.517953       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 227
          Number of winning bets: 109
          Number of losing bets: 118
          Number of underdog bets: 137
          Number of underdog wins: 50
          Number of underdog losses: 87
          Number of Favorite bets: 87
          Number of favorite wins: 58
          Number of favorite losses: 29
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -406.75898348291213
          Profit per bet: -1.791889795078908
          Profit per match: -1.6270359339316485


HI
HI
HI
HI
HI
The original score is 29568.51504322044
Score:  28707.602787496908
Score:  25689.6757830815
Score:  25373.378093631676
Score:  22327.073967660777
Score:  27971.236089392
Score:  26560.910984665417
Score:  28262.981350837457
NEW BEST FEATURE SET
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
29849.29195863912
Score:  26324.66870054805
Score:  28053.736164309943
Score:  29656.451084594402
Score:  28092.94212754171
Score:  27219.316038247453
Score:  27438.391164253164
Score:  26561.40774319291
Score:  27679.012790205314
Score:  27179.542249961094
Score:  29688.334353779894
Score:  7428.998732911335
Score:  20972.119783997234
Score:  28726.121182196403
Score:  28141.364189358577
Score:  28447.87576769461
Score:  24481.498790751266
Score:  -9149.163545015897
Score:  6063.641513544749
Score:  23470.5427128221
The original score is 29849.29195863912
Score:  28477.764939224493
Score:  26511.25257952983
Score:  25174.260188792992
Score:  21758.427914822394
Score:  27648.41498346207
Score:  26617.26804217542
Score:  28346.413236705826
Score:  27006.4543991467
Score:  28598.05103351415
Score:  29045.91384925483
Score:  27662.867458285848
Score:  27984.975961313892
Score:  28203.65083829254
Score:  26965.00203483136
Score:  29459.078969827533
Score:  27799.51519975286
NEW BEST FEATURE SET
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
30220.694943825707
Score:  6428.631584351151
Score:  21741.84266087866
Score:  28867.231839015454
Score:  28339.87300115409
Score:  28605.07591557564
Score:  24382.57516883575
Score:  -6141.919397178437
Score:  5487.140369531239
Score:  23044.562260846007
The original score is 30220.694943825707
Score:  28973.68966354152
Score:  24435.83194782837
Score:  24723.675628079007
Score:  22892.621299253744
Score:  29458.419677440794
Score:  26965.652414065877
Score:  28327.541331322736
Score:  27492.379279003
Score:  28999.087675718136
Score:  29874.05077342969
Score:  27746.382350398162
Score:  27894.025411146948
Score:  28697.60976747489
Score:  24359.0990658683
Score:  28553.45876652636
Score:  27793.997488781613
Score:  9858.831816139522
Score:  22280.34222405742
Score:  28561.10229419768
Score:  28038.549011920513
Score:  28658.397125708594
Score:  25986.44852032543
Score:  -6287.789000746111
Score:  6301.2586333346735
Score:  22076.253185792484
The features are different
OLD:
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'R_draw', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'B_Featherweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
NEW:
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 26)

(3712,)

(3712, 2)

(250, 26)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.777896  0.222104       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  0.739825  0.260175       0
246      250     -305  0.482047  0.517953       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 225
          Number of winning bets: 109
          Number of losing bets: 116
          Number of underdog bets: 140
          Number of underdog wins: 52
          Number of underdog losses: 88
          Number of Favorite bets: 82
          Number of favorite wins: 56
          Number of favorite losses: 26
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 99.79422453562138
          Profit per bet: 0.4435298868249839
          Profit per match: 0.3991768981424855


HI
HI
HI
HI
HI
Current best score is: 30220.694943825707
NO IMPROVEMENT
FINAL BEST SCORE: 30220.694943825707

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 26)

(3712,)

(3712, 2)

(250, 26)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.777896  0.222104       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  0.739825  0.260175       0
246      250     -305  0.482047  0.517953       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 225
          Number of winning bets: 109
          Number of losing bets: 116
          Number of underdog bets: 140
          Number of underdog wins: 52
          Number of underdog losses: 88
          Number of Favorite bets: 82
          Number of favorite wins: 56
          Number of favorite losses: 26
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 99.79422453562138
          Profit per bet: 0.4435298868249839
          Profit per match: 0.3991768981424855


HI
HI
HI
HI
HI


Starting New Run for KNeighborsClassifier


Previous Best Score: 30220.694943825707
weights: uniform n_neighbors: 1 Score: 10846.95661589884
weights: uniform n_neighbors: 2 Score: 17153.82568914636
weights: uniform n_neighbors: 3 Score: 13728.397671376017
weights: uniform n_neighbors: 4 Score: 28113.5770065741
weights: uniform n_neighbors: 5 Score: 23654.836861131
weights: uniform n_neighbors: 6 Score: 20213.490390735577
weights: uniform n_neighbors: 7 Score: 16664.552899656916
weights: uniform n_neighbors: 8 Score: 9370.378513576152
weights: uniform n_neighbors: 9 Score: 10013.695149911717
weights: uniform n_neighbors: 10 Score: 5030.364799536261
weights: distance n_neighbors: 1 Score: 10846.95661589884
weights: distance n_neighbors: 2 Score: 15144.919258986985
weights: distance n_neighbors: 3 Score: 14269.383592303737
weights: distance n_neighbors: 4 Score: 30220.694943825707
weights: distance n_neighbors: 5 Score: 24727.52621208418
weights: distance n_neighbors: 6 Score: 20830.549645732226
weights: distance n_neighbors: 7 Score: 17060.654921345274
weights: distance n_neighbors: 8 Score: 9785.690492508971
weights: distance n_neighbors: 9 Score: 12181.555222468734
weights: distance n_neighbors: 10 Score: 8669.013876389196
Real output model: KNeighborsClassifier(n_neighbors=4, weights='distance')

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 26)

(3712,)

(3712, 2)

(250, 26)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.777896  0.222104       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  0.739825  0.260175       0
246      250     -305  0.482047  0.517953       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 225
          Number of winning bets: 109
          Number of losing bets: 116
          Number of underdog bets: 140
          Number of underdog wins: 52
          Number of underdog losses: 88
          Number of Favorite bets: 82
          Number of favorite wins: 56
          Number of favorite losses: 26
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 99.79422453562138
          Profit per bet: 0.4435298868249839
          Profit per match: 0.3991768981424855


HI
HI
HI
HI
HI
0 29641.16874547118
1 29565.48071072154
2 29546.245982761404
3 30220.694943825707
4 29774.11997658945
5 28453.7954784533
6 28274.597259568807
7 26834.609393059993
8 25919.45022319799
9 25442.89903883049
10 24367.83329562631
11 23836.39399267091
12 23852.275257697234
13 23424.543089715848
14 22851.083855437962
15 21807.90785174693
16 20750.079800615516
17 21020.6590434246
18 21047.467393539137
19 20385.85088185112
20 21736.94229841718
21 21704.911144190006
22 21296.017797973167
23 20434.96742716079
24 21271.89136197626
25 20639.288556993386
26 21611.015613720443
27 21200.693530902685
28 20920.008912194648
29 21171.87274965851
30 21557.441872739597
31 20164.548783965503
32 19854.376176699734
33 18855.785341194023
34 18831.10776866699
35 17785.339818692344
36 17713.982823548147
37 17185.375192164654
38 16982.697485645047
39 15922.572102782437
40 15826.810904005111
41 14953.342051778689
42 13532.488352939125
43 14660.284618926878
44 13734.621163389282
45 13593.512022932311
46 13369.512399367472
47 12842.872615154381
48 12601.812009093775
49 11811.26971720151
50 12425.360626292422
51 12798.02296395476
52 12452.097038028833
53 12996.528360901231
54 12083.488918861789
55 11391.3495267224
56 11731.646785019657
57 12299.959933607415
58 11902.559999891444
59 12679.795294009089
60 12373.79529400909
61 11889.314774528571
62 11497.49659271039
63 10954.496592710391
64 10818.5875018013
65 10540.982279067042
66 10823.105426742057
67 12238.105426742055
68 11847.86733150396
69 12704.005262538441
70 12434.005262538441
71 11778.083276722838
72 11326.85511639396
73 11776.85511639396
74 11596.85511639396
75 10516.30508875438
76 10273.30508875438
77 10018.430749353323
78 9711.430749353323
79 10236.430749353323
80 9812.430749353323
81 9667.430749353323
82 9030.463536238567
83 8330.463536238569
84 8503.796869571903
85 8708.796869571903
86 8548.796869571903
87 7939.231652180599
88 8454.231652180599
89 8564.231652180599
90 8995.66022360917
91 8291.56931451826
92 9041.56931451826
93 9541.56931451826
94 10505.56931451826
95 10061.22969187675
96 9898.039215686274
97 8868.039215686274
98 9063.039215686274
99 9765.0
100 9905.0
101 9502.0
102 9862.0
103 10072.0
104 10022.0
105 9372.0
106 9087.0
107 8977.0
108 8937.0
109 8517.0
110 7792.0
111 7757.0
112 7454.0
113 6964.0
114 7029.0
115 6879.0
116 6738.0
117 6668.0
118 6683.0
119 7483.0
120 6928.0
121 6343.0
122 5700.0
123 5520.0
124 5232.0
125 5362.0
126 5707.0
127 6107.0
128 6262.0
129 6062.0
130 5952.0
131 5712.0
132 5415.0
133 5615.0
134 5381.0
135 4071.0
136 4371.0
137 4151.0
138 4436.0
139 5036.0
140 4116.0
141 3426.0
142 3521.0
143 3626.0
144 2984.0
145 2234.0
146 2399.0
147 2899.0
148 3399.0
149 3579.0
150 3679.0
151 2999.0
152 3299.0
153 3539.0
154 3719.0
155 3399.0
156 2754.0
157 2799.0
158 2689.0
159 2534.0
160 3014.0
161 3314.0
162 3194.0
163 3194.0
164 3194.0
165 2689.0
166 2134.0
167 1550.0
168 1505.0
169 1465.0
170 985.0
171 645.0
172 205.0
173 305.0
174 505.0
175 -580.0
176 -480.0
177 -157.0
178 -57.0
179 -155.0
180 65.0
181 17.0
182 157.0
183 -380.0
184 -440.0
185 -875.0
186 -475.0
187 -455.0
188 -610.0
189 -510.0
190 -1070.0
191 -1610.0
192 -2150.0
193 -1950.0
194 -1940.0
195 -1635.0
196 -1435.0
197 -1335.0
198 -1235.0
199 -1560.0
200 -1160.0
201 -1720.0
202 -1520.0
203 -1710.0
204 -1950.0
205 -1755.0
206 -1555.0
207 -1355.0
208 -1155.0
209 -1490.0
210 -1495.0
211 -1395.0
212 -1645.0
213 -1845.0
214 -1745.0
215 -1985.0
216 -1985.0
217 -1785.0
218 -1685.0
219 -1485.0
220 -1760.0
221 -2310.0
222 -2010.0
223 -2010.0
224 -1910.0
225 -1810.0
226 -1710.0
227 -1510.0
228 -1655.0
229 -1555.0
230 -1155.0
231 -1055.0
232 -1055.0
233 -1055.0
234 -1055.0
235 -655.0
236 -655.0
237 -900.0
238 -1055.0
239 -955.0
240 -995.0
241 -895.0
242 -895.0
243 -695.0
244 -695.0
245 -640.0
246 -440.0
247 -805.0
248 -605.0
249 -505.0

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 26)

(3712,)

(3712, 2)

(250, 26)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.777896  0.222104       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  0.739825  0.260175       0
246      250     -305  0.482047  0.517953       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 225
          Number of winning bets: 109
          Number of losing bets: 116
          Number of underdog bets: 140
          Number of underdog wins: 52
          Number of underdog losses: 88
          Number of Favorite bets: 82
          Number of favorite wins: 56
          Number of favorite losses: 26
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 99.79422453562138
          Profit per bet: 0.4435298868249839
          Profit per match: 0.3991768981424855


HI
HI
HI
HI
HI
The original score is 30220.694943825707
Score:  28973.68966354152
Score:  24435.83194782837
Score:  24723.675628079007
Score:  22892.621299253744
Score:  29458.419677440794
Score:  26965.652414065877
Score:  28327.541331322736
Score:  27492.379279003
Score:  28999.087675718136
Score:  29874.05077342969
Score:  27746.382350398162
Score:  27894.025411146948
Score:  28697.60976747489
Score:  24359.0990658683
Score:  28553.45876652636
Score:  27793.997488781613
Score:  9858.831816139522
Score:  22280.34222405742
Score:  28561.10229419768
Score:  28038.549011920513
Score:  28658.397125708594
Score:  25986.44852032543
Score:  -6287.789000746111
Score:  6301.2586333346735
Score:  22076.253185792484

model_8
KNeighborsClassifier(n_neighbors=4, weights='distance')
['R_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_win_by_TKO_Doctor_Stoppage', 'B_current_win_streak', 'B_win_by_Decision_Majority', 'R_Pound-for-Pound_rank', 'B_Flyweight_rank', 'B_Heavyweight_rank', 'R_Flyweight_rank', 'R_Bantamweight_rank', "R_Women's Bantamweight_rank", "R_Women's Flyweight_rank", 'B_Pound-for-Pound_rank', 'R_Featherweight_rank', 'B_Light Heavyweight_rank', 'R_Light Heavyweight_rank', 'avg_td_dif', 'gender', 'B_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', 'B_current_lose_streak', 'B_avg_SIG_STR_pct', 'B_avg_TD_pct', 'R_win_by_KO/TKO']
3

(3712, 26)

(3712,)

(3712, 2)

(250, 26)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.777896  0.222104       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  0.739825  0.260175       0
246      250     -305  0.482047  0.517953       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 225
          Number of winning bets: 109
          Number of losing bets: 116
          Number of underdog bets: 140
          Number of underdog wins: 52
          Number of underdog losses: 88
          Number of Favorite bets: 82
          Number of favorite wins: 56
          Number of favorite losses: 26
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 99.79422453562138
          Profit per bet: 0.4435298868249839
          Profit per match: 0.3991768981424855


HI
HI
HI
HI
HI

(3712, 26)

(3712,)

(3712, 2)

(250, 26)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.777896  0.222104       1
1       -320      250  0.277952  0.722048       1
2        130     -155  1.000000  0.000000       0
3       -155      135  0.273709  0.726291       1
4       -240      195  1.000000  0.000000       0
..       ...      ...       ...       ...     ...
245      175     -230  0.739825  0.260175       0
246      250     -305  0.482047  0.517953       0
247     -134      105  0.504278  0.495722       1
248     -105     -117  0.794480  0.205520       1
249      115     -143  0.231213  0.768787       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 225
          Number of winning bets: 109
          Number of losing bets: 116
          Number of underdog bets: 140
          Number of underdog wins: 52
          Number of underdog losses: 88
          Number of Favorite bets: 82
          Number of favorite wins: 56
          Number of favorite losses: 26
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: 99.79422453562138
          Profit per bet: 0.4435298868249839
          Profit per match: 0.3991768981424855


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 9


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'B_Middleweight_rank', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
15
Current best score is: -12994.590599466968
Feature: B_odds Score: -9657.138749843489
Feature: R_ev Score: -3299.580786627741
Feature: B_avg_SUB_ATT Score: 2148.7877504374455
The best feature was B_avg_SUB_ATT.  It scored 2148.7877504374455
Current best score is: 2148.7877504374455
Feature: B_current_win_streak Score: 4544.080771447043
Feature: R_avg_SIG_STR_pct Score: 5399.036716072258
Feature: R_win_by_TKO_Doctor_Stoppage Score: 8448.100471403992
Feature: win_streak_dif Score: 8544.97210520209
The best feature was win_streak_dif.  It scored 8544.97210520209
Current best score is: 8544.97210520209
Feature: ko_dif Score: 9006.762670146609
Feature: B_match_weightclass_rank Score: 11685.710755395856
The best feature was B_match_weightclass_rank.  It scored 11685.710755395856
Current best score is: 11685.710755395856
NO IMPROVEMENT
FINAL BEST SCORE: 11685.710755395856

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'B_Middleweight_rank', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
15

(3601, 18)

(3601,)

(3601, 2)

(248, 18)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.452581  0.547419       1
1       -320      250  1.000000  0.000000       1
2        130     -155  0.020699  0.979301       0
3       -155      135  0.000000  1.000000       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.000000  1.000000       0
245     -134      105  0.225826  0.774174       1
246     -105     -117  0.306119  0.693881       1
247      115     -143  0.411253  0.588747       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 209
          Number of winning bets: 114
          Number of losing bets: 95
          Number of underdog bets: 92
          Number of underdog wins: 40
          Number of underdog losses: 52
          Number of Favorite bets: 114
          Number of favorite wins: 72
          Number of favorite losses: 42
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: 824.42287204284
          Profit per bet: 3.9446070432671774
          Profit per match: 3.3242857743662904


HI
HI
HI
HI
HI


Starting New Run for SGDClassifier


Previous Best Score: 11685.710755395856
loss:  modified_huber penalty:  l1 alpha:  0.0001 Score:  2785.9483765715718
loss:  modified_huber penalty:  l1 alpha:  9e-05 Score:  -7499.239235208404
loss:  modified_huber penalty:  l1 alpha:  0.00011000000000000002 Score:  1007.9100501997405
loss:  modified_huber penalty:  l2 alpha:  0.0001 Score:  11685.710755395856
loss:  modified_huber penalty:  l2 alpha:  9e-05 Score:  4128.916182428865
loss:  modified_huber penalty:  l2 alpha:  0.00011000000000000002 Score:  -212.57444677885724
loss:  log penalty:  l1 alpha:  0.0001 Score:  1039.7345939863917
loss:  log penalty:  l1 alpha:  9e-05 Score:  3467.5809963587544
loss:  log penalty:  l1 alpha:  0.00011000000000000002 Score:  2895.1803212262394
loss:  log penalty:  l2 alpha:  0.0001 Score:  3675.789711723409
loss:  log penalty:  l2 alpha:  9e-05 Score:  2754.144746815881
loss:  log penalty:  l2 alpha:  0.00011000000000000002 Score:  2459.2454385214187
Real output model: SGDClassifier(loss='modified_huber', random_state=75)

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'B_Middleweight_rank', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
15

(3601, 18)

(3601,)

(3601, 2)

(248, 18)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.452581  0.547419       1
1       -320      250  1.000000  0.000000       1
2        130     -155  0.020699  0.979301       0
3       -155      135  0.000000  1.000000       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.000000  1.000000       0
245     -134      105  0.225826  0.774174       1
246     -105     -117  0.306119  0.693881       1
247      115     -143  0.411253  0.588747       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 209
          Number of winning bets: 114
          Number of losing bets: 95
          Number of underdog bets: 92
          Number of underdog wins: 40
          Number of underdog losses: 52
          Number of Favorite bets: 114
          Number of favorite wins: 72
          Number of favorite losses: 42
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: 824.42287204284
          Profit per bet: 3.9446070432671774
          Profit per match: 3.3242857743662904


HI
HI
HI
HI
HI
0 12289.885992771506
1 12037.512174998667
2 12610.614031379642
3 12235.978308700443
4 12905.564230025491
5 13168.892966439304
6 13356.692803148366
7 12632.845237560723
8 12210.231797604512
9 12192.061434917981
10 11862.564227651246
11 11944.51575156831
12 11024.968270646565
13 11963.138876082437
14 12207.522246880617
15 11685.710755395856
16 11186.690817621122
17 10862.589504708809
18 10782.50355785612
19 10696.44647502015
20 10808.972296830096
21 10614.142332954183
22 10824.017330707913
23 10265.571059197086
24 9773.762877999014
25 10330.484316663067
26 10310.757646181653
27 9755.58233086177
28 9842.06637586938
29 9306.19075339763
30 8882.25865234255
31 8840.546544470493
32 8522.54961712466
33 7759.048139289591
34 7069.600930071
35 6276.725783375465
36 5362.45114346058
37 5151.83770593971
38 4990.533005757061
39 4699.882093202123
40 5259.958324855325
41 4812.456388836666
42 4946.935639563956
43 4502.377771257337
44 3882.062485430235
45 3206.599522467272
46 2770.550841805968
47 2942.2005104123336
48 2749.446505158327
49 2998.8855295485687
50 2426.3296174010047
51 1619.2156848824493
52 1752.135912802678
53 1074.0469973321851
54 890.4089483214993
55 938.5431538513403
56 241.8736441297906
57 279.01643859284377
58 297.5690511638086
59 -817.4309488361937
60 -684.3443946717939
61 -426.76863709603685
62 -441.2847661282949
63 -424.735206830715
64 1.5705256533624379
65 17.458936796906983
66 -271.6151372771669
67 806.9216019218234
68 481.92160192182337
69 617.53883757627
70 512.7486277860612
71 420.8255508629841
72 985.1112651486987
73 809.1258636888438
74 973.8877684507493
75 679.6246053154259
76 1027.6680835762959
77 979.4091287906222
78 1014.4091287906222
79 916.3832570245931
80 231.38325702459406
81 -569.2619042657293
82 -1016.2184260048593
83 -701.2184260048598
84 15.448240661806722
85 60.70247794994293
86 460.7024779499425
87 998.3111736021156
88 980.5918753565015
89 1289.6827844474105
90 1935.3970701616963
91 3235.397070161696
92 3035.1589749236005
93 3148.0715962828235
94 3216.0715962828235
95 3627.392350999805
96 3694.0590176664723
97 3644.0590176664723
98 2969.0590176664723
99 2838.019801980198
100 1688.0
101 1678.0
102 1488.0
103 1473.0
104 1593.0
105 973.0
106 1173.0
107 1163.0
108 1363.0
109 943.0
110 1173.0
111 528.0
112 -631.0
113 -276.0
114 -76.0
115 699.0
116 468.0
117 513.0
118 460.0
119 660.0
120 545.0
121 190.0
122 -97.0
123 80.0
124 230.0
125 255.0
126 255.0
127 -35.0
128 -63.0
129 -218.0
130 -878.0
131 -878.0
132 -678.0
133 -328.0
134 -228.0
135 197.0
136 497.0
137 92.0
138 392.0
139 432.0
140 -708.0
141 -708.0
142 -408.0
143 -568.0
144 -413.0
145 -1028.0
146 -1688.0
147 -1923.0
148 -2078.0
149 -1878.0
150 -2793.0
151 -2493.0
152 -2293.0
153 -2523.0
154 -2323.0
155 -2863.0
156 -2763.0
157 -2663.0
158 -2321.0
159 -2321.0
160 -2281.0
161 -2081.0
162 -2081.0
163 -1881.0
164 -2321.0
165 -1846.0
166 -1741.0
167 -1908.0
168 -1976.0
169 -1776.0
170 -1026.0
171 -1026.0
172 -1026.0
173 -1026.0
174 -1106.0
175 -1881.0
176 -1881.0
177 -1481.0
178 -1481.0
179 -1381.0
180 -1121.0
181 -921.0
182 -1041.0
183 -941.0
184 -1031.0
185 -886.0
186 -786.0
187 -786.0
188 -1062.0
189 -1062.0
190 -812.0
191 -712.0
192 -712.0
193 -712.0
194 -612.0
195 -792.0
196 -792.0
197 -792.0
198 -792.0
199 -792.0
200 -692.0
201 -692.0
202 -692.0
203 -692.0
204 -592.0
205 -602.0
206 -777.0
207 -777.0
208 -777.0
209 -777.0
210 -287.0
211 -287.0
212 -287.0
213 -187.0
214 -87.0
215 -337.0
216 -237.0
217 -137.0
218 -137.0
219 -137.0
220 -517.0
221 -417.0
222 -417.0
223 -417.0
224 -417.0
225 -817.0
226 -617.0
227 -617.0
228 -617.0
229 -617.0
230 -547.0
231 -447.0
232 -742.0
233 -742.0
234 -742.0
235 -577.0
236 -577.0
237 -997.0
238 -997.0
239 -997.0
240 -977.0
241 -977.0
242 -977.0
243 -877.0
244 -877.0
245 -1457.0
246 -1357.0
247 -1357.0
248 -1605.0
249 -2330.0

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'B_Middleweight_rank', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
6

(3601, 18)

(3601,)

(3601, 2)

(248, 18)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.452581  0.547419       1
1       -320      250  1.000000  0.000000       1
2        130     -155  0.020699  0.979301       0
3       -155      135  0.000000  1.000000       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.000000  1.000000       0
245     -134      105  0.225826  0.774174       1
246     -105     -117  0.306119  0.693881       1
247      115     -143  0.411253  0.588747       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 229
          Number of winning bets: 129
          Number of losing bets: 100
          Number of underdog bets: 100
          Number of underdog wins: 44
          Number of underdog losses: 56
          Number of Favorite bets: 126
          Number of favorite wins: 83
          Number of favorite losses: 43
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: 1403.9259990127803
          Profit per bet: 6.13068121839642
          Profit per match: 5.660991931503146


HI
HI
HI
HI
HI
The original score is 13356.692803148366
Score:  8107.040112594347
Score:  -2436.3286622624373
Score:  -17694.66318289489
Score:  -1043.0530015406684
Score:  -11767.267609872992
Score:  -8563.145153078985
Score:  -734.1373522166081
Score:  -11308.116416954354
Score:  -2217.5662502615733
NEW BEST FEATURE SET
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
18889.557867190033
Score:  1280.7756970407627
Score:  -13320.612266722077
Score:  -1761.3903759983732
Score:  -6334.1032974235395
Score:  -3035.3788322940004
The original score is 18889.557867190033
Score:  4376.014560984815
Score:  2977.9399897051144
Score:  -1557.1153955257332
Score:  -8564.06628482395
Score:  -374.75090123395785
Score:  -5761.4516617782665
Score:  -10544.975935974198
Score:  -10674.465134266411
Score:  -184.12500473239993
Score:  -3111.218501086479
Score:  8287.380832694424
Score:  -3598.26569820816
Score:  -4545.4239027483945
Score:  2803.3248822056767
The features are different
OLD:
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'B_Middleweight_rank', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
NEW:
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
The EV is different
OLD:
15
NEW:
6

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
6

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 229
          Number of winning bets: 116
          Number of losing bets: 113
          Number of underdog bets: 120
          Number of underdog wins: 47
          Number of underdog losses: 73
          Number of Favorite bets: 107
          Number of favorite wins: 68
          Number of favorite losses: 39
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -218.30728139638012
          Profit per bet: -0.9533069056610486
          Profit per match: -0.8802712959531457


HI
HI
HI
HI
HI
Current best score is: 18889.557867190033
NO IMPROVEMENT
FINAL BEST SCORE: 18889.557867190033

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
6

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 229
          Number of winning bets: 116
          Number of losing bets: 113
          Number of underdog bets: 120
          Number of underdog wins: 47
          Number of underdog losses: 73
          Number of Favorite bets: 107
          Number of favorite wins: 68
          Number of favorite losses: 39
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -218.30728139638012
          Profit per bet: -0.9533069056610486
          Profit per match: -0.8802712959531457


HI
HI
HI
HI
HI


Starting New Run for SGDClassifier


Previous Best Score: 18889.557867190033
loss:  modified_huber penalty:  l1 alpha:  0.0001 Score:  -13945.429661310158
loss:  modified_huber penalty:  l1 alpha:  9e-05 Score:  -18618.87246080794
loss:  modified_huber penalty:  l1 alpha:  0.00011000000000000002 Score:  -12823.385425432874
loss:  modified_huber penalty:  l2 alpha:  0.0001 Score:  18889.557867190033
loss:  modified_huber penalty:  l2 alpha:  9e-05 Score:  -3081.685693371054
loss:  modified_huber penalty:  l2 alpha:  0.00011000000000000002 Score:  -1547.2678969613871
loss:  log penalty:  l1 alpha:  0.0001 Score:  1898.9613760059879
loss:  log penalty:  l1 alpha:  9e-05 Score:  5739.075606010833
loss:  log penalty:  l1 alpha:  0.00011000000000000002 Score:  -7525.230603147706
loss:  log penalty:  l2 alpha:  0.0001 Score:  174.72036254949205
loss:  log penalty:  l2 alpha:  9e-05 Score:  -399.9857982245828
loss:  log penalty:  l2 alpha:  0.00011000000000000002 Score:  -4664.844936674473
Real output model: SGDClassifier(loss='modified_huber', random_state=75)

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
6

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 229
          Number of winning bets: 116
          Number of losing bets: 113
          Number of underdog bets: 120
          Number of underdog wins: 47
          Number of underdog losses: 73
          Number of Favorite bets: 107
          Number of favorite wins: 68
          Number of favorite losses: 39
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -218.30728139638012
          Profit per bet: -0.9533069056610486
          Profit per match: -0.8802712959531457


HI
HI
HI
HI
HI
0 17288.773427975033
1 17387.586579814502
2 18041.488208086972
3 17716.370331303242
4 18200.545033472168
5 18635.941858868995
6 18889.557867190033
7 19247.469723851893
8 19222.430589799063
9 19325.038083478008
10 19491.092318916977
11 18490.000485104287
12 18217.16142473236
13 18158.557917182516
14 17196.534220414615
15 16262.465789620306
16 15702.708217011212
17 15623.064512331732
18 14978.188354165577
19 15611.458364845568
20 15056.635281916664
21 14220.329501466382
22 14798.72921685035
23 14696.241119775732
24 14530.926026409923
25 14630.520535315258
26 15359.922318507717
27 15835.332179544514
28 15908.030035288277
29 16821.626151188437
30 16190.43919042937
31 15786.480359116915
32 14821.394923284406
33 14283.300520772513
34 13141.704794839372
35 13058.199034748515
36 12426.657626560884
37 11970.13535192408
38 11728.426472472676
39 12226.564544078487
40 11786.806475119922
41 11354.411508335554
42 11363.472933338508
43 10939.519358751833
44 10963.31466167757
45 10088.630845493757
46 10130.520853568898
47 9710.541995217947
48 8373.258633418456
49 8325.625878883042
50 9171.761410018575
51 8221.469716411091
52 7819.281376706622
53 8434.676113548729
54 8167.32292909877
55 8579.349956125796
56 8107.1596700287555
57 7978.696750249714
58 8370.732435685486
59 7661.477657593015
60 7550.202027035947
61 7334.660901494823
62 7713.170601671189
63 9485.170601671187
64 9734.140005857982
65 9968.612146620448
66 9818.612146620446
67 10119.278813287114
68 9760.330131062572
69 10809.151541252999
70 10172.460324668165
71 10173.23729608656
72 10633.913897662442
73 10352.030906894684
74 9693.263399891885
75 9130.607874102028
76 9110.419904177219
77 9461.309536284241
78 8919.353014545111
79 8169.114919307014
80 7782.158397567884
81 7866.158397567884
82 7559.201875828754
83 7636.560778179713
84 7629.894111513046
85 7820.862634515468
86 7835.862634515468
87 6918.47133016764
88 7125.7520319220275
89 6875.513936683932
90 6906.2282223982165
91 7142.591858761854
92 7650.848739495799
93 7165.848739495799
94 7272.848739495799
95 7142.848739495799
96 7019.0392156862745
97 7094.0392156862745
98 7324.0392156862745
99 7301.0
100 7241.0
101 7341.0
102 7641.0
103 7716.0
104 8216.0
105 8756.0
106 8723.0
107 8668.0
108 9248.0
109 9593.0
110 9818.0
111 10018.0
112 10069.0
113 9614.0
114 9454.0
115 10079.0
116 9959.0
117 10069.0
118 9896.0
119 10046.0
120 9768.0
121 9233.0
122 8995.0
123 9030.0
124 9130.0
125 8755.0
126 8855.0
127 9428.0
128 9578.0
129 9470.0
130 8595.0
131 8382.0
132 8582.0
133 7937.0
134 8137.0
135 8562.0
136 7502.0
137 7702.0
138 7864.0
139 7694.0
140 6944.0
141 6944.0
142 6852.0
143 6642.0
144 6642.0
145 5982.0
146 5982.0
147 6182.0
148 6282.0
149 6032.0
150 5682.0
151 5512.0
152 5712.0
153 5547.0
154 5192.0
155 4952.0
156 4802.0
157 4802.0
158 4842.0
159 4842.0
160 4862.0
161 4637.0
162 4737.0
163 4774.0
164 4694.0
165 3914.0
166 3844.0
167 4044.0
168 3989.0
169 4189.0
170 4709.0
171 4369.0
172 4469.0
173 4296.0
174 4396.0
175 3671.0
176 3671.0
177 3871.0
178 3871.0
179 3931.0
180 3546.0
181 3646.0
182 3846.0
183 3846.0
184 3621.0
185 3626.0
186 3726.0
187 3726.0
188 4026.0
189 3856.0
190 3286.0
191 3286.0
192 3386.0
193 3486.0
194 3686.0
195 2836.0
196 3136.0
197 3136.0
198 3136.0
199 3136.0
200 2936.0
201 2686.0
202 2786.0
203 2886.0
204 2886.0
205 2321.0
206 2321.0
207 1936.0
208 2036.0
209 2136.0
210 2246.0
211 2346.0
212 2546.0
213 2646.0
214 2271.0
215 2241.0
216 2241.0
217 2241.0
218 2341.0
219 2341.0
220 1001.0
221 1001.0
222 1001.0
223 1101.0
224 1101.0
225 1151.0
226 831.0
227 831.0
228 831.0
229 831.0
230 491.0
231 211.0
232 211.0
233 411.0
234 411.0
235 811.0
236 526.0
237 281.0
238 281.0
239 281.0
240 -139.0
241 -139.0
242 -39.0
243 -39.0
244 -39.0
245 -29.0
246 171.0
247 171.0
248 -77.0
249 -77.0

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
10

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 219
          Number of winning bets: 110
          Number of losing bets: 109
          Number of underdog bets: 115
          Number of underdog wins: 44
          Number of underdog losses: 71
          Number of Favorite bets: 102
          Number of favorite wins: 65
          Number of favorite losses: 37
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -383.8633974115124
          Profit per bet: -1.752800901422431
          Profit per match: -1.5478362798851306


HI
HI
HI
HI
HI
The original score is 19491.092318916977
Score:  4820.850140624084
Score:  3440.474883024557
Score:  -983.595971852091
Score:  -8519.91062653611
Score:  20.49683941528656
Score:  -4650.661279553589
Score:  -9972.129222235042
Score:  -7981.76208489848
Score:  390.7489016892732
Score:  -3578.6339558043665
Score:  8415.666110703452
Score:  -5840.494812064049
Score:  -3339.190716133633
Score:  2947.678565467495
The EV is different
OLD:
6
NEW:
10

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
10

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 219
          Number of winning bets: 110
          Number of losing bets: 109
          Number of underdog bets: 115
          Number of underdog wins: 44
          Number of underdog losses: 71
          Number of Favorite bets: 102
          Number of favorite wins: 65
          Number of favorite losses: 37
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -383.8633974115124
          Profit per bet: -1.752800901422431
          Profit per match: -1.5478362798851306


HI
HI
HI
HI
HI
Current best score is: 19491.092318916977
NO IMPROVEMENT
FINAL BEST SCORE: 19491.092318916977

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
10

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 219
          Number of winning bets: 110
          Number of losing bets: 109
          Number of underdog bets: 115
          Number of underdog wins: 44
          Number of underdog losses: 71
          Number of Favorite bets: 102
          Number of favorite wins: 65
          Number of favorite losses: 37
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -383.8633974115124
          Profit per bet: -1.752800901422431
          Profit per match: -1.5478362798851306


HI
HI
HI
HI
HI


Starting New Run for SGDClassifier


Previous Best Score: 19491.092318916977
loss:  modified_huber penalty:  l1 alpha:  0.0001 Score:  -14248.831114774603
loss:  modified_huber penalty:  l1 alpha:  9e-05 Score:  -16461.338540301378
loss:  modified_huber penalty:  l1 alpha:  0.00011000000000000002 Score:  -12454.299921646507
loss:  modified_huber penalty:  l2 alpha:  0.0001 Score:  19491.092318916977
loss:  modified_huber penalty:  l2 alpha:  9e-05 Score:  -2659.6546327022397
loss:  modified_huber penalty:  l2 alpha:  0.00011000000000000002 Score:  -142.69240891521218
loss:  log penalty:  l1 alpha:  0.0001 Score:  7032.052653841518
loss:  log penalty:  l1 alpha:  9e-05 Score:  7136.845100790928
loss:  log penalty:  l1 alpha:  0.00011000000000000002 Score:  -4071.897792969102
loss:  log penalty:  l2 alpha:  0.0001 Score:  1896.6550863746286
loss:  log penalty:  l2 alpha:  9e-05 Score:  -638.6539762296287
loss:  log penalty:  l2 alpha:  0.00011000000000000002 Score:  -317.824815502343
Real output model: SGDClassifier(loss='modified_huber', random_state=75)

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
10

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 219
          Number of winning bets: 110
          Number of losing bets: 109
          Number of underdog bets: 115
          Number of underdog wins: 44
          Number of underdog losses: 71
          Number of Favorite bets: 102
          Number of favorite wins: 65
          Number of favorite losses: 37
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -383.8633974115124
          Profit per bet: -1.752800901422431
          Profit per match: -1.5478362798851306


HI
HI
HI
HI
HI
0 17288.773427975033
1 17387.586579814502
2 18041.488208086972
3 17716.370331303242
4 18200.545033472168
5 18635.941858868995
6 18889.557867190033
7 19247.469723851893
8 19222.430589799063
9 19325.038083478008
10 19491.092318916977
11 18490.000485104287
12 18217.16142473236
13 18158.557917182516
14 17196.534220414615
15 16262.465789620306
16 15702.708217011212
17 15623.064512331732
18 14978.188354165577
19 15611.458364845568
20 15056.635281916664
21 14220.329501466382
22 14798.72921685035
23 14696.241119775732
24 14530.926026409923
25 14630.520535315258
26 15359.922318507717
27 15835.332179544514
28 15908.030035288277
29 16821.626151188437
30 16190.43919042937
31 15786.480359116915
32 14821.394923284406
33 14283.300520772513
34 13141.704794839372
35 13058.199034748515
36 12426.657626560884
37 11970.13535192408
38 11728.426472472676
39 12226.564544078487
40 11786.806475119922
41 11354.411508335554
42 11363.472933338508
43 10939.519358751833
44 10963.31466167757
45 10088.630845493757
46 10130.520853568898
47 9710.541995217947
48 8373.258633418456
49 8325.625878883042
50 9171.761410018575
51 8221.469716411091
52 7819.281376706622
53 8434.676113548729
54 8167.32292909877
55 8579.349956125796
56 8107.1596700287555
57 7978.696750249714
58 8370.732435685486
59 7661.477657593015
60 7550.202027035947
61 7334.660901494823
62 7713.170601671189
63 9485.170601671187
64 9734.140005857982
65 9968.612146620448
66 9818.612146620446
67 10119.278813287114
68 9760.330131062572
69 10809.151541252999
70 10172.460324668165
71 10173.23729608656
72 10633.913897662442
73 10352.030906894684
74 9693.263399891885
75 9130.607874102028
76 9110.419904177219
77 9461.309536284241
78 8919.353014545111
79 8169.114919307014
80 7782.158397567884
81 7866.158397567884
82 7559.201875828754
83 7636.560778179713
84 7629.894111513046
85 7820.862634515468
86 7835.862634515468
87 6918.47133016764
88 7125.7520319220275
89 6875.513936683932
90 6906.2282223982165
91 7142.591858761854
92 7650.848739495799
93 7165.848739495799
94 7272.848739495799
95 7142.848739495799
96 7019.0392156862745
97 7094.0392156862745
98 7324.0392156862745
99 7301.0
100 7241.0
101 7341.0
102 7641.0
103 7716.0
104 8216.0
105 8756.0
106 8723.0
107 8668.0
108 9248.0
109 9593.0
110 9818.0
111 10018.0
112 10069.0
113 9614.0
114 9454.0
115 10079.0
116 9959.0
117 10069.0
118 9896.0
119 10046.0
120 9768.0
121 9233.0
122 8995.0
123 9030.0
124 9130.0
125 8755.0
126 8855.0
127 9428.0
128 9578.0
129 9470.0
130 8595.0
131 8382.0
132 8582.0
133 7937.0
134 8137.0
135 8562.0
136 7502.0
137 7702.0
138 7864.0
139 7694.0
140 6944.0
141 6944.0
142 6852.0
143 6642.0
144 6642.0
145 5982.0
146 5982.0
147 6182.0
148 6282.0
149 6032.0
150 5682.0
151 5512.0
152 5712.0
153 5547.0
154 5192.0
155 4952.0
156 4802.0
157 4802.0
158 4842.0
159 4842.0
160 4862.0
161 4637.0
162 4737.0
163 4774.0
164 4694.0
165 3914.0
166 3844.0
167 4044.0
168 3989.0
169 4189.0
170 4709.0
171 4369.0
172 4469.0
173 4296.0
174 4396.0
175 3671.0
176 3671.0
177 3871.0
178 3871.0
179 3931.0
180 3546.0
181 3646.0
182 3846.0
183 3846.0
184 3621.0
185 3626.0
186 3726.0
187 3726.0
188 4026.0
189 3856.0
190 3286.0
191 3286.0
192 3386.0
193 3486.0
194 3686.0
195 2836.0
196 3136.0
197 3136.0
198 3136.0
199 3136.0
200 2936.0
201 2686.0
202 2786.0
203 2886.0
204 2886.0
205 2321.0
206 2321.0
207 1936.0
208 2036.0
209 2136.0
210 2246.0
211 2346.0
212 2546.0
213 2646.0
214 2271.0
215 2241.0
216 2241.0
217 2241.0
218 2341.0
219 2341.0
220 1001.0
221 1001.0
222 1001.0
223 1101.0
224 1101.0
225 1151.0
226 831.0
227 831.0
228 831.0
229 831.0
230 491.0
231 211.0
232 211.0
233 411.0
234 411.0
235 811.0
236 526.0
237 281.0
238 281.0
239 281.0
240 -139.0
241 -139.0
242 -39.0
243 -39.0
244 -39.0
245 -29.0
246 171.0
247 171.0
248 -77.0
249 -77.0

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
10

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 219
          Number of winning bets: 110
          Number of losing bets: 109
          Number of underdog bets: 115
          Number of underdog wins: 44
          Number of underdog losses: 71
          Number of Favorite bets: 102
          Number of favorite wins: 65
          Number of favorite losses: 37
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -383.8633974115124
          Profit per bet: -1.752800901422431
          Profit per match: -1.5478362798851306


HI
HI
HI
HI
HI
The original score is 19491.092318916977
Score:  4820.850140624084
Score:  3440.474883024557
Score:  -983.595971852091
Score:  -8519.91062653611
Score:  20.49683941528656
Score:  -4650.661279553589
Score:  -9972.129222235042
Score:  -7981.76208489848
Score:  390.7489016892732
Score:  -3578.6339558043665
Score:  8415.666110703452
Score:  -5840.494812064049
Score:  -3339.190716133633
Score:  2947.678565467495

model_9
SGDClassifier(loss='modified_huber', random_state=75)
['B_match_weightclass_rank', 'win_streak_dif', 'B_avg_SUB_ATT', 'B_wins', 'R_Light Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_win_by_Decision_Unanimous', 'B_avg_SIG_STR_pct', 'B_Stance', 'R_win_by_KO/TKO', 'B_Featherweight_rank', "B_Women's Strawweight_rank", 'R_avg_TD_pct', 'B_ev']
10

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 219
          Number of winning bets: 110
          Number of losing bets: 109
          Number of underdog bets: 115
          Number of underdog wins: 44
          Number of underdog losses: 71
          Number of Favorite bets: 102
          Number of favorite wins: 65
          Number of favorite losses: 37
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -383.8633974115124
          Profit per bet: -1.752800901422431
          Profit per match: -1.5478362798851306


HI
HI
HI
HI
HI

(3601, 17)

(3601,)

(3601, 2)

(248, 17)

(248,)

(248, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.051932  0.948068       1
1       -320      250  0.586178  0.413822       1
2        130     -155  0.265725  0.734275       0
3       -155      135  0.409961  0.590039       1
4       -240      195  0.000000  1.000000       0
..       ...      ...       ...       ...     ...
243      175     -230  0.000000  1.000000       0
244      250     -305  0.338734  0.661266       0
245     -134      105  0.000000  1.000000       1
246     -105     -117  0.856963  0.143037       1
247      115     -143  0.165747  0.834253       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 219
          Number of winning bets: 110
          Number of losing bets: 109
          Number of underdog bets: 115
          Number of underdog wins: 44
          Number of underdog losses: 71
          Number of Favorite bets: 102
          Number of favorite wins: 65
          Number of favorite losses: 37
          Number of even bets: 2
          Number of even wins: 1
          Number of even losses: 1
          Profit: -383.8633974115124
          Profit per bet: -1.752800901422431
          Profit per match: -1.5478362798851306


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 10


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_10
GaussianProcessClassifier(random_state=75)
['R_draw', "B_Women's Flyweight_rank", "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'R_win_by_Decision_Majority', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
0
Current best score is: 25232.790628868835
Feature: R_ev Score: 25632.05378322761
Feature: B_ev Score: 26495.809498449125
Feature: R_avg_TD_landed Score: 26678.403526619037
Feature: R_Flyweight_rank Score: 26893.384466249576
Feature: B_Flyweight_rank Score: 28386.09038483439
The best feature was B_Flyweight_rank.  It scored 28386.09038483439
Current best score is: 28386.09038483439
Feature: B_Women's Strawweight_rank Score: 28564.228912972925
The best feature was B_Women's Strawweight_rank.  It scored 28564.228912972925
Current best score is: 28564.228912972925
NO IMPROVEMENT
FINAL BEST SCORE: 28564.228912972925

model_10
GaussianProcessClassifier(random_state=75)
["B_Women's Strawweight_rank", 'B_Flyweight_rank', 'R_draw', "B_Women's Flyweight_rank", "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'R_win_by_Decision_Majority', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
0

(3722, 23)

(3722,)

(3722, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.739858  0.260142       1
1       -320      250  0.492349  0.507651       1
2        130     -155  0.492719  0.507281       0
3       -155      135  0.498562  0.501438       1
4       -240      195  0.765189  0.234811       0
..       ...      ...       ...       ...     ...
245      175     -230  0.488259  0.511741       0
246      250     -305  0.502303  0.497697       0
247     -134      105  0.516302  0.483698       1
248     -105     -117  0.482736  0.517264       1
249      115     -143  0.268769  0.731231       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 218
          Number of winning bets: 101
          Number of losing bets: 117
          Number of underdog bets: 155
          Number of underdog wins: 58
          Number of underdog losses: 97
          Number of Favorite bets: 62
          Number of favorite wins: 43
          Number of favorite losses: 19
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: -60.57511146606298
          Profit per bet: -0.2778674837892797
          Profit per match: -0.24230044586425192


HI
HI
HI
HI
HI
Real output model: GaussianProcessClassifier(random_state=75)

model_10
GaussianProcessClassifier(random_state=75)
["B_Women's Strawweight_rank", 'B_Flyweight_rank', 'R_draw', "B_Women's Flyweight_rank", "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'R_win_by_Decision_Majority', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
0

(3722, 23)

(3722,)

(3722, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.739858  0.260142       1
1       -320      250  0.492349  0.507651       1
2        130     -155  0.492719  0.507281       0
3       -155      135  0.498562  0.501438       1
4       -240      195  0.765189  0.234811       0
..       ...      ...       ...       ...     ...
245      175     -230  0.488259  0.511741       0
246      250     -305  0.502303  0.497697       0
247     -134      105  0.516302  0.483698       1
248     -105     -117  0.482736  0.517264       1
249      115     -143  0.268769  0.731231       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 218
          Number of winning bets: 101
          Number of losing bets: 117
          Number of underdog bets: 155
          Number of underdog wins: 58
          Number of underdog losses: 97
          Number of Favorite bets: 62
          Number of favorite wins: 43
          Number of favorite losses: 19
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: -60.57511146606298
          Profit per bet: -0.2778674837892797
          Profit per match: -0.24230044586425192


HI
HI
HI
HI
HI
0 28564.228912972925
1 28302.878238852463
2 28302.76987012846
3 26090.066750475005
4 24412.78402363595
5 23455.959023187974
6 23580.04355167035
7 22474.50894552041
8 22759.521643259955
9 23161.54021219621
10 23875.654094987844
11 22382.376577861636
12 22338.42868124459
13 20513.937931428907
14 19498.946894161738
15 18177.012726064826
16 18508.704509042283
17 18122.183209370858
18 17386.212984538703
19 14964.54193491447
20 14619.188940360582
21 13620.748524922688
22 13312.48117115844
23 13431.679303992476
24 11777.884449093097
25 10649.554269236201
26 8988.805158249863
27 8894.510954351295
28 7542.267552591764
29 8802.86282939505
30 11076.885851991772
31 10132.929330252642
32 8718.929330252642
33 7272.76382908714
34 6621.76382908714
35 6112.576892601466
36 4525.338797363371
37 4127.33879736337
38 3255.6275174101265
39 3177.6275174101265
40 2982.6275174101265
41 2907.6275174101265
42 2355.6275174101265
43 1300.6275174101263
44 1460.6275174101265
45 1138.3418031244119
46 1053.3418031244119
47 928.3418031244123
48 940.4761904761908
49 870.4761904761908
50 687.4761904761908
51 914.4761904761906
52 1074.2380952380954
53 219.0
54 779.0
55 520.0
56 -190.0
57 -330.0
58 -1661.0
59 -1711.0
60 -1886.0
61 -2621.0
62 -2481.0
63 -3431.0
64 -3366.0
65 -3675.0
66 -4410.0
67 -4365.0
68 -3969.0
69 -4794.0
70 -4739.0
71 -5714.0
72 -5702.0
73 -5522.0
74 -4667.0
75 -5087.0
76 -5497.0
77 -5682.0
78 -5807.0
79 -5562.0
80 -5647.0
81 -5572.0
82 -5922.0
83 -5787.0
84 -5497.0
85 -5297.0
86 -5002.0
87 -5452.0
88 -5402.0
89 -5102.0
90 -4977.0
91 -4837.0
92 -4485.0
93 -3985.0
94 -4000.0
95 -4170.0
96 -3770.0
97 -3960.0
98 -3945.0
99 -3445.0
100 -4010.0
101 -3800.0
102 -3500.0
103 -3100.0
104 -3250.0
105 -3335.0
106 -3035.0
107 -2950.0
108 -2450.0
109 -2250.0
110 -2325.0
111 -2440.0
112 -2365.0
113 -2730.0
114 -2610.0
115 -2110.0
116 -1795.0
117 -1695.0
118 -1830.0
119 -1630.0
120 -1230.0
121 -870.0
122 -1015.0
123 -540.0
124 -835.0
125 -835.0
126 -1070.0
127 -1070.0
128 -970.0
129 -870.0
130 -1025.0
131 -1425.0
132 -1490.0
133 -1265.0
134 -1265.0
135 -1165.0
136 -1475.0
137 -1275.0
138 -875.0
139 -2000.0
140 -1900.0
141 -1825.0
142 -1725.0
143 -1625.0
144 -1525.0
145 -1325.0
146 -1950.0
147 -1650.0
148 -1550.0
149 -1550.0
150 -1665.0
151 -1465.0
152 -1765.0
153 -1665.0
154 -1565.0
155 -1365.0
156 -1815.0
157 -1715.0
158 -2065.0
159 -1865.0
160 -1805.0
161 -1805.0
162 -1805.0
163 -1955.0
164 -1955.0
165 -1955.0
166 -1855.0
167 -1895.0
168 -1595.0
169 -1495.0
170 -1295.0
171 -1295.0
172 -1295.0
173 -1295.0
174 -1095.0
175 -795.0
176 -695.0
177 -495.0
178 -295.0
179 -295.0
180 -95.0
181 5.0
182 -230.0
183 -130.0
184 70.0
185 70.0
186 170.0
187 370.0
188 370.0
189 470.0
190 220.0
191 420.0
192 420.0
193 420.0
194 520.0
195 620.0
196 620.0
197 820.0
198 320.0
199 320.0
200 320.0
201 620.0
202 820.0
203 820.0
204 820.0
205 1020.0
206 1020.0
207 595.0
208 695.0
209 145.0
210 145.0
211 145.0
212 -180.0
213 -505.0
214 -405.0
215 -405.0
216 -405.0
217 -305.0
218 -305.0
219 -1040.0
220 -840.0
221 -1460.0
222 -1260.0
223 -1060.0
224 -1060.0
225 -860.0
226 -860.0
227 -760.0
228 -760.0
229 -760.0
230 -760.0
231 -760.0
232 -560.0
233 -560.0
234 -560.0
235 -460.0
236 -460.0
237 -460.0
238 -460.0
239 -460.0
240 -460.0
241 -460.0
242 -460.0
243 -460.0
244 -460.0
245 -460.0
246 -360.0
247 -360.0
248 -360.0
249 -260.0

model_10
GaussianProcessClassifier(random_state=75)
["B_Women's Strawweight_rank", 'B_Flyweight_rank', 'R_draw', "B_Women's Flyweight_rank", "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'R_win_by_Decision_Majority', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
0

(3722, 23)

(3722,)

(3722, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.739858  0.260142       1
1       -320      250  0.492349  0.507651       1
2        130     -155  0.492719  0.507281       0
3       -155      135  0.498562  0.501438       1
4       -240      195  0.765189  0.234811       0
..       ...      ...       ...       ...     ...
245      175     -230  0.488259  0.511741       0
246      250     -305  0.502303  0.497697       0
247     -134      105  0.516302  0.483698       1
248     -105     -117  0.482736  0.517264       1
249      115     -143  0.268769  0.731231       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 218
          Number of winning bets: 101
          Number of losing bets: 117
          Number of underdog bets: 155
          Number of underdog wins: 58
          Number of underdog losses: 97
          Number of Favorite bets: 62
          Number of favorite wins: 43
          Number of favorite losses: 19
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: -60.57511146606298
          Profit per bet: -0.2778674837892797
          Profit per match: -0.24230044586425192


HI
HI
HI
HI
HI
The original score is 28564.228912972925
Score:  28386.09038483439
Score:  24886.387032465245
Score:  27969.158764827982
Score:  27873.649431700935
Score:  28341.926958311305
Score:  27092.836008378774
Score:  26915.002453624507
Score:  25520.651577954643
NEW BEST FEATURE SET
["B_Women's Strawweight_rank", 'B_Flyweight_rank', 'R_draw', "B_Women's Flyweight_rank", "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
28827.174879514256
Score:  21645.343029417716
Score:  11874.90228853227
Score:  27299.523677486206
Score:  23341.473898779786
Score:  24866.638695553156
Score:  24806.84466987801
Score:  24709.89835048613
Score:  27868.309033393183
Score:  23565.048184421466
Score:  26885.010243100587
Score:  28084.285380695794
Score:  23654.30943576009
Score:  20538.766738654813
Score:  22166.173483597362
The original score is 28827.174879514256
NEW BEST FEATURE SET
['B_Flyweight_rank', 'R_draw', "B_Women's Flyweight_rank", "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
29117.05832939771
Score:  26309.04589454776
Score:  27555.199340490184
Score:  28804.529569274582
Score:  29095.740309205423
Score:  25515.707999796177
Score:  28080.308310821667
Score:  24789.600705369212
Score:  23505.149945060133
Score:  12178.755206260375
Score:  27034.563010729613
Score:  23627.951143296836
Score:  23190.582043059352
Score:  25915.096405257445
Score:  25366.29186522666
Score:  28248.278620155816
Score:  23759.877273846014
Score:  27485.830587261666
Score:  28065.332812803274
Score:  24354.9493831313
Score:  18391.100182206806
Score:  22303.48425523212
The original score is 29117.05832939771
Score:  26921.7698372717
Score:  27491.7494570403
NEW BEST FEATURE SET
['B_Flyweight_rank', 'R_draw', "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
29246.631716913806
Score:  28938.623759088874
Score:  25804.56389421285
Score:  27803.002872939403
Score:  25285.290964766566
Score:  23973.942762598406
Score:  12538.989239961227
Score:  27045.717909635765
Score:  24171.5091322141
Score:  23796.04578983889
Score:  26695.660668580334
Score:  25481.710760057314
Score:  28781.495403372595
Score:  24177.206636567535
Score:  27878.60414703522
Score:  28542.0450309334
Score:  25032.654986445425
Score:  18971.51481446287
Score:  22126.293113040985
The original score is 29246.631716913806
Score:  27829.031901885
Score:  28359.192525158152
NEW BEST FEATURE SET
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
29483.209303185464
Score:  26874.053321507326
Score:  29088.415506904093
Score:  24854.983666890636
Score:  25375.040980064005
Score:  12899.976279023202
Score:  27794.433907711093
Score:  25205.37385650811
Score:  22656.5804691
Score:  27201.112780900374
Score:  25877.65518139564
Score:  29000.97737972629
Score:  24648.42566011852
Score:  28047.178787242312
Score:  28528.780202275164
Score:  26059.679793639123
Score:  19450.102776155753
Score:  24955.27861565756
The original score is 29483.209303185464
Score:  28001.73717840313
Score:  28378.122765180233
Score:  26488.751647242316
Score:  29399.233885707345
Score:  25375.462389013854
Score:  25044.413426770065
Score:  12901.584849561223
Score:  28298.99739000597
Score:  24330.61687035021
Score:  23008.261289306807
Score:  27423.289413231974
Score:  25970.897055814836
NEW BEST FEATURE SET
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
29669.740277006233
Score:  24466.176769459234
Score:  27248.261388639214
Score:  29325.08787924465
Score:  26876.698477409416
Score:  19735.807056738166
Score:  23569.736169524174
The original score is 29669.740277006233
Score:  27821.832416498368
Score:  28045.033832373912
Score:  26446.445611727206
Score:  29481.8166294743
Score:  24718.34612936392
Score:  25146.452273087652
Score:  12137.591204852699
Score:  28353.84082322937
Score:  23383.74873647772
Score:  23758.07000305291
Score:  25054.109551396323
Score:  25956.755559108133
Score:  22535.590949437865
Score:  25785.80012353515
NEW BEST FEATURE SET
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
29740.821291859975
Score:  25334.864800922973
Score:  19221.910474563596
Score:  25104.27257447604
The original score is 29740.821291859975
Score:  26548.501944674626
Score:  28245.245527951796
Score:  28698.133604982468
NEW BEST FEATURE SET
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
30566.5057603141
Score:  26681.502017572995
Score:  24579.824156559247
Score:  11986.678091571157
Score:  25710.6154477156
Score:  21977.16669962645
Score:  21923.611640405674
Score:  24972.316826486865
Score:  26343.581878534424
Score:  24343.470651646152
Score:  24570.791453324135
Score:  25186.194542535784
Score:  18928.688699700586
Score:  21943.990766260165
The original score is 30566.5057603141
Score:  26931.680585704667
Score:  29611.208055600655
Score:  29028.630373177843
Score:  27699.80403500391
Score:  26384.819536705225
Score:  12020.95389536607
Score:  27730.354934307372
Score:  22293.867951898945
Score:  21293.678632215167
Score:  25978.018676902015
Score:  26525.412580257325
Score:  26436.851483087332
Score:  24916.087622468778
Score:  27382.777880228088
Score:  20201.33108043824
Score:  23545.93630845497
The features are different
OLD:
["B_Women's Strawweight_rank", 'B_Flyweight_rank', 'R_draw', "B_Women's Flyweight_rank", "B_Women's Bantamweight_rank", 'B_Bantamweight_rank', "R_Women's Strawweight_rank", 'B_Welterweight_rank', 'R_win_by_Decision_Majority', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_Lightweight_rank', 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
NEW:
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_avg_SUB_ATT', 'R_age', 'loss_dif']

model_10
GaussianProcessClassifier(random_state=75)
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
0

(3722, 16)

(3722,)

(3722, 2)

(250, 16)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.735521  0.264479       1
1       -320      250  0.492471  0.507529       1
2        130     -155  0.492572  0.507428       0
3       -155      135  0.584516  0.415484       1
4       -240      195  0.775634  0.224366       0
..       ...      ...       ...       ...     ...
245      175     -230  0.485552  0.514448       0
246      250     -305  0.420520  0.579480       0
247     -134      105  0.504469  0.495531       1
248     -105     -117  0.704640  0.295360       1
249      115     -143  0.270516  0.729484       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 215
          Number of winning bets: 95
          Number of losing bets: 120
          Number of underdog bets: 147
          Number of underdog wins: 52
          Number of underdog losses: 95
          Number of Favorite bets: 66
          Number of favorite wins: 43
          Number of favorite losses: 23
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -1083.7730489967578
          Profit per bet: -5.040804879054687
          Profit per match: -4.335092195987031


HI
HI
HI
HI
HI
Current best score is: 30566.5057603141
NO IMPROVEMENT
FINAL BEST SCORE: 30566.5057603141

model_10
GaussianProcessClassifier(random_state=75)
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
0

(3722, 16)

(3722,)

(3722, 2)

(250, 16)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.735521  0.264479       1
1       -320      250  0.492471  0.507529       1
2        130     -155  0.492572  0.507428       0
3       -155      135  0.584516  0.415484       1
4       -240      195  0.775634  0.224366       0
..       ...      ...       ...       ...     ...
245      175     -230  0.485552  0.514448       0
246      250     -305  0.420520  0.579480       0
247     -134      105  0.504469  0.495531       1
248     -105     -117  0.704640  0.295360       1
249      115     -143  0.270516  0.729484       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 215
          Number of winning bets: 95
          Number of losing bets: 120
          Number of underdog bets: 147
          Number of underdog wins: 52
          Number of underdog losses: 95
          Number of Favorite bets: 66
          Number of favorite wins: 43
          Number of favorite losses: 23
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -1083.7730489967578
          Profit per bet: -5.040804879054687
          Profit per match: -4.335092195987031


HI
HI
HI
HI
HI
Real output model: GaussianProcessClassifier(random_state=75)

model_10
GaussianProcessClassifier(random_state=75)
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
0

(3722, 16)

(3722,)

(3722, 2)

(250, 16)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.735521  0.264479       1
1       -320      250  0.492471  0.507529       1
2        130     -155  0.492572  0.507428       0
3       -155      135  0.584516  0.415484       1
4       -240      195  0.775634  0.224366       0
..       ...      ...       ...       ...     ...
245      175     -230  0.485552  0.514448       0
246      250     -305  0.420520  0.579480       0
247     -134      105  0.504469  0.495531       1
248     -105     -117  0.704640  0.295360       1
249      115     -143  0.270516  0.729484       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 215
          Number of winning bets: 95
          Number of losing bets: 120
          Number of underdog bets: 147
          Number of underdog wins: 52
          Number of underdog losses: 95
          Number of Favorite bets: 66
          Number of favorite wins: 43
          Number of favorite losses: 23
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -1083.7730489967578
          Profit per bet: -5.040804879054687
          Profit per match: -4.335092195987031


HI
HI
HI
HI
HI
0 30566.5057603141
1 30220.276892414124
2 29409.855359573907
3 26617.64174614763
4 25492.112278976936
5 25183.05439745301
6 25416.806561880563
7 25636.07982262779
8 24973.87006144721
9 23765.483456991507
10 22035.047120071802
11 21235.407414935624
12 21333.438851649436
13 19417.834886676406
14 18448.787336061825
15 15721.129256087082
16 15386.15958199917
17 14761.95945996671
18 15736.93997112063
19 15245.390755080884
20 15703.582073092313
21 15429.020142485606
22 14301.934317761892
23 12778.292855041047
24 12864.946043264084
25 13319.520823322737
26 12051.227362454676
27 12277.807637018821
28 11519.85396428254
29 10999.988351634318
30 11435.739602281204
31 11868.393410558432
32 11278.393410558432
33 10455.346080402911
34 8863.107985164816
35 7959.347258921859
36 6047.831129889601
37 5414.831129889601
38 5080.593034651505
39 4246.6275174101265
40 3141.6275174101265
41 1998.6275174101265
42 1718.6275174101263
43 1571.6275174101265
44 1106.6275174101265
45 1399.7184265010355
46 1598.4761904761908
47 2428.476190476191
48 1382.4761904761908
49 1892.4761904761908
50 1347.4761904761908
51 884.4761904761908
52 809.4761904761908
53 -580.7619047619046
54 -889.7619047619046
55 -1530.0
56 -745.0
57 -1143.0
58 -788.0
59 -1073.0
60 -693.0
61 -903.0
62 -768.0
63 -1973.0
64 -2148.0
65 -3793.0
66 -4803.0
67 -5278.0
68 -5702.0
69 -5791.0
70 -5191.0
71 -5476.0
72 -6679.0
73 -7294.0
74 -7642.0
75 -8197.0
76 -7697.0
77 -7467.0
78 -7022.0
79 -6307.0
80 -5907.0
81 -5207.0
82 -4852.0
83 -5157.0
84 -5387.0
85 -4787.0
86 -5542.0
87 -6367.0
88 -6902.0
89 -6650.0
90 -6425.0
91 -6285.0
92 -6650.0
93 -6250.0
94 -6265.0
95 -6415.0
96 -5815.0
97 -5835.0
98 -5685.0
99 -5625.0
100 -5620.0
101 -5510.0
102 -5210.0
103 -4610.0
104 -4010.0
105 -4200.0
106 -3800.0
107 -3615.0
108 -3665.0
109 -3565.0
110 -3165.0
111 -3145.0
112 -3185.0
113 -3520.0
114 -2820.0
115 -2805.0
116 -2740.0
117 -2865.0
118 -3000.0
119 -2700.0
120 -2500.0
121 -2200.0
122 -2250.0
123 -1750.0
124 -1750.0
125 -2095.0
126 -1895.0
127 -1895.0
128 -1895.0
129 -2250.0
130 -2150.0
131 -1950.0
132 -1650.0
133 -2190.0
134 -2190.0
135 -2090.0
136 -1990.0
137 -2265.0
138 -2575.0
139 -2915.0
140 -2515.0
141 -2215.0
142 -2540.0
143 -2240.0
144 -2140.0
145 -2040.0
146 -1940.0
147 -2165.0
148 -1865.0
149 -1865.0
150 -2180.0
151 -2180.0
152 -2730.0
153 -2630.0
154 -2930.0
155 -2730.0
156 -2730.0
157 -2730.0
158 -2530.0
159 -2230.0
160 -2270.0
161 -2070.0
162 -2070.0
163 -1970.0
164 -1670.0
165 -1670.0
166 -1670.0
167 -1370.0
168 -1170.0
169 -1520.0
170 -1420.0
171 -1320.0
172 -1120.0
173 -920.0
174 -1445.0
175 -1245.0
176 -1145.0
177 -1145.0
178 -1045.0
179 -1045.0
180 -945.0
181 -845.0
182 -1080.0
183 -980.0
184 -880.0
185 -780.0
186 -1130.0
187 -930.0
188 -830.0
189 -730.0
190 -530.0
191 -530.0
192 -530.0
193 -430.0
194 -230.0
195 -230.0
196 -130.0
197 -765.0
198 -765.0
199 -765.0
200 -665.0
201 -665.0
202 -665.0
203 -665.0
204 -1845.0
205 -1645.0
206 -1445.0
207 -1445.0
208 -1245.0
209 -1695.0
210 -1695.0
211 -1595.0
212 -1295.0
213 -1195.0
214 -1095.0
215 -1095.0
216 -995.0
217 -795.0
218 -595.0
219 -595.0
220 -1115.0
221 -1115.0
222 -1115.0
223 -1015.0
224 -1015.0
225 -915.0
226 -915.0
227 -815.0
228 -815.0
229 -815.0
230 -815.0
231 -815.0
232 -815.0
233 -815.0
234 -815.0
235 -815.0
236 -815.0
237 -815.0
238 -815.0
239 -715.0
240 -715.0
241 -715.0
242 -715.0
243 -715.0
244 -715.0
245 -715.0
246 -715.0
247 -715.0
248 -715.0
249 -715.0

model_10
GaussianProcessClassifier(random_state=75)
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
0

(3722, 16)

(3722,)

(3722, 2)

(250, 16)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.735521  0.264479       1
1       -320      250  0.492471  0.507529       1
2        130     -155  0.492572  0.507428       0
3       -155      135  0.584516  0.415484       1
4       -240      195  0.775634  0.224366       0
..       ...      ...       ...       ...     ...
245      175     -230  0.485552  0.514448       0
246      250     -305  0.420520  0.579480       0
247     -134      105  0.504469  0.495531       1
248     -105     -117  0.704640  0.295360       1
249      115     -143  0.270516  0.729484       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 215
          Number of winning bets: 95
          Number of losing bets: 120
          Number of underdog bets: 147
          Number of underdog wins: 52
          Number of underdog losses: 95
          Number of Favorite bets: 66
          Number of favorite wins: 43
          Number of favorite losses: 23
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -1083.7730489967578
          Profit per bet: -5.040804879054687
          Profit per match: -4.335092195987031


HI
HI
HI
HI
HI
The original score is 30566.5057603141
Score:  26931.680585704667
Score:  29611.208055600655
Score:  29028.630373177843
Score:  27699.80403500391
Score:  26384.819536705225
Score:  12020.95389536607
Score:  27730.354934307372
Score:  22293.867951898945
Score:  21293.678632215167
Score:  25978.018676902015
Score:  26525.412580257325
Score:  26436.851483087332
Score:  24916.087622468778
Score:  27382.777880228088
Score:  20201.33108043824
Score:  23545.93630845497

model_10
GaussianProcessClassifier(random_state=75)
['B_Flyweight_rank', 'R_draw', 'B_Bantamweight_rank', 'B_Welterweight_rank', 'B_current_lose_streak', 'R_odds', 'R_win_by_TKO_Doctor_Stoppage', 'B_win_by_Submission', 'B_age', 'R_Middleweight_rank', 'B_Light Heavyweight_rank', 'avg_sub_att_dif', "R_Women's Bantamweight_rank", 'B_avg_SUB_ATT', 'R_age', 'loss_dif']
0

(3722, 16)

(3722,)

(3722, 2)

(250, 16)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.735521  0.264479       1
1       -320      250  0.492471  0.507529       1
2        130     -155  0.492572  0.507428       0
3       -155      135  0.584516  0.415484       1
4       -240      195  0.775634  0.224366       0
..       ...      ...       ...       ...     ...
245      175     -230  0.485552  0.514448       0
246      250     -305  0.420520  0.579480       0
247     -134      105  0.504469  0.495531       1
248     -105     -117  0.704640  0.295360       1
249      115     -143  0.270516  0.729484       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 215
          Number of winning bets: 95
          Number of losing bets: 120
          Number of underdog bets: 147
          Number of underdog wins: 52
          Number of underdog losses: 95
          Number of Favorite bets: 66
          Number of favorite wins: 43
          Number of favorite losses: 23
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -1083.7730489967578
          Profit per bet: -5.040804879054687
          Profit per match: -4.335092195987031


HI
HI
HI
HI
HI

(3722, 16)

(3722,)

(3722, 2)

(250, 16)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.735521  0.264479       1
1       -320      250  0.492471  0.507529       1
2        130     -155  0.492572  0.507428       0
3       -155      135  0.584516  0.415484       1
4       -240      195  0.775634  0.224366       0
..       ...      ...       ...       ...     ...
245      175     -230  0.485552  0.514448       0
246      250     -305  0.420520  0.579480       0
247     -134      105  0.504469  0.495531       1
248     -105     -117  0.704640  0.295360       1
249      115     -143  0.270516  0.729484       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 215
          Number of winning bets: 95
          Number of losing bets: 120
          Number of underdog bets: 147
          Number of underdog wins: 52
          Number of underdog losses: 95
          Number of Favorite bets: 66
          Number of favorite wins: 43
          Number of favorite losses: 23
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -1083.7730489967578
          Profit per bet: -5.040804879054687
          Profit per match: -4.335092195987031


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 11


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_11
AdaBoostClassifier(random_state=75)
['B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_win_by_Decision_Majority', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
249
Current best score is: 2580.0
Feature: no_of_rounds Score: 2680.0
The best feature was no_of_rounds.  It scored 2680.0
Current best score is: 2680.0
Feature: B_Reach_cms Score: 2780.0
The best feature was B_Reach_cms.  It scored 2780.0
Current best score is: 2780.0
NO IMPROVEMENT
FINAL BEST SCORE: 2780.0

model_11
AdaBoostClassifier(random_state=75)
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_win_by_Decision_Majority', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
249

(3611, 20)

(3611,)

(3611, 2)

(250, 20)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.505979  0.494021       1
1       -320      250  0.501406  0.498594       1
2        130     -155  0.500292  0.499708       0
3       -155      135  0.502559  0.497441       1
4       -240      195  0.501406  0.498594       0
..       ...      ...       ...       ...     ...
245      175     -230  0.503301  0.496699       0
246      250     -305  0.503743  0.496257       0
247     -134      105  0.498378  0.501622       1
248     -105     -117  0.502937  0.497063       1
249      115     -143  0.501128  0.498872       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI
Real output model: AdaBoostClassifier(random_state=75)

model_11
AdaBoostClassifier(random_state=75)
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_win_by_Decision_Majority', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
249

(3611, 20)

(3611,)

(3611, 2)

(250, 20)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.505979  0.494021       1
1       -320      250  0.501406  0.498594       1
2        130     -155  0.500292  0.499708       0
3       -155      135  0.502559  0.497441       1
4       -240      195  0.501406  0.498594       0
..       ...      ...       ...       ...     ...
245      175     -230  0.503301  0.496699       0
246      250     -305  0.503743  0.496257       0
247     -134      105  0.498378  0.501622       1
248     -105     -117  0.502937  0.497063       1
249      115     -143  0.501128  0.498872       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI
0 -4268.682196090454
1 -5292.938010043943
2 -5042.938010043943
3 -5355.021343377276
4 -4785.021343377276
5 -4479.021343377276
6 -4038.518518518519
7 -4422.518518518519
8 -3569.5185185185182
9 -4061.5185185185182
10 -2601.5185185185182
11 -3564.5185185185182
12 -3154.518518518518
13 -4129.518518518518
14 -5031.518518518518
15 -5399.518518518518
16 -7032.518518518518
17 -7480.592592592592
18 -8096.592592592592
19 -9304.666666666666
20 -10664.666666666666
21 -11171.666666666666
22 -10564.666666666666
23 -10449.666666666666
24 -10303.0
25 -10648.0
26 -11453.0
27 -11171.0
28 -11671.0
29 -11909.0
30 -13121.0
31 -13335.0
32 -12572.0
33 -13802.0
34 -13420.0
35 -11320.0
36 -11685.0
37 -11323.0
38 -12130.0
39 -12795.0
40 -12327.0
41 -11942.0
42 -12762.0
43 -11560.0
44 -11941.0
45 -10771.0
46 -9511.0
47 -9556.0
48 -9906.0
49 -11194.0
50 -11739.0
51 -10929.0
52 -11679.0
53 -11204.0
54 -9714.0
55 -8274.0
56 -8624.0
57 -8284.0
58 -8294.0
59 -8299.0
60 -8139.0
61 -7894.0
62 -8014.0
63 -7819.0
64 -7469.0
65 -6559.0
66 -6318.0
67 -7178.0
68 -7218.0
69 -7283.0
70 -7518.0
71 -7586.0
72 -7011.0
73 -6721.0
74 -6011.0
75 -5956.0
76 -5959.0
77 -6072.0
78 -6257.0
79 -6087.0
80 -6912.0
81 -7777.0
82 -7042.0
83 -6872.0
84 -7682.0
85 -7862.0
86 -7977.0
87 -7822.0
88 -6822.0
89 -6197.0
90 -6989.0
91 -6574.0
92 -6544.0
93 -7955.0
94 -8115.0
95 -7785.0
96 -7670.0
97 -6850.0
98 -7045.0
99 -7235.0
100 -6435.0
101 -5335.0
102 -5035.0
103 -4735.0
104 -4035.0
105 -4160.0
106 -3955.0
107 -3370.0
108 -2570.0
109 -2010.0
110 -1950.0
111 -2225.0
112 -2825.0
113 -3120.0
114 -2745.0
115 -2045.0
116 -1680.0
117 -1620.0
118 -1255.0
119 -695.0
120 -1280.0
121 -920.0
122 -420.0
123 -1010.0
124 -1610.0
125 -1660.0
126 -1460.0
127 -1115.0
128 -915.0
129 -615.0
130 -670.0
131 -270.0
132 -2260.0
133 -2160.0
134 -1660.0
135 -1560.0
136 -1710.0
137 -985.0
138 -860.0
139 -915.0
140 -995.0
141 -1080.0
142 -980.0
143 -1067.0
144 -767.0
145 -1057.0
146 -757.0
147 -757.0
148 -1057.0
149 -157.0
150 -657.0
151 -757.0
152 -657.0
153 -967.0
154 -867.0
155 -1082.0
156 -782.0
157 -1412.0
158 -1732.0
159 -1032.0
160 -2540.0
161 -1740.0
162 -1240.0
163 -1040.0
164 -965.0
165 -565.0
166 -500.0
167 -1270.0
168 -870.0
169 -670.0
170 -910.0
171 -810.0
172 -810.0
173 -860.0
174 -1560.0
175 -1260.0
176 -860.0
177 -1310.0
178 -1310.0
179 -1670.0
180 -1570.0
181 -1470.0
182 -1270.0
183 -770.0
184 -670.0
185 -370.0
186 -845.0
187 -1020.0
188 -1195.0
189 -1095.0
190 -895.0
191 -795.0
192 -795.0
193 -695.0
194 -1180.0
195 -1180.0
196 -1180.0
197 -1180.0
198 -1080.0
199 -580.0
200 -680.0
201 -580.0
202 -580.0
203 -580.0
204 -480.0
205 -280.0
206 -280.0
207 -280.0
208 -80.0
209 -80.0
210 -305.0
211 -630.0
212 -530.0
213 -430.0
214 -430.0
215 -430.0
216 -330.0
217 -130.0
218 170.0
219 -70.0
220 230.0
221 330.0
222 430.0
223 530.0
224 1030.0
225 480.0
226 580.0
227 780.0
228 980.0
229 1080.0
230 1080.0
231 1080.0
232 1080.0
233 1380.0
234 1580.0
235 1680.0
236 1780.0
237 1880.0
238 1880.0
239 1880.0
240 1980.0
241 1980.0
242 1980.0
243 2080.0
244 2080.0
245 2180.0
246 2280.0
247 2480.0
248 2580.0
249 2780.0

model_11
AdaBoostClassifier(random_state=75)
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_win_by_Decision_Majority', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
249

(3611, 20)

(3611,)

(3611, 2)

(250, 20)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.505979  0.494021       1
1       -320      250  0.501406  0.498594       1
2        130     -155  0.500292  0.499708       0
3       -155      135  0.502559  0.497441       1
4       -240      195  0.501406  0.498594       0
..       ...      ...       ...       ...     ...
245      175     -230  0.503301  0.496699       0
246      250     -305  0.503743  0.496257       0
247     -134      105  0.498378  0.501622       1
248     -105     -117  0.502937  0.497063       1
249      115     -143  0.501128  0.498872       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI
The original score is 2780.0
Score:  2680.0
Score:  2680.0
Score:  2680.0
Score:  2255.0
Score:  2680.0
NEW BEST FEATURE SET
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
2880.0
Score:  -375.0
Score:  2680.0
Score:  2480.0
Score:  2680.0
Score:  2680.0
Score:  2680.0
Score:  2680.0
Score:  2480.0
Score:  2580.0
Score:  2780.0
Score:  2780.0
Score:  2780.0
Score:  2780.0
Score:  1855.0
The original score is 2880.0
Score:  2680.0
Score:  2780.0
Score:  2780.0
Score:  2255.0
Score:  2780.0
Score:  -575.0
Score:  2780.0
Score:  2480.0
Score:  2680.0
Score:  2780.0
Score:  2780.0
Score:  2780.0
Score:  2480.0
Score:  2680.0
Score:  2880.0
Score:  2780.0
Score:  2780.0
Score:  2780.0
Score:  1855.0
The features are different
OLD:
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_win_by_Decision_Majority', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
NEW:
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']

model_11
AdaBoostClassifier(random_state=75)
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
249

(3611, 19)

(3611,)

(3611, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.505779  0.494221       1
1       -320      250  0.501640  0.498360       1
2        130     -155  0.497610  0.502390       0
3       -155      135  0.502359  0.497641       1
4       -240      195  0.501640  0.498360       0
..       ...      ...       ...       ...     ...
245      175     -230  0.503101  0.496899       0
246      250     -305  0.502323  0.497677       0
247     -134      105  0.498612  0.501388       1
248     -105     -117  0.502737  0.497263       1
249      115     -143  0.501362  0.498638       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI
Current best score is: 2880.0
NO IMPROVEMENT
FINAL BEST SCORE: 2880.0

model_11
AdaBoostClassifier(random_state=75)
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
249

(3611, 19)

(3611,)

(3611, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.505779  0.494221       1
1       -320      250  0.501640  0.498360       1
2        130     -155  0.497610  0.502390       0
3       -155      135  0.502359  0.497641       1
4       -240      195  0.501640  0.498360       0
..       ...      ...       ...       ...     ...
245      175     -230  0.503101  0.496899       0
246      250     -305  0.502323  0.497677       0
247     -134      105  0.498612  0.501388       1
248     -105     -117  0.502737  0.497263       1
249      115     -143  0.501362  0.498638       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI
Real output model: AdaBoostClassifier(random_state=75)

model_11
AdaBoostClassifier(random_state=75)
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
249

(3611, 19)

(3611,)

(3611, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.505779  0.494221       1
1       -320      250  0.501640  0.498360       1
2        130     -155  0.497610  0.502390       0
3       -155      135  0.502359  0.497641       1
4       -240      195  0.501640  0.498360       0
..       ...      ...       ...       ...     ...
245      175     -230  0.503101  0.496899       0
246      250     -305  0.502323  0.497677       0
247     -134      105  0.498612  0.501388       1
248     -105     -117  0.502737  0.497263       1
249      115     -143  0.501362  0.498638       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI
0 -4663.682196090454
1 -5487.938010043943
2 -5232.938010043943
3 -5550.021343377276
4 -4980.021343377276
5 -4774.021343377276
6 -4233.518518518519
7 -4717.518518518519
8 -3664.5185185185182
9 -4256.518518518518
10 -2796.5185185185182
11 -3759.5185185185182
12 -3324.518518518518
13 -4551.518518518518
14 -5226.518518518518
15 -5594.518518518518
16 -7227.518518518518
17 -7675.592592592592
18 -8191.592592592592
19 -9499.666666666666
20 -10859.666666666666
21 -11366.666666666666
22 -10759.666666666666
23 -10644.666666666666
24 -10498.0
25 -10843.0
26 -11648.0
27 -11366.0
28 -12021.0
29 -11944.0
30 -13121.0
31 -13170.0
32 -12572.0
33 -13802.0
34 -13420.0
35 -11320.0
36 -11785.0
37 -11423.0
38 -11950.0
39 -12795.0
40 -12427.0
41 -12042.0
42 -12662.0
43 -11760.0
44 -12041.0
45 -10771.0
46 -9511.0
47 -9556.0
48 -9711.0
49 -10994.0
50 -11474.0
51 -10584.0
52 -11779.0
53 -11204.0
54 -9714.0
55 -8274.0
56 -8624.0
57 -8184.0
58 -8194.0
59 -8299.0
60 -8139.0
61 -7894.0
62 -8014.0
63 -7819.0
64 -7569.0
65 -6559.0
66 -6318.0
67 -6943.0
68 -6983.0
69 -7183.0
70 -7518.0
71 -7586.0
72 -7011.0
73 -6721.0
74 -5911.0
75 -5956.0
76 -6209.0
77 -6327.0
78 -6257.0
79 -6447.0
80 -7172.0
81 -7777.0
82 -7042.0
83 -7137.0
84 -7682.0
85 -7862.0
86 -7977.0
87 -7922.0
88 -6922.0
89 -6197.0
90 -6989.0
91 -6574.0
92 -6419.0
93 -7830.0
94 -8215.0
95 -7785.0
96 -7670.0
97 -6850.0
98 -7045.0
99 -7235.0
100 -6435.0
101 -5335.0
102 -5035.0
103 -4735.0
104 -3935.0
105 -4430.0
106 -3955.0
107 -3370.0
108 -2570.0
109 -2010.0
110 -2050.0
111 -2225.0
112 -2825.0
113 -2895.0
114 -2645.0
115 -2045.0
116 -1680.0
117 -1620.0
118 -1255.0
119 -695.0
120 -1280.0
121 -920.0
122 -420.0
123 -1010.0
124 -1510.0
125 -1660.0
126 -1360.0
127 -1015.0
128 -815.0
129 -415.0
130 -570.0
131 -170.0
132 -2160.0
133 -2060.0
134 -1560.0
135 -1460.0
136 -1610.0
137 -885.0
138 -760.0
139 -815.0
140 -895.0
141 -980.0
142 -880.0
143 -967.0
144 -667.0
145 -957.0
146 -657.0
147 -657.0
148 -957.0
149 -57.0
150 -557.0
151 -657.0
152 -557.0
153 -457.0
154 -767.0
155 -982.0
156 -682.0
157 -897.0
158 -1632.0
159 -932.0
160 -2440.0
161 -1640.0
162 -1140.0
163 -940.0
164 -865.0
165 -465.0
166 -400.0
167 -1170.0
168 -770.0
169 -570.0
170 -810.0
171 -710.0
172 -710.0
173 -760.0
174 -1460.0
175 -1160.0
176 -760.0
177 -1210.0
178 -1210.0
179 -1570.0
180 -1470.0
181 -1270.0
182 -1170.0
183 -670.0
184 -570.0
185 -270.0
186 -745.0
187 -920.0
188 -1095.0
189 -995.0
190 -795.0
191 -695.0
192 -695.0
193 -595.0
194 -1080.0
195 -1080.0
196 -1080.0
197 -1080.0
198 -980.0
199 -480.0
200 -580.0
201 -480.0
202 -480.0
203 -480.0
204 -380.0
205 -280.0
206 -280.0
207 -180.0
208 20.0
209 20.0
210 -205.0
211 -530.0
212 -430.0
213 -330.0
214 -330.0
215 -330.0
216 -230.0
217 -30.0
218 270.0
219 30.0
220 330.0
221 430.0
222 530.0
223 630.0
224 1130.0
225 580.0
226 780.0
227 880.0
228 1080.0
229 1180.0
230 1180.0
231 1180.0
232 1180.0
233 1480.0
234 1680.0
235 1780.0
236 1880.0
237 1980.0
238 1980.0
239 1980.0
240 2080.0
241 2080.0
242 2080.0
243 2180.0
244 2180.0
245 2280.0
246 2380.0
247 2580.0
248 2580.0
249 2880.0

model_11
AdaBoostClassifier(random_state=75)
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
249

(3611, 19)

(3611,)

(3611, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.505779  0.494221       1
1       -320      250  0.501640  0.498360       1
2        130     -155  0.497610  0.502390       0
3       -155      135  0.502359  0.497641       1
4       -240      195  0.501640  0.498360       0
..       ...      ...       ...       ...     ...
245      175     -230  0.503101  0.496899       0
246      250     -305  0.502323  0.497677       0
247     -134      105  0.498612  0.501388       1
248     -105     -117  0.502737  0.497263       1
249      115     -143  0.501362  0.498638       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI
The original score is 2880.0
Score:  2680.0
Score:  2780.0
Score:  2780.0
Score:  2255.0
Score:  2780.0
Score:  -575.0
Score:  2780.0
Score:  2480.0
Score:  2680.0
Score:  2780.0
Score:  2780.0
Score:  2780.0
Score:  2480.0
Score:  2680.0
Score:  2880.0
Score:  2780.0
Score:  2780.0
Score:  2780.0
Score:  1855.0

model_11
AdaBoostClassifier(random_state=75)
['B_Reach_cms', 'no_of_rounds', 'B_longest_win_streak', 'total_round_dif', 'R_win_by_Submission', 'B_avg_SUB_ATT', "R_Women's Flyweight_rank", 'R_Light Heavyweight_rank', 'R_Bantamweight_rank', "B_Women's Flyweight_rank", 'B_Flyweight_rank', 'B_current_lose_streak', 'age_dif', 'B_draw', 'B_win_by_TKO_Doctor_Stoppage', 'B_win_by_KO/TKO', 'B_Featherweight_rank', 'B_win_by_Submission', 'R_avg_SUB_ATT']
249

(3611, 19)

(3611,)

(3611, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.505779  0.494221       1
1       -320      250  0.501640  0.498360       1
2        130     -155  0.497610  0.502390       0
3       -155      135  0.502359  0.497641       1
4       -240      195  0.501640  0.498360       0
..       ...      ...       ...       ...     ...
245      175     -230  0.503101  0.496899       0
246      250     -305  0.502323  0.497677       0
247     -134      105  0.498612  0.501388       1
248     -105     -117  0.502737  0.497263       1
249      115     -143  0.501362  0.498638       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI

(3611, 19)

(3611,)

(3611, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.505779  0.494221       1
1       -320      250  0.501640  0.498360       1
2        130     -155  0.497610  0.502390       0
3       -155      135  0.502359  0.497641       1
4       -240      195  0.501640  0.498360       0
..       ...      ...       ...       ...     ...
245      175     -230  0.503101  0.496899       0
246      250     -305  0.502323  0.497677       0
247     -134      105  0.498612  0.501388       1
248     -105     -117  0.502737  0.497263       1
249      115     -143  0.501362  0.498638       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 12


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_12
BaggingClassifier(random_state=75)
["R_Women's Bantamweight_rank", 'lose_streak_dif', 'B_Stance', 'B_wins', 'R_Reach_cms', 'B_match_weightclass_rank', 'B_avg_TD_landed', 'B_Pound-for-Pound_rank', 'B_draw', 'B_Welterweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'country', 'B_avg_TD_pct']
1
Current best score is: -3692.4603840502045
Feature: R_odds Score: 10794.330634366874
Feature: R_win_by_Decision_Unanimous Score: 11677.91805553466
The best feature was R_win_by_Decision_Unanimous.  It scored 11677.91805553466
Current best score is: 11677.91805553466
NO IMPROVEMENT
FINAL BEST SCORE: 11677.91805553466

model_12
BaggingClassifier(random_state=75)
['R_win_by_Decision_Unanimous', "R_Women's Bantamweight_rank", 'lose_streak_dif', 'B_Stance', 'B_wins', 'R_Reach_cms', 'B_match_weightclass_rank', 'B_avg_TD_landed', 'B_Pound-for-Pound_rank', 'B_draw', 'B_Welterweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'country', 'B_avg_TD_pct']
1

(3712, 44)

(3712,)

(3712, 2)

(248, 44)

(248,)

(248, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.7      0.3       1
1       -320      250      0.5      0.5       1
2        130     -155      0.5      0.5       0
3       -155      135      0.9      0.1       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
243      175     -230      0.8      0.2       0
244      250     -305      1.0      0.0       0
245     -134      105      0.9      0.1       1
246     -105     -117      0.7      0.3       1
247      115     -143      0.3      0.7       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 228
          Number of winning bets: 102
          Number of losing bets: 126
          Number of underdog bets: 162
          Number of underdog wins: 60
          Number of underdog losses: 102
          Number of Favorite bets: 63
          Number of favorite wins: 40
          Number of favorite losses: 23
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -228.96248616396798
          Profit per bet: -1.0042214305437192
          Profit per match: -0.9232358313063225


HI
HI
HI
HI
HI


Starting New Run for BaggingClassifier


Previous Best Score: 11677.91805553466
base_estimator:  GaussianNB() bootstrap:  True n_estimators:  10 Score:  3162.476392213942
base_estimator:  GaussianNB() bootstrap:  True n_estimators:  13 Score:  5548.508512392086
base_estimator:  GaussianNB() bootstrap:  True n_estimators:  7 Score:  7099.735723066859
base_estimator:  GaussianNB() bootstrap:  False n_estimators:  10 Score:  5750.5282388751275
base_estimator:  GaussianNB() bootstrap:  False n_estimators:  13 Score:  5750.5282388751275
base_estimator:  GaussianNB() bootstrap:  False n_estimators:  7 Score:  5750.5282388751275
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  True n_estimators:  10 Score:  11677.91805553466
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  True n_estimators:  13 Score:  10107.089215187014
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  True n_estimators:  7 Score:  9467.791268148423
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  False n_estimators:  10 Score:  -14167.419065681956
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  False n_estimators:  13 Score:  -12954.584159389458
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  False n_estimators:  7 Score:  -12753.01384561849
base_estimator:  LogisticRegression(random_state=75) bootstrap:  True n_estimators:  10 Score:  -2919.979928238371
base_estimator:  LogisticRegression(random_state=75) bootstrap:  True n_estimators:  13 Score:  -5224.999768152766
base_estimator:  LogisticRegression(random_state=75) bootstrap:  True n_estimators:  7 Score:  -5571.31409631799
base_estimator:  LogisticRegression(random_state=75) bootstrap:  False n_estimators:  10 Score:  -5783.43343820844
base_estimator:  LogisticRegression(random_state=75) bootstrap:  False n_estimators:  13 Score:  -5783.43343820844
base_estimator:  LogisticRegression(random_state=75) bootstrap:  False n_estimators:  7 Score:  -5783.43343820844
Real output model: BaggingClassifier(random_state=75)

model_12
BaggingClassifier(random_state=75)
['R_win_by_Decision_Unanimous', "R_Women's Bantamweight_rank", 'lose_streak_dif', 'B_Stance', 'B_wins', 'R_Reach_cms', 'B_match_weightclass_rank', 'B_avg_TD_landed', 'B_Pound-for-Pound_rank', 'B_draw', 'B_Welterweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'country', 'B_avg_TD_pct']
1

(3712, 44)

(3712,)

(3712, 2)

(248, 44)

(248,)

(248, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.7      0.3       1
1       -320      250      0.5      0.5       1
2        130     -155      0.5      0.5       0
3       -155      135      0.9      0.1       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
243      175     -230      0.8      0.2       0
244      250     -305      1.0      0.0       0
245     -134      105      0.9      0.1       1
246     -105     -117      0.7      0.3       1
247      115     -143      0.3      0.7       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 228
          Number of winning bets: 102
          Number of losing bets: 126
          Number of underdog bets: 162
          Number of underdog wins: 60
          Number of underdog losses: 102
          Number of Favorite bets: 63
          Number of favorite wins: 40
          Number of favorite losses: 23
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -228.96248616396798
          Profit per bet: -1.0042214305437192
          Profit per match: -0.9232358313063225


HI
HI
HI
HI
HI
0 11866.181104461324
1 11677.91805553466
2 11320.717379144202
3 10947.616655941938
4 11263.42398280658
5 11263.137641518122
6 12276.345342843393
7 11801.259692143087
8 10990.532043311989
9 10967.05451887806
10 11017.331085941449
11 11434.942481977927
12 11407.106307474667
13 9913.406725483155
14 11090.580645156968
15 10752.147842473725
16 11459.244629003526
17 11522.720113742687
18 10244.872673826283
19 10280.424432867745
20 9126.639036349694
21 9033.038867910911
22 8457.707115709602
23 9727.324952703711
24 10129.602904218358
25 9997.679827295284
26 9742.497131994944
27 9553.754639116785
28 8112.67133309677
29 8109.911723528652
30 8764.597713866815
31 9138.169441372045
32 8856.588796210755
33 7675.751703478926
34 6635.550368091149
35 5583.509981912831
36 5249.969074544339
37 4970.597400620778
38 4849.478092917557
39 4278.261876701341
40 4243.039654479118
41 3018.039654479119
42 3792.500378939842
43 4054.300128626952
44 3100.9416282364296
45 3155.3895557878054
46 2889.0259194241694
47 3624.9014468503274
48 2897.7908738075525
49 3112.2424867107775
50 3411.983687538936
51 2254.9836875389356
52 2162.9836875389356
53 1811.3349497068937
54 1081.3349497068943
55 1485.7982701702153
56 622.8055694402881
57 819.6309662656836
58 1370.2471219405127
59 1492.600063116983
60 1967.3883755797144
61 2766.176254367593
62 3126.176254367593
63 2338.676254367593
64 1758.6762543675934
65 39.1601253353349
66 755.8267920020014
67 598.6900398652504
68 1458.6900398652504
69 1733.8024836433613
70 1433.8024836433613
71 623.8024836433613
72 694.1327648729227
73 135.13276487292273
74 135.13276487292273
75 -279.86723512707727
76 -350.3434256032681
77 -1141.1126563724986
78 -1686.1126563724986
79 -1899.8528138528136
80 -1804.8528138528136
81 -1804.8528138528136
82 -1484.8528138528136
83 -1697.8528138528136
84 -2467.8528138528136
85 -2312.8528138528136
86 -2612.8528138528136
87 -2579.8528138528136
88 -2409.8528138528136
89 -2634.8528138528136
90 -2209.8528138528136
91 -2212.7619047619046
92 -2232.7619047619046
93 -2277.7619047619046
94 -1962.7619047619046
95 -1777.7619047619046
96 -678.0
97 -578.0
98 -403.0
99 -203.0
100 1012.0
101 1042.0
102 1142.0
103 1602.0
104 1387.0
105 1272.0
106 1105.0
107 590.0
108 830.0
109 1069.0
110 1419.0
111 1095.0
112 1465.0
113 -176.0
114 -803.0
115 -218.0
116 -988.0
117 -588.0
118 -923.0
119 -996.0
120 -1146.0
121 -1251.0
122 -1675.0
123 -1475.0
124 -935.0
125 -2060.0
126 -1960.0
127 -1860.0
128 -1880.0
129 -1880.0
130 -2140.0
131 -2400.0
132 -2570.0
133 -2735.0
134 -3115.0
135 -2885.0
136 -2880.0
137 -2975.0
138 -2854.0
139 -2819.0
140 -1819.0
141 -1719.0
142 -1532.0
143 -1102.0
144 -1412.0
145 -1312.0
146 -1112.0
147 -1112.0
148 -1232.0
149 -687.0
150 -387.0
151 -1122.0
152 -1182.0
153 -982.0
154 -982.0
155 -2070.0
156 -2155.0
157 -1955.0
158 -2070.0
159 -2855.0
160 -2465.0
161 -2055.0
162 -1955.0
163 -1880.0
164 -1580.0
165 -1710.0
166 -1510.0
167 -1310.0
168 -1145.0
169 -1145.0
170 -1690.0
171 -1690.0
172 -1970.0
173 -1770.0
174 -1770.0
175 -2780.0
176 -2480.0
177 -2652.0
178 -2552.0
179 -2452.0
180 -2252.0
181 -2252.0
182 -2152.0
183 -2052.0
184 -2182.0
185 -1182.0
186 -1182.0
187 -982.0
188 -542.0
189 -542.0
190 -432.0
191 -232.0
192 -32.0
193 168.0
194 268.0
195 268.0
196 368.0
197 568.0
198 668.0
199 668.0
200 268.0
201 368.0
202 -237.0
203 -237.0
204 -317.0
205 -252.0
206 -152.0
207 -152.0
208 -137.0
209 -252.0
210 -152.0
211 -52.0
212 -392.0
213 -392.0
214 -392.0
215 -92.0
216 108.0
217 108.0
218 108.0
219 108.0
220 108.0
221 208.0
222 208.0
223 208.0
224 -52.0
225 248.0
226 248.0
227 248.0
228 548.0
229 548.0
230 748.0
231 748.0
232 848.0
233 1048.0
234 1048.0
235 1248.0
236 1248.0
237 1248.0
238 1348.0
239 1348.0
240 1223.0
241 1223.0
242 1323.0
243 1323.0
244 1323.0
245 1323.0
246 1323.0
247 1323.0
248 1423.0
249 1163.0

model_12
BaggingClassifier(random_state=75)
['R_win_by_Decision_Unanimous', "R_Women's Bantamweight_rank", 'lose_streak_dif', 'B_Stance', 'B_wins', 'R_Reach_cms', 'B_match_weightclass_rank', 'B_avg_TD_landed', 'B_Pound-for-Pound_rank', 'B_draw', 'B_Welterweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'country', 'B_avg_TD_pct']
6

(3712, 44)

(3712,)

(3712, 2)

(248, 44)

(248,)

(248, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.7      0.3       1
1       -320      250      0.5      0.5       1
2        130     -155      0.5      0.5       0
3       -155      135      0.9      0.1       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
243      175     -230      0.8      0.2       0
244      250     -305      1.0      0.0       0
245     -134      105      0.9      0.1       1
246     -105     -117      0.7      0.3       1
247      115     -143      0.3      0.7       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 207
          Number of winning bets: 91
          Number of losing bets: 116
          Number of underdog bets: 150
          Number of underdog wins: 56
          Number of underdog losses: 94
          Number of Favorite bets: 54
          Number of favorite wins: 33
          Number of favorite losses: 21
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -181.06064878406107
          Profit per bet: -0.8746891245606815
          Profit per match: -0.7300832612260527


HI
HI
HI
HI
HI
The original score is 12276.345342843393
Score:  -3190.839191257687
Score:  2011.3171088131783
Score:  10938.129802084266
Score:  2130.7761153979864
Score:  -8901.310683738086
Score:  -2938.7270667013418
Score:  -678.7644411426669
Score:  -2746.6729120147565
Score:  10275.031176584185
Score:  8906.912435765158
Score:  3773.917851777681
Score:  5907.670133371074
Score:  1797.4023618697988
Score:  -1480.8434174091526
The EV is different
OLD:
1
NEW:
6

model_12
BaggingClassifier(random_state=75)
['R_win_by_Decision_Unanimous', "R_Women's Bantamweight_rank", 'lose_streak_dif', 'B_Stance', 'B_wins', 'R_Reach_cms', 'B_match_weightclass_rank', 'B_avg_TD_landed', 'B_Pound-for-Pound_rank', 'B_draw', 'B_Welterweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'country', 'B_avg_TD_pct']
6

(3712, 44)

(3712,)

(3712, 2)

(248, 44)

(248,)

(248, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.7      0.3       1
1       -320      250      0.5      0.5       1
2        130     -155      0.5      0.5       0
3       -155      135      0.9      0.1       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
243      175     -230      0.8      0.2       0
244      250     -305      1.0      0.0       0
245     -134      105      0.9      0.1       1
246     -105     -117      0.7      0.3       1
247      115     -143      0.3      0.7       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 207
          Number of winning bets: 91
          Number of losing bets: 116
          Number of underdog bets: 150
          Number of underdog wins: 56
          Number of underdog losses: 94
          Number of Favorite bets: 54
          Number of favorite wins: 33
          Number of favorite losses: 21
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -181.06064878406107
          Profit per bet: -0.8746891245606815
          Profit per match: -0.7300832612260527


HI
HI
HI
HI
HI
Current best score is: 12276.345342843393
NO IMPROVEMENT
FINAL BEST SCORE: 12276.345342843393

model_12
BaggingClassifier(random_state=75)
['R_win_by_Decision_Unanimous', "R_Women's Bantamweight_rank", 'lose_streak_dif', 'B_Stance', 'B_wins', 'R_Reach_cms', 'B_match_weightclass_rank', 'B_avg_TD_landed', 'B_Pound-for-Pound_rank', 'B_draw', 'B_Welterweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'country', 'B_avg_TD_pct']
6

(3712, 44)

(3712,)

(3712, 2)

(248, 44)

(248,)

(248, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.7      0.3       1
1       -320      250      0.5      0.5       1
2        130     -155      0.5      0.5       0
3       -155      135      0.9      0.1       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
243      175     -230      0.8      0.2       0
244      250     -305      1.0      0.0       0
245     -134      105      0.9      0.1       1
246     -105     -117      0.7      0.3       1
247      115     -143      0.3      0.7       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 207
          Number of winning bets: 91
          Number of losing bets: 116
          Number of underdog bets: 150
          Number of underdog wins: 56
          Number of underdog losses: 94
          Number of Favorite bets: 54
          Number of favorite wins: 33
          Number of favorite losses: 21
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -181.06064878406107
          Profit per bet: -0.8746891245606815
          Profit per match: -0.7300832612260527


HI
HI
HI
HI
HI


Starting New Run for BaggingClassifier


Previous Best Score: 12276.345342843393
base_estimator:  GaussianNB() bootstrap:  True n_estimators:  10 Score:  5192.5360477281065
base_estimator:  GaussianNB() bootstrap:  True n_estimators:  13 Score:  4895.9881087586
base_estimator:  GaussianNB() bootstrap:  True n_estimators:  7 Score:  7895.6983840170315
base_estimator:  GaussianNB() bootstrap:  False n_estimators:  10 Score:  5522.8307591633875
base_estimator:  GaussianNB() bootstrap:  False n_estimators:  13 Score:  5522.8307591633875
base_estimator:  GaussianNB() bootstrap:  False n_estimators:  7 Score:  5522.8307591633875
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  True n_estimators:  10 Score:  12276.345342843393
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  True n_estimators:  13 Score:  10757.057729764128
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  True n_estimators:  7 Score:  10232.398285274665
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  False n_estimators:  10 Score:  -14737.117318930159
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  False n_estimators:  13 Score:  -12219.638387486228
base_estimator:  DecisionTreeClassifier(random_state=75) bootstrap:  False n_estimators:  7 Score:  -12760.652686791373
base_estimator:  LogisticRegression(random_state=75) bootstrap:  True n_estimators:  10 Score:  -2170.577161848476
base_estimator:  LogisticRegression(random_state=75) bootstrap:  True n_estimators:  13 Score:  -2869.718406253148
base_estimator:  LogisticRegression(random_state=75) bootstrap:  True n_estimators:  7 Score:  -1426.8849743654127
base_estimator:  LogisticRegression(random_state=75) bootstrap:  False n_estimators:  10 Score:  -2626.2374949793284
base_estimator:  LogisticRegression(random_state=75) bootstrap:  False n_estimators:  13 Score:  -2626.2374949793284
base_estimator:  LogisticRegression(random_state=75) bootstrap:  False n_estimators:  7 Score:  -2626.2374949793284
Real output model: BaggingClassifier(random_state=75)

model_12
BaggingClassifier(random_state=75)
['R_win_by_Decision_Unanimous', "R_Women's Bantamweight_rank", 'lose_streak_dif', 'B_Stance', 'B_wins', 'R_Reach_cms', 'B_match_weightclass_rank', 'B_avg_TD_landed', 'B_Pound-for-Pound_rank', 'B_draw', 'B_Welterweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'country', 'B_avg_TD_pct']
6

(3712, 44)

(3712,)

(3712, 2)

(248, 44)

(248,)

(248, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.7      0.3       1
1       -320      250      0.5      0.5       1
2        130     -155      0.5      0.5       0
3       -155      135      0.9      0.1       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
243      175     -230      0.8      0.2       0
244      250     -305      1.0      0.0       0
245     -134      105      0.9      0.1       1
246     -105     -117      0.7      0.3       1
247      115     -143      0.3      0.7       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 207
          Number of winning bets: 91
          Number of losing bets: 116
          Number of underdog bets: 150
          Number of underdog wins: 56
          Number of underdog losses: 94
          Number of Favorite bets: 54
          Number of favorite wins: 33
          Number of favorite losses: 21
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -181.06064878406107
          Profit per bet: -0.8746891245606815
          Profit per match: -0.7300832612260527


HI
HI
HI
HI
HI
0 11866.181104461324
1 11677.91805553466
2 11320.717379144202
3 10947.616655941938
4 11263.42398280658
5 11263.137641518122
6 12276.345342843393
7 11801.259692143087
8 10990.532043311989
9 10967.05451887806
10 11017.331085941449
11 11434.942481977927
12 11407.106307474667
13 9913.406725483155
14 11090.580645156968
15 10752.147842473725
16 11459.244629003526
17 11522.720113742687
18 10244.872673826283
19 10280.424432867745
20 9126.639036349694
21 9033.038867910911
22 8457.707115709602
23 9727.324952703711
24 10129.602904218358
25 9997.679827295284
26 9742.497131994944
27 9553.754639116785
28 8112.67133309677
29 8109.911723528652
30 8764.597713866815
31 9138.169441372045
32 8856.588796210755
33 7675.751703478926
34 6635.550368091149
35 5583.509981912831
36 5249.969074544339
37 4970.597400620778
38 4849.478092917557
39 4278.261876701341
40 4243.039654479118
41 3018.039654479119
42 3792.500378939842
43 4054.300128626952
44 3100.9416282364296
45 3155.3895557878054
46 2889.0259194241694
47 3624.9014468503274
48 2897.7908738075525
49 3112.2424867107775
50 3411.983687538936
51 2254.9836875389356
52 2162.9836875389356
53 1811.3349497068937
54 1081.3349497068943
55 1485.7982701702153
56 622.8055694402881
57 819.6309662656836
58 1370.2471219405127
59 1492.600063116983
60 1967.3883755797144
61 2766.176254367593
62 3126.176254367593
63 2338.676254367593
64 1758.6762543675934
65 39.1601253353349
66 755.8267920020014
67 598.6900398652504
68 1458.6900398652504
69 1733.8024836433613
70 1433.8024836433613
71 623.8024836433613
72 694.1327648729227
73 135.13276487292273
74 135.13276487292273
75 -279.86723512707727
76 -350.3434256032681
77 -1141.1126563724986
78 -1686.1126563724986
79 -1899.8528138528136
80 -1804.8528138528136
81 -1804.8528138528136
82 -1484.8528138528136
83 -1697.8528138528136
84 -2467.8528138528136
85 -2312.8528138528136
86 -2612.8528138528136
87 -2579.8528138528136
88 -2409.8528138528136
89 -2634.8528138528136
90 -2209.8528138528136
91 -2212.7619047619046
92 -2232.7619047619046
93 -2277.7619047619046
94 -1962.7619047619046
95 -1777.7619047619046
96 -678.0
97 -578.0
98 -403.0
99 -203.0
100 1012.0
101 1042.0
102 1142.0
103 1602.0
104 1387.0
105 1272.0
106 1105.0
107 590.0
108 830.0
109 1069.0
110 1419.0
111 1095.0
112 1465.0
113 -176.0
114 -803.0
115 -218.0
116 -988.0
117 -588.0
118 -923.0
119 -996.0
120 -1146.0
121 -1251.0
122 -1675.0
123 -1475.0
124 -935.0
125 -2060.0
126 -1960.0
127 -1860.0
128 -1880.0
129 -1880.0
130 -2140.0
131 -2400.0
132 -2570.0
133 -2735.0
134 -3115.0
135 -2885.0
136 -2880.0
137 -2975.0
138 -2854.0
139 -2819.0
140 -1819.0
141 -1719.0
142 -1532.0
143 -1102.0
144 -1412.0
145 -1312.0
146 -1112.0
147 -1112.0
148 -1232.0
149 -687.0
150 -387.0
151 -1122.0
152 -1182.0
153 -982.0
154 -982.0
155 -2070.0
156 -2155.0
157 -1955.0
158 -2070.0
159 -2855.0
160 -2465.0
161 -2055.0
162 -1955.0
163 -1880.0
164 -1580.0
165 -1710.0
166 -1510.0
167 -1310.0
168 -1145.0
169 -1145.0
170 -1690.0
171 -1690.0
172 -1970.0
173 -1770.0
174 -1770.0
175 -2780.0
176 -2480.0
177 -2652.0
178 -2552.0
179 -2452.0
180 -2252.0
181 -2252.0
182 -2152.0
183 -2052.0
184 -2182.0
185 -1182.0
186 -1182.0
187 -982.0
188 -542.0
189 -542.0
190 -432.0
191 -232.0
192 -32.0
193 168.0
194 268.0
195 268.0
196 368.0
197 568.0
198 668.0
199 668.0
200 268.0
201 368.0
202 -237.0
203 -237.0
204 -317.0
205 -252.0
206 -152.0
207 -152.0
208 -137.0
209 -252.0
210 -152.0
211 -52.0
212 -392.0
213 -392.0
214 -392.0
215 -92.0
216 108.0
217 108.0
218 108.0
219 108.0
220 108.0
221 208.0
222 208.0
223 208.0
224 -52.0
225 248.0
226 248.0
227 248.0
228 548.0
229 548.0
230 748.0
231 748.0
232 848.0
233 1048.0
234 1048.0
235 1248.0
236 1248.0
237 1248.0
238 1348.0
239 1348.0
240 1223.0
241 1223.0
242 1323.0
243 1323.0
244 1323.0
245 1323.0
246 1323.0
247 1323.0
248 1423.0
249 1163.0

model_12
BaggingClassifier(random_state=75)
['R_win_by_Decision_Unanimous', "R_Women's Bantamweight_rank", 'lose_streak_dif', 'B_Stance', 'B_wins', 'R_Reach_cms', 'B_match_weightclass_rank', 'B_avg_TD_landed', 'B_Pound-for-Pound_rank', 'B_draw', 'B_Welterweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'country', 'B_avg_TD_pct']
6

(3712, 44)

(3712,)

(3712, 2)

(248, 44)

(248,)

(248, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.7      0.3       1
1       -320      250      0.5      0.5       1
2        130     -155      0.5      0.5       0
3       -155      135      0.9      0.1       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
243      175     -230      0.8      0.2       0
244      250     -305      1.0      0.0       0
245     -134      105      0.9      0.1       1
246     -105     -117      0.7      0.3       1
247      115     -143      0.3      0.7       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 207
          Number of winning bets: 91
          Number of losing bets: 116
          Number of underdog bets: 150
          Number of underdog wins: 56
          Number of underdog losses: 94
          Number of Favorite bets: 54
          Number of favorite wins: 33
          Number of favorite losses: 21
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -181.06064878406107
          Profit per bet: -0.8746891245606815
          Profit per match: -0.7300832612260527


HI
HI
HI
HI
HI
The original score is 12276.345342843393
Score:  -3190.839191257687
Score:  2011.3171088131783
Score:  10938.129802084266
Score:  2130.7761153979864
Score:  -8901.310683738086
Score:  -2938.7270667013418
Score:  -678.7644411426669
Score:  -2746.6729120147565
Score:  10275.031176584185
Score:  8906.912435765158
Score:  3773.917851777681
Score:  5907.670133371074
Score:  1797.4023618697988
Score:  -1480.8434174091526

model_12
BaggingClassifier(random_state=75)
['R_win_by_Decision_Unanimous', "R_Women's Bantamweight_rank", 'lose_streak_dif', 'B_Stance', 'B_wins', 'R_Reach_cms', 'B_match_weightclass_rank', 'B_avg_TD_landed', 'B_Pound-for-Pound_rank', 'B_draw', 'B_Welterweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'country', 'B_avg_TD_pct']
6

(3712, 44)

(3712,)

(3712, 2)

(248, 44)

(248,)

(248, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.7      0.3       1
1       -320      250      0.5      0.5       1
2        130     -155      0.5      0.5       0
3       -155      135      0.9      0.1       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
243      175     -230      0.8      0.2       0
244      250     -305      1.0      0.0       0
245     -134      105      0.9      0.1       1
246     -105     -117      0.7      0.3       1
247      115     -143      0.3      0.7       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 207
          Number of winning bets: 91
          Number of losing bets: 116
          Number of underdog bets: 150
          Number of underdog wins: 56
          Number of underdog losses: 94
          Number of Favorite bets: 54
          Number of favorite wins: 33
          Number of favorite losses: 21
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -181.06064878406107
          Profit per bet: -0.8746891245606815
          Profit per match: -0.7300832612260527


HI
HI
HI
HI
HI

(3712, 44)

(3712,)

(3712, 2)

(248, 44)

(248,)

(248, 2)

     t1_odds  t2_odds  t1_prob  t2_prob  winner
0       -210      175      0.7      0.3       1
1       -320      250      0.5      0.5       1
2        130     -155      0.5      0.5       0
3       -155      135      0.9      0.1       1
4       -240      195      0.8      0.2       0
..       ...      ...      ...      ...     ...
243      175     -230      0.8      0.2       0
244      250     -305      1.0      0.0       0
245     -134      105      0.9      0.1       1
246     -105     -117      0.7      0.3       1
247      115     -143      0.3      0.7       1

[248 rows x 5 columns]

          Number of matches: 248
          Number of bets: 207
          Number of winning bets: 91
          Number of losing bets: 116
          Number of underdog bets: 150
          Number of underdog wins: 56
          Number of underdog losses: 94
          Number of Favorite bets: 54
          Number of favorite wins: 33
          Number of favorite losses: 21
          Number of even bets: 3
          Number of even wins: 2
          Number of even losses: 1
          Profit: -181.06064878406107
          Profit per bet: -0.8746891245606815
          Profit per match: -0.7300832612260527


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 13


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_13
BernoulliNB()
['B_Middleweight_rank', 'B_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
0
Current best score is: 17931.296345684932
Feature: weight_class Score: 18808.25860759699
Feature: gender Score: 19345.562345365786
Feature: B_avg_TD_landed Score: 19556.43454506567
Feature: B_Stance Score: 20915.165090201586
Feature: R_win_by_Decision_Split Score: 21276.93402849297
The best feature was R_win_by_Decision_Split.  It scored 21276.93402849297
Current best score is: 21276.93402849297
Feature: R_draw Score: 21871.432754651476
The best feature was R_draw.  It scored 21871.432754651476
Current best score is: 21871.432754651476
Feature: R_win_by_Decision_Unanimous Score: 21950.202553033236
Feature: B_Women's Strawweight_rank Score: 22069.442484412775
The best feature was B_Women's Strawweight_rank.  It scored 22069.442484412775
Current best score is: 22069.442484412775
Feature: R_Women's Featherweight_rank Score: 22087.68792543838
Feature: B_Women's Featherweight_rank Score: 22169.442484412775
The best feature was B_Women's Featherweight_rank.  It scored 22169.442484412775
Current best score is: 22169.442484412775
NO IMPROVEMENT
FINAL BEST SCORE: 22169.442484412775

model_13
BernoulliNB()
["B_Women's Featherweight_rank", "B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'B_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
0

(3601, 20)

(3601,)

(3601, 2)

(250, 20)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764997  0.235003       1
1       -320      250  0.815715  0.184285       1
2        130     -155  0.471190  0.528810       0
3       -155      135  0.571893  0.428107       1
4       -240      195  0.782745  0.217255       0
..       ...      ...       ...       ...     ...
245      175     -230  0.505148  0.494852       0
246      250     -305  0.639713  0.360287       0
247     -134      105  0.407067  0.592933       1
248     -105     -117  0.345394  0.654606       1
249      115     -143  0.517373  0.482627       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 218
          Number of winning bets: 92
          Number of losing bets: 126
          Number of underdog bets: 138
          Number of underdog wins: 48
          Number of underdog losses: 90
          Number of Favorite bets: 78
          Number of favorite wins: 44
          Number of favorite losses: 34
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -3073.5826279676044
          Profit per bet: -14.099002880585342
          Profit per match: -12.294330511870417


HI
HI
HI
HI
HI
Real output model: BernoulliNB()

model_13
BernoulliNB()
["B_Women's Featherweight_rank", "B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'B_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
0

(3601, 20)

(3601,)

(3601, 2)

(250, 20)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764997  0.235003       1
1       -320      250  0.815715  0.184285       1
2        130     -155  0.471190  0.528810       0
3       -155      135  0.571893  0.428107       1
4       -240      195  0.782745  0.217255       0
..       ...      ...       ...       ...     ...
245      175     -230  0.505148  0.494852       0
246      250     -305  0.639713  0.360287       0
247     -134      105  0.407067  0.592933       1
248     -105     -117  0.345394  0.654606       1
249      115     -143  0.517373  0.482627       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 218
          Number of winning bets: 92
          Number of losing bets: 126
          Number of underdog bets: 138
          Number of underdog wins: 48
          Number of underdog losses: 90
          Number of Favorite bets: 78
          Number of favorite wins: 44
          Number of favorite losses: 34
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -3073.5826279676044
          Profit per bet: -14.099002880585342
          Profit per match: -12.294330511870417


HI
HI
HI
HI
HI
0 22169.442484412775
1 22049.27371795368
2 21011.41702008055
3 18194.991670935753
4 16723.235873067435
5 18345.43847755129
6 16689.79467033648
7 15725.838893285938
8 15078.366340161914
9 15755.964148816223
10 16019.286660890266
11 14762.934866405854
12 15188.42650104424
13 13421.565992201002
14 11162.442438240152
15 11915.527132454972
16 12889.647241638511
17 12305.94668712837
18 12424.334430092302
19 13955.250106622032
20 14399.56292364832
21 15034.422610702517
22 14314.079554107499
23 14609.51683429282
24 14355.407563045022
25 13452.965310820164
26 13879.122264258336
27 14369.833549937013
28 14860.309410412874
29 14249.038770043837
30 13178.526684443026
31 12156.704550055674
32 10842.412400763526
33 10026.269543620669
34 8551.031448382573
35 7834.851673101673
36 8153.238095238095
37 7183.238095238095
38 7433.238095238095
39 6458.238095238095
40 7363.238095238095
41 5880.238095238095
42 4680.238095238095
43 3750.2380952380954
44 3582.0
45 3712.0
46 3697.0
47 2832.0
48 2175.0
49 2955.0
50 3430.0
51 3225.0
52 2976.0
53 3436.0
54 3866.0
55 3928.0
56 3610.0
57 3965.0
58 4390.0
59 4780.0
60 5305.0
61 5735.0
62 5455.0
63 5685.0
64 5905.0
65 5601.0
66 5931.0
67 6176.0
68 6676.0
69 6066.0
70 5636.0
71 5826.0
72 4371.0
73 4246.0
74 4411.0
75 5181.0
76 4956.0
77 4031.0
78 3496.0
79 3196.0
80 3438.0
81 3283.0
82 3123.0
83 2808.0
84 2553.0
85 2318.0
86 2518.0
87 2618.0
88 1473.0
89 1348.0
90 1548.0
91 1256.0
92 1556.0
93 806.0
94 1006.0
95 1206.0
96 1406.0
97 1516.0
98 1038.0
99 498.0
100 -70.0
101 230.0
102 330.0
103 150.0
104 250.0
105 -305.0
106 -205.0
107 95.0
108 295.0
109 395.0
110 230.0
111 370.0
112 370.0
113 470.0
114 -75.0
115 -75.0
116 -300.0
117 -300.0
118 -200.0
119 -100.0
120 0.0
121 300.0
122 -435.0
123 -35.0
124 265.0
125 -110.0
126 -485.0
127 -1300.0
128 -1100.0
129 -1345.0
130 -1345.0
131 -1660.0
132 -1560.0
133 -1915.0
134 -1815.0
135 -2165.0
136 -2165.0
137 -2165.0
138 -2165.0
139 -2065.0
140 -1865.0
141 -1765.0
142 -1765.0
143 -1765.0
144 -1565.0
145 -1465.0
146 -1465.0
147 -1465.0
148 -1465.0
149 -1465.0
150 -1465.0
151 -1465.0
152 -1365.0
153 -1365.0
154 -1365.0
155 -1265.0
156 -1065.0
157 -965.0
158 -865.0
159 -865.0
160 -865.0
161 -1250.0
162 -1250.0
163 -1150.0
164 -1150.0
165 -1050.0
166 -950.0
167 -950.0
168 -950.0
169 -950.0
170 -850.0
171 -850.0
172 -750.0
173 -750.0
174 -650.0
175 -550.0
176 -900
177 -800
178 -800
179 -800
180 -800
181 -800
182 -800
183 -700
184 -700
185 -700
186 -700
187 -700
188 -700
189 -700
190 -700
191 -700
192 -600
193 -600
194 -600
195 -600
196 -600
197 -600
198 -600
199 -600
200 -600
201 -600
202 -600
203 -600
204 -600
205 -600
206 -600
207 -500
208 -400
209 -400
210 -400
211 -400
212 -400
213 -400
214 -400
215 -400
216 -400
217 -400
218 -400
219 -400
220 -400
221 -400
222 -400
223 -400
224 -400
225 -400
226 -400
227 -400
228 -400
229 -300
230 -300
231 -300
232 -300
233 -300
234 -300
235 -300
236 -200
237 -200
238 -200
239 -200
240 -200
241 -200
242 -200
243 -200
244 -200
245 -200
246 -100
247 -100
248 -100
249 -100

model_13
BernoulliNB()
["B_Women's Featherweight_rank", "B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'B_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
0

(3601, 20)

(3601,)

(3601, 2)

(250, 20)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.764997  0.235003       1
1       -320      250  0.815715  0.184285       1
2        130     -155  0.471190  0.528810       0
3       -155      135  0.571893  0.428107       1
4       -240      195  0.782745  0.217255       0
..       ...      ...       ...       ...     ...
245      175     -230  0.505148  0.494852       0
246      250     -305  0.639713  0.360287       0
247     -134      105  0.407067  0.592933       1
248     -105     -117  0.345394  0.654606       1
249      115     -143  0.517373  0.482627       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 218
          Number of winning bets: 92
          Number of losing bets: 126
          Number of underdog bets: 138
          Number of underdog wins: 48
          Number of underdog losses: 90
          Number of Favorite bets: 78
          Number of favorite wins: 44
          Number of favorite losses: 34
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -3073.5826279676044
          Profit per bet: -14.099002880585342
          Profit per match: -12.294330511870417


HI
HI
HI
HI
HI
The original score is 22169.442484412775
Score:  22069.442484412775
Score:  21871.432754651476
Score:  21461.048799465694
Score:  18201.86698238903
Score:  21538.92873507522
NEW BEST FEATURE SET
["B_Women's Featherweight_rank", "B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
22427.85408688074
Score:  19697.9071631618
Score:  19119.36033132369
Score:  21116.070188264723
Score:  21850.932326750564
Score:  18248.598541316645
Score:  13084.954010033094
Score:  20422.82254009908
Score:  19845.464867143786
Score:  18746.190252162203
Score:  12637.776537604352
Score:  -3284.6029914283863
The original score is 22427.85408688074
NEW BEST FEATURE SET
["B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
22437.85408688074
Score:  21840.35408688074
Score:  22181.8336215918
Score:  18921.540603537465
Score:  22013.199986454
Score:  21286.77138561355
Score:  18990.29514388075
Score:  20550.71917035032
Score:  21637.749166616413
Score:  18953.42206196297
Score:  13974.19897351514
Score:  20421.844832556028
Score:  21076.039046305505
Score:  18871.90267288977
Score:  12310.791104307062
Score:  -2465.560245972958
The original score is 22437.85408688074
Score:  22002.85408688074
Score:  22191.833621591803
Score:  18743.540603537465
Score:  22213.199986454
Score:  21286.77138561355
Score:  18990.29514388075
Score:  20450.71917035032
Score:  21737.749166616413
Score:  18649.598532551205
Score:  13974.19897351514
Score:  20421.844832556028
Score:  21115.067823283924
Score:  18871.90267288977
Score:  12310.791104307062
Score:  -2465.560245972958
The features are different
OLD:
["B_Women's Featherweight_rank", "B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'B_win_by_Decision_Majority', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
NEW:
["B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']

model_13
BernoulliNB()
["B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
0

(3601, 18)

(3601,)

(3601, 2)

(250, 18)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.765560  0.234440       1
1       -320      250  0.816187  0.183813       1
2        130     -155  0.471972  0.528028       0
3       -155      135  0.572661  0.427339       1
4       -240      195  0.783278  0.216722       0
..       ...      ...       ...       ...     ...
245      175     -230  0.505932  0.494068       0
246      250     -305  0.593909  0.406091       0
247     -134      105  0.407824  0.592176       1
248     -105     -117  0.346104  0.653896       1
249      115     -143  0.518156  0.481844       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 219
          Number of winning bets: 92
          Number of losing bets: 127
          Number of underdog bets: 139
          Number of underdog wins: 48
          Number of underdog losses: 91
          Number of Favorite bets: 78
          Number of favorite wins: 44
          Number of favorite losses: 34
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: -3173.5826279676044
          Profit per bet: -14.491244876564403
          Profit per match: -12.694330511870417


HI
HI
HI
HI
HI
Current best score is: 22437.85408688074
Feature: B_win_by_TKO_Doctor_Stoppage Score: 22593.204563895215
Feature: R_Women's Flyweight_rank Score: 22594.733492969364
Feature: R_Women's Featherweight_rank Score: 22757.682706632375
Feature: B_Women's Flyweight_rank Score: 22858.69901021074
The best feature was B_Women's Flyweight_rank.  It scored 22858.69901021074
Current best score is: 22858.69901021074
NO IMPROVEMENT
FINAL BEST SCORE: 22858.69901021074

model_13
BernoulliNB()
["B_Women's Flyweight_rank", "B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
0

(3601, 19)

(3601,)

(3601, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.765109  0.234891       1
1       -320      250  0.815809  0.184191       1
2        130     -155  0.471345  0.528655       0
3       -155      135  0.637509  0.362491       1
4       -240      195  0.782851  0.217149       0
..       ...      ...       ...       ...     ...
245      175     -230  0.505303  0.494697       0
246      250     -305  0.593302  0.406698       0
247     -134      105  0.407217  0.592783       1
248     -105     -117  0.409905  0.590095       1
249      115     -143  0.517528  0.482472       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 220
          Number of winning bets: 93
          Number of losing bets: 127
          Number of underdog bets: 139
          Number of underdog wins: 49
          Number of underdog losses: 90
          Number of Favorite bets: 78
          Number of favorite wins: 44
          Number of favorite losses: 34
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -3091.5826279676044
          Profit per bet: -14.052648308943656
          Profit per match: -12.366330511870418


HI
HI
HI
HI
HI
Real output model: BernoulliNB()

model_13
BernoulliNB()
["B_Women's Flyweight_rank", "B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
0

(3601, 19)

(3601,)

(3601, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.765109  0.234891       1
1       -320      250  0.815809  0.184191       1
2        130     -155  0.471345  0.528655       0
3       -155      135  0.637509  0.362491       1
4       -240      195  0.782851  0.217149       0
..       ...      ...       ...       ...     ...
245      175     -230  0.505303  0.494697       0
246      250     -305  0.593302  0.406698       0
247     -134      105  0.407217  0.592783       1
248     -105     -117  0.409905  0.590095       1
249      115     -143  0.517528  0.482472       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 220
          Number of winning bets: 93
          Number of losing bets: 127
          Number of underdog bets: 139
          Number of underdog wins: 49
          Number of underdog losses: 90
          Number of Favorite bets: 78
          Number of favorite wins: 44
          Number of favorite losses: 34
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -3091.5826279676044
          Profit per bet: -14.052648308943656
          Profit per match: -12.366330511870418


HI
HI
HI
HI
HI
0 22858.69901021074
1 22364.707097426086
2 20320.34513433718
3 18430.355595990728
4 16868.08150695209
5 18272.766984027185
6 17266.77982629261
7 15593.01621840163
8 14856.344111561915
9 15053.098369236335
10 16045.472102420421
11 14081.801224727864
12 14530.590867889847
13 13529.5369460317
14 11394.312288112971
15 12653.993424275359
16 13890.505186749431
17 12520.37442628963
18 12613.82160957948
19 14298.77237382851
20 15253.262224347623
21 15549.499533779439
22 14787.15647718442
23 14937.355662131646
24 14801.527964382816
25 13957.019364874217
26 14246.344486480559
27 14255.86496596843
28 15071.810911914376
29 14789.984715989784
30 13969.472630388973
31 12324.650496001621
32 10507.412400763526
33 9081.031448382573
34 8421.031448382573
35 8059.613577863578
36 7733.238095238095
37 7233.238095238095
38 7338.238095238095
39 6748.238095238095
40 7283.238095238095
41 6550.238095238095
42 5365.238095238095
43 4372.238095238095
44 4862.0
45 4597.0
46 4682.0
47 3582.0
48 2825.0
49 3420.0
50 4050.0
51 3945.0
52 3546.0
53 4161.0
54 4391.0
55 4093.0
56 4035.0
57 4390.0
58 4715.0
59 5305.0
60 5060.0
61 5890.0
62 5255.0
63 5175.0
64 5531.0
65 5191.0
66 5721.0
67 5866.0
68 6466.0
69 5756.0
70 5426.0
71 5166.0
72 4261.0
73 4456.0
74 4301.0
75 4971.0
76 5371.0
77 4271.0
78 3636.0
79 3296.0
80 3438.0
81 3283.0
82 3023.0
83 2808.0
84 2218.0
85 2318.0
86 2518.0
87 2618.0
88 1473.0
89 1448.0
90 1271.0
91 1356.0
92 1556.0
93 806.0
94 1006.0
95 1106.0
96 1406.0
97 1616.0
98 1138.0
99 598.0
100 130.0
101 230.0
102 330.0
103 250.0
104 450.0
105 65.0
106 -205.0
107 295.0
108 495.0
109 595.0
110 430.0
111 570.0
112 570.0
113 670.0
114 125.0
115 125.0
116 225.0
117 -100.0
118 0.0
119 0.0
120 200.0
121 400.0
122 -235.0
123 65.0
124 465.0
125 90.0
126 -285.0
127 -1100.0
128 -1100.0
129 -1245.0
130 -1145.0
131 -1560.0
132 -1460.0
133 -1160.0
134 -1160.0
135 -1410.0
136 -1410.0
137 -1410.0
138 -1410.0
139 -1310.0
140 -1210.0
141 -1210.0
142 -1110.0
143 -1010.0
144 -910.0
145 -910.0
146 -810.0
147 -810.0
148 -810.0
149 -810.0
150 -810.0
151 -810.0
152 -710.0
153 -710.0
154 -710.0
155 -510.0
156 -410.0
157 -410.0
158 -210.0
159 -210.0
160 -210.0
161 -595.0
162 -495.0
163 -495.0
164 -495.0
165 -495.0
166 -295.0
167 -295.0
168 -295.0
169 -295.0
170 -195.0
171 -195.0
172 -95.0
173 -95.0
174 5.0
175 105.0
176 -345.0
177 -145.0
178 -145.0
179 -145.0
180 -145.0
181 -145.0
182 -145.0
183 -45.0
184 -45.0
185 -45.0
186 -45.0
187 -45.0
188 -45.0
189 -45.0
190 -45.0
191 -45.0
192 55.0
193 55.0
194 55.0
195 55.0
196 55.0
197 55.0
198 55.0
199 55.0
200 55.0
201 -600
202 -600
203 -600
204 -600
205 -600
206 -600
207 -600
208 -400
209 -400
210 -400
211 -400
212 -400
213 -400
214 -400
215 -400
216 -400
217 -400
218 -400
219 -400
220 -400
221 -400
222 -400
223 -400
224 -400
225 -400
226 -400
227 -400
228 -400
229 -300
230 -300
231 -300
232 -300
233 -300
234 -300
235 -300
236 -200
237 -200
238 -200
239 -200
240 -200
241 -200
242 -200
243 -200
244 -200
245 -200
246 -100
247 -100
248 -100
249 -100

model_13
BernoulliNB()
["B_Women's Flyweight_rank", "B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
0

(3601, 19)

(3601,)

(3601, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.765109  0.234891       1
1       -320      250  0.815809  0.184191       1
2        130     -155  0.471345  0.528655       0
3       -155      135  0.637509  0.362491       1
4       -240      195  0.782851  0.217149       0
..       ...      ...       ...       ...     ...
245      175     -230  0.505303  0.494697       0
246      250     -305  0.593302  0.406698       0
247     -134      105  0.407217  0.592783       1
248     -105     -117  0.409905  0.590095       1
249      115     -143  0.517528  0.482472       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 220
          Number of winning bets: 93
          Number of losing bets: 127
          Number of underdog bets: 139
          Number of underdog wins: 49
          Number of underdog losses: 90
          Number of Favorite bets: 78
          Number of favorite wins: 44
          Number of favorite losses: 34
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -3091.5826279676044
          Profit per bet: -14.052648308943656
          Profit per match: -12.366330511870418


HI
HI
HI
HI
HI
The original score is 22858.69901021074
Score:  22437.85408688074
Score:  22199.007548265294
Score:  22328.474339348166
Score:  18942.867072441986
Score:  22448.65656989244
Score:  21122.237493522684
Score:  19125.764763520696
Score:  20636.97682891614
Score:  22349.310791266274
Score:  18876.442786519543
Score:  12834.137758453926
Score:  20698.406457205885
Score:  21081.24821690734
Score:  18925.52934445117
Score:  12786.432767249484
Score:  -2120.0759154886296

model_13
BernoulliNB()
["B_Women's Flyweight_rank", "B_Women's Strawweight_rank", 'R_draw', 'R_win_by_Decision_Split', 'B_Middleweight_rank', 'R_Lightweight_rank', 'R_Stance', 'R_Light Heavyweight_rank', 'R_avg_SUB_ATT', 'R_avg_SIG_STR_pct', 'age_dif', 'R_Featherweight_rank', 'B_draw', 'R_wins', 'B_avg_TD_pct', 'B_ev']
0

(3601, 19)

(3601,)

(3601, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.765109  0.234891       1
1       -320      250  0.815809  0.184191       1
2        130     -155  0.471345  0.528655       0
3       -155      135  0.637509  0.362491       1
4       -240      195  0.782851  0.217149       0
..       ...      ...       ...       ...     ...
245      175     -230  0.505303  0.494697       0
246      250     -305  0.593302  0.406698       0
247     -134      105  0.407217  0.592783       1
248     -105     -117  0.409905  0.590095       1
249      115     -143  0.517528  0.482472       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 220
          Number of winning bets: 93
          Number of losing bets: 127
          Number of underdog bets: 139
          Number of underdog wins: 49
          Number of underdog losses: 90
          Number of Favorite bets: 78
          Number of favorite wins: 44
          Number of favorite losses: 34
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -3091.5826279676044
          Profit per bet: -14.052648308943656
          Profit per match: -12.366330511870418


HI
HI
HI
HI
HI

(3601, 19)

(3601,)

(3601, 2)

(250, 19)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.765109  0.234891       1
1       -320      250  0.815809  0.184191       1
2        130     -155  0.471345  0.528655       0
3       -155      135  0.637509  0.362491       1
4       -240      195  0.782851  0.217149       0
..       ...      ...       ...       ...     ...
245      175     -230  0.505303  0.494697       0
246      250     -305  0.593302  0.406698       0
247     -134      105  0.407217  0.592783       1
248     -105     -117  0.409905  0.590095       1
249      115     -143  0.517528  0.482472       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 220
          Number of winning bets: 93
          Number of losing bets: 127
          Number of underdog bets: 139
          Number of underdog wins: 49
          Number of underdog losses: 90
          Number of Favorite bets: 78
          Number of favorite wins: 44
          Number of favorite losses: 34
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -3091.5826279676044
          Profit per bet: -14.052648308943656
          Profit per match: -12.366330511870418


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 14


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_14
CalibratedClassifierCV(base_estimator=LinearSVC())
["B_Women's Strawweight_rank", 'R_draw', 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
0
Current best score is: 19586.32783124996
Feature: gender Score: 19662.693744490527
Feature: no_of_rounds Score: 19993.91251275175
Feature: B_current_lose_streak Score: 20448.129083148553
Feature: B_longest_win_streak Score: 21451.445348029003
Feature: B_losses Score: 22228.77481133825
The best feature was B_losses.  It scored 22228.77481133825
Current best score is: 21838.652266360634
Feature: B_total_rounds_fought Score: 22071.247054697254
Feature: R_win_by_Submission Score: 22542.211247182076
The best feature was R_win_by_Submission.  It scored 22542.211247182076
Current best score is: 22543.32444917629
Feature: avg_sub_att_dif Score: 22626.84436129983
Feature: R_Pound-for-Pound_rank Score: 22668.874317531878
The best feature was R_Pound-for-Pound_rank.  It scored 22668.874317531878
Current best score is: 21668.31030917588
Feature: R_Reach_cms Score: 21952.893150324075
Feature: sub_dif Score: 22569.318899994716
The best feature was sub_dif.  It scored 22569.318899994716
Current best score is: 21088.324421706122
Feature: no_of_rounds Score: 21203.1940201165
Feature: B_win_by_TKO_Doctor_Stoppage Score: 21618.021060936862
The best feature was B_win_by_TKO_Doctor_Stoppage.  It scored 21618.021060936862
Current best score is: 21401.94789704568
NO IMPROVEMENT
FINAL BEST SCORE: 21401.94789704568

model_14
CalibratedClassifierCV(base_estimator=LinearSVC())
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_Pound-for-Pound_rank', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_draw', 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
0

(4197, 23)

(4197,)

(4197, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.546741  0.453259       1
1       -320      250  0.650937  0.349063       1
2        130     -155  0.434255  0.565745       0
3       -155      135  0.580363  0.419637       1
4       -240      195  0.633387  0.366613       0
..       ...      ...       ...       ...     ...
245      175     -230  0.442038  0.557962       0
246      250     -305  0.312449  0.687551       0
247     -134      105  0.446128  0.553872       1
248     -105     -117  0.435884  0.564116       1
249      115     -143  0.517853  0.482147       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 202
          Number of winning bets: 96
          Number of losing bets: 106
          Number of underdog bets: 150
          Number of underdog wins: 60
          Number of underdog losses: 90
          Number of Favorite bets: 50
          Number of favorite wins: 36
          Number of favorite losses: 14
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: 810.8115316500993
          Profit per bet: 4.013918473515343
          Profit per match: 3.243246126600397


HI
HI
HI
HI
HI
Real output model: CalibratedClassifierCV(base_estimator=LinearSVC())

model_14
CalibratedClassifierCV(base_estimator=LinearSVC())
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_Pound-for-Pound_rank', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_draw', 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
0

(4197, 23)

(4197,)

(4197, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.546498  0.453502       1
1       -320      250  0.647226  0.352774       1
2        130     -155  0.434982  0.565018       0
3       -155      135  0.580511  0.419489       1
4       -240      195  0.634331  0.365669       0
..       ...      ...       ...       ...     ...
245      175     -230  0.441859  0.558141       0
246      250     -305  0.313723  0.686277       0
247     -134      105  0.446668  0.553332       1
248     -105     -117  0.435546  0.564454       1
249      115     -143  0.518510  0.481490       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 204
          Number of winning bets: 100
          Number of losing bets: 104
          Number of underdog bets: 151
          Number of underdog wins: 62
          Number of underdog losses: 89
          Number of Favorite bets: 51
          Number of favorite wins: 38
          Number of favorite losses: 13
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: 1429.9024407410084
          Profit per bet: 7.009325689906904
          Profit per match: 5.7196097629640335


HI
HI
HI
HI
HI
0 20604.605329219237
1 19692.69702478195
2 19415.57287316984
3 20045.79742961846
4 19177.32590475651
5 17711.052897556885
6 18485.77205247347
7 15361.089723287112
8 13688.491543447555
9 11341.405261659176
10 8299.043359486644
11 9338.9050370429
12 8296.246822157262
13 7803.499646410086
14 9593.173325407293
15 7866.392303700047
16 7760.1324141642945
17 5784.187713703465
18 4870.25131615254
19 5254.584649485873
20 5468.9258422736675
21 6283.016751364577
22 5265.822134387352
23 3562.8221343873515
24 4098.488801054018
25 4951.822134387352
26 6176.822134387352
27 6096.155467720686
28 4884.822134387352
29 4864.822134387352
30 3889.822134387352
31 2893.8656126482215
32 3683.8656126482215
33 4463.865612648222
34 4373.865612648222
35 5043.865612648222
36 4318.865612648222
37 4153.865612648222
38 4806.865612648222
39 4859.865612648222
40 2601.909090909091
41 1891.909090909091
42 2421.909090909091
43 2276.0
44 2866.0
45 2606.0
46 3416.0
47 2861.0
48 3201.0
49 3431.0
50 3136.0
51 2701.0
52 2451.0
53 2941.0
54 2696.0
55 2446.0
56 2746.0
57 2631.0
58 1991.0
59 1561.0
60 1676.0
61 2176.0
62 2476.0
63 2621.0
64 2596.0
65 1941.0
66 1611.0
67 468.0
68 668.0
69 723.0
70 823.0
71 993.0
72 418.0
73 518.0
74 -737.0
75 -537.0
76 -572.0
77 -472.0
78 -502.0
79 -377.0
80 -377.0
81 -77.0
82 -77.0
83 -277.0
84 -277.0
85 -362.0
86 -632.0
87 -132.0
88 168.0
89 268.0
90 120.0
91 120.0
92 420.0
93 620.0
94 820.0
95 335.0
96 35.0
97 510.0
98 335.0
99 115.0
100 215.0
101 315.0
102 315.0
103 315.0
104 415.0
105 145.0
106 245.0
107 445.0
108 345.0
109 345.0
110 445.0
111 445.0
112 645.0
113 745.0
114 845.0
115 845.0
116 845.0
117 945.0
118 630.0
119 630.0
120 350.0
121 350.0
122 450.0
123 450.0
124 190.0
125 190.0
126 190.0
127 190.0
128 190.0
129 390.0
130 390.0
131 390.0
132 390.0
133 390.0
134 390.0
135 390.0
136 390.0
137 490.0
138 -65.0
139 -65.0
140 -515.0
141 -515.0
142 -415.0
143 -315.0
144 -215.0
145 -215.0
146 -115.0
147 -115.0
148 -115.0
149 -15.0
150 -15.0
151 -465.0
152 -465.0
153 -465.0
154 -715.0
155 -615.0
156 -615.0
157 -715.0
158 -615.0
159 -615.0
160 -515.0
161 -515.0
162 -415.0
163 -415.0
164 -415.0
165 -415.0
166 -415.0
167 -415.0
168 -215.0
169 -115.0
170 -115.0
171 -115.0
172 -115.0
173 85.0
174 85.0
175 85.0
176 85.0
177 185.0
178 85.0
179 185.0
180 185.0
181 285.0
182 285.0
183 285.0
184 285.0
185 285.0
186 285.0
187 285.0
188 285.0
189 285.0
190 285.0
191 285.0
192 285.0
193 285.0
194 285.0
195 285.0
196 285.0
197 285.0
198 285.0
199 285.0
200 285.0
201 285.0
202 285.0
203 285.0
204 285.0
205 285.0
206 285.0
207 285.0
208 285.0
209 285.0
210 285.0
211 285.0
212 285.0
213 285.0
214 285.0
215 285.0
216 285.0
217 285.0
218 285.0
219 285.0
220 285.0
221 285.0
222 285.0
223 285.0
224 285.0
225 285.0
226 285.0
227 285.0
228 285.0
229 285.0
230 285.0
231 285.0
232 285.0
233 285.0
234 285.0
235 285.0
236 285.0
237 285.0
238 285.0
239 285.0
240 285.0
241 385.0
242 385.0
243 385.0
244 385.0
245 385.0
246 385.0
247 385.0
248 485.0
249 485.0

model_14
CalibratedClassifierCV(base_estimator=LinearSVC())
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_Pound-for-Pound_rank', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_draw', 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
0

(4197, 23)

(4197,)

(4197, 2)

(250, 23)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.545882  0.454118       1
1       -320      250  0.652806  0.347194       1
2        130     -155  0.433966  0.566034       0
3       -155      135  0.579698  0.420302       1
4       -240      195  0.633050  0.366950       0
..       ...      ...       ...       ...     ...
245      175     -230  0.442132  0.557868       0
246      250     -305  0.314368  0.685632       0
247     -134      105  0.446076  0.553924       1
248     -105     -117  0.435161  0.564839       1
249      115     -143  0.518101  0.481899       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 203
          Number of winning bets: 96
          Number of losing bets: 107
          Number of underdog bets: 151
          Number of underdog wins: 60
          Number of underdog losses: 91
          Number of Favorite bets: 50
          Number of favorite wins: 36
          Number of favorite losses: 14
          Number of even bets: 2
          Number of even wins: 0
          Number of even losses: 2
          Profit: 710.8115316500991
          Profit per bet: 3.501534638670439
          Profit per match: 2.8432461266003966


HI
HI
HI
HI
HI
The original score is 21270.652519932773
NEW BEST FEATURE SET
['sub_dif', 'R_Pound-for-Pound_rank', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_draw', 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
21529.683935549503
Score:  20571.099968806444
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_draw', 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
21936.506292773516
Score:  20290.86082153945
Score:  20102.586592391945
Score:  19879.27196998731
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_Pound-for-Pound_rank', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
21956.46274934369
Score:  19051.133310787827
Score:  20324.526916110237
Score:  20590.04272367539
Score:  21146.654606342214
Score:  21452.824558717897
Score:  18895.49781763873
Score:  18669.1555695853
Score:  20522.449622240663
Score:  17215.785850323882
Score:  17718.30017341457
Score:  19149.90976157233
Score:  19775.521526018725
Score:  18093.429224528543
Score:  16057.26929093149
Score:  15539.131890727076
Score:  -8373.66276136543
The original score is 21158.70262058773
NEW BEST FEATURE SET
['sub_dif', 'R_Pound-for-Pound_rank', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
21918.712498235232
Score:  20500.030997749163
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
22034.072569229633
Score:  20470.930961592327
Score:  19342.28084642635
Score:  20814.0059868519
Score:  18672.98656844417
Score:  19855.806458572133
Score:  20639.552281939752
Score:  20527.356202931536
Score:  20387.199344564535
Score:  20122.79355075014
Score:  19312.89508092364
Score:  19680.0525068145
Score:  16783.24003684675
Score:  16952.74450712052
Score:  18571.646322855875
Score:  19312.456718042602
Score:  19280.32040220518
Score:  16972.661463705626
Score:  14073.379738160915
Score:  -8865.005357761775
The original score is 21319.74560877098
NEW BEST FEATURE SET
['sub_dif', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
22275.1787026082
Score:  21563.984849931385
Score:  21882.18518184225
Score:  19293.51783671568
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_win_by_Submission', 'B_losses', 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
22323.663369676477
Score:  19850.183358863764
Score:  20383.08830051381
Score:  20761.56961780063
Score:  21454.053602894874
Score:  21622.791048108345
Score:  20520.4672113982
Score:  20816.38148510283
Score:  20758.236196415328
Score:  17401.708336512136
Score:  19817.890784916104
Score:  20425.969263271298
Score:  21598.768786200315
Score:  21693.777126110395
Score:  17623.21233021606
Score:  16837.424364300492
Score:  -6750.336014196444
The original score is 23117.85483318373
Score:  22748.484000943798
Score:  22844.6676986808
Score:  22592.5440864302
Score:  20338.59718241498
Score:  19640.71551098236
Score:  21312.26858853765
Score:  21759.67159807505
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_win_by_Submission', 'B_losses', 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
23408.414805729793
Score:  21047.599443939962
Score:  20053.381840638405
Score:  20862.940271394993
Score:  21159.465606810947
Score:  17658.332558902777
Score:  18832.239031672503
Score:  20295.585297597558
Score:  20633.98347975711
Score:  20933.511292742616
Score:  18658.884988789152
Score:  16103.709739863476
Score:  -6067.948352291207
The original score is 22198.812379809067
Score:  21924.964520424313
Score:  22023.895016601975
Score:  20792.25797247772
Score:  19719.061717879515
Score:  20042.770471938253
Score:  20794.56585267702
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_win_by_Submission', 'B_losses', 'R_Weight_lbs', 'ko_dif', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
22273.323551723286
Score:  21904.625080393515
Score:  19128.049284630222
Score:  21104.039159580407
Score:  21180.14606256813
Score:  16571.87114330452
Score:  19186.10442984023
Score:  20226.09308693609
Score:  21189.970239550865
Score:  21465.08272131405
Score:  17656.49763981971
Score:  16701.530286466634
Score:  -6217.491850110568
The original score is 22316.163341026266
Score:  21654.082695218556
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'R_win_by_Submission', 'B_losses', 'R_Weight_lbs', 'ko_dif', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
22325.22883909212
Score:  21315.888008862177
Score:  20251.648533942353
Score:  19586.99672031874
Score:  19587.07380961405
Score:  21120.37837292573
Score:  22023.505267280852
Score:  20475.20883864639
Score:  20397.286757888167
Score:  17365.618164611395
Score:  18048.67737923651
Score:  19351.107402652764
Score:  20546.61510099467
Score:  20171.49967972858

Score:  17870.855483953732
Score:  15693.695070249714
Score:  -7212.692458474246
The original score is 21691.50257100992
Score:  21516.07713931734
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'B_losses', 'R_Weight_lbs', 'ko_dif', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
21790.02982589027
Score:  18855.375273042297
Score:  18715.851241165332
Score:  20261.555122815764
Score:  20163.3468000969
Score:  20887.41406390703
Score:  20493.13269971257
Score:  20182.342956679782
Score:  16954.11806708001
Score:  18142.68503943987
Score:  19839.753844795294
Score:  21269.627916389996
Score:  19839.672502929705
Score:  17873.657735562763
Score:  15949.904014955515
Score:  -6831.483710292158
The original score is 22248.027275017368
Score:  21780.6791533182
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'R_Weight_lbs', 'ko_dif', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
22675.42946236946
Score:  19898.31118712947
Score:  21044.472174606144
Score:  19082.970861459482
Score:  22039.296704630557
Score:  20364.91564656815
Score:  20381.046762057624
Score:  16451.36506417289
Score:  17875.934627699182
Score:  17433.174733100102
Score:  20653.480246095933
Score:  19349.04773441582
Score:  18980.64222167732
Score:  15463.025561744233
Score:  -6216.962327936728
The original score is 21394.61749655749
NEW BEST FEATURE SET
['R_Weight_lbs', 'ko_dif', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
21808.486235263805
Score:  21046.90685991022
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'R_Weight_lbs', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
22557.936739602985
Score:  21926.642483076426
NEW BEST FEATURE SET
['B_win_by_TKO_Doctor_Stoppage', 'R_Weight_lbs', 'ko_dif', 'R_Middleweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
23092.850971807897
Score:  21630.028925267798
Score:  19770.357432535468
Score:  17907.66470238314
Score:  19460.244010967275
Score:  21208.302165825084
Score:  22189.51541166231
Score:  20327.65576658032
Score:  19023.29576648614
Score:  14138.113005312742
Score:  -7267.929076098488
The original score is 22492.52212008774
NEW BEST FEATURE SET
['R_Weight_lbs', 'ko_dif', 'R_Middleweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
24910.710772797396
Score:  23739.830885019917
Score:  22108.45111958108
Score:  21980.17768737772
Score:  22261.37532789833
Score:  23081.18114054188
Score:  22350.562214039306
Score:  21562.175126206457
Score:  21464.90787020501
Score:  22821.453710397775
Score:  20899.55455696321
Score:  18716.346399824248
Score:  6903.9978406523405
Score:  -9514.35190882525
The original score is 25478.980003566627
NEW BEST FEATURE SET
['ko_dif', 'R_Middleweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
26026.257001743757
Score:  24374.17143733588
Score:  24719.82321268613
Score:  23863.88459902745
Score:  23314.339590801937
Score:  24610.368093824134
Score:  23575.65036528379
Score:  24603.50321780036
Score:  24880.096243792075
Score:  23397.31615487712
Score:  20887.08923458989
Score:  7418.325160820421
Score:  -10492.425283954566
The original score is 25586.993111595308
Score:  24898.604417269533
NEW BEST FEATURE SET
['ko_dif', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
26371.826427056585
Score:  25035.454106755813
Score:  23715.37951249806
Score:  25650.963522824444
Score:  23921.360190851963
Score:  23868.957968958603
Score:  25555.73247808572
Score:  22638.94270468305
Score:  19068.862474558766
Score:  12120.379711138336
Score:  -9165.234764753946
The original score is 26249.324706554864
NEW BEST FEATURE SET
['R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
27156.468219112416
Score:  25337.663474295583
Score:  24828.63269569372
Score:  21834.30834659305
Score:  24414.739251308085
Score:  24781.358527046126
Score:  24309.359455224592
Score:  22249.582264176526
Score:  18894.577638753373
Score:  12060.136112975786
Score:  -8929.947443429475
The original score is 26820.20479564098
Score:  25801.692327544442
Score:  25946.352549541665
Score:  21207.82064362897
Score:  24258.554402634112
Score:  24332.816721756208
Score:  24140.742446242115
Score:  23204.854747703033
Score:  18290.638083726983
Score:  13389.946711315155
Score:  -9293.082936582901
The features are different
OLD:
['B_win_by_TKO_Doctor_Stoppage', 'sub_dif', 'R_Pound-for-Pound_rank', 'R_win_by_Submission', 'B_losses', "B_Women's Strawweight_rank", 'R_draw', 'R_Weight_lbs', 'ko_dif', 'R_total_title_bouts', 'B_win_by_Submission', 'R_Middleweight_rank', 'R_avg_SIG_STR_pct', 'R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
NEW:
['R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']

model_14
CalibratedClassifierCV(base_estimator=LinearSVC())
['R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
0

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.526983  0.473017       1
1       -320      250  0.665792  0.334208       1
2        130     -155  0.432639  0.567361       0
3       -155      135  0.582694  0.417306       1
4       -240      195  0.659896  0.340104       0
..       ...      ...       ...       ...     ...
245      175     -230  0.444995  0.555005       0
246      250     -305  0.306268  0.693732       0
247     -134      105  0.445464  0.554536       1
248     -105     -117  0.426772  0.573228       1
249      115     -143  0.524453  0.475547       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 204
          Number of winning bets: 93
          Number of losing bets: 111
          Number of underdog bets: 152
          Number of underdog wins: 57
          Number of underdog losses: 95
          Number of Favorite bets: 51
          Number of favorite wins: 36
          Number of favorite losses: 15
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: -95.1486952413719
          Profit per bet: -0.46641517275182304
          Profit per match: -0.3805947809654876


HI
HI
HI
HI
HI
Current best score is: 27240.377955814143
NO IMPROVEMENT
FINAL BEST SCORE: 27240.377955814143

model_14
CalibratedClassifierCV(base_estimator=LinearSVC())
['R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
0

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.527173  0.472827       1
1       -320      250  0.664542  0.335458       1
2        130     -155  0.432508  0.567492       0
3       -155      135  0.582794  0.417206       1
4       -240      195  0.660145  0.339855       0
..       ...      ...       ...       ...     ...
245      175     -230  0.444948  0.555052       0
246      250     -305  0.302800  0.697200       0
247     -134      105  0.445541  0.554459       1
248     -105     -117  0.426706  0.573294       1
249      115     -143  0.524409  0.475591       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 204
          Number of winning bets: 93
          Number of losing bets: 111
          Number of underdog bets: 152
          Number of underdog wins: 57
          Number of underdog losses: 95
          Number of Favorite bets: 51
          Number of favorite wins: 36
          Number of favorite losses: 15
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: -95.1486952413719
          Profit per bet: -0.46641517275182304
          Profit per match: -0.3805947809654876


HI
HI
HI
HI
HI
Real output model: CalibratedClassifierCV(base_estimator=LinearSVC())

model_14
CalibratedClassifierCV(base_estimator=LinearSVC())
['R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
0

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.526956  0.473044       1
1       -320      250  0.664977  0.335023       1
2        130     -155  0.432498  0.567502       0
3       -155      135  0.582716  0.417284       1
4       -240      195  0.659967  0.340033       0
..       ...      ...       ...       ...     ...
245      175     -230  0.444881  0.555119       0
246      250     -305  0.307758  0.692242       0
247     -134      105  0.445429  0.554571       1
248     -105     -117  0.426845  0.573155       1
249      115     -143  0.524432  0.475568       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 204
          Number of winning bets: 93
          Number of losing bets: 111
          Number of underdog bets: 152
          Number of underdog wins: 57
          Number of underdog losses: 95
          Number of Favorite bets: 51
          Number of favorite wins: 36
          Number of favorite losses: 15
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: -95.1486952413719
          Profit per bet: -0.46641517275182304
          Profit per match: -0.3805947809654876


HI
HI
HI
HI
HI
0 26669.42557486176
1 22606.169516686303
2 18131.091971575643
3 18486.960690549273
4 17888.509534594043
5 16810.226829255902
6 16727.007563332376
7 16960.902657989085
8 16547.679393325438
9 14651.605044766844
10 12739.67351004087
11 11531.0776861043
12 11992.128456413915
13 10257.189652280915
14 10271.707324529547
15 8650.751083946376
16 8449.629466433453
17 9899.20089500488
18 9666.20974123112
19 9278.20974123112
20 8844.300650322028
21 8111.300650322027
22 7229.344128582897
23 7189.344128582897
24 7627.67746191623
25 8839.1872658378
26 7963.187265837799
27 9558.1872658378
28 7818.1872658378
29 7340.294184076794
30 6600.294184076793
31 7130.294184076793
32 7130.294184076793
33 6420.294184076793
34 7116.294184076793
35 5630.3850931677025
36 5500.3850931677025
37 5120.385093167702
38 4978.95652173913
39 5388.95652173913
40 4903.95652173913
41 3927.9565217391305
42 3892.9565217391305
43 4642.95652173913
44 4112.95652173913
45 3252.9565217391305
46 3982.9565217391305
47 3822.9565217391305
48 4302.95652173913
49 4077.9565217391305
50 3852.9565217391305
51 3332.9565217391305
52 3577.9565217391305
53 3371.0
54 2971.0
55 2546.0
56 2311.0
57 2266.0
58 1756.0
59 1956.0
60 1971.0
61 1856.0
62 1406.0
63 961.0
64 1361.0
65 1376.0
66 1576.0
67 1038.0
68 603.0
69 -377.0
70 -425.0
71 -325.0
72 -550.0
73 -450.0
74 -50.0
75 -350.0
76 -350.0
77 -195.0
78 305.0
79 155.0
80 130.0
81 730.0
82 830.0
83 930.0
84 1030.0
85 350.0
86 205.0
87 450.0
88 230.0
89 -335.0
90 -135.0
91 -195.0
92 -95.0
93 -95.0
94 -170.0
95 -55.0
96 145.0
97 145.0
98 345.0
99 545.0
100 745.0
101 155.0
102 160.0
103 -265.0
104 -265.0
105 -680.0
106 -580.0
107 -580.0
108 -480.0
109 -480.0
110 -1135.0
111 -1035.0
112 -835.0
113 -835.0
114 -635.0
115 -435.0
116 -715.0
117 -715.0
118 -615.0
119 -415.0
120 -415.0
121 -415.0
122 -315.0
123 -315.0
124 -215.0
125 -215.0
126 -115.0
127 -15.0
128 -15.0
129 85.0
130 85.0
131 85.0
132 85.0
133 -465.0
134 -465.0
135 -465.0
136 -465.0
137 -465.0
138 -465.0
139 -465.0
140 -465.0
141 -715.0
142 -715.0
143 -715.0
144 -715.0
145 -715.0
146 -515.0
147 -515.0
148 -515.0
149 -515.0
150 -515.0
151 -515.0
152 -515.0
153 -515.0
154 -415.0
155 -315.0
156 -215.0
157 -215.0
158 -215.0
159 -215.0
160 -215.0
161 -215.0
162 -115.0
163 -115.0
164 -115.0
165 -115.0
166 -115.0
167 -115.0
168 -15.0
169 -15.0
170 -15.0
171 -15.0
172 -15.0
173 -15.0
174 85.0
175 85.0
176 85.0
177 85.0
178 85.0
179 85.0
180 85.0
181 85.0
182 85.0
183 85.0
184 185.0
185 285.0
186 285.0
187 285.0
188 285.0
189 285.0
190 285.0
191 285.0
192 285.0
193 285.0
194 285.0
195 285.0
196 285.0
197 285.0
198 285.0
199 285.0
200 285.0
201 285.0
202 285.0
203 285.0
204 285.0
205 285.0
206 285.0
207 285.0
208 285.0
209 285.0
210 285.0
211 285.0
212 385.0
213 385.0
214 385.0
215 385.0
216 385.0
217 385.0
218 385.0
219 385.0
220 385.0
221 385.0
222 385.0
223 385.0
224 385.0
225 385.0
226 385.0
227 385.0
228 385.0
229 385.0
230 385.0
231 385.0
232 385.0
233 385.0
234 385.0
235 385.0
236 385.0
237 385.0
238 385.0
239 385.0
240 385.0
241 385.0
242 385.0
243 385.0
244 -100
245 0
246 0
247 0
248 0
249 0

model_14
CalibratedClassifierCV(base_estimator=LinearSVC())
['R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
0

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.527547  0.472453       1
1       -320      250  0.661128  0.338872       1
2        130     -155  0.433133  0.566867       0
3       -155      135  0.583115  0.416885       1
4       -240      195  0.660098  0.339902       0
..       ...      ...       ...       ...     ...
245      175     -230  0.445594  0.554406       0
246      250     -305  0.301087  0.698913       0
247     -134      105  0.445852  0.554148       1
248     -105     -117  0.427309  0.572691       1
249      115     -143  0.524351  0.475649       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 204
          Number of winning bets: 93
          Number of losing bets: 111
          Number of underdog bets: 152
          Number of underdog wins: 57
          Number of underdog losses: 95
          Number of Favorite bets: 51
          Number of favorite wins: 36
          Number of favorite losses: 15
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: -95.1486952413719
          Profit per bet: -0.46641517275182304
          Profit per match: -0.3805947809654876


HI
HI
HI
HI
HI
The original score is 27070.20479564098
Score:  25960.28881877251
Score:  25802.978187585217
Score:  22618.946190523635
Score:  24074.44201438379
Score:  24341.89079583028
Score:  24241.8230323227
Score:  23246.037543401955
Score:  18229.051112140016
Score:  14243.102957529869
Score:  -9599.604675713339

model_14
CalibratedClassifierCV(base_estimator=LinearSVC())
['R_win_by_TKO_Doctor_Stoppage', 'lose_streak_dif', 'avg_td_dif', 'R_Flyweight_rank', 'B_match_weightclass_rank', 'B_Flyweight_rank', 'B_Lightweight_rank', 'R_win_by_Decision_Split', 'age_dif', 'B_ev']
0

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.526845  0.473155       1
1       -320      250  0.664226  0.335774       1
2        130     -155  0.432164  0.567836       0
3       -155      135  0.582665  0.417335       1
4       -240      195  0.660027  0.339973       0
..       ...      ...       ...       ...     ...
245      175     -230  0.444771  0.555229       0
246      250     -305  0.309000  0.691000       0
247     -134      105  0.445326  0.554674       1
248     -105     -117  0.426675  0.573325       1
249      115     -143  0.524287  0.475713       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 204
          Number of winning bets: 93
          Number of losing bets: 111
          Number of underdog bets: 152
          Number of underdog wins: 57
          Number of underdog losses: 95
          Number of Favorite bets: 51
          Number of favorite wins: 36
          Number of favorite losses: 15
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: -95.1486952413719
          Profit per bet: -0.46641517275182304
          Profit per match: -0.3805947809654876


HI
HI
HI
HI
HI

(4554, 10)

(4554,)

(4554, 2)

(250, 10)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.526932  0.473068       1
1       -320      250  0.667708  0.332292       1
2        130     -155  0.432633  0.567367       0
3       -155      135  0.582547  0.417453       1
4       -240      195  0.659755  0.340245       0
..       ...      ...       ...       ...     ...
245      175     -230  0.444923  0.555077       0
246      250     -305  0.304056  0.695944       0
247     -134      105  0.445527  0.554473       1
248     -105     -117  0.427116  0.572884       1
249      115     -143  0.524169  0.475831       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 204
          Number of winning bets: 93
          Number of losing bets: 111
          Number of underdog bets: 152
          Number of underdog wins: 57
          Number of underdog losses: 95
          Number of Favorite bets: 51
          Number of favorite wins: 36
          Number of favorite losses: 15
          Number of even bets: 1
          Number of even wins: 0
          Number of even losses: 1
          Profit: -95.1486952413719
          Profit per bet: -0.46641517275182304
          Profit per match: -0.3805947809654876


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 15


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_15
LinearDiscriminantAnalysis(solver='lsqr')
["R_Women's Flyweight_rank", "R_Women's Featherweight_rank", 'R_avg_SUB_ATT', 'R_Heavyweight_rank', 'R_Reach_cms', 'B_Flyweight_rank', 'R_Lightweight_rank', 'R_age', 'B_age', 'R_Welterweight_rank', 'R_Bantamweight_rank', 'R_match_weightclass_rank', 'R_total_rounds_fought', 'R_avg_TD_landed', 'R_Stance', 'B_current_win_streak', "B_Women's Bantamweight_rank", "B_Women's Flyweight_rank", "B_Women's Strawweight_rank", 'B_wins', 'R_Flyweight_rank', 'R_win_by_KO/TKO', 'location', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'reach_dif', 'age_dif', 'R_Featherweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
0
Current best score is: 17010.126474840617
Feature: gender Score: 18311.90384657664
Feature: R_Height_cms Score: 18485.492303759864
The best feature was R_Height_cms.  It scored 18485.492303759864
Current best score is: 18485.492303759864
Feature: no_of_rounds Score: 18604.86666261451
Feature: B_win_by_Decision_Majority Score: 18750.490342716344
The best feature was B_win_by_Decision_Majority.  It scored 18750.490342716344
Current best score is: 18750.490342716344
Feature: gender Score: 18805.928161076634
Feature: no_of_rounds Score: 18917.16018707933
Feature: R_longest_win_streak Score: 19032.31152895307
Feature: R_Middleweight_rank Score: 19288.67933596678
The best feature was R_Middleweight_rank.  It scored 19288.67933596678
Current best score is: 19288.67933596678
Feature: B_losses Score: 19292.838409453296
Feature: B_win_by_Submission Score: 19659.965408958335
The best feature was B_win_by_Submission.  It scored 19659.965408958335
Current best score is: 19659.965408958335
Feature: R_current_lose_streak Score: 19882.665844633386
The best feature was R_current_lose_streak.  It scored 19882.665844633386
Current best score is: 19882.665844633386
Feature: gender Score: 20019.689716360175
Feature: win_streak_dif Score: 20336.745751041173
The best feature was win_streak_dif.  It scored 20336.745751041173
Current best score is: 20336.745751041173
NO IMPROVEMENT
FINAL BEST SCORE: 20336.745751041173

model_15
LinearDiscriminantAnalysis(solver='lsqr')
['win_streak_dif', 'R_current_lose_streak', 'B_win_by_Submission', 'R_Middleweight_rank', 'B_win_by_Decision_Majority', 'R_Height_cms', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", 'R_avg_SUB_ATT', 'R_Heavyweight_rank', 'R_Reach_cms', 'B_Flyweight_rank', 'R_Lightweight_rank', 'R_age', 'B_age', 'R_Welterweight_rank', 'R_Bantamweight_rank', 'R_match_weightclass_rank', 'R_total_rounds_fought', 'R_avg_TD_landed', 'R_Stance', 'B_current_win_streak', "B_Women's Bantamweight_rank", "B_Women's Flyweight_rank", "B_Women's Strawweight_rank", 'B_wins', 'R_Flyweight_rank', 'R_win_by_KO/TKO', 'location', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'reach_dif', 'age_dif', 'R_Featherweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
0

(3513, 210)

(3513,)

(3513, 2)

(250, 210)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.864306  0.135694       1
1       -320      250  0.632702  0.367298       1
2        130     -155  0.537706  0.462294       0
3       -155      135  0.742697  0.257303       1
4       -240      195  0.567764  0.432236       0
..       ...      ...       ...       ...     ...
245      175     -230  0.549392  0.450608       0
246      250     -305  0.682145  0.317855       0
247     -134      105  0.766018  0.233982       1
248     -105     -117  0.625916  0.374084       1
249      115     -143  0.525221  0.474779       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 224
          Number of winning bets: 102
          Number of losing bets: 123
          Number of underdog bets: 159
          Number of underdog wins: 60
          Number of underdog losses: 99
          Number of Favorite bets: 63
          Number of favorite wins: 41
          Number of favorite losses: 22
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -182.41751724884136
          Profit per bet: -0.8143639162894704
          Profit per match: -0.7296700689953655


HI
HI
HI
HI
HI


Starting New Run for LinearDiscriminantAnalysis
LinearDiscriminantAnalysis(solver='lsqr')


Previous Best Score: 20336.745751041173
solver:  svd tol:  0.0001 Score:  20218.563932859357
solver:  svd tol:  0.00011000000000000002 Score:  20218.563932859357
solver:  svd tol:  9e-05 Score:  20218.563932859357
solver:  lsqr tol:  0.0001 Score:  20336.745751041173
solver:  lsqr tol:  0.00011000000000000002 Score:  20336.745751041173
solver:  lsqr tol:  9e-05 Score:  20336.745751041173
output model: LinearDiscriminantAnalysis(solver='lsqr')
pos model: LinearDiscriminantAnalysis(solver='lsqr')
 output_model: LinearDiscriminantAnalysis(solver='lsqr')
Real output model: LinearDiscriminantAnalysis(solver='lsqr')

model_15
LinearDiscriminantAnalysis(solver='lsqr')
['win_streak_dif', 'R_current_lose_streak', 'B_win_by_Submission', 'R_Middleweight_rank', 'B_win_by_Decision_Majority', 'R_Height_cms', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", 'R_avg_SUB_ATT', 'R_Heavyweight_rank', 'R_Reach_cms', 'B_Flyweight_rank', 'R_Lightweight_rank', 'R_age', 'B_age', 'R_Welterweight_rank', 'R_Bantamweight_rank', 'R_match_weightclass_rank', 'R_total_rounds_fought', 'R_avg_TD_landed', 'R_Stance', 'B_current_win_streak', "B_Women's Bantamweight_rank", "B_Women's Flyweight_rank", "B_Women's Strawweight_rank", 'B_wins', 'R_Flyweight_rank', 'R_win_by_KO/TKO', 'location', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'reach_dif', 'age_dif', 'R_Featherweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
0

(3513, 210)

(3513,)

(3513, 2)

(250, 210)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.864306  0.135694       1
1       -320      250  0.632702  0.367298       1
2        130     -155  0.537706  0.462294       0
3       -155      135  0.742697  0.257303       1
4       -240      195  0.567764  0.432236       0
..       ...      ...       ...       ...     ...
245      175     -230  0.549392  0.450608       0
246      250     -305  0.682145  0.317855       0
247     -134      105  0.766018  0.233982       1
248     -105     -117  0.625916  0.374084       1
249      115     -143  0.525221  0.474779       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 224
          Number of winning bets: 102
          Number of losing bets: 123
          Number of underdog bets: 159
          Number of underdog wins: 60
          Number of underdog losses: 99
          Number of Favorite bets: 63
          Number of favorite wins: 41
          Number of favorite losses: 22
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -182.41751724884136
          Profit per bet: -0.8143639162894704
          Profit per match: -0.7296700689953655


HI
HI
HI
HI
HI
0 20336.745751041173
1 17419.97766822765
2 16806.82616480988
3 17149.809312626472
4 16946.584222020516
5 15831.272704247167
6 16121.45154716478
7 16715.76969164115
8 17803.52085706409
9 17498.378750041724
10 16252.263670955548
11 16653.45163106165
12 15887.7514373195
13 15772.016429446356
14 15057.541002638545
15 13669.895473318173
16 12792.370619174637
17 12925.669160061912
18 13567.503869390883
19 13220.978320627419
20 13201.297233490372
21 12142.355976643188
22 11802.894842250636
23 11710.668395346234
24 11283.889838397077
25 12072.597058968253
26 11030.954061787797
27 11105.083782641654
28 11229.570630191163
29 10652.294794083406
30 10854.555082134288
31 10957.662326741534
32 10351.202609784923
33 9889.842769590749
34 10195.326323897834
35 9815.966492341986
36 10018.302674678169
37 10796.053605289138
38 9999.701167637962
39 10083.965880804279
40 10538.717167253679
41 11190.377508809655
42 11540.358734274752
43 11631.124262225061
44 11444.457595558397
45 11918.654919973113
46 10800.750008792338
47 10211.251174293502
48 9831.79450304484
49 8617.005813473543
50 9576.580593532193
51 9441.580593532191
52 8639.624071793063
53 8656.29073845973
54 9019.640906809898
55 9523.392193259298
56 9061.574011441116
57 9128.741843608948
58 8271.832752699856
59 8955.923661790766
60 8140.68556655267
61 8580.685566552671
62 8447.062378146873
63 7788.153287237783
64 8653.153287237783
65 7836.196765498653
66 8526.196765498653
67 8801.857142857143
68 8473.285714285714
69 8724.952380952382
70 7359.476190476191
71 7872.476190476191
72 8212.238095238095
73 8742.238095238095
74 8387.238095238095
75 8432.238095238095
76 8222.238095238095
77 7750.238095238095
78 6913.238095238095
79 7318.238095238095
80 7083.238095238095
81 7108.238095238095
82 7488.238095238095
83 6946.0
84 6741.0
85 5721.0
86 6276.0
87 6436.0
88 6391.0
89 5556.0
90 5516.0
91 6216.0
92 4804.0
93 4939.0
94 5274.0
95 5084.0
96 4634.0
97 4994.0
98 5694.0
99 5289.0
100 5789.0
101 5574.0
102 5859.0
103 5874.0
104 5634.0
105 5804.0
106 5174.0
107 4839.0
108 3729.0
109 2712.0
110 2757.0
111 2857.0
112 2232.0
113 2065.0
114 2125.0
115 2210.0
116 1387.0
117 1687.0
118 1782.0
119 1062.0
120 1362.0
121 1862.0
122 892.0
123 907.0
124 927.0
125 940.0
126 -260.0
127 190.0
128 -235.0
129 65.0
130 10.0
131 410.0
132 665.0
133 1165.0
134 1300.0
135 1065.0
136 1665.0
137 1965.0
138 1925.0
139 2025.0
140 2325.0
141 1705.0
142 2080.0
143 2280.0
144 2032.0
145 1482.0
146 1672.0
147 1972.0
148 1482.0
149 1137.0
150 532.0
151 172.0
152 -121.0
153 -94.0
154 -94.0
155 -79.0
156 321.0
157 421.0
158 721.0
159 1021.0
160 1721.0
161 1656.0
162 1646.0
163 1641.0
164 1641.0
165 1493.0
166 1893.0
167 1893.0
168 1298.0
169 1193.0
170 1293.0
171 1293.0
172 1293.0
173 1393.0
174 1393.0
175 1493.0
176 1893.0
177 1753.0
178 1853.0
179 2053.0
180 1818.0
181 1918.0
182 2018.0
183 1783.0
184 1783.0
185 1883.0
186 2183.0
187 2028.0
188 2228.0
189 2228.0
190 2158.0
191 2258.0
192 2028.0
193 2028.0
194 2128.0
195 2128.0
196 1778.0
197 1878.0
198 1878.0
199 1523.0
200 1623.0
201 1623.0
202 1723.0
203 1323.0
204 1423.0
205 1423.0
206 1423.0
207 1423.0
208 1208.0
209 1408.0
210 1608.0
211 1708.0
212 1433.0
213 1533.0
214 1533.0
215 1533.0
216 1443.0
217 1643.0
218 1643.0
219 1278.0
220 1378.0
221 1378.0
222 1378.0
223 1378.0
224 1378.0
225 1378.0
226 1378.0
227 1678.0
228 1678.0
229 1028.0
230 1128.0
231 1128.0
232 718.0
233 718.0
234 718.0
235 918.0
236 1018.0
237 1018.0
238 1018.0
239 1018.0
240 1018.0
241 1018.0
242 1018.0
243 1218.0
244 1318.0
245 1318.0
246 1418.0
247 995.0
248 1195.0
249 1195.0

model_15
LinearDiscriminantAnalysis(solver='lsqr')
['win_streak_dif', 'R_current_lose_streak', 'B_win_by_Submission', 'R_Middleweight_rank', 'B_win_by_Decision_Majority', 'R_Height_cms', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", 'R_avg_SUB_ATT', 'R_Heavyweight_rank', 'R_Reach_cms', 'B_Flyweight_rank', 'R_Lightweight_rank', 'R_age', 'B_age', 'R_Welterweight_rank', 'R_Bantamweight_rank', 'R_match_weightclass_rank', 'R_total_rounds_fought', 'R_avg_TD_landed', 'R_Stance', 'B_current_win_streak', "B_Women's Bantamweight_rank", "B_Women's Flyweight_rank", "B_Women's Strawweight_rank", 'B_wins', 'R_Flyweight_rank', 'R_win_by_KO/TKO', 'location', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'reach_dif', 'age_dif', 'R_Featherweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
0

(3513, 210)

(3513,)

(3513, 2)

(250, 210)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.864306  0.135694       1
1       -320      250  0.632702  0.367298       1
2        130     -155  0.537706  0.462294       0
3       -155      135  0.742697  0.257303       1
4       -240      195  0.567764  0.432236       0
..       ...      ...       ...       ...     ...
245      175     -230  0.549392  0.450608       0
246      250     -305  0.682145  0.317855       0
247     -134      105  0.766018  0.233982       1
248     -105     -117  0.625916  0.374084       1
249      115     -143  0.525221  0.474779       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 224
          Number of winning bets: 102
          Number of losing bets: 123
          Number of underdog bets: 159
          Number of underdog wins: 60
          Number of underdog losses: 99
          Number of Favorite bets: 63
          Number of favorite wins: 41
          Number of favorite losses: 22
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -182.41751724884136
          Profit per bet: -0.8143639162894704
          Profit per match: -0.7296700689953655


HI
HI
HI
HI
HI
The original score is 20336.745751041173
Score:  19882.665844633386
Score:  19674.33004084979
Score:  19574.585037635352
Score:  18684.085330632493
Score:  19069.279553512257
Score:  19195.03799160006
Score:  19991.98384627927
Score:  20219.792484616348
Score:  18706.06875184511
Score:  18964.090470406016
Score:  19056.48985962716
Score:  18059.005452822017
Score:  19398.92072012423
Score:  14893.734191260091
Score:  15049.796942517096
Score:  19712.112307773677
Score:  20248.909586537866
Score:  18695.742631084933
Score:  19114.260104280856
Score:  15513.02005348249
Score:  14826.367954862344
Score:  19711.743858817783
Score:  18357.584960671367
Score:  19832.40834701481
Score:  18171.10323490142
Score:  19260.036094903408
Score:  16082.540032760746
Score:  17182.167062166314
Score:  12132.27982444593
Score:  17384.582689160576
Score:  18868.79401980784
Score:  19403.772291627523
Score:  17253.044154922674
Score:  18285.31356343883
Score:  15382.97142439919
Score:  17745.75542690936
Score:  19811.743858817783
Score:  8118.214631258031
Score:  17592.127056383593

model_15
LinearDiscriminantAnalysis(solver='lsqr')
['win_streak_dif', 'R_current_lose_streak', 'B_win_by_Submission', 'R_Middleweight_rank', 'B_win_by_Decision_Majority', 'R_Height_cms', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", 'R_avg_SUB_ATT', 'R_Heavyweight_rank', 'R_Reach_cms', 'B_Flyweight_rank', 'R_Lightweight_rank', 'R_age', 'B_age', 'R_Welterweight_rank', 'R_Bantamweight_rank', 'R_match_weightclass_rank', 'R_total_rounds_fought', 'R_avg_TD_landed', 'R_Stance', 'B_current_win_streak', "B_Women's Bantamweight_rank", "B_Women's Flyweight_rank", "B_Women's Strawweight_rank", 'B_wins', 'R_Flyweight_rank', 'R_win_by_KO/TKO', 'location', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_win_by_KO/TKO', 'reach_dif', 'age_dif', 'R_Featherweight_rank', 'R_win_by_TKO_Doctor_Stoppage', 'R_current_win_streak', 'B_avg_SIG_STR_landed', 'country']
0

(3513, 210)

(3513,)

(3513, 2)

(250, 210)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.864306  0.135694       1
1       -320      250  0.632702  0.367298       1
2        130     -155  0.537706  0.462294       0
3       -155      135  0.742697  0.257303       1
4       -240      195  0.567764  0.432236       0
..       ...      ...       ...       ...     ...
245      175     -230  0.549392  0.450608       0
246      250     -305  0.682145  0.317855       0
247     -134      105  0.766018  0.233982       1
248     -105     -117  0.625916  0.374084       1
249      115     -143  0.525221  0.474779       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 224
          Number of winning bets: 102
          Number of losing bets: 123
          Number of underdog bets: 159
          Number of underdog wins: 60
          Number of underdog losses: 99
          Number of Favorite bets: 63
          Number of favorite wins: 41
          Number of favorite losses: 22
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -182.41751724884136
          Profit per bet: -0.8143639162894704
          Profit per match: -0.7296700689953655


HI
HI
HI
HI
HI

(3513, 210)

(3513,)

(3513, 2)

(250, 210)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.864306  0.135694       1
1       -320      250  0.632702  0.367298       1
2        130     -155  0.537706  0.462294       0
3       -155      135  0.742697  0.257303       1
4       -240      195  0.567764  0.432236       0
..       ...      ...       ...       ...     ...
245      175     -230  0.549392  0.450608       0
246      250     -305  0.682145  0.317855       0
247     -134      105  0.766018  0.233982       1
248     -105     -117  0.625916  0.374084       1
249      115     -143  0.525221  0.474779       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 224
          Number of winning bets: 102
          Number of losing bets: 123
          Number of underdog bets: 159
          Number of underdog wins: 60
          Number of underdog losses: 99
          Number of Favorite bets: 63
          Number of favorite wins: 41
          Number of favorite losses: 22
          Number of even bets: 3
          Number of even wins: 1
          Number of even losses: 2
          Profit: -182.41751724884136
          Profit per bet: -0.8143639162894704
          Profit per match: -0.7296700689953655


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 16


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_16
LogisticRegressionCV(random_state=75)
['B_Light Heavyweight_rank', 'total_round_dif', 'no_of_rounds', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'B_Weight_lbs', 'B_age', "R_Women's Bantamweight_rank", 'B_draw', "B_Women's Flyweight_rank", 'B_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_match_weightclass_rank', 'R_win_by_Decision_Split', 'age_dif', 'R_age', 'B_ev']
0
Current best score is: 17995.62914184672
Feature: title_bout Score: 18420.45489814612
Feature: B_total_title_bouts Score: 19587.365580194728
Feature: B_win_by_Decision_Unanimous Score: 20582.87091552965
Feature: R_total_title_bouts Score: 21448.261851695534
Feature: total_title_bout_dif Score: 21516.58241542804
The best feature was total_title_bout_dif.  It scored 21516.58241542804
Current best score is: 21516.58241542804
Feature: B_win_by_Decision_Split Score: 22456.11440576964
Feature: B_win_by_KO/TKO Score: 22615.80408047216
Feature: empty_arena Score: 22630.81335568222
The best feature was empty_arena.  It scored 22630.81335568222
Current best score is: 22630.81335568222
Feature: B_win_by_Decision_Unanimous Score: 24109.054173154076
Feature: R_Weight_lbs Score: 24702.333983955625
The best feature was R_Weight_lbs.  It scored 24702.333983955625
Current best score is: 24702.333983955625
Feature: R_current_win_streak Score: 25451.956906600415
Feature: R_win_by_TKO_Doctor_Stoppage Score: 26539.733828525637
The best feature was R_win_by_TKO_Doctor_Stoppage.  It scored 26539.733828525637
Current best score is: 26539.733828525637
NO IMPROVEMENT
FINAL BEST SCORE: 26539.733828525637

model_16
LogisticRegressionCV(random_state=75)
['R_win_by_TKO_Doctor_Stoppage', 'R_Weight_lbs', 'empty_arena', 'total_title_bout_dif', 'B_Light Heavyweight_rank', 'total_round_dif', 'no_of_rounds', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'B_Weight_lbs', 'B_age', "R_Women's Bantamweight_rank", 'B_draw', "B_Women's Flyweight_rank", 'B_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_match_weightclass_rank', 'R_win_by_Decision_Split', 'age_dif', 'R_age', 'B_ev']
0

(4554, 21)

(4554,)

(4554, 2)

(250, 21)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.696249  0.303751       1
1       -320      250  0.761745  0.238255       1
2        130     -155  0.465166  0.534834       0
3       -155      135  0.634652  0.365348       1
4       -240      195  0.695464  0.304536       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455622  0.544378       0
246      250     -305  0.399948  0.600052       0
247     -134      105  0.547690  0.452310       1
248     -105     -117  0.588929  0.411071       1
249      115     -143  0.484632  0.515368       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 203
          Number of winning bets: 103
          Number of losing bets: 100
          Number of underdog bets: 117
          Number of underdog wins: 48
          Number of underdog losses: 69
          Number of Favorite bets: 83
          Number of favorite wins: 55
          Number of favorite losses: 28
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -126.48121562282495
          Profit per bet: -0.6230601754818963
          Profit per match: -0.5059248624912998


HI
HI
HI
HI
HI


Starting New Run for LogisticRegression


Previous Best Score: 26539.733828525637
solver: newton-cg penalty: l2 tol: 0.0001 Score: 24704.35049230094
solver: newton-cg penalty: l2 tol: 0.00012 Score: 24704.35049230094
solver: newton-cg penalty: l2 tol: 8e-05 Score: 24704.35049230094
solver: newton-cg penalty: l2 tol: 4.439514718356161 Score: 24395.96235563115
solver: newton-cg penalty: none tol: 0.0001 Score: 24843.957845562352
solver: newton-cg penalty: none tol: 0.00012 Score: 24843.957845562352
solver: newton-cg penalty: none tol: 8e-05 Score: 24843.957845562352
solver: newton-cg penalty: none tol: 4.439514718356161 Score: 23447.040089336955
solver: lbfgs penalty: l2 tol: 0.0001 Score: 24804.35049230094
solver: lbfgs penalty: l2 tol: 0.00012 Score: 24804.35049230094
solver: lbfgs penalty: l2 tol: 8e-05 Score: 24804.35049230094
solver: lbfgs penalty: l2 tol: 4.439514718356161 Score: 23494.103068356708
solver: lbfgs penalty: none tol: 0.0001 Score: 24843.957845562352
solver: lbfgs penalty: none tol: 0.00012 Score: 24843.957845562352
solver: lbfgs penalty: none tol: 8e-05 Score: 24843.957845562352
solver: lbfgs penalty: none tol: 4.439514718356161 Score: 22586.82757858122
solver: sag penalty: l2 tol: 0.0001 Score: 24704.35049230094
solver: sag penalty: l2 tol: 0.00012 Score: 24804.35049230094
solver: sag penalty: l2 tol: 8e-05 Score: 24768.866621333196
solver: sag penalty: l2 tol: 4.439514718356161 Score: 7949.373818298423
solver: sag penalty: none tol: 0.0001 Score: 24843.957845562352
solver: sag penalty: none tol: 0.00012 Score: 24843.957845562352
solver: sag penalty: none tol: 8e-05 Score: 24843.957845562352
solver: sag penalty: none tol: 4.439514718356161 Score: 7770.919063831421
Real output model: LogisticRegressionCV(random_state=75)

model_16
LogisticRegressionCV(random_state=75)
['R_win_by_TKO_Doctor_Stoppage', 'R_Weight_lbs', 'empty_arena', 'total_title_bout_dif', 'B_Light Heavyweight_rank', 'total_round_dif', 'no_of_rounds', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'B_Weight_lbs', 'B_age', "R_Women's Bantamweight_rank", 'B_draw', "B_Women's Flyweight_rank", 'B_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_match_weightclass_rank', 'R_win_by_Decision_Split', 'age_dif', 'R_age', 'B_ev']
0

(4554, 21)

(4554,)

(4554, 2)

(250, 21)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.696249  0.303751       1
1       -320      250  0.761745  0.238255       1
2        130     -155  0.465166  0.534834       0
3       -155      135  0.634652  0.365348       1
4       -240      195  0.695464  0.304536       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455622  0.544378       0
246      250     -305  0.399948  0.600052       0
247     -134      105  0.547690  0.452310       1
248     -105     -117  0.588929  0.411071       1
249      115     -143  0.484632  0.515368       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 203
          Number of winning bets: 103
          Number of losing bets: 100
          Number of underdog bets: 117
          Number of underdog wins: 48
          Number of underdog losses: 69
          Number of Favorite bets: 83
          Number of favorite wins: 55
          Number of favorite losses: 28
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -126.48121562282495
          Profit per bet: -0.6230601754818963
          Profit per match: -0.5059248624912998


HI
HI
HI
HI
HI
0 26539.733828525637
1 23562.645720505843
2 22336.2400416867
3 18565.861499484552
4 17359.058467619518
5 14580.297924855144
6 13930.478579877143
7 13514.04266551497
8 10044.300238073605
9 8535.775738132246
10 8430.054940883943
11 9220.97021548303
12 7917.360387127074
13 6001.440653934569
14 6104.409729802521
15 5359.227332004182
16 4984.899148110781
17 5599.880833092467
18 4976.634079845713
19 5341.75312746476
20 5090.6833200791625
21 6280.683320079163
22 6670.207129602972
23 5777.8051111529385
24 7093.229541794759
25 7211.273020055629
26 7096.273020055629
27 7939.273020055629
28 8359.273020055629
29 7744.606353388962
30 7097.606353388962
31 6637.606353388963
32 7138.532279314888
33 7255.532279314888
34 6350.532279314888
35 5935.532279314888
36 4816.103707886317
37 5094.1037078863155
38 4641.1037078863155
39 4401.103707886317
40 3761.103707886316
41 3214.1037078863164
42 3019.1037078863164
43 2359.1037078863164
44 2358.194616977226
45 2178.194616977226
46 1613.194616977226
47 1623.1946169772257
48 1586.0
49 1361.0
50 1211.0
51 1351.0
52 1406.0
53 1156.0
54 1226.0
55 1001.0
56 1153.0
57 613.0
58 -187.0
59 -432.0
60 -477.0
61 -522.0
62 -122.0
63 78.0
64 23.0
65 223.0
66 408.0
67 433.0
68 -372.0
69 -520.0
70 -595.0
71 -305.0
72 -395.0
73 -555.0
74 -675.0
75 -960.0
76 -960.0
77 -660.0
78 -1050.0
79 -1030.0
80 -1040.0
81 -940.0
82 -1165.0
83 -1315.0
84 -1015.0
85 -920.0
86 -720.0
87 -120.0
88 -185.0
89 -85.0
90 115.0
91 -10.0
92 -300.0
93 -560.0
94 -560.0
95 -560.0
96 -980.0
97 -780.0
98 -780.0
99 -680.0
100 -580.0
101 -480.0
102 -480.0
103 -480.0
104 -480.0
105 -480.0
106 -480.0
107 -380.0
108 -280.0
109 -180.0
110 20.0
111 120.0
112 120.0
113 120.0
114 -265.0
115 -265.0
116 -265.0
117 -265.0
118 -65.0
119 -445.0
120 -345.0
121 -245.0
122 -245.0
123 -45.0
124 -45.0
125 -45.0
126 55.0
127 -395.0
128 -395.0
129 -195.0
130 -95.0
131 -545.0
132 -545.0
133 -545.0
134 -545.0
135 -445.0
136 -445.0
137 -245.0
138 -245.0
139 -145.0
140 -145.0
141 55.0
142 55.0
143 55.0
144 155.0
145 155.0
146 155.0
147 155.0
148 155.0
149 255.0
150 255.0
151 255.0
152 255.0
153 255.0
154 255.0
155 355.0
156 455.0
157 455.0
158 455.0
159 455.0
160 455.0
161 455.0
162 455.0
163 455.0
164 455.0
165 455.0
166 455.0
167 455.0
168 455.0
169 455.0
170 455.0
171 455.0
172 455.0
173 455.0
174 455.0
175 455.0
176 455.0
177 455.0
178 455.0
179 455.0
180 455.0
181 455.0
182 455.0
183 455.0
184 455.0
185 455.0
186 455.0
187 555.0
188 555.0
189 555.0
190 555.0
191 555.0
192 555.0
193 555.0
194 555.0
195 555.0
196 555.0
197 555.0
198 555.0
199 555.0
200 555.0
201 555.0
202 555.0
203 555.0
204 555.0
205 555.0
206 555.0
207 555.0
208 555.0
209 555.0
210 555.0
211 555.0
212 555.0
213 555.0
214 555.0
215 555.0
216 555.0
217 555.0
218 555.0
219 555.0
220 555.0
221 -100
222 -100
223 -100
224 -100
225 -100
226 -100
227 -100
228 -100
229 -100
230 -100
231 -100
232 -100
233 -100
234 -100
235 -100
236 -100
237 -100
238 -100
239 -100
240 -100
241 -100
242 -100
243 -100
244 -100
245 -100
246 -100
247 -100
248 -100
249 -100

model_16
LogisticRegressionCV(random_state=75)
['R_win_by_TKO_Doctor_Stoppage', 'R_Weight_lbs', 'empty_arena', 'total_title_bout_dif', 'B_Light Heavyweight_rank', 'total_round_dif', 'no_of_rounds', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'B_Weight_lbs', 'B_age', "R_Women's Bantamweight_rank", 'B_draw', "B_Women's Flyweight_rank", 'B_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_match_weightclass_rank', 'R_win_by_Decision_Split', 'age_dif', 'R_age', 'B_ev']
0

(4554, 21)

(4554,)

(4554, 2)

(250, 21)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.696249  0.303751       1
1       -320      250  0.761745  0.238255       1
2        130     -155  0.465166  0.534834       0
3       -155      135  0.634652  0.365348       1
4       -240      195  0.695464  0.304536       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455622  0.544378       0
246      250     -305  0.399948  0.600052       0
247     -134      105  0.547690  0.452310       1
248     -105     -117  0.588929  0.411071       1
249      115     -143  0.484632  0.515368       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 203
          Number of winning bets: 103
          Number of losing bets: 100
          Number of underdog bets: 117
          Number of underdog wins: 48
          Number of underdog losses: 69
          Number of Favorite bets: 83
          Number of favorite wins: 55
          Number of favorite losses: 28
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -126.48121562282495
          Profit per bet: -0.6230601754818963
          Profit per match: -0.5059248624912998


HI
HI
HI
HI
HI
The original score is 26539.733828525637
Score:  24702.333983955625
Score:  23531.618216486047
Score:  22839.816638932214
Score:  22800.67101336816
Score:  25425.684483360932
Score:  22508.84191327947
Score:  23871.21134319253
Score:  24673.175688870775
Score:  24187.547700433082
Score:  21703.036510200818
Score:  20067.98409762147
Score:  22554.247318097838
Score:  23303.3043425608
Score:  25514.581193843194
Score:  23762.87612203698
Score:  21807.74782365648
Score:  24419.660946832024
Score:  17602.163966133583
Score:  24307.01333436622
Score:  18938.846687935475
Score:  -12494.945716687831

model_16
LogisticRegressionCV(random_state=75)
['R_win_by_TKO_Doctor_Stoppage', 'R_Weight_lbs', 'empty_arena', 'total_title_bout_dif', 'B_Light Heavyweight_rank', 'total_round_dif', 'no_of_rounds', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'B_Weight_lbs', 'B_age', "R_Women's Bantamweight_rank", 'B_draw', "B_Women's Flyweight_rank", 'B_win_by_Decision_Majority', 'B_Lightweight_rank', 'B_match_weightclass_rank', 'R_win_by_Decision_Split', 'age_dif', 'R_age', 'B_ev']
0

(4554, 21)

(4554,)

(4554, 2)

(250, 21)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.696249  0.303751       1
1       -320      250  0.761745  0.238255       1
2        130     -155  0.465166  0.534834       0
3       -155      135  0.634652  0.365348       1
4       -240      195  0.695464  0.304536       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455622  0.544378       0
246      250     -305  0.399948  0.600052       0
247     -134      105  0.547690  0.452310       1
248     -105     -117  0.588929  0.411071       1
249      115     -143  0.484632  0.515368       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 203
          Number of winning bets: 103
          Number of losing bets: 100
          Number of underdog bets: 117
          Number of underdog wins: 48
          Number of underdog losses: 69
          Number of Favorite bets: 83
          Number of favorite wins: 55
          Number of favorite losses: 28
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -126.48121562282495
          Profit per bet: -0.6230601754818963
          Profit per match: -0.5059248624912998


HI
HI
HI
HI
HI

(4554, 21)

(4554,)

(4554, 2)

(250, 21)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.696249  0.303751       1
1       -320      250  0.761745  0.238255       1
2        130     -155  0.465166  0.534834       0
3       -155      135  0.634652  0.365348       1
4       -240      195  0.695464  0.304536       0
..       ...      ...       ...       ...     ...
245      175     -230  0.455622  0.544378       0
246      250     -305  0.399948  0.600052       0
247     -134      105  0.547690  0.452310       1
248     -105     -117  0.588929  0.411071       1
249      115     -143  0.484632  0.515368       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 203
          Number of winning bets: 103
          Number of losing bets: 100
          Number of underdog bets: 117
          Number of underdog wins: 48
          Number of underdog losses: 69
          Number of Favorite bets: 83
          Number of favorite wins: 55
          Number of favorite losses: 28
          Number of even bets: 3
          Number of even wins: 0
          Number of even losses: 3
          Profit: -126.48121562282495
          Profit per bet: -0.6230601754818963
          Profit per match: -0.5059248624912998


HI
HI
HI
HI
HI
5


OPTIMIZING MODEL 17


5
250
250
250
4554
4554
4554
250
4554

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
250,Marina Rodriguez,Amanda Ribas,250,-335,250.000000,29.850746,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,375.0,125.0,1800.0,165.0,1000.0,1000.0,0
251,Brad Tavares,Antonio Carlos Junior,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,175.0,250.0,1400.0,275.0,550.0,800.0,0
252,Julianna Pena,Sara McMann,105,-130,105.000000,76.923077,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,250.0,150.0,475.0,375.0,900.0,1000.0,0
253,Khalil Rountree Jr.,Marcin Prachnio,-335,250,29.850746,250.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,NaN,650.0,NaN,2200.0,NaN,400.0,1
254,Nik Lentz,Movsar Evloev,390,-560,390.000000,17.857143,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,700.0,-175.0,950.0,550.0,1400.0,500.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4799,Duane Ludwig,Darren Elkins,-155,135,64.516129,135.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,1.0,0:44,44.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4800,John Howard,Daniel Roberts,-210,175,47.619048,175.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,2:01,121.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4801,Brendan Schaub,Chase Gormley,-260,220,38.461538,220.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,1.0,0:47,47.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4802,Mike Pierce,Julio Paulino,-420,335,23.809524,335.000000,2010-03-21,"Broomfield, Colorado, USA",USA,Red,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4803,Eric Schafer,Jason Brilz,140,-160,140.000000,62.500000,2010-03-21,"Broomfield, Colorado, USA",USA,Blue,...,3.0,5:00,900.0,NaN,NaN,NaN,NaN,NaN,NaN,1

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,label
0,Cory Sandhagen,TJ Dillashaw,-210,175,47.619048,175.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,5.0,5:00,1500.0,500.0,500.0,600.0,1100.0,110.0,400.0,1
1,Kyler Phillips,Raulian Paiva,-320,250,31.250000,250.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,-125.0,500.0,1000.0,1000.0,400.0,900.0,1
2,Darren Elkins,Darrick Minner,130,-155,130.000000,64.516129,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,3:48,528.0,275.0,250.0,600.0,240.0,800.0,600.0,0
3,Miranda Maverick,Maycee Barber,-155,135,64.516129,135.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Blue,...,3.0,5:00,900.0,120.0,275.0,650.0,1400.0,750.0,450.0,1
4,Adrian Yanez,Randy Costa,-240,195,41.666667,195.000000,2021-07-24,"Las Vegas, Nevada, USA",USA,Red,...,2.0,2:11,431.0,380.0,500.0,1100.0,1600.0,-110.0,450.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SeungWoo Choi,Youssef Zalal,175,-230,175.000000,43.478261,2021-02-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,350.0,125.0,1400.0,450.0,600.0,425.0,0
246,Dustin Poirier,Conor McGregor,250,-305,250.000000,32.786885,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Red,...,NaN,NaN,NaN,650.0,750.0,750.0,1600.0,675.0,-220.0,0
247,Dan Hooker,Michael Chandler,-134,105,74.626866,105.000000,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,325.0,300.0,850.0,675.0,150.0,500.0,1
248,Jessica Eye,Joanne Calderwood,-105,-117,95.238095,85.470085,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,125.0,140.0,1200.0,1000.0,900.0,600.0,1
249,Andrew Sanchez,Makhmud Muradov,115,-143,115.000000,69.930070,2021-01-23,"Abu Dhabi, Abu Dhabi, United Arab Emirates",United Arab Emirates,Blue,...,NaN,NaN,NaN,260.0,200.0,1000.0,1800.0,800.0,175.0,1

['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date', 'location', 'country', 'Winner', 'title_bout', 'weight_class', 'gender', 'no_of_rounds', 'B_current_lose_streak', 'B_current_win_streak', 'B_draw', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_longest_win_streak', 'B_losses', 'B_total_rounds_fought', 'B_total_title_bouts', 'B_win_by_Decision_Majority', 'B_win_by_Decision_Split', 'B_win_by_Decision_Unanimous', 'B_win_by_KO/TKO', 'B_win_by_Submission', 'B_win_by_TKO_Doctor_Stoppage', 'B_wins', 'B_Stance', 'B_Height_cms', 'B_Reach_cms', 'B_Weight_lbs', 'R_current_lose_streak', 'R_current_win_streak', 'R_draw', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_longest_win_streak', 'R_losses', 'R_total_rounds_fought', 'R_total_title_bouts', 'R_win_by_Decision_Majority', 'R_win_by_Decision_Split', 'R_win_by_Decision_Unanimous', 'R_win_by_KO/TKO', 'R_win_by_Submission', 'R_win_by_TKO_Doctor_Stoppage', 'R_wins', 'R_Stance', 'R_Height_cms', 'R_Reach_cms', 'R_Weight_lbs', 'R_age', 'B_age', 'lose_streak_dif', 'win_streak_dif', 'longest_win_streak_dif', 'win_dif', 'loss_dif', 'total_round_dif', 'total_title_bout_dif', 'ko_dif', 'sub_dif', 'height_dif', 'reach_dif', 'age_dif', 'sig_str_dif', 'avg_sub_att_dif', 'avg_td_dif', 'empty_arena', 'constant_1', 'B_match_weightclass_rank', 'R_match_weightclass_rank', "R_Women's Flyweight_rank", "R_Women's Featherweight_rank", "R_Women's Strawweight_rank", "R_Women's Bantamweight_rank", 'R_Heavyweight_rank', 'R_Light Heavyweight_rank', 'R_Middleweight_rank', 'R_Welterweight_rank', 'R_Lightweight_rank', 'R_Featherweight_rank', 'R_Bantamweight_rank', 'R_Flyweight_rank', 'R_Pound-for-Pound_rank', "B_Women's Flyweight_rank", "B_Women's Featherweight_rank", "B_Women's Strawweight_rank", "B_Women's Bantamweight_rank", 'B_Heavyweight_rank', 'B_Light Heavyweight_rank', 'B_Middleweight_rank', 'B_Welterweight_rank', 'B_Lightweight_rank', 'B_Featherweight_rank', 'B_Bantamweight_rank', 'B_Flyweight_rank', 'B_Pound-for-Pound_rank', 'better_rank', 'finish', 'finish_details', 'finish_round', 'finish_round_time', 'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'label']
model_17
NuSVC(probability=True, random_state=75)
['R_Lightweight_rank', 'R_Flyweight_rank', 'B_win_by_KO/TKO', 'B_Lightweight_rank', 'B_win_by_Decision_Unanimous', 'B_ev', 'win_streak_dif', 'R_ev', 'R_Welterweight_rank', 'B_Flyweight_rank', 'B_losses', 'R_total_title_bouts', 'B_avg_SUB_ATT', 'height_dif', "R_Women's Featherweight_rank", 'empty_arena', 'country', 'R_odds', 'location', 'R_avg_SIG_STR_landed', 'B_avg_TD_landed']
182
Current best score is: 4595.0
Feature: B_win_by_Decision_Split Score: 4895.0
Feature: B_win_by_Submission Score: 5070.0
The best feature was B_win_by_Submission.  It scored 5070.0
Current best score is: 5070.0
Feature: B_total_title_bouts Score: 5393.0
The best feature was B_total_title_bouts.  It scored 5393.0
Current best score is: 5393.0
NO IMPROVEMENT
FINAL BEST SCORE: 5393.0

model_17
NuSVC(probability=True, random_state=75)
['B_total_title_bouts', 'B_win_by_Submission', 'R_Lightweight_rank', 'R_Flyweight_rank', 'B_win_by_KO/TKO', 'B_Lightweight_rank', 'B_win_by_Decision_Unanimous', 'B_ev', 'win_streak_dif', 'R_ev', 'R_Welterweight_rank', 'B_Flyweight_rank', 'B_losses', 'R_total_title_bouts', 'B_avg_SUB_ATT', 'height_dif', "R_Women's Featherweight_rank", 'empty_arena', 'country', 'R_odds', 'location', 'R_avg_SIG_STR_landed', 'B_avg_TD_landed']
182

(3513, 191)

(3513,)

(3513, 2)

(250, 191)

(250,)

(250, 2)

     t1_odds  t2_odds   t1_prob   t2_prob  winner
0       -210      175  0.449039  0.550961       1
1       -320      250  0.467403  0.532597       1
2        130     -155  0.526260  0.473740       0
3       -155      135  0.633903  0.366097       1
4       -240      195  0.653040  0.346960       0
..       ...      ...       ...       ...     ...
245      175     -230  0.509853  0.490147       0
246      250     -305  0.460372  0.539628       0
247     -134      105  0.742775  0.257225       1
248     -105     -117  0.629299  0.370701       1
249      115     -143  0.588253  0.411747       1

[250 rows x 5 columns]

          Number of matches: 250
          Number of bets: 0
          Number of winning bets: 0
          Number of losing bets: 0
          Number of underdog bets: 0
          Number of underdog wins: 0
          Number of underdog losses: 0
          Number of Favorite bets: 0
          Number of favorite wins: 0
          Number of favorite losses: 0
          Number of even bets: 0
          Number of even wins: 0
          Number of even losses: 0
          Profit: 0
          Profit per bet: 0
          Profit per match: 0.0


HI
HI
HI
HI
HI


Starting New Run for NuSVC


Previous Best Score: 5393.0
nu:  0.5 tol:  0.001 Score:  5393.0
nu:  0.5 tol:  0.0011 Score:  5393.0
nu:  0.5 tol:  0.0009000000000000001 Score:  5393.0
nu:  0.5 tol:  0.20701385600043498 Score:  1580.0
nu:  0.55 tol:  0.001 Score:  1913.0
nu:  0.55 tol:  0.0011 Score:  1913.0
nu:  0.55 tol:  0.0009000000000000001 Score:  1913.0
nu:  0.55 tol:  0.20701385600043498 Score:  1155.0
nu:  0.45 tol:  0.001 Score:  3318.0
nu:  0.45 tol:  0.0011 Score:  3318.0
nu:  0.45 tol:  0.0009000000000000001 Score:  3418.0
nu:  0.45 tol:  0.20701385600043498 Score:  1325.0

ValueError: specified nu is infeasible

ValueError: specified nu is infeasible

In [ ]:
#model_num = 15

In [ ]:
#%run TM-Optimize-Models.ipynb