In [1]:
import pandas as pd

In [2]:
#df.loc[df.R_fighter == r_fighter, ['R_odds', 'B_odds', 'R_ev', 'B_ev']] = (r_odds), (b_odds), (r_ev), (b_ev)

In [3]:
df_exotics = pd.read_csv('export_test.csv')
df = pd.read_csv('../data/kaggle_data/ufc-master.csv')

In [4]:
df_exotics

,r_fighter,b_fighter,date,r_dec_odds,r_ko_odds,r_sub_odds,b_dec_odds,b_ko_odds,b_sub_odds
0,Chan Sung Jung,Dan Ige,6/19/2021,+260,+300,+775,+225,+275,+1000
1,Aleksei Oleinik,Serghei Spivac,6/19/2021,NaN,NaN,NaN,+500,-145,+1800
2,Marlon Vera,Davey Grant,6/19/2021,+188,+400,+300,+450,+450,+1200
3,Julian Erosa,SeungWoo Choi,6/19/2021,+300,+600,+550,+180,+250,+1000
4,Wellington Turman,Bruno Silva,6/19/2021,+350,+650,+375,+350,+185,+1000
...,...,...,...,...,...,...,...,...,...
5932,Duane Ludwig,Darren Elkins,3/21/2010,NaN,NaN,NaN,NaN,NaN,NaN
5933,John Howard,Daniel Roberts,3/21/2010,NaN,NaN,NaN,NaN,NaN,NaN
5934,Brendan Schaub,Chase Gormley,3/21/2010,NaN,NaN,NaN,NaN,NaN,NaN
5935,Mike Pierce,Julio Paulino,3/21/2010,NaN,NaN,NaN,NaN,NaN,NaN
5936,Eric Schafer,Jason Brilz,3/21/2010,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
r_fighter_list = df_exotics['r_fighter'].tolist()
b_fighter_list = df_exotics['b_fighter'].tolist()
date_list = df_exotics['date'].tolist()
r_dec_odds_list = df_exotics['r_dec_odds'].tolist()
b_dec_odds_list = df_exotics['b_dec_odds'].tolist()
r_sub_odds_list = df_exotics['r_sub_odds'].tolist()
b_sub_odds_list = df_exotics['b_sub_odds'].tolist()
r_ko_odds_list = df_exotics['r_ko_odds'].tolist()
b_ko_odds_list = df_exotics['b_ko_odds'].tolist()

In [6]:
df['r_dec_odds'] = ''

In [7]:
for n in range(len(r_fighter_list)):
    df.loc[(df.R_fighter == r_fighter_list[n]) & (df.B_fighter == b_fighter_list[n]) & (df.date == date_list[n]), ['r_dec_odds', 'b_dec_odds', 'r_sub_odds', 'b_sub_odds' , 'r_ko_odds', 'b_ko_odds']] = (r_dec_odds_list[n]), (b_dec_odds_list[n]), (r_sub_odds_list[n]), (b_sub_odds_list[n]), (r_ko_odds_list[n]), (b_ko_odds_list[n])

In [9]:
df.to_csv('master_test.csv', index=False)